### ISSUE TITLE
confusing (incorrect?) error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1003]
For the program
```
data Foo:
  | m(x)
    with:
    method get(): self.x * 2 end
end
```
which is intentionally missing a `self` param in the method, the error says
"This method declaration does not accept at least one argument:"

This is a really confusing wording. It should say something like "should accept" rather than this roundabout "does not accept". It's easy to misread it to think it's saying "method declarations do not accept at least one argument", which makes it especially head-scratchy.

**Comment by blerner** [comment]
Ironically, this message is better in the non-fancy version...  I'll push a fix momentarily.
