### ISSUE TITLE
Arity isn't checked for method invocation.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#1005]
Demonstrative code:
```
data Foo:
    foo
sharing:
  method bar(self, baz):
    baz
  end
end

m = foo.bar

m(1, 2, 3)
```

The expected arity mismatch error _is_ thrown for this invocation, however:

```
(foo.bar)(1, 2, 3)
```

**Comment by blerner** [comment]
Specifically, this is happening when we extract a method and bind its `self`, so that we get a function.

**Comment by blerner** [comment]
D'oh.  Arity _is_ being checked inside the method, but the curried methods (`app0` through `app9`) explicitly pass whatever formal parameters they receive, so if they're called with too few arguments, they'll explicitly pass `undefined` as an argument to the underlying method, so our check that `arguments.length` is the correct length is too simple.  The only fix, currently, is to check for arity mismatches in the `app#` functions too.  With ES6, we ought to be able to use spread arguments.  They are supported currently in Chrome46+, Firefox27+, Edge12.10240+, Opera37+, and Safari7.1+. (per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator#Browser_compatibility).  Dunno how fast they are, but they exist and we probably can rely on them...

**Comment by schanzer** [comment]
They're not fast in production browsers, but all the major vendors are optimizing the spread operators for their next release.
