### ISSUE TITLE
Programs not loading

### ISSUE THREAD

**Issue by vikas-codeforfun** [brownplt/pyret-lang#1012]
Few of my students shared their program with me and the link is not working. They said that they used the "share" button
I get the following error: "The Project Failed to Load"

Example:
https://goo.gl/jdPtYy
https://code.pyret.org/editor#program=0B6-aAlAhZHSBWEtzWFczUElOX2M
https://code.pyret.org/editor#program=0B6-aAlAhZHSBV2wwR1BUaGc3SE0
https://code.pyret.org/editor#program=0B60QXCqdtnm-T1UxZXNCRWEzV3M

**Comment by jpolitz** [comment]
Thanks for reporting, and sorry you had trouble.

This is likely just a confusion with the interface, which is something we're working on improving to make it more obvious.  Your students aren't the only ones who've been confused by it.

When you share a file, there's a dedicated share link created for it, and the best way to get to it is to click "(Share Link)" from the "Publish..." menu:

<img width="1196" alt="screen shot 2017-04-24 at 5 59 10 pm" src="https://cloud.githubusercontent.com/assets/119891/25364500/cd2e6b60-2917-11e7-9a6d-eb422cc72961.png">

**Comment by schanzer** [comment]
Do we have a separate issue for improving the UI? If not, can we close this since?

**Comment by shriram** [comment]
If you've confirmed things that work, close them, just making sure you've
confirmed them on the right system.
