### ISSUE TITLE
Allow rotation by any angle

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#1014]
Dr. Racket used to limit the rotate function to 360 degrees, now it doesn't. This makes it much easier to write lessons using rotation without the overhead of modulo. CPO seems to have inherited the old limitation, which makes those lessons harder to write. Can we match Dr. Racket on this, and allow rotation by any degree?

**Comment by schanzer** [comment]
+1. This would be an extremely valuable change from a curricular perspective.

**Comment by blerner** [comment]
Hmmmmm, I don't think you want to indiscriminately add one to all angles... ;-)

**Comment by schanzer** [comment]
Grrrrrrr

**Comment by ds26gte** [comment]
A fix is already in my fork (both for Patch and Pyret) --  https://github.com/ds26gte/code.pyret.org/blob/patch/src/web/js/trove/image.js, lines 264, 782.

**Comment by schanzer** [comment]
❤️!!!

You have no idea how excited we are to have this change. Any objections to merging this into horizon?

**Comment by jpolitz** [comment]
No objection, happy to PR it in.​

**Comment by blerner** [comment]
Pinging @shriram since I think this might impact PAPL.  Otherwise, I'm fine with it.

**Comment by ds26gte** [comment]
PR submitted as brownplt/code.pyret.org#170.  (This is a change to the `code.pyret.org` repo, not `pyret-lang`.)

**Comment by shriram** [comment]
Nope, I'm good.​ Thanks.

**Comment by schanzer** [comment]
You guys are the best. @shriram , remind me to tell you why this is so significant the next time we talk. :)

**Comment by schanzer** [comment]
Confirming fixed on CPO and horizon
