### ISSUE TITLE
Arity error message uses "were" regardless of number of args

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#1033]
![image](https://user-images.githubusercontent.com/77126/27253160-3c19bbac-533d-11e7-9de6-b8162418050a.png)

Can be easily reproduced with `num-min(1)`

Should be "was passed..."

**Comment by blerner** [comment]
Already fixed by https://github.com/brownplt/pyret-lang/commit/1b5e3ab8098925ece2f7dafd1c35412cb54dec7f
