### ISSUE TITLE
overlay-xy docs confusing around negative numbers for shifts

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1037]
The overlay-xy docs say 

     "lines up the two images upper-left corners and then shifts img2 to the right by dx pixels"

But you have to enter the number of pixels to shift right by as a negative number.  This isn't at all clear from the docs.

**Comment by blerner** [comment]
Huh?  It does exactly that: it moves img2 to the right (when positive) and down (when positive)
![image](https://user-images.githubusercontent.com/918464/27261183-a1e95996-540b-11e7-850d-ed8c36494c9b.png)

I agree more broadly though, the image docs should be overhauled to actually show pictures and examples, like https://course.ccs.neu.edu/cs2510/image-doc.html or http://docs.racket-lang.org/teachpack/2htdpimage.html (though preferably, load as fast as the former page, not the latter!)

**Comment by kfisler** [comment]
Sorry -- I misread and thought img1 was the one shifting.  I was trying to get the effect of your third example and was confused as to why I needed the negatives.

Shifting img2 does seem backwards (at least in isolation), since img1 is the one placed on top (I think of img2 as fixed position while img1 aligns with it).  But this is a very low-priority comment.

**Comment by blerner** [comment]
I agree, but it matches the semantics of Racket's `overlay/xy`, and therefore WeScheme... Sigh.
