### ISSUE TITLE
was/were confusion

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1038]
![image](https://user-images.githubusercontent.com/75030/27260885-edf5a288-5404-11e7-9e89-fb4ccf9b3c99.png)

How is this even a thing? How could it be that the error messages are not parameterized over was/were for singular/plural?

Incidentally, the screenshot @blerner posted in https://github.com/brownplt/pyret-lang/issues/899#issuecomment-309257969 says "was", so maybe this is fixed in some versions but not others? I'm copying off the current, live CPO.

**Comment by blerner** [comment]
This is fixed in #899, but that hasn't merged anywhere yet.  Joe and I are getting to that this week.  Closing this as a dupe.
