### ISSUE TITLE
Expressions like ~10/2 cause internal error in  repl.

### ISSUE THREAD

**Issue by fedel** [brownplt/pyret-lang#1046]
Expressions like ~10/2 cause internal error in  repl.

I attach a screenshot:

![pyret-bug](https://user-images.githubusercontent.com/509238/27356687-d6aeffa6-55e5-11e7-94de-d86eb8b95d27.png)

**Comment by blerner** [comment]
This isn't your errors' fault, @jswrenn  :)  It's a bug in js-numbers.  @ds26gte -- you have an optimization in Rational.makeInstance, such that when the result is an exact integer, you return the exact integer.  Then, that integer doesn't have a toRoughnum method, so things blow up...

**Comment by jswrenn** [comment]
Thanks for reporting! This is an interesting bug.

This is the result of an internal javascript error (`"Rational.makeInstance(...).toRoughnum is not a function"`) leaking into pyret-land, being misinterpreted as a parse error, and going down the wrong code path. Consequently, [`result.exn.exn`](https://github.com/brownplt/code.pyret.org/blob/master/src/web/js/repl-ui.js#L103) is `undefined`, and attempted to render `undefined` as an error message completely chokes.

**Comment by fedel** [comment]
blerner, jswrenn, thanks to you.

Also ~10/0 throw me an error.
