### ISSUE TITLE
“left side”

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1048]
I watched Kathi struggle with an error report today. She had written
```
max(3, 6)
```
and got an error about the “left side”. I had her slowly talk me through why she was confused by it, and the critical thing she said was, “Well, to me the left side is `3`.” You can see that if you start with that, everything else is going to go haywire.

I've never been a fan of this text (I don't remember even reviewing it…). I'm going to push for us to remove it and replace it with something more meaningful.

**Comment by blerner** [comment]
To clarify -- what function is "min" or "max"?  The only ones I can think of are num-min and num-max, and they *do* take two arguments...?

**Comment by shriram** [comment]
This `min` comes from the `math` library:

http://www.pyret.org/docs//latest/math.html#%28part._math_min%29

**Comment by jswrenn** [comment]
See also https://github.com/brownplt/pyret-lang/issues/868.

As @blerner [pointed out](https://github.com/brownplt/pyret-lang/issues/868#issuecomment-309257676), "left side" is a revised wording. I would also prefer a more meaningful term (or at least one that isn't meaningful in a misleading manner).

Whatever term we use for the applicant position should be usable for both arity mismatch and non-function-application errors. Therefore, the term should describe the syntactic position, not its particular runtime value.

**Comment by jpolitz** [comment]
"The function position evaluated to..."

"Expected a function in function position..."

**Comment by jswrenn** [comment]
Will make this change tomorrow.

**Comment by blerner** [comment]
@jswrenn I don't see these changes; have you had a chance to make them yet?

**Comment by jswrenn** [comment]
@blerner Not yet; there are deeper changes than I anticipated would be required when I made the "tomorrow" comment; in light of #1004 and the [unresolved issues with providing consistent highlighting](https://github.com/brownplt/pyret-lang/issues/1070#issuecomment-315493158), I think @shriram and I need to sit down and work out the full story on function-related error reports.

**Comment by jswrenn** [comment]
bbdc98f415c27d39ca1f838b17314d0f80c4672b makes changes to `arity-mismatch` and an overview of those changes is given in https://github.com/brownplt/pyret-lang/commit/bbdc98f415c27d39ca1f838b17314d0f80c4672b#commitcomment-23300156.

This issue is resolved by using "operator" instead of "left side".
