### ISSUE TITLE
Why is there a colon in table order operations?

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1051]
I'm confused as to why Pyret need the colon in
   order mytable: mycolumn descending

But not in 
    select mycolumn from table

It looks to me like both involve four fixed terms.  Is there some flexibility in order that requires the colon?  If so, I don't see it in the docs ...

**Comment by blerner** [comment]
Order operations can sort on multiple columns, so there's a block there -- you're missing an `end`.  By contrast, select operations are fixed-size and don't need an `end`.  And every block in Pyret gets a colon at its start.

**Comment by schanzer** [comment]
This is something Joe and I talked about last summer: that it would be really helpful if `select` queries had an (unnecessary) colon in them, solely for the sake of consistency between queries. But I'm comfortable punting on this, since we're changing the query syntax next year anyway.

**Comment by blerner** [comment]
Just to be clear: Then you will lose the other consistency, that every colon matches an end.  (One exception: else-if blocks, which have their own colons but share their end with the initial if.)  I'm not arguing in either direction right now; I'm just pointing out that there are two competing "consistencies" that can't both be maintained.

**Comment by kfisler** [comment]
This still leaves the other part of my original issue open though, which is that the docs don't give any idea of how to order on multiple columns (none of the things I've tried have worked, so I don't think this is obvious ...) -- how does one do this anyway?

**Comment by shriram** [comment]
@blerner According to the docs:

‹table-order›: order ‹expr› : ‹column-order› end
‹column-order›: NAME ascending | descending

https://www.pyret.org/docs/latest/Expressions.html#%28part._s~3atable-exprs%29

So this doesn't square with your response that "Order operations can sort on multiple columns, so there's a block there -- you're missing an end."

**Comment by blerner** [comment]
That's true, and surprises me: and I checked the grammar, it matches the docs. I thought our ordering mechanism allowed for sorting on multiple columns...

Either we should support multiple columns, or the colon and end can go...

**Comment by kfisler** [comment]
If you do decide to change this, just make it consistent with select (which has end but no colon).

Note that I'm teaching tables starting on Wednesday this week, so if any syntax is about to change on the live CPO, I need to know no later than Tuesday noon so I can update lecture notes and assignments.  I can work with this as it is too -- just letting you know my constraints.

**Comment by shriram** [comment]
I thought one goal of having the sorting allow multiple columns was so we
could provide a stable sort over them… Stability would not be guaranteed if
you broke it up into multiple ordering commands.

**Comment by blerner** [comment]
Kathi, this is now fixed: there's now support for multiple-column sorting on tables (and it's documented -- http://www.pyret.org/docs/latest/tables.html#%28part._.Ordering_.Tables%29).  Now that it's there, the colon makes more sense.  Ok to close this issue?

**Comment by shriram** [comment]
Awesome, thank you. This is just what we wanted. Fine to close.
