### ISSUE TITLE
Consider adding a row-count operation on tables?

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1058]
As I've worked out examples for my course, I've often wanted to be able to ask how many rows are in a table. I know I could compute this by extracting some column and computing its length, but I've been wanting the row count before I get to extraction and lists.

Just a suggestion for wherever you are tracking possible additions.  Not time critical.

**Comment by jpolitz** [comment]
FWIW, there's actually a `.length()` method directly on tables, so you can do it without the `extract`.

I'm not sure if the pedagogy of methods-on-tables alongside the query syntax makes tons of sense, but it is an option.

**Comment by blerner** [comment]
@kfisler is this ok enough for you to use (and close this issue), or do you need a syntactic form here?

**Comment by kfisler** [comment]
Close it.  I already did this in class using extract.

Operating on tables as objects would have been awkward in my pedagogic
context, but adding this one operation would be ad-hoc.  At some point, we
need to discuss what pedagogic flows to support, which would let us
approach this question more systematically.
