### ISSUE TITLE
Absent column in `select` error message missing locations

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#1059]
![image](https://user-images.githubusercontent.com/119891/27646316-2b16d68e-5bdd-11e7-810e-2355c6243251.png)

**Comment by jswrenn** [comment]
Fixed with 2e93c55f5c22c81b1ad066d40cd2adc87fd4e256:
![screenshot-localhost-5000 2017-08-02 16-13-20](https://user-images.githubusercontent.com/3820879/28894428-dc2446c4-77a2-11e7-8ea4-d934200cf427.png)
