### ISSUE TITLE
Improper error arrow in table query

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#1063]
A broken REPL query generates the correct error message, but the "scroll up" arrow appears in the Interactions Area -- even though there's nothing to scroll up _to_.

![image](https://user-images.githubusercontent.com/77126/27773060-131f956a-5f3f-11e7-9e54-b921afe36750.png)

**Comment by blerner** [comment]
That's pretty funny :)

**Comment by schanzer** [comment]
This appears to be fixed on CPO, possibly due to Jack's recent changes.
