### ISSUE TITLE
Are table-column types checked for anything other than manual row creation?

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1064]
I was surprised that Pyret allowed me to write a transform expression that produced a result that violated a stated column type (example below).  Are column types checked at any point other than manual row creation?
```
wages3 = table: name :: String, hourly-wage :: Number, dept :: String
  row: "Pat", 18, "shipping"
  row: "Jay", 15, "sales"
end

transform wages3 using hourly-wage:
  hourly-wage: "low"
end
```

**Comment by blerner** [comment]
I can easily argue that since transform is creating a new table, it merely needs to use the existing values at their stated types -- but as output, it's transformed the table to one whose hourly-wage column has type string...

**Comment by blerner** [comment]
Closing as not-really-a-bug.
