### ISSUE TITLE
lin-reg-2V is in docs for statistics module, but is unbound after include

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1065]
One of my students was looking for it -- do I just tell him to hold off for now?

**Comment by schanzer** [comment]
I spoke with @SDooman about this on Slack. It looks like it's been removed, and replaced with a few functions that break out the statmodel functionality:

`linear-regression : List<Number> List<Number> -> (Number->Number)`
`r-squared : List<Number> List<Number> (Number->Number) -> Number`
etc.

**Comment by schanzer** [comment]
Since it's been removed, I'm closing.
