### ISSUE TITLE
incorrect highlighting

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1075]
![image](https://user-images.githubusercontent.com/75030/28282453-b9bb69ae-6ae7-11e7-9937-920ffebd6281.png)

This highlight is clearly pointing to the entire application, and hence the _result_ (in particular, as opposed to the _argument_). Saying "it" compounds that it must be referring to the result of the application as a whole.

**Comment by jswrenn** [comment]
I think the fix is to use `checkArgsInternal` (instead of `checkNumber`) [just as we do in the image lib](https://github.com/brownplt/code.pyret.org/blob/aeb0aa80ca794e80c26deaf1909effd3953b6514/src/web/js/trove/image.js#L738-L741). 

@jpolitz, @blerner: Are there any reasons why uses of `checkNumber` in `runtime.js` shouldn't be replaced with `checkArgsInternal`? It would improve the error messages for a slew of builtin functions, but I don't know if there would be any adverse consequences.

**Comment by blerner** [comment]
How does that help at all?  It doesn't take in srclocs for the arguments, instead it uses some generic "happened in this module" location -- which is even *worse* than the image above, since it won't show any user code at all.

**Comment by jswrenn** [comment]
Unlike `generic-type-mismatch` (the error variant raised by `checkNumber`) which carries with it virtually no information, `failure-at-arg` (the error variant raised by `checkArgsInternal`) keeps track of the argument position of the annotation failure. Consequently: 
![screenshot-code pyret org 2017-07-20 17-24-34](https://user-images.githubusercontent.com/3820879/28439641-b777df0c-6d70-11e7-8944-5f97414371b0.png)

**Comment by blerner** [comment]
Ewwwwwwwwwwww!  You get that information by reparsing the function application, don't you?  Ok, yeah, that's a much better approach, then.  That should probably be done throughout runtime.js then...

**Comment by jswrenn** [comment]
As of ad3de8147eeef5fa4fde075de7ec3f4e18792d72, nearly all argument annotation failures for builtin functions now result in `failure-at-arg` (and therefore have useful highlighting); e.g.:
![screenshot-localhost-5000 2017-07-21 16-08-21](https://user-images.githubusercontent.com/3820879/28480478-d791ed50-6e2e-11e7-98f0-70f87cd99304.png)

**Comment by jswrenn** [comment]
Something bad happened here between 5f8107e4eacdd460efdab9d76441e7cf0cc16fb9 and the merge to master: `num-sqrt("3")` now produces a fall-back error report instead of a fully highlighted one because of an internal error:
![screenshot-code pyret org 2017-09-27 11-13-31-668](https://user-images.githubusercontent.com/3820879/30921706-1b43f432-a375-11e7-8dd0-b76de51e3c0c.png)


@jpolitz, @blerner: Any thoughts?

**Comment by jpolitz** [comment]
The error is at https://github.com/brownplt/pyret-lang/blob/master/src/arr/trove/contracts.arr#L74

It seems like it was expecting to get an `s-app` and got an `s-program`.

I don't think the parser changed dramatically; maybe something in `maybe-ast` changed what it returns?

**Comment by jswrenn** [comment]
I think fixing this is as simple as adding `s-program` to the set of ignorable AST nodes here: https://github.com/brownplt/code.pyret.org/blob/ff7465eec7a0a8fb588788ccd63489a2ca48f835/src/web/js/output-ui.js#L488-L495.

**Comment by blerner** [comment]
As I recall though, in your original visitor code that got replaced by the js traversal, `s-program` nodes hadn't had special treatment. Could you confirm that this would've been a problem back with that code, too?

**Comment by jswrenn** [comment]
> As I recall though, in your original visitor code that got replaced by the js traversal, s-program nodes hadn't had special treatment.

It looks like `s-program` was skipped over in the [original visitor code](https://github.com/brownplt/pyret-lang/commit/47cc8cea0169a98fe1c2ce912261f23e286c2901#diff-a9847c39b48995b9da7555966130e3f9R3431) so this would not have been a problem.

**Comment by blerner** [comment]
Ok.  Could you go through that then and make a list of the expressions that had special treatment?  Was `s-module` (just above your linked line) also special?  (Does it matter here?) Were there others?  Then we can add them to the list of ignored expression forms.

**Comment by jswrenn** [comment]
Will do (but I'm at a Bootstrap DS PD workshop, so I won't be able to make the change until late tonight at the earliest).

`s-module` doesn't exist in pre-desugared code, so it doesn't matter here.

**Comment by jpolitz** [comment]
I'll add that some Selenium testing could go a long way towards making
these errors not slip through.
