### ISSUE TITLE
frequency chart needs to use integers

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1080]
When counting frequencies, the graph should show integers on the Y axis. Right now it seems to take the maximum - minimum, then divide by 10, and then use that value as the step. However, that results in nonsensical-looking axis labels (as a teacher said, "there can't be .2 countries in South America"), and makes it difficult to figure out how many items there actually are for some entities.

**Comment by blerner** [comment]
More generally, I think we want a plot option of "tick granularity", for both axes. The decimal marks we get by default on most graphs seem kinda perversely hard to read -- as a secondary improvement, I'd love our defaults to be more legible, too.

**Comment by schanzer** [comment]
I'd go so far as to rename the issue entirely: we need better tick marks. We should default to integers when possible, and then fall back to "reasonable" decimals based on the data being displayed - counting off by 0.5, 0.25, etc. It's obvious _why_ it does what it does now, but the user experience could definitely be better.

**Comment by schanzer** [comment]
@sorawee , OK to close?

**Comment by sorawee** [comment]
Yes!
