### ISSUE TITLE
feature request: grids in frequency bar chart

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1081]
Participants would like to be able to overlay a grid. Some form of interaction that has the same effect (making it easy to read off the values) would also be good.

**Comment by blerner** [comment]
Interactively toggleable, or given as a plot option at rendering time?

**Comment by shriram** [comment]
Interactive would be nice. People can decide which look they prefer and
then generate the final image.

**Comment by blerner** [comment]
Is this solved by #1092?

**Comment by sorawee** [comment]
Currently it looks like this

![screenshot from 2017-11-04 14-10-33](https://user-images.githubusercontent.com/9099577/32408185-34e770fe-c16a-11e7-9751-dcf6a35d35b8.png)

This is not exactly a "grid," but I think it does what the student want. Each bar also has a tooltip showing the exact quantity. I will close this. Feel free to reopen if anyone disagrees.
