### ISSUE TITLE
`mode` and `modes` not documented?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1082]
I can't find any trace of these functions in

http://www.pyret.org/docs/latest/statistics.html

We really need a principle of "no new functions without documentation". It's really unhealthy to push out "code" alone.

**Comment by blerner** [comment]
That's laughable and annoying: of course it's a good idea, but we often have to ship code in a hurry (see #1083)

**Comment by shriram** [comment]
But this is an _old_ bug. It wasn't shipped out "in a hurry", or if it was, the documentation was never patched subsequently. Surely you aren't advocating for a principle where if a function is shipped in a hurry, it _never_ needs to be documented?

**Comment by blerner** [comment]
These are now documented.
