### ISSUE TITLE
the word "series" is confusing

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1091]
Data Science participants point out that the word "series" sounds like a plural to non-native speakers, and this is confusing since it's used in a singular sense here. So that's another way this is problematic. 

(@schanzer wants me to link this to some other issue. I can't figure out which one he means, so I'm going to let him link to it.)

**Comment by schanzer** [comment]
Update: after lots of consideration and talking with both @sorawee, @blerner and other teachers, I think `DataSeries` is at least a local maxima.
