### ISSUE TITLE
labeled-scatterplot

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#1097]
A TON of teachers have identified "interesting" points in their scatterplots, and are frustrated that it's not easy to find out which row they represent. Several have asked for a `labeled-scatterplot` series, which _also_ takes in a `List<String>`. 

I think this would be incredibly valuable for students, and offers a nice pedagogical progression: "suppose we want labels on those points - what would the contract for that function be?"

**Comment by sorawee** [comment]
l or double l? https://www.grammarly.com/blog/labeled-labelled/ :) 

Yes, this is super easy to do in Google Charts.

I am going to do the same thing for histogram as well. `label(l)ed-histogram` and `unlabel(l)ed-histogram`.

**Comment by schanzer** [comment]
One-l is American English. Two is more common in British English. I'd opt for American, since I'm focused on US classrooms for now. 

https://www.grammarly.com/blog/labeled-labelled/
