### ISSUE TITLE
why do you have to include image

### ISSUE THREAD

**Issue by Efe-Bidav** [brownplt/pyret-lang#1099]
like why

**Comment by shriram** [comment]
There are different ways of defining an image library (see https://www.eecs.northwestern.edu/~robby/pubs/papers/sfp2010-bff.pdf). Someday there may be multiple image libraries in Pyret. If we forced you to use one, then you wouldn't be able to take advantage of newer, better ones. So what you're actually doing is indicating _which_ image library you want — of which, for now, there is only one, but someday there may be others.
