### ISSUE TITLE
0-based indexing in Pyret a deliberate choice?

### ISSUE THREAD

**Issue by ds26gte** [brownplt/pyret-lang#1108]
Was there ever a discussion about trying 1-based rather than 0-based indexing in Pyret (for strings, lists, arrays, etc)?

Especially if Pyret is targeted for math curricula, 1-based would have been both more traditional and intuitive. (I realize there are lots of pluses for 0-based, but I'd like to consider just math ed here.)

- 0-based simply doesn't mirror what students are learning in their math texts
- user constantly has to make ±1 adjustments in their head, e.g.,
  * length is 1+ index of last element
  * nth element is really (n-1)th (or is it vice versa?)
  * locating substrings is done by finding an ending index +1 in order to keep the difference between the index arguments equal to the substring length
  * I'm sure many more mental contortions that we've all internalized because 0-based has de facto edged out 1-based in the programming industry (although some 1-based heavyweights like Fortran, Cobol, and Lua still exist)

The jarring math dissonance is the biggest argument for 1-based. It's the same reason we've already adopted for avoiding `x = x + 1` and `1 / 2 == 0`.

--d

**Comment by blerner** [comment]
I don't think this is a particularly fruitful discussion to be rehashing, four years into the language's development and now that teachers and students have been using the existing approach.  Moreover it's an intuitive argument without much in the way of falsifiable hypotheses... But: 

* Zero-indexing satisfies closure properties that one-indexing doesn't.  Zero-based indices form semi-open intervals, and those compose with each other in ways that the closed intervals needed for one-based indexing don't.  
* We don't ever teach students the standard C-style "for i = 0 to length of string minus 1 do ..." kind of loop -- we teach map/each/filter/fold loops that don't care about indices
* Concatenating two strings S1 and S2 of length l1 and l2 results in a string of length l1 + l2.  The characters in S1 are still at indices [0, l1), and the characters in S2 are now at indices [0, l2) + l1, i.e. [l1, l2 + l2).  Trying to do that with 1-based indices would have far more fumbling around with off-by-one errors
* Strings behave the same as lists in this scheme: and in particular we have the invariant that splitting a list at an index n results in a front-part list of length n and a back-part list of length (orig-length - n), which can be composed again and get back the original list.  Finding the index of a value in the back-part of the list (after splitting) becomes an exercise in off-by-one fumbles.
* Pyret isn't "targeted for math curricula", at least not as its sole goal.

**Comment by ds26gte** [comment]
Yeah, if it's a done deal, it's a done deal. Needed to assure myself that the choice was deliberate, at least post facto.

**Comment by shriram** [comment]
Thanks for bringing it up, Dorai, but this is indeed a done deal for now.

We also adopted the computer science graphics coordinate convention, which
doesn't correspond to any of the standard quadrants. That, at least, is one
I would be open to revisiting when we have no other fires to put out. This
one, not really!
