### ISSUE TITLE
`scale-xy` doesn't draw anything with negative scale factors

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#1122]
I'd expect `scale-xy(-1, 1, an-image)` to produce a flipped image.  At the REPL, at least, it doesn't display anything at all.  @schanzer is this a bounding-box issue, a rendering issue, or just some dumb little bug somewhere?

**Comment by schanzer** [comment]
On WeScheme, negative values result in a runtime error. I have no objection to this behavior switching to "flip"

**Comment by blerner** [comment]
I'd like to see it flip -- if you imagine an animation `scale-xy(t, 1, some-image)` as t goes from positive numbers to negative numbers, it's a natural interpretation for the right side of the image to compress to zero width _and keep going_ past the left side of the image, i.e. flipping horizontally.

If we _don't_ do flipping then we _must_ raise an error.  Leaving a blank image isn't a good outcome.

**Comment by ds26gte** [comment]
As this is a `code.pyret.org` rather than `pyret-lang` issue, I've submitted a PR there: brownplt/code.pyret.org#209

**Comment by schanzer** [comment]
Since it's not a pyret-lang issue, can we close this?

**Comment by blerner** [comment]
We can close this, so long as we don't forget about Dorai's PR. :)
