### ISSUE TITLE
redundant list-to-raw-array

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1125]
There exists `raw-array-from-list` which checks for arity mismatch, etc. already. `list-to-raw-array` does exactly same thing, but has no arity check.

**Comment by blerner** [comment]
Ironically, your plot libraries are the only client of `list-to-raw-array`... ;-)

**Comment by sorawee** [comment]
Yup. I took those out from my local version already. When that get merged, I will submit another PR to clean this up. This issue is just a reminder.

**Comment by sorawee** [comment]
Related: `raw-array-from-list` checks that the arity is 2 instead of 1....

**Comment by blerner** [comment]
@sorawee is this finished, now?

**Comment by schanzer** [comment]
Confirming that `list-to-raw-array` is no longer defined on CPO. Closing.
