### ISSUE TITLE
docs example doesn't work

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1137]
https://www.pyret.org/docs/latest/tables.html contains
```
imported-my-table =
  GS.load-spreadsheet("1BAexzf08Q5o8bXb_k8PwuE3tMKezxRfbKBKT-4L6UzI")
```
But no such spreadsheet exists, so you can't actually run this code and see it work. That's bad for docs.

**Comment by jwang78** [comment]
The document exists on [Google Drive](https://docs.google.com/spreadsheets/d/1BAexzf08Q5o8bXb_k8PwuE3tMKezxRfbKBKT-4L6UzI/edit); it requires permission to access.  Turning on link sharing will solve this problem.

**Comment by jpolitz** [comment]
@belph @sorawee @jswrenn do one of you own this sheet?

**Comment by jswrenn** [comment]
No :(

Full link:
https://docs.google.com/spreadsheets/d/1BAexzf08Q5o8bXb_k8PwuE3tMKezxRfbKBKT-4L6UzI/edit?usp=sharing

**Comment by sorawee** [comment]
Not mine :(

**Comment by jswrenn** [comment]
This issue is probably best tracked in pyret-docs: brownplt/pyret-docs#23. Closing as a duplicate.
