### ISSUE TITLE
obiwan error on num-to-roughnum(<bignum>)

### ISSUE THREAD

**Issue by ds26gte** [brownplt/pyret-lang#1147]
`num-to-roughnum(1e100)` returns `~1e99`. Tests apparently didn't catch it because we were converting ratios of bignums (so the `-1`s cancel), though it's not clear why
```
check "comparing rough MAX_VALUEs":
  ~1.7976931348623157e+308 - ~1.7976931348623157e+308 is%(within-abs(0.001)) ~0
   1.7976931348623157e+308 - ~1.7976931348623157e+308 is%(within-abs(0.001)) ~0
end
```
(which contains an implicit `num-to-roughnum` of a bignum) passed during `make test` but not when explicitly tested in the IDE.

**Comment by blerner** [comment]
Looks like this is fixed; closing.
