### ISSUE TITLE
Unreachable code (according to complaint from Firefox 57)

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1149]
https://github.com/brownplt/pyret-lang/blob/7b0c78ee0b238eb9b7e9563ccdfb5947fd8658f3/src/js/base/runtime.js#L1140

**Comment by schanzer** [comment]
@sorawee do you still see this with more recent versions of FF?

**Comment by sorawee** [comment]
It's fixed now: https://github.com/brownplt/pyret-lang/blob/horizon/src/js/base/runtime.js#L1271

**Comment by sorawee** [comment]
(For reference, it's fixed in https://github.com/brownplt/pyret-lang/commit/ba4c81a968ccea1d3cc7129f30c1d0b7e48f2b55#diff-856c8edab38aab6a7aebf62b991351e6)
