### ISSUE TITLE
Invalid shadowing of id included from gdrive is reported as shadowing of built-in

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1153]
Say, in `a.arr`, we export `x = 0`

In `b.arr` which includes `a.arr`, we define `x = 1`. This rightfully results in an error. However, it says that `x` is built-in which is wrong.

**Comment by jpolitz** [comment]
This is effectively a dup of #747, same underlying cause

**Comment by sorawee** [comment]
Ah, close as dup then :)
