### ISSUE TITLE
type checker bug?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1156]
![image](https://user-images.githubusercontent.com/75030/30113475-d0e4d714-92e2-11e7-8a80-5e0a4272c1a9.png)

What am I missing here? This works just fine in the untyped language.

Since this example is critical to my first lecture, I can't actually show students the type checker, which means we're probably going to miss out on any data collection…

If you can identify the problem in the next 35 minutes, please email me directly (or even text).

**Comment by sorawee** [comment]
This needs to be changed: https://github.com/brownplt/pyret-lang/blob/master/src/arr/compiler/type-defaults.arr#L130

**Comment by blerner** [comment]
Go for it. Should be String -> list<String> right?
