### ISSUE TITLE
importing built-in modules fails with type-checker in REPL

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#1158]
![image](https://user-images.githubusercontent.com/119891/30130046-ca3ddfc2-92fc-11e7-8c24-e10ab234c69a.png)

The same thing doesn't seem to happen when running with `-type-check` offline, but if we add, in repl-tests:

```

  tc-result = restart("import lists as L", true)
  tc-result.v satisfies L.is-success-result
  should-fail-map-use = next-interaction("L.map(4, 5)")
  should-fail-map-use.v satisfies L.is-failure-result
  should-succeed-constructor = next-interaction("[L.list: 1, 2, 3]")
  should-succeed-constructor.v satisfies L.is-success-result

```

We see the same failure at the first line.

**Comment by jpolitz** [comment]
It looks like what's happening is that the REPL is trying to re-provide the name `L`, but the way the type context is constructed that doesn't get added. As a result, during `gather-provides`, the type checker is making a bad assumption that all provided values will be in the type context.

**Comment by jpolitz** [comment]
I think I need some help here @mkolosick .

First, the code in the `| s-module` case of `_checking` that I first thought was responsible for this doesn't seem to be reached. It seems like the only place that updates the `type` bindings in `context.info` is `remove-binding`.

The upshot is that there are things provided that aren't correctly noticed by the type checker when it's constructing the `info` for what's provided from a module.

In this case, it's perhaps weirder because it's happening by the REPL inserting a provide for this module. But I'm fairly sure this used to work, and I'm not sure what changed.

I added a call to `_checking` in the synthesis case for `s-module`, but that led to other issues.

**Comment by jpolitz** [comment]
Actually, it seems like any use of a builtin has issues; using `include` also causes a bizarre internal issue:

![image](https://user-images.githubusercontent.com/119891/30137114-b75165e0-9316-11e7-8c36-baef6b56b91b.png)

**Comment by mkolosick** [comment]
This is on master?

**Comment by jpolitz** [comment]
Yeah those screenshots behave the same on code.pyret.org, pyret-horizon.herokuapp.com, and my local checkout.

**Comment by mkolosick** [comment]
Okay, so this is two separate issues. I've fixed the initial one and am looking at `include` now.

**Comment by mkolosick** [comment]
And I've found the `include` issue. It seems that it adds an import of `_` for some reason. So I'm ignoring `_` imports
