### ISSUE TITLE
`all` has arguments in the "wrong" order?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1163]
When converting between functions and methods, I'd expect the object parameter to become the first argument and vice versa. This is true for `member` but not for `any`.

```
import lists as L

l = [list: -1, 0, 1]

check:
  l.member(0) is L.member(l, 0)  # `l` became first parameter on the right
  l.any(_ == 0) is L.any(_ == 0, l)  # `l` became second parameter on the right
  L.any(l, _ == 0) raises "Function"  # `l` can't be the first parameter
end
```

I realize this would be awkward for functions like `map`, which conventionally take a function as the first argument, so perhaps there's nothing that can be done about it?

**Comment by blerner** [comment]
The function arguments come first so that these hofs are compatible with for-syntax. Member isn't a hof...

**Comment by shriram** [comment]
Aaargh. Inconsistent design constraints.
