### ISSUE TITLE
rudimentary program doesn't type-check

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1164]
A cs019 student wasted a bunch of time unable to do homework because he was unable to run

```
fun test(str :: String) -> List<Number>:
string-to-code-points(str)
end

check:
test("abc") is [list: 97, 98, 99]
end
```

(and various variants of it). The problem is that `string-to-code-points` has type `Any`, and so results in a type error. Once we got him out of the Type Checker mode, he's fine, and finally able to start on his homework.

Color me not happy. At all.

**Comment by sorawee** [comment]
I have a fix in my computer. Pushing soon.
