### ISSUE TITLE
`+` on lists not recognized by type checker

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1167]
`[list: 1, 2] + [list: 3, 4]` works fine in untyped but not in typed code. Is that intentional? If so, I would like to request a better error message: the current error highlights the `list` and says "Unable to infer the type of the expression. Please add an annotation", which is baffling.

Worse, it happened to a student who reported the following:
```
Unable to infer the type of the expression at
splitter(r,[list: ""] + titles)
Please add an annotation.
I have an annotation in the first line of the function, so I am not sure how to proceed:

splitter(chars :: List<String>, titles :: List<String>)-> List<String>:
```
Sure enough, this is a pretty baffling response to fix.

**Comment by jpolitz** [comment]
It's not intentional. A bit more information that suggests something weird is going on:

```
lst :: List<String> = empty

lst + [list: "b"]
```

type-checks, but

```
lst :: List<String> = [list: "a"]

lst + [list: "b"]
```

Says it can't infer the type of `lst`.

**Comment by sorawee** [comment]
Two interesting things:

```
fun iden(x :: List<String>) -> List<String>: x end
a :: List<String> = empty
iden([list: ""]) + a
```

type checked. But parametric polymorphism seems to fail:

```
fun iden<A>(x :: List<A>) -> List<A>: x end
a :: List<String> = empty
iden([list: ""]) + a
```
not type checked.

**Comment by mkolosick** [comment]
Okay, I've found the issue for all of these (it's one bug). The issue was that the constraint solver wasn't properly applying substitutions internally between its phases. I've fixed the bug for master in the type-fixes branch.
