### ISSUE TITLE
call home for new versions?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1170]
Multiple students in 19 are trying out the type checker. They've all been running into bugs — bugs that @mkolosick fixed yesterday. But there is no way for them to know when to reload their buffer to get a new version. Could CPO periodically call home [modulo network availability — if there's no network, don't kill the battery…] and tell the user "A new version is available"? Some poor student seems to have spent forever trying to figure out how to get around a particularly complex configuration of `Any` errors when a reload would have shown him his code was fine all along.

**Comment by blerner** [comment]
Isn't this encouraging the opposite of what we want to do, namely have CPO/master be *stable* for the duration of the school year?

I'm ok with this concept on CPO/horizon, but for master this seems to be encouraging the wrong attitude of "it's ok if we break stuff; CPO will notify students when we fix^H^H^Hchange it!"

**Comment by shriram** [comment]
But we did just push out a critical fix without which the type checker was unusable, and would have resulted in no users at all this fall.

**Comment by blerner** [comment]
Yes, and that's a failure on Pyret's part, one that shouldn't be made up for by another failure of design.  CS019 is the only client of the type checker right now; presumably you have another out-of-band communications channel?

We need to figure out out a policy for when we're allowed to update Pyret in the middle of the year.  Building a notification channel into CPO itself seems like a remediation to a policy problem we haven't solved yet.

**Comment by shriram** [comment]
This has nothing to do with the type checker. You're saying if there were a critical bug in Pyret — e.g., Google Drive changed its API due to a security breach, and saving to Drive no longer worked — we wouldn't patch it midstream?

The out-of-band-channel isn't the question. I can't notify people about things I don't know, and nor can any other instructor.

But you're right the real problem isn't calling home. It's notification. Why wasn't there a message sent to the mailing list saying "We just pushed an update, here's what changed, if it affects you, please reload"? We don't need new software complexity, but given our total unwillingness to use the mailing list, I don't know what else we can do to keep users informed. There seems to be a total lack of culture on that, and I've pretty much given up on asking.

**Comment by jpolitz** [comment]
I think it's pretty reasonable ​to add a check that can display a message:
"there are updates to Pyret available, please save and reload to get the
newest version".

That's not hard to do, given that we have commit hashes stored in multiple
places and can do a straightforward comparison; the server knows the
current commit hash, and the page knows the one it was served with.

The mailing list point is good, and orthogonal to this.

**Comment by jpolitz** [comment]
Happy to take suggestions on wording:

![image](https://user-images.githubusercontent.com/119891/30334168-aa202182-9793-11e7-865d-36499bbe6208.png)

**Comment by blerner** [comment]
I'm inclined to show Bonnie spinning in this bar, to make it a bit more 
noticeable than the usual info-bars...

**Comment by jpolitz** [comment]
That seems confusing. Usually when Bonnie is spinning, it means something is working and I should be patient and wait for it to stop.

**Comment by schanzer** [comment]
This wording is so generic - I would read that as some kind of XSS attack, and notify the Pyret team immediately.

**Comment by shriram** [comment]
I agree w/ @schanzer. Why doesn't it at least say "A new version of Pyret" instead of "an update for this site"?

**Comment by jpolitz** [comment]
The current solution is OK, but leaves something to be desired.

I think we should have a release notes link in the message, which requires putting release notes with every push.

Also, I'm not convinced that every push needs a release indicator; sometimes it really doesn't matter if folks refresh, we just want to get a change out that has something to do with logging, etc, and it's not worth interrupting people's workflow to do that.

So some kind of dev-side control here could go a long way, for providing the release messages and for tagging releases as user-prompting or not.

**Comment by schanzer** [comment]
@shriram so now we DO call home and display something, but as @jpolitz points out there's something to be desired. Would you like to keep this open and rename it, or does it make more sense to close this one and open a new issue specific to the dev-side control?
