### ISSUE TITLE
bad "shadowing" error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1175]
[Running on CLI.]

If you have an identifier named `sets` in your program, you will get weird "shadowing" errors: eg,
```
stelvio ~/Desktop/CodePyret> pyret mst.arr 
1/1 modules compiled (mst.arr)      
Cleaning up and generating standalone...
The declaration of the identifier named `sets` at file:///Users/sk/Desktop/CodePyret/mst.arr:80:16-80:20 shadows the declaration of an identifier also named `sets` at file:///Users/sk/Desktop/CodePyret/mst.arr:1:0-109:70
There were compilation errors
```
This error is meaningless because `sets` is not "declared" anywhere in the program. The program doesn't even include/import the sets module! So a user has no way of making sense out of this.

**Comment by blerner** [comment]
A little more context for triaging this would be helpful.  What does the program say?  Does the same error happen for other libraries (like lists, or option, or whatever)?

**Comment by shriram** [comment]
Here's a complete file:
```
sets = 3
```
This produces
```
Cleaning up and generating standalone...
The declaration of the identifier named `sets` at file:///Users/sk/Desktop/CodePyret/sd.arr:1:0-1:4 shadows the declaration of an identifier also named `sets` at file:///Users/sk/Desktop/CodePyret/sd.arr:1:0-1:8
```

**Comment by shriram** [comment]
Same happens if I replace `sets` with `lists` (with the error message updating, of course).

**Comment by blerner** [comment]
This no longer occurs; closing.
