### ISSUE TITLE
`spy` documentation?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1176]
(Where) Is `spy` documented?

**Comment by blerner** [comment]
It is: https://github.com/brownplt/pyret-docs/blob/21d142c9a5b827dac85e88c13a34f7c924e55948/src/lang/spies.scrbl  But that's on the horizon branch of docs so far; it's not merged to master yet.

**Comment by jpolitz** [comment]
You can read it at https://www.pyret.org/docs/horizon/s_spies.html

**Comment by schanzer** [comment]
@shriram , OK to close?
