### ISSUE TITLE
Test case produces refinement error

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1191]
```
data PHR:
  | phr(name :: String,
        height :: Number,
        weight :: Number,
        heart-rate :: Number)
end

# Added data type used to store BMI data
data PersonBMI:
  | personbmi(name :: String, bmi :: Number)
end

fun get-bmi(person :: PHR) -> Number: ... end


fun phr-to-bmi-list(phr-list :: List<PHR>) -> List<PersonBMI>:
  doc: "Converts a list of PHRs into a list of PersonBMIs"
  cases (List) phr-list: 
    | empty => empty
    | link(f, r) =>
      link(personbmi(f.name, get-bmi(f)), phr-to-bmi-list(r))
  end
where:
  phr-to-bmi-list([list: phr("eugene", 2, 60, 77),
      phr("matty", 1.55, 58.17, 56 ),
      phr("ray", 1.8, 55, 84),
      phr("mike", 1.5, 100, 64)]) is
  [list: personbmi("eugene", 60 / (2 * 2)), 
    personbmi("matty", 58.17 / (1.55 * 1.55)),
    personbmi("ray", 55 / (1.8 * 1.8)), personbmi("mike", 100 / (1.5 * 1.5))]
end
```

Type-checking this program produces what looks like an internal error message:

  "Refinements should have been removed"

There's no highlight, indication of where to fix what, etc.

Note that removing the single test case for `phr-to-bmi-list` gets rid of this error, so there's some unhappy interaction between type annotations and tests. But since tests should only be relevant for _inference_, and inference is unnecessary in the presence of annotations (though the inferred type can be checked against the annotated one), the error is particularly baffling. 

Is the problem that the tests are inferring types with variant refinements while the annotations lack the variant refinements, even though in this case there is only one variant so the variant and type are effectively the same? Even if that is the general problem, it needs a far better error report to make clear what went wrong. I think it is also not practical to expect users to write refinements in type headers.

Of course, the explanation could be something entirely different.

Problem found by Spencer Cheleden.

**Comment by mkolosick** [comment]
This is from the test inference, but it is from the extra test inference that is being used for logging (therefore it still runs with the annotation there). But this is likely just a logic bug in the test inference software so I'll iron that out.

**Comment by mkolosick** [comment]
@blerner, @jpolitz: should a fix to a bug like this get pushed to horizon or done as a pull request on master?

**Comment by jpolitz** [comment]
Horizon preferred; I can then handle moving over to be released. Thanks!
