### ISSUE TITLE
add example of multiple named args to contract docs

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1194]
It's useful to have an example like
```
add :: (a :: Number, b :: Number) -> Number
fun add(a, b): a + b end
```
in the docs to show how to write multiple named arguments in a top-level annotation header. It might also be worthwhile to have a variant of this that drops one of the names (say the `b :: ` part) and indicates that this is an error: if you name one, you must name them all.

Btw, I'm not sure whether this exactly matches the BNF:
![image](https://user-images.githubusercontent.com/75030/30785461-fc5b8a68-a134-11e7-8f46-7943f9172d65.png)
looks to me like it's saying each `NAME :: <ann>` pair must also be surrounded by parens.

**Comment by schanzer** [comment]
Named contracts are used in at least [the Table library documentation](https://www.pyret.org/docs/latest/tables.html#%28part._tables_running-fold%29)

**Comment by blerner** [comment]
Shriram, there's a font-color convention at work there: black text is exact literals, but gray text is BNF meta-notation.  So the paren and star is repetition notation...

**Comment by shriram** [comment]
Aargh.

**Comment by schanzer** [comment]
@shriram I can't parse "aargh" :) Does this mean it's ok to close?
