### ISSUE TITLE
`<>` doesn't work in Typed Pyret

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1195]
![image](https://user-images.githubusercontent.com/75030/30789456-9f10cda2-a173-11e7-9381-d0c9c722c1dd.png)

Please fix ASAP. This syntax was shown to students, so some of them will try to use it soon.

**Comment by jpolitz** [comment]
Fix should show up in 30 min or so.

**Comment by jpolitz** [comment]
This fix ended up showing up this morning, rather than last night. Release-pushing mistake on my part, sorry.
