### ISSUE TITLE
presentation of types in type error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1203]
```
type NSet = List<Number>

mt-set = empty

insertD :: Number, NSet -> NSet
fun insertD(n, s): ... end

list2set :: List<Number>, (Number, NSet -> NSet) -> NSet
fun list2set(s, i): ... end

list2setD :: List<Number> -> NSet

fun list2setD(l):
  cases (List) l:
    | empty => mt-set
    | link(f, r) =>
      insertD(f, list2set(r))
  end
end
```

Note that the recursive call in `list2setD` should have gone to `list2set`. Also, the problem is independent of whether the function bodies are defined or not; I purposely replaced them with `...` to give you a smaller program, but that's not the issue below.

The problem is with the way types are being printed:

![image](https://user-images.githubusercontent.com/75030/30915429-d37dd380-a364-11e7-86ea-c2965641fcd2.png)

Surely it's a bug that the type is being printed with all those commas? And even otherwise, it needs a pretty-printer to know where to and not use spaces, etc. The current form of output is just not readable and I claim a true bug (because of the commas).

**Comment by blerner** [comment]
This seems like it's a goof in using the valueskeleton to render the output, and not a deeper issue.  Shriram, I think if you `s/, //g` in that output, you turn
```
(, List, <, Number, >, , , (, Number, , , List, <, Number, >,  -> , List, <, Number, >, ),  -> , List, <, Number, >, )
```
into
```
(List<Number>(NumberList<Number> -> List<Number>) -> List<Number>)
```
which looks pretty-printed to me.

**Comment by shriram** [comment]
Well, that needs a few spaces and commas there. I'd have preferred to see
```
(List<Number>, (Number, List<Number> -> List<Number>) -> List<Number>)
```

**Comment by blerner** [comment]
Heheh.  They probably are there, and I couldn't distinguish between the commas in the output, and the commas separating the output items ;-)  I bet that's what the `, , , ` actually were.

**Comment by blerner** [comment]
(All I'm saying is, I'm 99+% sure that this is properly pretty-printed according to how the AST pretty-prints itself, and I know that that's correct by definition.  I just don't know offhand where the rendering glitch is in the valueskeleton output; that's Matthew's to find and fix.)

**Comment by shriram** [comment]
Oh, I agree, I don't think this is a deep bug at all. Just a different printer, and maybe a bit of smoothing to get the spacing right.

**Comment by mkolosick** [comment]
This is what the type `_output` is producing
```
vs-seq([list: vs-str("("), vs-seq([list: vs-str("List"), vs-str("<"), vs-str("Number"), vs-str(">")]), vs-str(", "), vs-seq([list: vs-str("("), vs-str("Number"), vs-str(", "), vs-seq([list: vs-str("List"), vs-str("<"), vs-str("Number"), vs-str(">")]), vs-str(" -> "), vs-seq([list: vs-str("List"), vs-str("<"), vs-str("Number"), vs-str(">")]), vs-str(")")]), vs-str(" -> "), vs-seq([list: vs-str("List"), vs-str("<"), vs-str("Number"), vs-str(">")]), vs-str(")")])
```
which looks right to me. Additionally, from the command line this prints properly as `(List<Number>, (Number, List<Number> -> List<Number>) -> List<Number>)`. So this is likely a CPO bug.

**Comment by blerner** [comment]
`vs-seq`  as rendered by cpo/output-ui.js adds its items into a container, and I think that container's CSS styling is what's adding the comma-space separation.

**Comment by mkolosick** [comment]
I guess the question then is: what are the semantics of the different value-skeleton forms? Is that correct and I should be using a different form?

**Comment by jpolitz** [comment]
My take is that this is a command-line bug, since other things rely on
commas in sequences (I think; I know I showed @schanzer how to use it for
data science).

A simple solution may be to just stringify the whole type and stick it in a
vs-str, because the vs-seq doesn't seem to be doing much useful structuring
here.

There's a separate question of if we want to put a delimiter-and-bracket
construct into valueskeleton, which could be useful for things like type
arguments.

**Comment by mkolosick** [comment]
Fixed in https://github.com/brownplt/pyret-lang/commit/09fb97db09b0652e3d001570eab1e7e3e8a565bb

**Comment by blerner** [comment]
Note that this is an unfortunate workaround; the better solution will be to revamp `valueskeleton` to include this sort of sequencing...and we're gonna need to revamp `valueskeleton` anyway because we want control over length and depth elision.  So this is fine for now, but let's remember to come back to it once we redo this data type...
