### ISSUE TITLE
result-after-check collides

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1207]
From a student in CS173:

```
include my-gdrive("a.arr")
include my-gdrive("b.arr")
```

results in an error because of `The declaration of the identifier named result-after-checks1 shadows ...`

where 

```
# a.arr

provide *

check:
 1 is 1
end
```

```
# b.arr

provide *

check:
 1 is 1
end
```

**Comment by jpolitz** [comment]
Confirmed offline, too. That's a stupid hygiene bug with check blocks. Moving provide resolution later seems to have caused some hidden issues.

I think the solution needs to be more explicit information about synthetic names in places like `get-named-provides` and friends.

**Comment by sorawee** [comment]
Close as a dup of #1566
