### ISSUE TITLE
another "refinements should have been removed" error

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1210]
```
data File:
  | file(name :: String, size :: Number, content :: String)
end

fun get-sizes(lof :: List<File>) -> Number:
  cases (List) lof:
    | empty => 0
    | link(f,r) =>
      f.size + 1 + get-sizes(r)
  end
where:
  get-sizes([list: ]) is 0
  get-sizes([list: 
      file("system32", 1, "delete this"), 
      file("virus.exe", 1, "pls open"), 
      file("emails", 30000, "inside")])
    is 30005
end
```

Note that deleting the first test (empty list) still produces the error, so the problem is caused entirely by the second test.

**Comment by shriram** [comment]
@mkolosick Students are still getting this error, and since it's fatal, they have to stop using the type checker for that assignment. These are students trying to use it in part (they say) because we asked them to try it out and provide feedback, so we don't want to lose them.

**Comment by mkolosick** [comment]
@jpolitz: This is fixed on horizon in https://github.com/brownplt/pyret-lang/commit/88ecfa8c3a61299eb24b9c0197c4bfc570f7f113, should we make the fix on master or merge horizon?

**Comment by jpolitz** [comment]
Thanks, I'll push this out today.

**Comment by jpolitz** [comment]
Or at least I hope to. Fighting with a recent update of `npm`'s stable version on Travis that is buggy. Sorry for the delay.

**Comment by shriram** [comment]
Thanks. Please notify when it's done.

**Comment by mkolosick** [comment]
@jpolitz This seems to be done. Can you confirm and close?

**Comment by blerner** [comment]
@jpolitz @shriram ping?

**Comment by shriram** [comment]
Well, I don't see the error any longer, so we can close this. I'm a bit annoyed that this notification never happened, so we didn't get to tell students to go back to using the checker, thereby probably losing useful student data…but that's unrelated to this PR.

**Comment by jpolitz** [comment]
Sorry – I actually got it working that same night, and it looks like I just
never re-notified. :-/  I'm not sure if there's a good automation solution
here, since even notifying folks of new Pyret versions wouldn't tell you
it's _this_ fix that happened. I just need to track things like this better.
