### ISSUE TITLE
losing old .arr files

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1211]
Student Michael Litt reports:

I've had a recurring problem that occasionally when I go back to some of my old '.arr' files in Google Drive, the contents of the file have been completely wiped, and I am left with a blank document.

If I right-click on the file and select "Manage versions..." I am able to restore the working code by deleting the newest version (sometimes I need to do it more than once for the non-wiped version to be restored). I have never manually deleted all of my code from a file, so I think this may be a bug with the Pyret website.

While I can't determine what causes this to happen, I think it usually happens when I open files through the Pyret interface.

When this happened to me the most recent time, I double checked all of my old submissions to make sure none were affected by this bug. It seems that only my bmi-1.arr (from DS2) ended up being submitted as a blank file. I know that I can't resubmit since it is long past the deadline, I was hoping that this bug could be looked into so that it doesn't happen in the future.

**Comment by dlicata335** [comment]
The same thing happened to one of my students.  In case it helps with debugging, I think the sequence of events was: she had the file saved and not open in a browser window, and then opened it in code.pyret.org to run it, and saw a blank file (both in code.pyret.org and when downloaded).  The code was in the previous revision in the revision history in Google Drive.

**Comment by schanzer** [comment]
I've had the same thing happen

**Comment by blerner** [comment]
Joe, could it be a race where our credentials are incorrect to read the file, so it shows up blank, then the credentials get populated enough to autosave the file (and thereby blank it out)?

**Comment by jpolitz** [comment]
I'm pretty sure it's a run-of-the-mill race with loading things from the Open dialog and saving a currently-blank editor. I believe it only happens if the editor is currently blank and you use the file picker. I'm testing to be more sure.

**Comment by jpolitz** [comment]
Closing because I think the fix above resolved it; we know what to reopen if we see it again.
