### ISSUE TITLE
Case branches can contain unbound constructors

### ISSUE THREAD

**Issue by dlicata335** [brownplt/pyret-lang#1213]
Sorry if there is already an issue for this; I couldn't find one on a quick search.

Should this be a scope error (checked while "Run"ing the file)? 

```
data Foo:
  | c(y :: Number)
end

fun ok(x :: Foo):
  cases (Foo) x : 
    | d(y) => true  # typo, d instead of c
  end
end
```

Since expressions/right-hand sides are scope-checked statically, it seems to me like left-hand sides should be as well.

**Comment by blerner** [comment]
Yup, known limitation right now. In untyped mode, we plan to allow this, but in typed mode we eventually plan to have checking for invalid branches, and totality of all branches. There's some static information that needs to be plumbed from one module to the next in order for this to work out, and we've got most of that machinery working now.

**Comment by blerner** [comment]
In terms of "scope checking" those constructor names are really just treated as labels, not as identifiers, so it's not a scope error, per se...

**Comment by dlicata335** [comment]
OK, thank you!  Happy to hear that typed mode will catch it.  

Personally, even in untyped mode, I would expect a name resolution error, because the way datatypes are treated doesn't suggest "anonymous labeled sum" to me: I have to write the name of a type in the annotation on the cases (though it seems I can put Any there); and constructor names can't be overloaded (? as far as I can tell), so for a given case expression there can be at most one data declaration that defines the constructor names that it uses.    So there's no way to write ``cases (Any) - : | f(x) => blah end`` and use it work for "any type that happens to have a constructor labeled f" (? again, as far as I can tell).  This makes things seem a little weird under the product/sum duality
```
{f : 7, g : "hi"}   vs   cases (?) ... : | f(x) => ... | g(y) => ... end
r.f                     vs    f(r) 
```
because for products both are allowed, but for sums the case analysis is allowed and the injection is rejected (because there's no syntax for combing a value and a label to make an element of an anonymous sum type, dual to the . projection for records).  I'm not particularly arguing for anonymous sums as a language feature; but  for named datatypes, it's harder for me to think of the constructors as free-floating labels rather than scoped references to a binding site.

But anyway, a tiny issue that I won't likely run into once I can use the typed mode!

**Comment by schanzer** [comment]
This appears fixed on CPO. The program in question now generates the correct error when run with type-checking turned on. @blerner , OK to close?

**Comment by blerner** [comment]
Yes, but there's a related bug to file, unfortunately... ;-)
