### ISSUE TITLE
PAPL Chapter 8

### ISSUE THREAD

**Issue by Kaykwanu** [brownplt/pyret-lang#1219]
I am having issues getting past this chapter. Pyret keeps saying that "The identifier set-size is unbound:"

check:
  song-set3 = [set: lver, so, wnkkhs, so, so, lver, so]
  song-set is song-set3
  set-size(song-set3) is 3
end

More so, I can't seem to run this:

fun an-elt(s :: Set):
  cases (Pick) set-pick(s):
    | pick-none => error("empty set")
    | pick-some(e, r) => e
  end
end

Pyret also says "Pick" is not defined as a type and that both "set-pick" and "error" are unbound.

Is this a case of the intentional mistakes included in the book, as part of teaching style? I can't seem to figure it out. Please help.

**Comment by Kaykwanu** [comment]
![chapter 8 papl](https://user-images.githubusercontent.com/23130491/31390486-f67cbff6-adcb-11e7-9e96-15199ae153d4.JPG)

**Comment by shriram** [comment]
Thanks for the feedback. I'll think about how to improve this section, but for now, to help you make progress:

- Instead of `set-size(S)`, write `S.size()` and you'll get the size.
- `error` should be `raise` (thanks!)
- Add `include pick` at the top of your program [https://www.pyret.org/docs/latest/pick.html]

Hope this helps you make progress for now.

**Comment by Kaykwanu** [comment]
That was really quick. Thanks. But on correction,

include pick
fun an-elt(s :: Set):
  cases (Pick) set-pick(s):
    | pick-none => raise("empty set")
    | pick-some(e, r) => e
  end
end

Pyret says "set-pick" is undefined? I tried this though:

include pick
fun an-elt(s :: Set):
  cases (Pick) s:
    | pick-none => raise("empty set")
    | pick-some(e, r) => e
  end
end

Is that fine? Find attached.

**Comment by sorawee** [comment]
Use `s.pick()` instead of `set-pick(s)` :)

**Comment by Kaykwanu** [comment]
Really appreciate the prompt response. Thanks alot.

**Comment by blerner** [comment]
Closing as resolved?
