### ISSUE TITLE
convenience constructor and parenthesis

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1220]
`[1 + (2): 3]` parses fine

`[(1) + 2: 3]` somehow is not.

(very low priority indeed)

**Comment by blerner** [comment]
This is an easy fix:  in the tokenizer, make the LBRACK token have `parenIsForExp: true`.  This shouldn't affect much, possibly only some quirky tests.

**Comment by sorawee** [comment]
@blerner : fixed?

**Comment by blerner** [comment]
Fixed by d89fc0e20e27b9e45a2fd18f89e8e9e635cce182 and 78c29be2ea99980c5f5f4a94f105f20de6762186.
