### ISSUE TITLE
Cursor position when resizing definitions/interactions frame

### ISSUE THREAD

**Issue by dlicata335** [brownplt/pyret-lang#1229]
There's some bug in the handling of the cursor position when you resize the left/right definitions/interactions frames.  This happens to me a bunch in lecture, when I make the interactions frame wider to show something, and then go back to coding on the left.  (Chome on a Mac in case that's important).  

To reproduce:
1) have some text in the definitions frame, with the cursor also in the definitions 
2) make the interactions bigger, so that it line-wraps the text in the definitions.  The cursor will stay in the same physical location on the screen through the resizing, as the text moves.  
3) but the next time you type something, the cursor will jump back to the *text* position it was at before the resizing.  

Also, 
1) have some text in the definitions frame, but the cursor in the interactions
2) make the interactions bigger, so that it line-wraps the text in the definitions.   
3) click in the definitions, and the cursor will (sometimes) appear where you clicked 
4) but the next time you type something it jumps somewhere else
In step 3, the cursor will sometimes not appear where you typed, but elsewhere on the line (I think if the clicked position is not a valid position for the "logical" position in the text that it seems to think the cursor is at, which seems like it's relative to the text before the window resizing).

**Comment by blerner** [comment]
This is very likely a bug in CodeMirror (the editor toolkit we use to show the definitions area and the individual REPL lines).  We've seen issues like it before, when e.g. you change the font size.  It may be worth investigating if there's a newer version of CM that is still basically compatible with us (CM has an annoying habit of occasionally breaking API compatibility) but happens to fix this bug.  I'd looked into things like this before, and found myself stymied by the innards of CM not being particularly easy to reverse-engineer.

Question: in your scenarios above, what happens between steps (n-1) and n, if you resize the overall browser window?  My hunch is that the cursor location will fix itself...

**Comment by dlicata335** [comment]
that works -- thanks for the workaround! The best one I had found was that changing the font size also resets it.

**Comment by schanzer** [comment]
The new `cm.refresh()` calls @blerner  added make it impossible for me to reproduce this bug. Recommend closing?

**Comment by dlicata335** [comment]
thank you!
