### ISSUE TITLE
test block output looks buggy

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1231]
I ran

```
fun iter(a :: Number, b :: Number, count :: Number) -> Number:
  if count == 0:
    b
  else:
    iter((a + b), a, (count - 1))
  end
end


fun fib(n :: Number) -> Number:
  iter(1, 0, n)
where:
  fib(10) == 55
end

fib(10)
```

Note that `fib(10)` evaluates to `512`, not `55`. But the output looks like this:

![image](https://user-images.githubusercontent.com/75030/31855448-785f9e1e-b6a3-11e7-8dd8-fed5785ffb8e.png)

where clicking on the green block causes a small expansion but nothing more.

**Comment by blerner** [comment]
What did you expect to see? There indeed are no tests in that test block...

**Comment by YanyanR** [comment]
When students use "==" instead of "is" in check block, would it be helpful to give an error message like _you need to use **is** operator for testing_?

**Comment by sorawee** [comment]
There are multiple testing operators, so saying "you need to use is" wouldn't be correct. But we can report "you need to use some testing operator (e.g., is)"

But I recall @blerner has some opinion about how Pyret should be easy to comment out tests. Not sure if making this an error is a good idea (warning might be OK, idk)

**Comment by jpolitz** [comment]
This is an opportunity for Pyret to be really smart and impressive with relatively little effort. We should capitalize on that. Suggesting testing operators here is totally the right thing to do.

I don't want to go down the warning road for this feature – we've avoided having a notion of a warning thus far, and I don't think this is sufficiently different from other well-formedness issues to warrant a new UI concept.

**Comment by shriram** [comment]
Fair enough, I edited the title to say it _looks_ like a bug. But it sure does. This is a mistake I've made a few times before, and it's just not obvious what the problem is when you do, in part because one way to *read* `==` is "is".

I suppose there might be some use to having a naked, Boolean-valued top-level expression inside a testing block, but it's not clear to me what real use it has (other than triggering a side-effect, which isn't really the purpose of testing blocks), especially as the last value. Sure seems to me this should be a well-formedness error at least in (ahem) student language levels.

**Comment by jswrenn** [comment]
@blerner: There _is_  a bug here, though: what ought to go in that blue box? Usually, it's where we write "All tests passed!". While that's vacuously true in this case, I'm not sure it's a very appropriate message.

**Comment by shriram** [comment]
In fact, a message that said "There were no errors to pass" would actually be a useful clue to the student that the block didn't do quite what they wanted. (Of course, this doesn't help if they have a few real tests and a few `==` "tests".)

**Comment by blerner** [comment]
Well, there _is_ that message already, in the green box.  But I agree that the blue box should've said something at all, and that something should be informative.

We've gone back and forth over allowing standalone expressions-as-statements in test blocks, and IIRC we hadn't quite decided in either direction but were leaning towards permitting them.  Does this mean we're leaning towards _disallowing_ them now?

**Comment by jpolitz** [comment]
Looking at this for the nth time, it is becoming obvious to me that making this an error is the right thing to do.

Actually, it has been in my mind for quite a while:

https://github.com/brownplt/pyret-lang/issues/383

This is actually a good first issue for someone to learn the WF checker.

**Comment by jpolitz** [comment]
Note that this is different than allowing expressions-as-statements in general.

But binary operators, field lookups, etc are really weird to have as standalone statements.

**Comment by schanzer** [comment]
CPO now reports this as a WF-error, and even recommends `is` when using `==`! 

I recommend closing this, and _maybe_ opening another issue about being smarter when recommending testing operators based on whatever boolean we see inside a `where` block.

**Comment by shriram** [comment]
This looks great.
