### ISSUE TITLE
cannot use images with types

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1237]
```
include image
rectangle(1, 2, "solid", "blue")
```
produces the error

![image](https://user-images.githubusercontent.com/75030/32250246-1345cfe6-be62-11e7-8dc4-582d0ccae7e1.png)

**Comment by sorawee** [comment]
https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/trove/image.js is needed to be changed.

**Comment by blerner** [comment]
Yes.....and we should decide for really-real this time, whether we're going to switch from a stringly-typed API to a strongly-typed one.

**Comment by schanzer** [comment]
I'm in favor of the switching, as long as we have a compatibility story. But either way, we should include the proper types in both libraries.

**Comment by mkolosick** [comment]
What should I do about `ImageColor` in, for example, the type of `circle`?

**Comment by schanzer** [comment]
In the old API? Those functions consume strings. If those don’t map to a color, it’s a runtime error

**Comment by blerner** [comment]
Right. The question is, concretely, how and when do we transition to the new API with Color arguments. I'd like to avoid Racket's fate of having "images" and "images2", and would rather have "images" be the better typed module. The only sticking point is how that impacts Bootstrap and its pedagogy, and I know you're concerned to avoid any unnecessary concepts whenever possible.  Are Colors unnecessary, or helpful? How would you like to see the transition between apis happen?

**Comment by schanzer** [comment]
Something I’ve learned from data science is that you want to keep the number of types to “do the basics“ as small as possible. My gut sense is that we could provide the old API through the Pyret equivalent of a teachpack, and then introduce the real API partway through the class for students and teachers who are interested.

@Emmay , would you have a problem with requiring all reactive programs to have an `include` line at the top?

**Comment by Emmay** [comment]
All reactive programs already use two include lines: include image, and
include reactors. Would this change the image library at all, or change the
need for including that library? If the library is only changing under the
hood, there won't be any change for reactive programs.

**Comment by blerner** [comment]
I'm suggesting that it *would* change the image library, and we could provide a "simple-image" library that continues to provide the use-strings-as-color-names API that we currently have.

**Comment by schanzer** [comment]
@shriram , Now that the migration question is settled, and we have a library that addresses the issue, is this OK to close?
