### ISSUE TITLE
type checker internal error on `!`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1240]
This program works fine in the untyped version but effectively gives an internal error in the typed version:
```
data Box<T>:
  | box(ref v :: T)
end

n1 = box(1)
n1!v
```
This is problematic because it means we can't use the type checker on any of the remaining assignments in 019.

(I'm curious how this got past the test suite, because it's such a rudimentary program.)

Note that there are two problems:

- the fact that this produces an error at all
- the output of which says "One or more internal errors prevented us from showing the best error message possible. Please report this as a bug."

**Comment by mkolosick** [comment]
This was due to a typo in substitution for references. It got past the test suite because it only occurred when a reference field was on a polymorphic data type.
