### ISSUE TITLE
internal error in accessing mutable fields through `.` instead of `!`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1241]
Given
```
data CList: clink(v, ref r) end

white = clink("white", empty)
grey = clink("grey", empty)
```
we can write `white!r!r!r`, etc. We can also write `white.r` which prints what looks like the same thing as `white!r`, though there's a subtle difference: the former says "cyclic ref" while the latter says "cyclic object". Still, both look like constructed values: `clink("grey", clink("white", <cyclic-something>))`. But while we can write `white!r!r!r`, we can't write `white.r.r.r`. This produces an error with two problems:

![image](https://user-images.githubusercontent.com/75030/32375153-ec8a55c2-c076-11e7-84d4-27a7f28ba623.png)

1. The output doesn't make clear why I couldn't take the `.r` field.

2. It has an internal error.

**Comment by shriram** [comment]
Another "transparent ref" problem:
```
n1 = box(1)
n1.v # evaluates to 1
n1.v + 3
```
produces

![image](https://user-images.githubusercontent.com/75030/32375238-487d85ac-c077-11e7-921a-de9ab9b82e66.png)

**Comment by shriram** [comment]
Also, seemingly paradoxically:

![image](https://user-images.githubusercontent.com/75030/32375376-bab5edf8-c077-11e7-9542-7bbdd2899a44.png)

Alright, transparent refs suck.

**Comment by blerner** [comment]
No, it evaluates to something that currently renders (slightly but almost indistinguishably differently) as 1.  That's the same complaint as https://github.com/brownplt/pyret-lang/issues/936.

**Comment by blerner** [comment]
And given that that screenshot is *identical* to #936, one of these bugs needs to be marked as duped.

**Comment by shriram** [comment]
Dup of #936. Just need to make sure these examples are all considered when that is fixed. Left a comment there to this effect so this isn't lost.
