### ISSUE TITLE
internal error in error reporting on common, natural error

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1258]
![image](https://user-images.githubusercontent.com/75030/32947701-3f5ed392-cb6a-11e7-8990-a329d1abf0f0.png)

**Comment by jswrenn** [comment]
This was fixed by brownplt/code.pyret.org@5ed26eaa8022c41f3139be7b44da12731482a626 about a month ago and is resolved on horizon.

**Comment by jpolitz** [comment]
:-( Sorry, pushed out now.
