### ISSUE TITLE
No tests warning is wrong for empty check/where

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#127]
The warning the command line gives about no tests is incorrect if empty `where` or `check` blocks are defined.  We should detect programs that define a testing block, but don't throw exceptions dynamically, and give a different warning.

**Comment by schanzer** [comment]
Well-formedness now complains about empty blocks on CPO, so I'd call this fixed.

**Comment by schanzer** [comment]
Any resolution on whether or not an empty block is considered not-well-formed? Current behavior is "no". If that's what we want, this can be closed.

**Comment by schanzer** [comment]
pinging @jpolitz @blerner

**Comment by jpolitz** [comment]
I'm going to close this as not being important – if the warning text starts to cause issues, we can re-report this.
