### ISSUE TITLE
`make` should run `make phaseA`

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1272]
@mkolosick raised this issue up somewhere but I think it got lost.

**Comment by blerner** [comment]
This has gotten even less useful recently, now that `make` seems to run something related to stopify...

**Comment by jpolitz** [comment]
Huh? It runs `browserify`, but there's no Stopify on horizon.

Agree that this should change, though.

**Comment by blerner** [comment]
Mrph, meant to say "browserify" -- they're both "ify", though! ;-)
