### ISSUE TITLE
include doesn't work inside compiler

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1275]
I `include file('ast-transformer.arr')` but Pyret doesn't seem to recognize ids that are in the module. If I use `import`, there's no error. Also note that I used to use `include file` before when grading 173 and there seems to be no problem.

**Comment by jpolitz** [comment]
I can't reproduce this. If I change e.g. `import file("js-ast.arr") ...` to `include file("js-ast.arr")` I don't get an error at the module-finding phase. Where did you put the include/import?

**Comment by sorawee** [comment]
Seems to work to me now. I might have been hallucinating.
