### ISSUE TITLE
Publishing code

### ISSUE THREAD

**Issue by Jasleen1** [brownplt/pyret-lang#1279]
Hi!

I seem to be having trouble accessing published code. For example, if I use the link from pressing publish and paste it to an in cognito window, it just keeps loading. 

Thanks!

**Comment by sorawee** [comment]
Can you give more details? E.g., what link is it? What's your browser / OS?

**Comment by Jasleen1** [comment]
Here's a link:
https://code.pyret.org/editor#share=12hYF2xKfvmpqvWEaQOSVASePbBtzVOto&v=45205ac

The browser is Safari on a Mac, in cognito. I just tried it in Firefox and
it worked.

**Comment by sorawee** [comment]
Whoops. I thought it's a random program. Please don't publish an assignment solution publicly!

When you run it in Safari and it keeps loading, there should be an error appearing in the JavaScript console. Can you follow the instruction in https://www.wickedlysmart.com/hfjsconsole/ to open the console and report what you see?

**Comment by Jasleen1** [comment]
I'll get back to you on the technical part but it's not publically -- I'm interviewing with a company that does functional programming and wanted to talk about a code sample during the interview. Is that ok?

**Comment by schanzer** [comment]
@jpolitz do we want to leave this open? It's 3 years old and we were never able to reproduce it...

**Comment by schanzer** [comment]
@jpolitz I'm going to close this, but feel free to re-open if you feel strongly.
