### ISSUE TITLE
Awkward function name from sugar

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1284]
```
for lam(x): x end():
  1
end
```

results in

```
<function:for-body<line 1, column 0>>
```

**Comment by blerner** [comment]
I'm not particularly concerned by this: this is a particularly obtuse way of using lambdas and for-syntax, so it's not likely to come up particularly often.  And while we need *some* kind of name here, I don't think this one's particularly worse than others.  The display-name of a function is not part of the semantics of Pyret...

**Comment by jpolitz** [comment]
Yeah this seems pretty reasonable. I don't know of a qualitatively different alternative than using the location of the for body.
