### ISSUE TITLE
Non-associative roughnum equality error

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#1301]
These should certainly produce the same result, not one be `false` and the other be `true`.

![image](https://user-images.githubusercontent.com/119891/35179011-6b5a277c-fd46-11e7-9bc3-ab201e83d39c.png)

**Comment by blerner** [comment]
Yikes.  That's a sloppy mistake to have allowed through!  Is this a 
recent regression, or did we screw this up for quite some time now?

**Comment by ds26gte** [comment]
Is it ok that both return `false`? (They can't return `true`. The only other option is a `can't compare` error.)

**Comment by SethPoulsen** [comment]
Should this issue be closed since its a duplicate and the other identical issue has a pull request for it?
