### ISSUE TITLE
When tests fail but the code is otherwise OK, REPL should still import defined identifiers

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1306]
Consider:

```
fun foo(x):
  x
where:
  foo(10) is 11
end
```

The test fails, and `foo` is simply unbound in the REPL because of that. However, perhaps I still want to try out what's wrong with `foo` on different input. So I think that REPL should still import `foo`.

**Comment by SethPoulsen** [comment]
I can't duplicate this in Firefox or Chrome.

**Comment by sorawee** [comment]
Apparently I was being non-sense (by the way, this kind of problem would be compiler-related, so it should be browser-independent)
