### ISSUE TITLE
Convenience constructor should accept method as well

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1320]
```
[{method make1(self, x): x end}: 1]
```

results in "The left side was not a defined convenience constructor."

while:

```
[{make1: lam(x): x end}: 1]
```

works fine.

**Comment by blerner** [comment]
I'm not sure I agree with this, actually: the compilation of convenience constructors is meant to be fast, and it may not know whether the field is a lambda or a method.  Which means that we'd have to use the slow `getField` *every single time* we use a convenience constructor, and which (in the method case) would allocate a lambda that closes over the self argument.

Do you have any important use case for needing this ability, or is it just coming from a sense of design symmetry?

**Comment by sorawee** [comment]
Design symmetry

**Comment by blerner** [comment]
Talked this over with Joe: closing as not really necessary.
