### ISSUE TITLE
Overly currying in function application

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1321]
```
(_.a(_))({a: num-to-string}, 2)
```

produces "2". But I think this is not right. In particular, I expect `_.a` to evaluate to `lam(x): x.a end`, so `(_.a(_))` evaluates to `lam(y): (lam(x): x.a end)(y) end` which should accept one argument, not two.

**Comment by blerner** [comment]
No, this desugaring is by design.  Methods are defined here as `method a(self, arg): ... end`, so you can curry over both `self` and `arg` simultaneously.

**Comment by sorawee** [comment]
Sorry, I don't understand your comment.

All other `ds-curry-*` obeys this rule:

If `e = syntax(..., e2, ...)`, then either 
- `e2` is an underscore, resulting in `e` evaluating to a lambda, 
- `e2` is not an underscore, and `e2` will be evaluated normally.

This rule is the reason why we can't curry two levels deep.

If this currying is by design, then I argue it's not consistent with other designs.

**Comment by blerner** [comment]
Methods are not quite as syntactically compositional as that -- think of them as an infix operator.  `_ + _` is a single lambda with two arguments, and the infix operator is `+`.  `_.a(_)` is likewise a single lambda with two arguments, and the infix operator is `method a`.

**Comment by sorawee** [comment]
Again, there's no `method` in my code... Syntactically, `_.a(_)` is:

```
s-app(s-dot(..., "a"), ...)
```

**Comment by blerner** [comment]
Syntactically yes, but semantically no.  That specific pattern gets ANFed into `a-method-app`, not `a-app` -- see anf.arr, line 354.  Suppose I had a function
```
fun foo(obj):
  obj.a(5)
end
check:
  foo({a: lam(x): x + 3 end}) is 8
  foo({method a(self, x): x + 6 end}) is 11
end
```
Both tests pass, because at compile time we compile `o.f(a)` to a method application, and at runtime we determine whether the invocant has a lambda or a method there.

**Comment by jpolitz** [comment]
To be clear (and mostly just restating what @blerner says, but with an eye on the semantics vs. implementation here):

- The desugaring is syntactic, and is a convenience specific to matching on this nested dot-plus-app form. It's a concession to the fact that the syntax `o.f(x)` is often an application of a method value, which makes it convenient to curry in a specific way.
- _Semantically_, `o.f(x)` is exactly equivalent to
    ```
    m = o.f
    m(x)
    ```
    However, the former may be _faster_ because it's easier to recognize the pattern and avoid allocating a closure to create the function that closes over the receiver `o`. The `method-app` forms are there to make this optimization easier to write.
