### ISSUE TITLE
Using a built-in module name as a type causes an internal error

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#1332]
For example:

```
a :: option<Number> = some(5)
```

which is an easy typo of the intended program:

```
a :: Option<Number> = some(5)
```

**Comment by jpolitz** [comment]
NB: This is a namespace error, not a type-checker error

**Comment by blerner** [comment]
Well it's slightly less bad on the modules branch: `"Name not found in globals.types: option"`

Still not good, but at least the internal error is avoided
