### ISSUE TITLE
Weird (?) contract-weaving scope

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#1339]
I wrote this program, and was surprised that there wasn't an unbound type id:

```
build-col :: (t :: Table, col :: String, builder :: (Row -> A)) -> Table
fun build-col<A>(t, col, builder):
  t.build-column(t, col, builder)
end
```

Note that the `A` in the standalone contract is bound by the `<A>` in the function definition, which appears "later".

I don't think there's anything unsafe or unsound about the binding structure, it just feels weird.

My icky feeling would be remedied if we had a way to write a forall type for a standalone contract, like:

```
build-col<A> :: (t :: Table, col :: String, builder :: (Row -> A)) -> Table
```

**Comment by blerner** [comment]
I suspect this would be solvable more easily as
```
build-col :: <A>(t :: Table, col :: String, builder :: (Row -> A)) -> Table
```
which to my eye looks even more identical to the function header
```
fun build-col<A>(t :: Table, col :: String, builder :: (Row -> A)) -> Table:
```
i.e. a grammar of
```
contract-stmt: NAME COLONCOLON [ty-params] (ann | noparen-arrow-ann)
```
There's some annoying little bits of AST constructor-arguments plumbing to do to mush those names through to where we weave annotations, but it shouldn't be too bad.
