### ISSUE TITLE
Passing build-column a single argument results in internal errors

### ISSUE THREAD

**Issue by doshiro** [brownplt/pyret-lang#1346]
For example. using [this code](https://code.pyret.org/editor#share=0BzzMl1BJlJDkbnZhbE1QSEE0eEE) (Animals Dataset with functions from Bootstrap: Data Science) and running`animals-table.build-column("nametag")` or `animals-table.build-column(nametag)` results in 

> Internal errors prevented this error message from being shown. Please report this as a bug.

Whereas I would expect something like the error that results from this code:
`animals-table.filter(is-kitten, "is-kitten")`

> 3 arguments were passed to the operator.
>The operator evaluated to a method accepting 2 parameters.
>An application expression expects the number of parameters and arguments to be the same.

Edit: looking at this now, I only see two arguments, rather than 3 as the error claims.

**Comment by blerner** [comment]
The third argument is `animals-table` itself, which is the `self` argument for the method.  Good catch on the error!  Fix coming up...

**Comment by doshiro** [comment]
@blerner 
> The third argument is animals-table itself, which is the self argument for the method

Ah, I remember this being mentioned! It might be helpful for the highlighting to reflect this. As it is currently implemented, only nametag and "nametag" are highlighted in purple, like one would expect.

![screenshot](https://user-images.githubusercontent.com/30014374/42011077-a004e19c-7a46-11e8-8b7f-04ef22d05cef.png)

It's confusing that there are only 2 highlights when the error implies there should be three.

**Comment by blerner** [comment]
This is a longstanding concern, and this is the best compromise that's feasible in general.  By the time users get up to methods, we address the number-of-arguments issue.
