### ISSUE TITLE
Add optional `because` clause to `is`/`is-not`/`is-roughly` tests

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#1350]
In writing down test cases, we have a design tension between the following two styles of tests:
```
examples:
  distance(0, 0, 3, 4) is 5
  distance(0, 0 3, 4) is num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0))
end
```
The first shows the final answer, while the second shows your work.  We use the second form in the boostrap design recipes, to figure out the body of the function.  But what if that formula simply is wrong?  Then the second test case passes because it matches the function definition, but not because it matches the intended answer.

Proposal: add a new optional clause to `is` (and `is-not`, `is-roughly`) tests
```
examples:
  distance(0, 0, 3, 4) is 5 because num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0))
end
```
The semantics are: 
* Evaluate all three expressions
* If the latter two are not equal, we can provide a very interesting error message: "The test was inconsistent: the expected answer and the expected formula do not match.  Make sure both of these are consistent with each other."  
* If the latter two are equal, compare the expected answer to the actual answer and give the existing test-case feedback messages we currently have.

And we get a much better pedagogy (IMHO): we start off by writing just `foo is bar` test cases, without the `because` clause.  Then, we can explain that there's no good way to see how to construct the answer from the inputs, so introduce the `because` clause and continue with the DR from there.  Then, we can say "Once you're confident in your formula, you can write tests without needing the `because` clause.  Or, if your functions have gotten complex and you're not sure why they're failing, you can *add* a `because` clause to a simple test, to see whether you're expectations are consistent!"

**Comment by jpolitz** [comment]
Love it.

I just want to discuss shorter names than `because` since horizontal space is premium in worksheets, etc. Some ideas:

```
  distance(0, 0, 3, 4) is 5 since num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0))

  distance(0, 0, 3, 4) is 5 also num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0))

  distance(0, 0, 3, 4) is num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0)) aka 5

  distance(0, 0, 3, 4) is 5 from num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0))

  distance(0, 0, 3, 4) is 5 by num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0))

  distance(0, 0, 3, 4) is 5 via num-sqrt(num-sqr(3 - 0) + num-sqr(4 - 0))
```

**Comment by blerner** [comment]
A small plug in favor of `because`: it lends itself to in-class dialogue. Teacher: "What should your example produce?" Student: "42." Teacher: "But *why* should it produce that?" Student: "Because ....(some reason)..." Teacher: "Great, write that down!" I doubt many students would start that dialogue with "since" or "via" or whatever; I suspect the natural connective word there is "because".

If we don't want to create a new keyword, and don't mind reusing one we already have, we might consider `using`, perhaps? I would like the out-loud reading of this test to indicate causality between the answer and the formula designed to produce that answer.  The suggestions `by` and `via` are decent, though I suspect `via` isn't a familiar word (and, in Spanish it means "road", so that's not a helpful connotation for bilingual students). I don't like `also` and `aka` (the latter isn't even a word, so that's not ideal). `since` is an interesting compromise. So is `from`, which also is an existing keyword.

I'm imagining that we write
```
foo is bar
  because blah-blah-blah-blah-blah-blah-long-formula
``|
And stylistically we expect a two-line test.  I recognize that this is luxurious use of space when we're trying to smash things into a single DR worksheet, so that might not work in general...


(BTW, for the eagle-eyed among you: there is nothing semantically preventing a student from writing `num-sqr(2) is 2 * 2 because 4` -- the semantics are symmetric with respect to the second two expressions. Which is a large part of why I want the reading of this test form to suggest an idiomatic ordering of the three components.)

**Comment by shriram** [comment]
I LOVE THIS. 

I've asked in the past for the ability to chain multiple `is`s (there might well be a PR on it) for this reason, but that's awkward for parsing, etc. And for that matter it's not clear you need an _arbitrary_ number.

This beautifully solves the problem.

The argument for the verbose `because` is the same as that for `otherwise` in `ask`: it's about the verbalization.

Ben's follow-up also answered the question I had, which is that there's nothing in the rules preventing abuse/misuse of what goes after `is` and what after `because`. I'm happy with the symmetric semantics.

The "interesting" error message can be a bit less verbose ("Make sure the two are consistent" is better than "Make sure both of these are consistent with each other") but this is a minor nit.

**Comment by mfelleisen** [comment]
@blerner pointed me to this issue. I like this idea and seems to make a lot of sense to me, even for the first couple of weeks for Fundamentals I. 

Here is how I wrote it down real quick: 
```
(begin-for-syntax
  (define-syntax-class value
    (pattern x:number)
    (pattern x:boolean) ))

(define-syntax (check-expect stx)
  (syntax-parse stx
    #:literals (because)
    [(_ actual-value expected-value)
     #'(check-equal? actual-value expected-value)]
    
    [(_ actual:expr expected:value because justification:expr)
     #'(begin
         (check-equal? actual expected)
         (check-equal? actual justification))]))

(define-syntax (because stx)
  (raise-syntax-error #f "used out of context" stx))

;; - - - student code - - - 

(check-expect (+ 1 1) 2 because (+ (+ 0 1) (+ 0 1)))
(check-expect (+ 1 1) (- 2 0) because (+ (+ 0 1) (+ 0 2)))
```

Note how the restriction on the second clause insists on a syntactic value, which I equated with number and boolean here but could expand to everything in BSL with a few more lines. You may wish to do this too just to prevent strange test report messages from showing up.

**Comment by shriram** [comment]
Infix syntax in BSL! Hallelujah!!!

**Comment by blerner** [comment]
As I'm working on this issue, I'm noticing that **if** we allow `because` on test operators besides `is`, then there is indeed an asymmetry in the semantics: The relationship between the *actual* and the expected answer should be the same as the relationship between the *explanation* and the expected answer.

E.g. `doubler(1) satisfies is-even because (2 * 1)` ==> "The actual answer satisfies is-even because the explanation satisfies is-even."  The other ordering wouldn't even make type-correct sense...  So the general case is `A op B because C` passes when `C op B` and `A op B`, for whatever the test operator is.

The only symmetric case, it turns out, is the unadorned `is` operator (or `is==` or `is=~` or `is<=>`) -- anything else is actually asymmetric.

As a design question: do we want to allow `because` on the other test operators?  I'm inclined to allow it, under these semantics.

**Comment by blerner** [comment]
The negated test operators are indeed tricky.  `is-not`, violates`, `raises-other-than` and `raises-violates` are tricky to read as a three-part relation.  The only example I have of a negated test operator right now that I'm somewhat happy with how it reads is `dice-roll() is-not 7 because num-random(6) + 1` == "A dice-roll is not 7 because a random number up to 6 is not 7".

Thinking about how this works for other test forms is intriguing, too.  A roughnum computation can't be evaluated reliably as "A because C" and "A op B", because there's no safe way to compare A and C.  (Which notion of equality do you unconditionally use, in every possible scenario?)  For `satisfies` connectives, the whole point is we don't know exactly what A is, or can't efficiently check its structure, so both it and C can only relate to B; A and C can't relate directly to each other.

Of our testing operators:
1. is, is-roughly, is==, is=~, is<=>
2. is-not, is-not==, is-not=~, is-not<=>
3. satisfies
4. violates
5. raises, does-not-raise
6. raises-other-than
7. raises-satisfies
8. raises-violates
I think this `because` form reads most fluently with the odd-numbered entries here (the positive test forms), works so-so with 4, 6 and 8, and works least well with 2.  Should we prohibit `because` on those negative forms?

**Comment by jpolitz** [comment]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/119891/89936546-abc55580-dbc8-11ea-9b94-20d0d8a4b86c.png">
