### ISSUE TITLE
Emacs' pyret-indent doesn't work

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1355]
Got the following error:

```
or: Wrong type argument: pyret-indent, [pyret-indent 0 0 0 0 0 0 0 0 0 ...]
```

GNU Emacs 26.1

**Comment by sorawee** [comment]
Seems to be related to https://github.com/skeeto/elfeed/issues/217

**Comment by blerner** [comment]
Not sure about that, but -- did you recompile pyret.el?  Bytecode files (.elc) aren't portable between versions of emacs...

**Comment by sorawee** [comment]
@blerner it's actually about how our code assumes that defstruct's instance will be a vector, but this is not true in Emacs 26. Fixed in the above PR :)
