### ISSUE TITLE
File errors not catchable

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#137]
```
#lang pyret
import File as F
try: F.input-file("dne") # file "dne" does not exist in the working directory
except(e): "caught";
```

Because of the way the FFI is set up, this results in an exception that Pyret cannot catch.  Either in ffi-helpers.rkt (if we want to design a broader solution), or in filelib.rkt (if we want to solve it in this particular case), the Racket exception needs to be wrapped in something more meaningful.

**Comment by blerner** [comment]
@jpolitz closeable since Pyret doesn't have try/catch?
