### ISSUE TITLE
explain alignment strings

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1375]
https://www.pyret.org/docs/latest/image.html#%28part._image_.X.Place%29

XPlace talks about both "middle" and "center". Are these the same? YPlace talks about the same two; same question. Also YPlace talks about "baseline". It would be good to explain these options.

**Comment by shriram** [comment]
Sure, file a report there if you want.

**Comment by blerner** [comment]
This is an easy doc fix; I'll handle it.  But note that the YPlace "baseline" argument doesn't even work properly right now until the new image library lands, so...that's a fun little caveat :-\

**Comment by blerner** [comment]
Fixed in docs
