### ISSUE TITLE
make reference to Racket more explicit

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1376]
The image teachpack has a prominent link at the top to

https://www.pyret.org/docs/latest/image.html

But this is pretty confusingly done. It's not clear to a random reader what "HtDP" is or a "teachpack" is, or even that this is a reference to something in _some other language_. One of the physics teachers clicked through to it and went and tried to copy random expressions from those docs into the CPO REPL. Naturally, even the syntax doesn't work, which leaves them baffled.

(I'm not excusing a person randomly clicking around, but there is simply too much contextual baggage to that block.)

**Comment by schanzer** [comment]
@blerner is this fixed on horizon? I see a commit that resolves it..
