### ISSUE TITLE
Image library's `open-image-url` not defined

### ISSUE THREAD

**Issue by ZacharyEspiritu** [brownplt/pyret-lang#1377]
The [`open-image-url`](https://www.pyret.org/docs/latest/image.html#%28part._image_open-image-url%29) function described in the `Image` documentation is not defined:

```
import image as I
I.open-image-url  
# => Evaluating this field lookup expression errored 
```

Unsure if this is a documentation error or a renaming, since `image-url` is documented to do the same thing and exists.

**Comment by blerner** [comment]
Docs error

**Comment by schanzer** [comment]
IIRC, we deprecated that in favor of image-url (and eventually spreadsheet-url, file-url, or whatever else)
