### ISSUE TITLE
search for docs

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1382]
Can we please get a search box for the documentation? I can sometimes be really hard to find things, and not being able to search by words is pretty frustrating. There's no need to build a facility; just a Google search box with `site:https://www.pyret.org/docs/` would be a big help.

**Comment by sorawee** [comment]
This is now implemented in horizon (https://www.pyret.org/docs/horizon/)

**Comment by shriram** [comment]
YESSS!!! THANK YOU!

**Comment by shriram** [comment]
Unfortunately it's not perfect w/ Google injecting itself into the way,
e.g.,

[image: image.png]

If there was a way of setting search parameters to tell Google to *only* give
results from the site, that would be very awesome.

**Comment by sorawee** [comment]
I can't see the image. Can you try it one more time? (perhaps using the Github interface directly, or use an image link instead)

**Comment by shriram** [comment]
![image](https://user-images.githubusercontent.com/75030/43538472-22fd0048-9590-11e8-9989-631bc6bc2ef5.png)

**Comment by schanzer** [comment]
@shriram this is now implemented in the latest docs, and google no longer gets in the way. OK to close?
