### ISSUE TITLE
Relative-tolerance equality around 0 is annoying

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#1389]
I know I'm a big proponent of relative tolerances (rather than absolute tolerances), but the behavior of this around zero is quite annoying:
```
check:
  0.0000001 is-roughly 0.0000001 # Succeeds
  0.0000001 is-roughly 0.00000001 # Fails
end
# because
check:
  10 is-roughly 10 # Succeeds
  10 is-roughly 1 # Fails
end
```
The second example in each block is certainly not within one-millionth (relatively) of the other value.  But it's pretty hard to argue that 0.0000001 and 0.000001 aren't both roughly zero, so these two tests would fail:
```
check:
  0.0000001 is-roughly 0
  0.00000000000000000001 is-roughly 0
end
```
Maybe we should reconsider this?  I dunno...

**Comment by shriram** [comment]
Wow. That is *super *counter-intuitive!

**Comment by hilmar-hoffmann** [comment]
I found [this link](https://www.mathworks.com/matlabcentral/answers/26743-absolute-and-relative-tolerance-definitions) that pretty much covers the problem and potential solutions, just as an external frame ...

**Comment by blerner** [comment]
Resolved by https://github.com/brownplt/pyret-lang/pull/1749/commits/dfae63b60175bca95ffa5ae117fe1e615e7da556#diff-67bf1956cb18e4eafd9e3ae63013cb1c2006209c3cb628b0851ff071c8495c6bR2031-R2032, https://github.com/brownplt/pyret-lang/pull/1749/commits/dfae63b60175bca95ffa5ae117fe1e615e7da556#diff-ad83f78f81957dc7c5692096f28b09773ab1047ae7be82d518875cf4964b7ee4R569-R572, https://github.com/brownplt/pyret-lang/pull/1749/commits/dfae63b60175bca95ffa5ae117fe1e615e7da556#diff-67bf1956cb18e4eafd9e3ae63013cb1c2006209c3cb628b0851ff071c8495c6bR6033-R6037, https://github.com/brownplt/pyret-lang/pull/1749/commits/db6cbe348d6f66a77cde4f88e4325886e621a5a2, and other changes in https://github.com/brownplt/pyret-lang/pull/1749.

This should be available on CPO-horizon relatively soon.
