### ISSUE TITLE
Typo in documentation for fold

### ISSUE THREAD

**Issue by miragordin** [brownplt/pyret-lang#1395]
There is a small typo in the documentation for the functions [`fold`](https://www.pyret.org/docs/latest/lists.html#%28part._lists_fold%29) and [`foldr`](https://www.pyret.org/docs/latest/lists.html#%28part._lists_foldr%29): In the function signature (light blue box), the base is said to have type `a`, but in the expository text below that, the base value is said to have type `b`. 

In order to be consistent with the documentation for [`.foldl`](https://www.pyret.org/docs/latest/lists.html#%28part._lists_.List_shared._methods_foldl%29) and [`.foldr`](https://www.pyret.org/docs/latest/lists.html#%28part._lists_.List_shared._methods_foldr%29), I think the base should universally (i.e. for functions `fold`, `foldl`, and `foldr`) have type `b` and the list elements type `a`, so that, for example, the signature for `fold` would read:
```
fold :: (
f :: (b, a -> b),
base :: b,
lst :: List<a>
)
-> b
```

**Comment by jpolitz** [comment]
Thanks, fixed. Prompted by your suggestion, I went ahead and made more meaningful names for these (`Base` and `Elt`) everywhere:

file:///Users/joe/src/pyret-docs/build/docs/lists.html#%28part._lists_foldl%29
