### ISSUE TITLE
better error message for misuses of `raises`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1407]
Suppose I have accidentally written
```
fun f(l):
  cases (List) l:
    | empty => raises("should not get here")
  end
end
```
[Note: `raises` instead of `raise`.] The error is half-useful:
![image](https://user-images.githubusercontent.com/75030/45751204-b004b600-bbdf-11e8-89a3-b9b097b0f1b0.png)
The hint to a "comparison operator" is weird when it's just as likely the person got confused or even had a typo and really was looking for `raise` instead.

(I know in general we don't want errors to reveal "dangerous" features — and don't have language levels to address that — but `raise` and `raises` go hand-in-hand, and indeed students typically see `raise` before `raises`, so it's not clear that it makes sense to "hide" it here. Therefore, I would suggest adding the line

> You may have been looking for the `raise` operator, or perhaps you meant to use a comparison operator instead.

[I can't recall in what context the comparison operator became the right thing to suggest, but I'm sure someone will remember and remind me…]

**Comment by blerner** [comment]
```
if (1 + 1 is 2) then: ... else: ... end
```

As for `raise` vs `raises` --- ugh, this is slightly tedious to fix.  It requires plumbing knowledge of which bad operator was encountered, from parse-pyret.js (line 1558) through ffi.js (line 468) all the way down to the error message itself (line 2603), so it can render.  It's doable.
