### ISSUE TITLE
clicking run dropdown while program is running causes running indicator to disappear

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1411]
Run this program:
```
fun f():
  f()
end

f()
```
The Run button says Running and Bonnie spins.

During this time, the Run button is no longer active.

However, the dropdown button next to it still is.

Selecting it causes the selection to overwrite the Run button, and the spinner disappears, even though the program is still running.

I think it's as simple as deactivating the dropdown exactly when Running is active.

**Comment by ds26gte** [comment]
This appears to have been fixed with the addition of the a11y code. Try https://pyret-horizon.herokuapp.com rather than https://code.pyret.org.

I admit I didn't specifically notice or address this: But I had to rewrite the toolbar from scratch for other reasons.

**Comment by jpolitz** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/119891/89936452-80db0180-dbc8-11ea-9c0d-4a2f311b07b1.png">

(The arrow is disabled)
