### ISSUE TITLE
should all quotes auto-convert?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1412]
When this is pasted into CPO,
![image](https://user-images.githubusercontent.com/75030/46832050-0abea700-cd73-11e8-9269-400a656888dc.png)
it turns into
![image](https://user-images.githubusercontent.com/75030/46832092-232ec180-cd73-11e8-88d6-46b334de56bc.png)

Arguably only the outer quotes should have been converted. 

(I'm okay with this being a #wontfix.)

**Comment by blerner** [comment]
I *think* we want to #wontfix this, because I *don't* think we want to be in the business of trying to actually tokenize-and-parse pasted-in snippets of code to check for balanced quotes...

**Comment by blerner** [comment]
Closing as #wontfix, since no one's commented on this further in ~10 months and I don't want to take on the implementation complexity here.
