### ISSUE TITLE
Examplar issue

### ISSUE THREAD

**Issue by geoffglass** [brownplt/pyret-lang#1421]
![image](https://user-images.githubusercontent.com/30180478/46983510-d0287780-d0ae-11e8-96bf-ab43b034fd78.png)

**Comment by geoffglass** [comment]
Expected output is 0 chaffs rejected, 2 wheats accepted.

**Comment by jswrenn** [comment]
I can't reproduce this. Did the problem resolve itself for you?

**Comment by geoffglass** [comment]
Yes, it seems like it was specific to one computer in the lab.
