### ISSUE TITLE
Some colors listed in documentation aren't defined

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1424]
Neither light-slate-gray nor slate-gray appear defined.

circle(50, "solid", "light-slate-gray") yields error that this is not a valid color (same for slate-gray).

I just know about these two based on an error report from a teacher.  I haven't done any systematic checking of the others

**Comment by blerner** [comment]
Same as #1316?  If so, this should be fixed in the new image library... Which obviously doesn't help yet, I know.

**Comment by kfisler** [comment]
Looks the same.  I'll tell the teacher to avoid all the colors mentioned in #1316

**Comment by blerner** [comment]
Closing as duplicate of #1316
