### ISSUE TITLE
1 and l look very similar in editor

### ISSUE THREAD

**Issue by berkowitze** [brownplt/pyret-lang#1426]
The "1" (one) and "l" (lowercase L) characters look extremely similar in the Pyret edit which has led to some frustrating debugging. Any chance they can be rendered more obviously?

**Comment by blerner** [comment]
On which browser, on which operating system?  Those affect which fonts the browser will actually use...

**Comment by berkowitze** [comment]
**Chrome & Mac**
![image](https://user-images.githubusercontent.com/10499901/48284686-16fb5a00-e42e-11e8-8776-31f3ba58ecf5.png)

**Firefox & Mac**
![image](https://user-images.githubusercontent.com/10499901/48284711-31353800-e42e-11e8-8fb3-a98f092cff77.png)

**Safari & Mac**
![image](https://user-images.githubusercontent.com/10499901/48284720-3a260980-e42e-11e8-8f95-33020652ea4c.png)

**Comment by schanzer** [comment]
https://github.com/brownplt/code.pyret.org/issues/152

**Comment by blerner** [comment]
Closing here, since the CPO issue should track the UI fixes.
