### ISSUE TITLE
Examplar issue 

### ISSUE THREAD

**Issue by jennifernino** [brownplt/pyret-lang#1428]
The predicateis-linkin the annotation atfile:///home/examplar/examplar/node_modules/pyret-lang/src/arr/compiler/well-formed.arr:316:37-316:51 at (file:///home/examplar/examplar/node_modules/pyret-lang/src/arr/compiler/well-formed.arr:316:37-316:51)returned false for this value:

[list: ]
One or more internal errors prevented us from showing the best error message possible. Please report this as a bug.

**Comment by jswrenn** [comment]
Hi @jennifernino. This is a known bug in the version of Pyret used by Examplar, and it's typically encountered if you have an empty `check` block anywhere in your test suite.

CPO uses a version of Pyret that doesn't have this bug. To get a proper error message to help you fix your program, open the 'File' dropdown in Examplar, select 'Open in Code.Pyret.Org' and run your test suite there. You should get an error message pointing you to exactly where the empty block is.
