### ISSUE TITLE
code is really faint in Brave

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1430]
In the Brave browser, the code looks really faint and washed out:

![image](https://user-images.githubusercontent.com/75030/48564088-bce21500-e8c3-11e8-8629-c340770b5344.png)

**Comment by blerner** [comment]
On which OS?  I think this is just a general Windows-doesn't-have-that-font issue...

**Comment by shriram** [comment]
OS X

**Comment by schanzer** [comment]
@shriram this is no longer an issue in modern Brave versions on OSX. OK to close?

**Comment by shriram** [comment]
It seems much better now.
