### ISSUE TITLE
Make `import` paths be relative to the `.arr` file's directory

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#144]
Pyret-racket resolves paths relative to the location of the `.arr` file being run.  Pyret-node currently resolves paths relative to the current working directory.  This means you can't run Pyret files from other directories in both modes, to confirm they behave the same...

**Comment by blerner** [comment]
@jpolitz  does this bug make any more or less sense with the new module system?  It's been a very long time since we've been running Pyret-on-racket...

**Comment by jpolitz** [comment]
Yeah this makes a lot of sense.  Modulo making sure we have a good
cross-platform path library, I wrote the rudimentary version of this​,
which works, at
https://github.com/brownplt/pyret-lang/commit/47ce864e65d4c6e0d46c5a8adb81790cd4149727

**Comment by blerner** [comment]
Is this now obsolete, given the new locator stuff?

**Comment by jpolitz** [comment]
Hey, this works with `file` imports now!
