### ISSUE TITLE
re-indentation should not go into multi-line comments

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1440]
Consider this program:

```
var acc = 0

#|

fun change-acc(n):
  acc := acc + n
end

fun move() block:
  vel := vel + acc
  pos := pos + vel
end

|#
```

When I re-indent all, it becomes

```
var acc = 0

#|

   fun change-acc(n):
  acc := acc + n
   end

   fun move() block:
  vel := vel + acc
  pos := pos + vel
   end

|#
```

This may or may not be related to https://github.com/brownplt/pyret-lang/issues/553 but either way it's an issue with the current CPO.

**Comment by blerner** [comment]
Unrelated, I think.  It's more to do with the idea that when we incrementally press Enter to add a new line and auto-indent it, we want the bodies of block comments to be indented by one level.  Further, we have an explicit check that says (https://github.com/brownplt/pyret-codemirror-mode/blob/master/mode/pyret.js#L942-L950) if we see a line of text that's indented to exactly the level of the comment, then it needs to be indented further, but if it's already been indented to some custom level, don't muck about with it.  We need this check in order for _incremental_ indentation to work, and we only get one indentation function (which doesn't get a mode flag to know whether it's in incremental or reindent-all mode)...

**Comment by blerner** [comment]
Also note that when the indentation method gets called, it gets called one line at a time -- so it doesn't even know that the block comment might be terminated some number of lines ahead.  CodeMirror basically enforces that `indentAll = for each line: indent line`, without any extra context.

**Comment by blerner** [comment]
@shriram are you ok closing this as a technical-limitation?

**Comment by shriram** [comment]
I guess. It's really annoying but it's not messaging up anything functional, and when that code gets uncommented it can just be reindented again, so it's not the end of the world.

**Comment by blerner** [comment]
I sympathize :(  If/when we upgrade to CodeMirror 6, I'll look into revisiting this.
