### ISSUE TITLE
image APIs to enable shifting 0,0

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1450]
This tweet
https://twitter.com/AndrewSommer78/status/1126173306179035136
asks:
"Is there a way to shift the point 0,0 to the middle of an image or background, in stead of the bottom left corner?"

What might such an API look like? We know how to do this, easily, in user-land: it's just a bit of arithmetic on the coordinates. But how might this look in system land? The user knows where the moved origin is, so they know to apply the translation consistently. But the system doesn't "know" where the moved origin is. We're not pinhole-based, either.

I expect @blerner has several thoughts.

**Comment by blerner** [comment]
We currently have the `place-image-align` function, that takes a single reference point to be used in both images, and pins both images together at that reference point.  In the new image library (when that lands), this is trivial: we'll have `overlay-onto-offset`, which as we discussed extensively in https://github.com/brownplt/pyret-lang/issues/417#issuecomment-274344214, lets you pick a reference point in each image, an offset, and then pins the two references together separated by the given offset.  I don't understand your follow-up tweet about "the center not being a well defined thing" -- sure it is, we use it all the time already...?

**Comment by shriram** [comment]
Okay, so can we set up Andrew to use the new library?

**Comment by blerner** [comment]
I think this issue is long since moot?
