### ISSUE TITLE
Row rendering error in Microsoft Edge

### ISSUE THREAD

**Issue by BootstrapJen** [brownplt/pyret-lang#1452]
A teacher using Microsoft Edge as a browser cannot display rows.  This is the message from the console:

<[object Error]: {description: "Object doesn't support property or method 'append'", message: "Object doesn't support property or method 'append'", number: -2146827850, stack: "TypeError: Object doesn't support property or method 'append' at helper (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:201230:11) at renderValueSkeleton (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:201391:9) at toReprHelp (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:168852:13) at toReprFun (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:168869:13) at reenterToReprFun (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:168931:13) at toReprLoop (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:168949:7) at toReprJS (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:168962:14) at Anonymous function (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:204212:13) at Anonymous function (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:170638:11) at iter (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:170756:17) at run (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:170855:7) at runThunk (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:171026:7) at Anonymous function (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:204211:11) at iter (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:170782:37) at run (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:170855:7) at runThunk (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:171026:7) at Anonymous function (https://d251z2akfyabv3.cloudfront.net/releases/09b2597/cpo-main.jarr.gz.js:172460:19) at _fulfilled (https://code.pyret.org/js/q.js:834:13) at Anonymous function (https://code.pyret.org/js/q.js:863:13) at promise.promiseDispatch (https://code.pyret.org/js/q.js:796:13) at Anonymous function (https://code.pyret.org/js/q.js:556:17) at runSingle (https://code.pyret.org/js/q.js:137:13) at flush (https://code.pyret.org/js/q.js:125:13)"}
 Full time including compile/load: {"bounces":3,"tos":3,"time":767.0200579708908}
cpo-main.jarr.gz.js (203806,11)
 Time to run compiled program: {"bounces":1,"tos":1,"time":156.88023188407533}
cpo-main.jarr.gz.js (203848,21)>

**Comment by blerner** [comment]
This isn't quite enough information to debug: could you share the program that caused the error?

**Comment by jpolitz** [comment]
I pushed a likely fix through, you could ask the teacher to refresh and try (I'm won't be near a windows machine to try for a few hours).

**Comment by schanzer** [comment]
@BootstrapJen let us know how this went after you’re done training? Totally curious.

**Comment by BootstrapJen** [comment]
It worked!  Thank you!
