### ISSUE TITLE
"unterminated"

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1463]
I think this is a weird, big word, especially to a middle-schooler. E.g., in response to:

```
"hello
```
Can we use a phrase with smaller words? How about "does not finish"?

**Comment by blerner** [comment]
I don't like "does not finish", grammatically: we're talking about a syntactic property of a chunk of code, so the phrasing should be passive; that unterminated string doesn't deserve an active verb saying it doesn't finish ("huh?  doesn't finish _what_?").  I don't much  mind the longer word, honestly, but if we really need to bikeshed here, I'd prefer "is unclosed".

**Comment by shriram** [comment]
"not closed"?
