### ISSUE TITLE
rows don't have headers

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1464]
When you type, say, `t.row-n(k)`, you get a _row_, but if it has a lot of columns, you can easily forget which one is which (esp. if you have a bunch of booleans in there). Would it make sense to print column headers? Does it make sense to have a notion of anonymous versus nominal row, where the latter come _from_ tables, and can then be printed appropriately?

**Comment by blerner** [comment]
Huh? When I try, eg

```
a = table: x, y
  row: 1, 2
end

a.row-n(0)
```

I see a row that's rendered as the attached image. (If it doesn't attach, I
see `["x" 1 "y" 2]`, as four separate cells.)

What more rendering do you want?

**Comment by shriram** [comment]
Huh. That's not what I saw on screen, or I missed what I was seeing. Will reopen if there's still an issue.
