### ISSUE TITLE
Octal string escapes don't seem to work, should this slice from zero?

### ISSUE THREAD

**Issue by gfbee** [brownplt/pyret-lang#1480]
https://github.com/brownplt/pyret-lang/blob/2af42d6c8fd44d329f95b83141f5c777df52f44f/src/js/base/pyret-tokenizer.js#L65

**Comment by blerner** [comment]
Thanks for noticing!  (It appears we haven't ever had any uses of these escape sequences to notice that this was busted...)  Yeah, it appears it doesn't need to slice at all.  If you'd like to open a PR to fix it, go ahead: you should base the PR off the horizon branch, and you should add tests to `tests/parse/parse.js`, e.g. `expect(parse("\\101")).toBe("A");` and others, to confirm that the escape sequences are all working properly.

**Comment by gfbee** [comment]
I appreciate the invitation to fix, but will have to leave that for someone else.

**Comment by jpolitz** [comment]
<img width="79" alt="image" src="https://user-images.githubusercontent.com/119891/89936344-59843480-dbc8-11ea-926e-8088f3ed6607.png">
