### ISSUE TITLE
invalid cert

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1481]
I found this in the console log:

![image](https://user-images.githubusercontent.com/75030/63091293-eb148400-bf2b-11e9-93a7-c5b632dbcbce.png)

  | AJAXBackend.log | @ | log.js:17
-- | -- | -- | --
  | log | @ | log.js:84
  | runner | @ | cpo-main.jarr.gz.js:204370
  | Enter | @ | cpo-main.jarr.gz.js:204389
  | doHandleBinding | @ | codemirror.js:7063
  | (anonymous) | @ | codemirror.js:7134
  | lookupKey | @ | codemirror.js:6709
  | lookupKeyForEditor | @ | codemirror.js:7076
  | dispatchKeyInner | @ | codemirror.js:7104
  | dispatchKey | @ | codemirror.js:7100
  | handleKeyBinding | @ | codemirror.js:7134
  | onKeyDown | @ | codemirror.js:7152
  | (anonymous) | @ | codemirror.js:3874

**Comment by jpolitz** [comment]
Thanks to @jswrenn , this has been updated.
