### ISSUE TITLE
Updating multiple columns of a table with single transform (PAPL typo)

### ISSUE THREAD

**Issue by frodokomodo** [brownplt/pyret-lang#1485]
PAPL 4.2.5 demonstrates the transform expression being used to update multiple columns (temperature unit conversion example)

Trying this out on code.pyret.org gives an error. For
```
names-and-ages = table: name, age
  row: "Alice", 30
  row: "Bob", 40
  row: "Carol", 25
end
```
I am able to access both columns, but only update one of them with the same construct. These run fine:
```
transform names-and-ages using name, age:
  age: "changed"
end

transform names-and-ages using name, age:
  name: "changed"
end
```
but trying to update both gives an error:
```
transform names-and-ages using name, age:
  age: "changed"
  name: "changed"
end
```
It complains about not understanding the second column assignment (in this case, name:)

**Comment by shriram** [comment]
I've just fixed the bug in PAPL. Would you please send me your name so I
can acknowledge you? You can email me directly (sk@cs.brown.edu) if you
prefer. Else I will list you as frodokomodo.

Thanks!
