### ISSUE TITLE
Duplicate record field names in type don't error, but do in values

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#1499]
This program doesn't report an error:

```
type O = { x :: Number, x :: Number }
```

but it should. The related value has a well-formedness error:

```
{x : 10, x: 20}
```

![image](https://user-images.githubusercontent.com/119891/70475363-37f70a00-1a89-11ea-8c8e-c3729f41d31d.png)

**Comment by blerner** [comment]
Can we just copy these lines (https://github.com/brownplt/pyret-lang/blob/horizon/src/arr/compiler/well-formed.arr#L755-L759) to a new method `a-record`?

**Comment by safwansamsudeen** [comment]
Argh! I wanted to take this up, but I think it should actually be closed.
