### ISSUE TITLE
inconsistent error messages for variable rebinding

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1508]
If I run
```
x = 1
x = 2
```
from definitions I get
![image](https://user-images.githubusercontent.com/75030/74957750-ff06da00-53d5-11ea-9064-7ad4d240a273.png)
which I expect. But if I do it in interactions,
![image](https://user-images.githubusercontent.com/75030/74957802-1219aa00-53d6-11ea-9fb6-dab30fbfe717.png)
not only do I get a very different error, but it also claims `x` is "built-in" (which it's not), *and* if it were the error should have occurred at the first (re)definition…

I suspect this is actually a bug manifesting as the wrong error message.

**Comment by blerner** [comment]
This is a known issue, and fixed on horizon with the updated modules work.

**Comment by jpolitz** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/119891/89936075-feead880-dbc7-11ea-8419-772347117c7e.png">
