### ISSUE TITLE
Design a DSL for expessing runtime functions that still play nicely with the stack-management system

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#151]
Currently, to add a primitive function to the runtime, you have to be very careful: if the function _never_ calls back into Pyret, you're ok, but if it even _might_, then you have to manually wrap the body of the function in a `try`/`catch` that manually CPS'es the remaining control flow of the function.  This is very tricky, easy to forget, and ought to be largely auomatable.

**Comment by schanzer** [comment]
@jpolitz would Stopify would obviate the need for this?

**Comment by shriram** [comment]
@schanzer That's what it's supposed to do. Simplifies library authoring. You write "normal" code, Stopify stopifies it.

**Comment by shriram** [comment]
But note that @blerner does not believe in Stopify. (-:

**Comment by blerner** [comment]
I am willing to believe :)

**Comment by jswrenn** [comment]
Even with Stopify, there are still opportunities for ergonomic improvements. Checking the arity and contracts of javascript-implemented function parameters involves writing frustratingly mechanical boilerplate and has been resistant to improvement (e.g., #1144).

There was an attempt to [generate these checks with macros](https://github.com/brownplt/pyret-lang/blob/a7d28dcf717cc3df53d1008cab8610a98cb45582/src/js/macros.js), but as far as I know, that didn't go anywhere.
