### ISSUE TITLE
Error message for Order of Operations needs a tweak

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#1515]
"The operator + and * are at the same level..." a math teacher pointed out that PEMDAS already implies a notion of "level", and that those operators are very much NOT at the same level.

Suggest we remove that first sentence entirely, or reword.

**Comment by blerner** [comment]
We very specifically don't include PEMDAS in Pyret, as you know -- and as is (even better, now!) documented -- is this actually a problem for *students*, or more accurately a problem for *teachers' expectations*?

**Comment by shriram** [comment]
Emmanuel, is the issue here just that the word "level" is standard
terminology for algebra teachers? If so, we would just need to change the
word.

**Comment by schanzer** [comment]
It’s primarily the latter, but since students see the exact same language, I could imagine this also being a student problem as well

**Comment by shriram** [comment]
Sorry, what is "latter"? I didn't give two optoins.

**Comment by schanzer** [comment]
Sorry, Git on my phone showed me Ben’s comment but not yours. Yes, the issue is the word “level”.

**Comment by schanzer** [comment]
Any chance of this change making it onto CPO before the start of the school year?

**Comment by blerner** [comment]
This is now an easy fix, if you give me a specific message you'd like to see

**Comment by schanzer** [comment]
![image](https://user-images.githubusercontent.com/77126/89973389-368c6b80-dc2e-11ea-8f2b-3b68fad40ae7.png)

I'd love for this to read as "`+` and `-` are at the same grouping level. Add parentheses to group the operations, and make the order of operations clear."
