### ISSUE TITLE
type errors are broken

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1525]
This program
```
fun f(x :: Number):
  x / "3"
end
```
reports the following type error:
![image](https://user-images.githubusercontent.com/75030/92342772-ddc6bc00-f08f-11ea-848e-cca995057dd6.png)

Changing it to
```
fun f(x :: String):
  x / "3"
end
```
produces
![image](https://user-images.githubusercontent.com/75030/92342788-ee773200-f08f-11ea-81a2-4aa5ec511283.png)

It seems like somewhere the error-reporting mechanism is failing to recognize structures and is just printing them out literally?

**Comment by jpolitz** [comment]
I think your diagnosis is right, and “failing to recognize” is really that the print-for-compiler-debugging and print-for-user ended up being the same thing on these types.

Should be fixed by https://github.com/brownplt/pyret-lang/pull/1527
