### ISSUE TITLE
don't include blank lines in REPL history

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1529]
If you slip up in hitting up-arrow and hit Enter too quickly, you get a blank line in the REPL. That's fine; this may be useful for offsetting sets of interactions during a demo. However, if you then hit up-arrow to get back the command you wanted, you retrieve the…blank line.

This very much reminds me of
![image](https://user-images.githubusercontent.com/75030/93287160-caf66a80-f7a6-11ea-9081-bfe5cb31fd68.png)

**Comment by jpolitz** [comment]
"I'm drawing a blank," said colonel REPL.

This seems worth fixing. It's not totally trivial because for a11y we
probably want to keep the blanks in the history to not lie to screenreaders
about the count of entries, and the a11y history and the REPL history use
the same underlying data structure. So I can't push the fix right away. But
I agree it's worth not retrieving them and this can be figured out.

**Comment by sorawee** [comment]
I'm curious--currently the REPL already ignores duplicate entries (#416). How is a11y history in that case? And wouldn't the same strategy work here?

**Comment by jpolitz** [comment]
I just tried exactly that (set duo=true if nextItem.code === “”) and I’m having an issue where the uncommitted last entry isn’t recalled when going back down. Not sure 🤔

**Comment by jpolitz** [comment]
And the a11y history keeps the item but internally marks it as a skip. So you can ask for any dup by index via screen reader but up arrow skips them.

**Comment by jpolitz** [comment]
Another good question -- if a user enters

> 6
> 5
> <blank>
> <blank>
> 5
>

And then presses up arrow twice, should they get 5 or 6 at the prompt?
Basically, do duplicates span blank sequences?

**Comment by jpolitz** [comment]
I think this is mostly working at https://github.com/brownplt/code.pyret.org/commit/26115d394bfbe833ebcbcc6e7c89f0257e9eba0e

**Comment by jpolitz** [comment]
This is pushed to code.pyret.org now.

![Dec-14-2020 16-02-04](https://user-images.githubusercontent.com/119891/102150585-c719c900-3e25-11eb-8514-075488da3e82.gif)
