### ISSUE TITLE
browser hang

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1535]
On Brave, latest. This program is buggy (should take the difference `a - new-a`, not `n - new-a`).
```
eps = 0.01

fun root(n):
  fun iter(a):
    new-a = (a + (n / a)) / 2
    if num-abs(n - new-a) < eps:
      new-a
    else:
      iter(new-a)
    end
  end
  iter
end
```
When I run it as `root(4)(2)` I get a Stop button that works. When I run it as `root(4)(1)`, I get no Stop button, and the whole browser tab freezes up (can't even copy the code, and if I go to another tab and return, there's no redraw).

**Comment by blerner** [comment]
If you try it with `eps = ~0.01`, does it still lock up?  If not, then it's probably #1118 again.

**Comment by shriram** [comment]
I replaced it with the roughnum and it *still* locks up.

**Comment by shriram** [comment]
Ah, I think that was the wrong suggestion. I instead ran `root(~4)(1)` and then I *do* get the stop button. So I think it's safe to call this a dup of #1118.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/75030/96286586-98f74480-0fae-11eb-94ee-89cec3075f62.png">

**Comment by blerner** [comment]
Oh, I misread the code ;-)  I thought you were doing a derivative type calculation, some sort of  `f(x + eps) - f(x)` thing, and didn't read it carefully enough.  But yeah: if you have the-value-that-keeps-updating be a roughnum, and that change gives you back a stop button, then this is #1118.

**Comment by shriram** [comment]
I mean, it *is* a derivative-type-thing, it's Newton-Raphson (-:. Okay, mark as dup.
