### ISSUE TITLE
README link leads nowhere

### ISSUE THREAD

**Issue by RojerGS** [brownplt/pyret-lang#1539]
The http://reservationsbvi.com/thisoldpirate/glossary.html link in the README file goes to a domain that has expired and only contains ads.

**Comment by sorawee** [comment]
Here's a possible replacement: http://bvipirate.com/piratespeak/index.html

The original site can still be accessed via archive.org: https://web.archive.org/web/20080312004620/http://reservationsbvi.com/thisoldpirate/glossary.html

**Comment by RojerGS** [comment]
Did not know of the existence of archive.org and the new link looks like a fit replacement.

**Comment by jpolitz** [comment]
Thanks so much for reporting this!
