### ISSUE TITLE
Exit code control from command-line Pyret

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#154]
Currently, the exit code of a Pyret program is determined by `pyret-start.js`, which is a pretty dumb wrapper for bootstrapping the Pyret evaluator.  We should make it so somehow, the main Pyret program can have more control over at least the exit code of the program.

**Comment by blerner** [comment]
@jpolitz I think this is solved now with the `exit` and `exit-quiet` errors that can be thrown, correct?

**Comment by jpolitz** [comment]
Yup
