### ISSUE TITLE
CI: switch from Travis to GHA (both pyret-lang and CPO)

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1549]
- We are using travis-ci.ORG, which will be shutdown [at the end of the year](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom).
- We could try to migrate to travis-ci.COM, but it recently changes [its pricing plan](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), effectively making it not usable. 

GitHub Actions might be a better alternative.

**Comment by jpolitz** [comment]
Thanks, I’d forgotten about this. I’ll open a request for credits, I think we are a reasonable qualifying project. Worst case we pay a bit of $ which won’t be prohibitive in the near term based on their plans.

GitHub actions might work great, but I think we have priorities other than doing that migration right now.

**Comment by jpolitz** [comment]
Everything is green on https://travis-ci.com/github/brownplt :-)

**Comment by jpolitz** [comment]
(I have the request in for OSS credits with no response yet, but this will keep things running just fine on a cheap-enough tier, if not free, and settles the immediate issue.)

**Comment by jpolitz** [comment]
Just documenting here, some evidence on social media that the free OSS credits may not happen: https://twitter.com/james_hilliard/status/1336081776691843072?s=21
