### ISSUE TITLE
bug in declared type of built-in

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1551]
This program type-checks:
```
include string-dict
msd1 = [mutable-string-dict: "a", 5, "b", 10]
ks :: Set<Number> = msd1.keys-now()
```
Pyret thinks the return-type of `.keys-now` is `Set<Number>` when it should be `Set<String>`.

**Comment by shriram** [comment]
Credit to Kikuyo Shaw (cs019) for writing the program that surfaced this error.

**Comment by jpolitz** [comment]
This is on code.pyret.org now
