### ISSUE TITLE
Failed tests in the Sets library

### ISSUE THREAD

**Issue by Ulna101** [brownplt/pyret-lang#1552]
In pyret-lang/src/arr/trove/sets.arr, the tests on lines 251 and 252 fail even though they correctly show a preorder and postorder traversal.
https://github.com/brownplt/pyret-lang/blob/f9ba480d73cd84eb869ddaea83361f7c8cc240d9/src/arr/trove/sets.arr#L251-L252
This is likely due to a possible implementation error on fold-rev-postorder and fold-rev-preorder
https://github.com/brownplt/pyret-lang/blob/f9ba480d73cd84eb869ddaea83361f7c8cc240d9/src/arr/trove/sets.arr#L124-L128
https://github.com/brownplt/pyret-lang/blob/f9ba480d73cd84eb869ddaea83361f7c8cc240d9/src/arr/trove/sets.arr#L134-L138
I may be wrong in this assumption, but wouldn't a reversed pre-order traversal want to start at the bottom-right node and work its way rightwards and upwards until it ends up at the topmost node? This would be similar to a postorder traversal, except that it traverses the right subtree before the left subree. Similarly, a reversed post-order traversal would want to start at the very top and work its way down to the bottom left, which would be a pre-order traversal but it traverses the right subtree before the left one. Switching the implementations of fold-rev-postorder and fold-rev-preorder seems to resolve the testing issues.

**Comment by blerner** [comment]
Actually... All _four_ of the pre/post-order tests are wrong: two are passing that shouldn't, and two are failing that shouldn't.

**Comment by blerner** [comment]
@shriram @jpolitz -- this is a _really pretty_ use of `because` in tests:
https://github.com/brownplt/pyret-lang/blob/f4acb1dd016210a22bcfb8dfbf3ddd228d8c38f2/src/arr/trove/sets.arr#L257-L279
