### ISSUE TITLE
`set` signature

### ISSUE THREAD

**Issue by danil-braun** [brownplt/pyret-lang#1568]
https://papl.cs.brown.edu/2020/processing-lists.html

> Note that `my-len` did not actually “care” that whether all the values were of
> the same type or not: it never looks at the individual elements, much less at
> pairs of them. However, as a convention **we demand that lists always be
> monomorphic. This is important because it enables us to process the elements of
> the list uniformly**: if we know how to process elements of type `T`, then we will
> know how to process a `List<T>`. If the list elements can be of truly any old
> type, we can’t know how to process its elements.

And also we have `set`[1]:

```
set :: (
  lst :: List<a>,
  n :: Number,
  v :: Any
)
-> a
```

So why is it then said that lists must be monomorphic, but there are built-in
functions that allow you to insert a value of another type into a list?

And why `set` returns a value of type `a` and not `List<a>`?

[1] https://www.pyret.org/docs/latest/lists.html#%28part._lists_set%29

**Comment by sorawee** [comment]
Yes, that's a typo. It should be fixed to:

```
set :: (
  lst :: List<a>,
  n :: Number,
  v :: a
)
-> List<a>
```

**Comment by sorawee** [comment]
Fixed by https://github.com/brownplt/pyret-docs/commit/469aa0c2fd3397547742aa94a14f74ab263426a2
