### ISSUE TITLE
make: browserify: No such file or directory

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1570]
I just cloned a fresh `pyret-lang` and attempted to run `make`. It failed with `make: browserify: No such file or directory`.

IIUC, there are three possible fixes:

1. Ask users to install `browserify` globally (`npm install -g browserify`). That way, `browserify` will be available as a command.
2. Since [version 5.2.0](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b), `npm` will also install `npx` which allows us to run `npx browserify` (note that version 5.2.0 coincides with  `node` version 8.2, released in 2017). `npx` will search for local binaries under `node_modules` and invoke them correctly.
3. Alternatively, we can reference the actual binary at `./node_modules/.bin/browserify` directly.

Personally, I like option 2 most, but it does require us to bump the minimal supported version of Node from 6 to 8.2.

**Comment by jpolitz** [comment]
Another option – we could add `npm bin/` in front of `browserify`.

I wonder why this works on Travis; we don't install it globally there.

**Comment by sorawee** [comment]
Does `npm bin/browserify` actually work? I tried but it didn't. 

```
npm bin/browserify src/js/trove/require-node-dependencies.js -o build/bundled-node-deps.js

Usage: npm <command>

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term>
npm help npm       more involved overview
```

**Comment by jpolitz** [comment]
Ah email formatting. This is what I meant:

```
$(BUNDLED_DEPS): src/js/trove/require-node-dependencies.js
  `npm bin`/browserify src/js/trove/require-node-dependencies.js -o $(BUNDLED_DEPS)
```

**Comment by jpolitz** [comment]
e.g.

```
⤇ npm bin
/Users/joe/src/pyret-lang/node_modules/.bin
```

**Comment by jpolitz** [comment]
I changed it to `npx`, though, because that's the “right” solution.

https://github.com/brownplt/pyret-lang/commit/356504011b422b00b03fad1cea126b75b247aa53

**Comment by sorawee** [comment]
Nice, thanks!
