### ISSUE TITLE
Update PAPL link

### ISSUE THREAD

**Issue by jeapostrophe** [brownplt/pyret-lang#1577]
https://www.pyret.org/docs/latest/Getting_Started.html

links to

http://papl.cs.brown.edu/2015/

and not

https://papl.cs.brown.edu/2020/

or https://papl.cs.brown.edu/2019/ (which says the code doesn't work, despite being listed as stable in the 2020 version)

**Comment by jpolitz** [comment]
Thank you! Fixed in pyret-docs.
