### ISSUE TITLE
document the pyret-npm package

### ISSUE THREAD

**Issue by martindemello** [brownplt/pyret-lang#1579]
Just tried the pyret-npm package out and it works wonderfully. Could it be added to the README under "Installing"?

**Comment by jpolitz** [comment]
Done, thanks. Happy to hear it worked out of the box for you, and happy to see you're reporting issues with it! Thanks!

https://github.com/brownplt/pyret-lang/commit/8cf90a354014b16ec0106659367f2a4ce7fbdb5b
