### ISSUE TITLE
Cannot suppress the "The program didn't define any tests" message

### ISSUE THREAD

**Issue by martindemello** [brownplt/pyret-lang#1580]
I looked through the help, and it seems like `pyret -q -k` should just display my program's output, but it doesn't work:

```
$ cat hello.arr 
print("hello world\n")

$ pyret -q -k hello.arr 
hello world
The program didn't define any tests.
```

**Comment by martindemello** [comment]
update: `pyret -q -e none` worked; I think `-k` should imply `-e none` since the help text says

```
  -k, --no-check-mode         Omit check blocks during compilation, and generate a standalone program that  
                              doesn't print testing information at all.
```

**Comment by jpolitz** [comment]
Thanks! I added the implication you suggested. Now that `-e` exists, it's silly for `-k` to only mean “elide check blocks during compilation” and not the same thing as `-e none`.

**Comment by blerner** [comment]
@jpolitz I think the above commit means this is fixed?
