### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by Vm900** [brownplt/pyret-lang#1590]
Hi,
Relatively new to linux .Just finished compiling,so now how do i run it and is the app a local version of web one or its just 
for console?Thanks

**Comment by shriram** [comment]
Hi,

You can use Pyret directly from the Web:

https://code.pyret.org/

You don't need to compile it to use it.

Does that help?

**Comment by Vm900** [comment]
No not at i just to run a local copy in cases where im offline

**Comment by jpolitz** [comment]
Thanks for following up. Can you say a little more about what you hope to
do offline?

If you want to use Pyret from the command line, there's an npm package:
https://www.npmjs.com/package/pyret-npm

(For this, you'd install node/npm [
https://docs.npmjs.com/downloading-and-installing-node-js-and-npm] and then
npm install pyret-npm)

This doesn't install the editor environment from code.pyret.org; we haven't
quite been able to make that into an offline app yet.

**Comment by shriram** [comment]
Good to hear!

A desktop version is not an immediate priority because so few of our users
need it.

**Comment by kishvanchee** [comment]
I understand this is a closed issue. Can you please tell me what's the difference between `pyret-experimental-cli` and `pyret-npm` packages? The website points to `pyret-experimental-cli` (https://www.pyret.org/set-sail/index.html) while you have suggested `pyret-npm`

**Comment by jpolitz** [comment]
Thanks! I've changed the recommendation on the site from `pyret-experimental-cli` to `pyret-npm`. They are essentially the same thing; the only difference is that `pyret-npm` is where I've put the one we want to maintain long-term.
