### ISSUE TITLE
Wrong statement on landing page.

### ISSUE THREAD

**Issue by citharus** [brownplt/pyret-lang#1604]
In the section `Highlights vs. Existing Languages` it's stated that "Most 'scripting' languages don't support annotations for checking parameters and return values". In the comparison, the language compared to Pyret is Python, which does support annotations for parameters and return values:
```python
def square(n: int) -> int:
    return n * n
```

**Comment by citharus** [comment]
Sorry, I posted the issue in the wrong repo.

**Comment by sorawee** [comment]
FWIW, when we [added that content](https://github.com/brownplt/pyret.org/commit/26a0a0c64a1fec5845e22882b64955774f6f3114#diff-1ebff5a5ca689f49ee7eaf5bf10dbb52cbed6ef35ff311a1ea54ba8974210078R213) (October 2013), Python didn't have the type hint feature. The type hint PEP was proposed in [September 2014](https://www.python.org/dev/peps/pep-0484/), and accepted in May 2015.

**Comment by jpolitz** [comment]
Thanks, I think I've made a useful update here: https://github.com/brownplt/pyret.org/issues/15
