### ISSUE TITLE
within type

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1608]
The various `within` checkers have `(Any, Any)` types: e.g.,
<img width="536" alt="image" src="https://user-images.githubusercontent.com/75030/126917443-4af8bed1-31d1-400c-a65e-5dfbfc5cc0ea.png">
Does this make sense? Shouldn't they take numbers rather than `Any`?

**Comment by blerner** [comment]
Not in general, no.  E.g. `[list: 1, 2, 3] is%(within-abs(5)) [list: 2, 3, 4]`.  `num-within{-abs,-rel}` are weird, and less specific.  Regardless, this is only a documentation error, not an implementation one; the actual type is `(tol :: number) -> (Number, Number -> Boolean)`, as you can find out from typechecking `num-within-abs(5)([list: 1, 2], [list: 2, 3])`.
