### ISSUE TITLE
Make sure well-formedness checks catch all well-formedness errors

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#161]
Currently, the following program:

    fun badX(x, x): nothing end
    fun badXY(x, y, x, y): nothing end

reports only two errors, that `x` is duplicated in `badX` and that `x` is duplicated in `badXY`, and says nothing about the duplicate `y`s.

In general, any well-formedness error that could happen in multiple ways should be checked to ensure that all those ways are flagged.

**Comment by jpolitz** [comment]
This appears to be fixed now
