### ISSUE TITLE
prose / button text mismatch

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1611]
This menu (on horizon) is slightly confusing, because it refers to a button that doesn't exist.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/75030/128545368-55e4eaa3-f20d-4f75-b868-465e7b25c4a9.png">

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/code.pyret.org/commit/e3bf0a032ae03c7ca3b192e29ecc9096c97dcff5
