### ISSUE TITLE
Can you consider changing the logo design?

### ISSUE THREAD

**Issue by fenginsc** [brownplt/pyret-lang#1615]
The name and logo in this language may scare some people.
Using some bones and skulls as a logo will arouse some people’s disgust. It looks cool, but it seems that not everyone can accept this design.

**Comment by fenginsc** [comment]
@jpolitz 
There is no problem with the name of the language, but it is suggested that the design of the logo can be improved to make it look more friendly, thank you.

**Comment by shriram** [comment]
Thank you for your suggestion, but we haven't received any complaints about it from our many users; in fact, people seem to rather enjoy it. Furthermore,  it's used in a bunch of places (e.g., many teachers have used it on their Web pages), so it would be confusing now to change it. Finally, to be honest, we rather like it. (-:

By the way, the logo is also a tribute to the original DrRacket logo: https://users.cs.northwestern.edu/~robby/logos/ See the first logo on that page.
