### ISSUE TITLE
List `filter` relies on JavaScript filter raw list filter, which is truthy/falsy

### ISSUE THREAD

**Issue by jchen** [brownplt/pyret-lang#1624]
List `filter` is not currently enforcing that function passed in is a predicate (that is, return a `Boolean` value). Instead, it seems to rely on JavaScript raw list filter which is determined using JavaScript truthy/falsy values. Functions can return non `Boolean` values and built-in filter will admit them (as JavaScript does). For example, Pyret accepts the following tests: 
```
check: 
  [list: -1, 0, 1, 2].filter(lam(x): x end) 
    is [list: -1, 1, 2]
  [list: "hello", "", "world", "a"].filter(lam(x): x end) 
    is [list: "hello", "world", "a"]
end
```

Source at line 390 in [`src/arr/trove/lists.arr`](https://github.com/brownplt/pyret-lang/blob/horizon/src/arr/trove/lists.arr).

**Comment by blerner** [comment]
Fixed by now.
