### ISSUE TITLE
transform-column and count functions -mismatch between pyret docs and dcic book

### ISSUE THREAD

**Issue by kishvanchee** [brownplt/pyret-lang#1632]
I'm going through the DCIC book. Under https://dcic-world.org/2021-08-21/processing-tables.html#%28part._.Normalizing_.Data%29 there is a function which does not work currently.

```
discount-fixed =
  transform-column(event-data, "discount", cell-to-discount-code)
```
But when I change it to the following it works.
```
discount-fixed =
  event-data.transform-column("discount", cell-to-discount-code)
```
Is the book out of date wrt the docs?

Here's an MWE
```
use context essentials2021
include gdrive-sheets
include data-source

ssid = "1DKngiBfI2cGTVEazFEyXf7H4mhl8IU5yv2TfZWv6Rc8"
event-data =
  load-table: name, email, tickcount, discount, delivery
    source: load-spreadsheet(ssid).sheet-by-name("Data", true)
    sanitize name using string-sanitizer
    sanitize email using string-sanitizer
    sanitize tickcount using num-sanitizer
    sanitize discount using string-sanitizer
    sanitize delivery using string-sanitizer
  end

fun cell-to-discount-code(str :: String) -> String:
  doc: ```uppercase all strings other than none,
       convert blank cells to contain none```
  if (str == "") or (string-to-lower(str) == "none"):
    "none"
  else:
    string-to-upper(str)
  end
where:
  cell-to-discount-code("") is "none"
  cell-to-discount-code("none") is "none"
  cell-to-discount-code("birthday") is "BIRTHDAY"
  cell-to-discount-code("Birthday") is "BIRTHDAY"
  cell-to-discount-code("NoNe") is "none"
end

discount-fixed =
  transform-column(event-data, "discount", cell-to-discount-code)
```
![Screenshot_20211126_175124](https://user-images.githubusercontent.com/24776049/143580355-18da509e-f311-4a9c-bac8-3132949ca6e3.png)

The docs shows only `.transform-column` is available - https://www.pyret.org/docs/horizon/Glossary.html?q=transform

I can say the same thing for `count(discount-fixed, "discount")` as well in the same section.

**Comment by jpolitz** [comment]
Thanks! This is a place where the book should probably have a reminder. In the previous chapter there's this bit about a helper library used with the table operations in the book:

![image](https://user-images.githubusercontent.com/119891/143781529-40de29c6-a475-4480-a080-d23141b381eb.png)

That library is needed for the `transform-column` function to be defined (as opposed to a method).

**Comment by kishvanchee** [comment]
Thank you. Can you please let me know if the `functions notation for working with tables` have docs which we can refer to? I would like to understand what all is available and how they can be used.

**Comment by kfisler** [comment]
Apologies for the slow followup. Yes, there is a documentation page for the function-based operations. It currently lives at https://hackmd.io/@cs111/table. This document is now linked into the book, both when we first introduce table operations, and again at the normalizing tables example on which the issue was first reported.

The fix will appear in the next book release, which is due out very soon.
