### ISSUE TITLE
can't combine `else` with `block`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1654]
Is it intentional that I can't use `block` with `else`? E.g.:
```
if true:
  1
else block:
  print('hello')
  2
end
```
is a parse error (points to `else`!), and I must instead write
```
if true:
  1
else:
  block:
    print('hello')
    2
  end
end
```

**Comment by blerner** [comment]
Yes.  If either branch is blocky and you want to use the shorthand notation, put the `block` keyword after the `if` and both branches are then blocky:  `if ... block: ... else: ... end`

**Comment by shriram** [comment]
Could we at least get a better error message that indicates this? I don't think this is guessable at all. (Also, why isn't `block` after `else` allowed? Too hard to handle?)

**Comment by blerner** [comment]
I'm confused. You're trying to use a shortcut, right? All of them are consistent: `if ... block`, `ask ... block`, `cases ... block`. All of them let the blockiness apply to the entirety of the expression. There's no way to apply a shortcut to just one branch of any of those; you can use the explicit `block` keyword if you want that. And if someone wants to use the shortcut syntax, honestly I'm fine with them looking up how to do so.

As for a better parse error, I don't know if that's easy to hack in to the grammar.

**Comment by shriram** [comment]
I don't understand why it's considered a "shortcut". Why can't `block`
associated more locally than "the whole construct"?

**Comment by blerner** [comment]
That's what `block: ... end` was for. We discussed this at length when we designed this syntax. Putting `block` at the outset of an if/ask/cases was intended as a shortcut to effectively put `block` on each of the branches, all at once.
