### ISSUE TITLE
swf files in Pyret tutorial in docs appear broken

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1657]
This as reported in a tweet directed to me (https://twitter.com/gordon_zhu/status/1563890842569433092), from [@gordon_zhu](https://twitter.com/gordon_zhu)

-----

[@KathiFisler](https://twitter.com/KathiFisler)
The .swf files here don't seem to work in Chrome and Safari (on Mac or iOS).
https://pyret.org/docs/latest/Tutorial__A_Flight_Lander_Game.html

Would it be possible to use a different file format?

In the meantime, how are you and your students handling this? Is there a recommended workaround? Thanks!

**Comment by jpolitz** [comment]
Thanks, removed via https://github.com/brownplt/pyret-docs/commit/c9a8bcedc3f3f734188b3810df9dc50dbf3c081b.
