### ISSUE TITLE
image library documentation incorrectly uses the same snippet for "include image" for both untyped and typed

### ISSUE THREAD

**Issue by dyoo** [brownplt/pyret-lang#1668]
The documentation at https://www.pyret.org/docs/latest/image.html uses the same example for importing the typed version of the image libraries as the untyped:

````
* The image module functions ...:

include image

import image as ...
````

followed by the item:

```
* The image-typed module functions ...

include image

import image as ...
````

and the second code snippet is identical in content to the first.  The second code snippet should probably use "image-typed" instead of "image".

**Comment by asolove** [comment]
This was fixed more than a year ago in source code: https://github.com/brownplt/pyret-docs/commit/a7aad4c6432e6863b3a3a7a6adb4aedfc6c7ca0d but the live docs page does not yet have the fix. I'll check in on making sure that is deployed.

**Comment by blerner** [comment]
It's definitely deployed by now :)
