### ISSUE TITLE
Something up on Node v0.11 in Travis

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#169]
See the Travis logs (https://travis-ci.org/brownplt/pyret-lang/builds).  Seems that our tests fail sometimes on Node 0.11, but always succeed on Node 0.10.

This could be a Travis problem or a Node incompatibility (even with some package we depend on in npm), so we should look into this more.

For now, we should turn off the v0.11 build, because it could mask other real failures.

**Comment by blerner** [comment]
Do we need this bug anymore?
