### ISSUE TITLE
fold documentation appears to be incorrect

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1703]
The signature says the first argument must be a function but the expansion shows it as the second argument.

![image](https://github.com/brownplt/pyret-lang/assets/75030/78c6d163-21fc-4c01-83a8-fe29ed9bdd00)

This is for both `fold` and `foldr`.

Identified by Luna Wang.

**Comment by sorawee** [comment]
Already have a fix in https://github.com/brownplt/pyret-docs/pull/74 (though not yet merged)

**Comment by shriram** [comment]
Student also points out:

<img width="378" alt="image" src="https://github.com/brownplt/pyret-lang/assets/75030/b9d18bea-cc75-460e-a5f0-f8cfd31bf72c">

"Since the set appears to the left of the base b , shouldn't the function be in the form f :: (a, b -> b) instead?"

**Comment by sorawee** [comment]
The issues with `foldl` / `foldr` in the list documentation are now fixed.

@shriram: I don't understand what's wrong in your second comment. The method is documented correctly, agreeing with the implementation:

```
import sets as S

t1 = [S.tree-set: 1, 2, 3]

fun add(acc, elem) block:
  acc.add(elem + 100)
end

t1.fold(add, [S.tree-set: ]) # [tree-set: 101, 102, 103]
```

Perhaps the student meant that the argument ordering of set's `.fold` is not consistent with list's `.foldl/r`, which is true. But it's not fixable without breaking backward compatibility (then again, perhaps `use context` allows us to break backward compat?)

**Comment by jpolitz** [comment]
Thanks for PR on docs.
