### ISSUE TITLE
Error messages about undefined identifiers -> Use variables instead

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#1716]
Teachers and students have _no idea_ what this error means:
<img width="501" alt="image" src="https://github.com/brownplt/pyret-lang/assets/77126/fbbcf2d6-944f-4472-88ea-c85127bdfe05">

In our Pyret meeting 11/2/23, we agreed to change "identifier" to the less-correct but more-practical "variable"

**Comment by blerner** [comment]
I'm really not a fan of misusing `variable` in this context.  After talking to @schanzer , we are trying out "name" instead, in contexts that rephrase the sentences slightly to avoid awkward duplication of the word "name"/"named".
