### ISSUE TITLE
newline in URL renders as space, confusing

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1722]
![image](https://github.com/brownplt/pyret-lang/assets/75030/589d2e21-a411-4d5e-83a4-1d34f5aec7a4)

The space is easy to miss, and more to the point, isn't a newline, which made it hard for the student to find the error (and needed a TA to help).

Also a bit unclear why this is raising an exception and returning undefined instead of failing a bit more gracefully… Note that this also exposes the `downloadImg` URL.

**Comment by blerner** [comment]
This is rather hard to fix.  Pretty much _every_ UI suggestion you can make here won't work in the general case (show a weird inserted glyph?  prevent line-breaking altogether?  have  runtime error in your `run-on-url` function somehow?)  

As for the unable-to-load error showing `undefined`: we're trying to show the `message` field from the JS error that we get from that broken url, and apparently that error object doesn't _have_ a `message` field -- in fact, it doesn't provide _any_ useful information whatsoever in this case.

**Comment by blerner** [comment]
Btw, the current error message here is improved (as of https://github.com/brownplt/code.pyret.org/commit/317cc82b0da11be564c3c91687c4148c52026744), so I'm closing this issue:
![image](https://github.com/brownplt/pyret-lang/assets/918464/fb5fa3d2-a139-47f7-8f5f-5668b1035a33)
