### ISSUE TITLE
How to add Pyret language support to Emacs

### ISSUE THREAD

**Issue by garare992** [brownplt/pyret-lang#1753]
Emacs novice here. How do I use the add Pyret support to Emacs? 

I wish you guys would include some comments in the files to guide us through the process.

**Comment by blerner** [comment]
Hi!  The Pyret emacs mode isn't really one of the intended ways to program in Pyret: the best way, by far, is to use code.pyret.org, and the majority of our development effort goes in to that.  (There are bugs in the emacs mode that we have no active plans for fixing, and adding new features to the language does not imply we'll backport those features to the emacs mode, either...)  Emacs is somewhat of a power-user tool, and the Pyret emacs mode is installed in it exactly the same as all other language modes:
```elisp
  (add-to-list 'load-path (expand-file-name "the/path/to/wherever/you/saved/pyret.el"))
  (require 'pyret)
  (add-to-list 'auto-mode-alist '("\\.arr$" . pyret-mode))
```
