### ISSUE TITLE
"Your test failed"

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#189]
Please let's not use personalized text.

**Comment by blerner** [comment]
This message is gone.  Other second-person messages still exist ("Looks shipshape, your test(s) passed!", etc.); do you want to eliminate those also?  Less facetiously, are there any remaining *accusative* second-person messages?  I don't think there are -- there are proscriptive ones ("You need to pick a new name for one of [the two shadowed names]") and descriptive ones ("Defining an anonymous variable is pointless; you have no name to modify"), but those don't seem as objectionable.

**Comment by shriram** [comment]
Sounds like this has been dealt with? @jswrenn Please audit and once confirmed, close. Thanks.
