### ISSUE TITLE
error highlighting sometimes off

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#198]
When there are multiple loci, the error highlighting seems off. For instance, in this (complete) program:

```
fun f(x, y):
  x + y
end

f(2)
```

hovering over the error (when you run it) highlights the whole program, and even clicking on "definitions: line 1, column 0" and "definitions: line 5, column 0" does not highlight anything specific.

For this program:

```
data Foo:
  | foo(x, y)
end

foo(1)
```

it highlights just the right two places, but both at once, and clicking on the definitions: ... links doesn't remove the other highlight.

In another situation, for a much longer program, it doesn't highlight anything at all, though that could be related to editor lockup (https://github.com/brownplt/pyret-lang/issues/197).

**Comment by shriram** [comment]
A lot has changed, but note that this program
```
data Foo:
  | foo(x, y)
end

foo(1)
```
still does not produce a useful error message. I get

![image](https://cloud.githubusercontent.com/assets/75030/19191661/b3e717a8-8ca3-11e6-8064-784f6d9106a6.png)

where the only link, "2 arguments", does not lead anywhere.

**Comment by jswrenn** [comment]
As of https://github.com/brownplt/pyret-lang/issues/899#issuecomment-258874946, that program now produces:

<img title="Constructor Arity Mismatch" alt="data Foo:&#13;  | foo(x, y)&#13;end&#13;&#13;foo(1)&#13;" src="https://cloud.githubusercontent.com/assets/3820879/21534228/f7f77518-cd31-11e6-9fb9-aa595291211f.png"></img>

The particular issue described in this bug report has long been fixed. I'm going to mark this as closed. Although there are still areas in which highlights are incorrect, but more recent and focused bugs track these problems.
