### ISSUE TITLE
bad error for missing lib

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#200]
Program:

````
import treasure as T
````

Error:

````
The module(s) trove/treasure failed to load
````

That suggests the module exists, it just _failed to load_ (network outage? bad sector on disk? BGP corruption?). The error should say that there is no such module.

[As an aside, it would be awesome for treasure to be an actual easter egg module.]

**Comment by shriram** [comment]
Given the confusion about module names like `reactors` and `lists` (as opposed to the singular versions), the Levenshtein proposal would be especially helpful. Even a simple string prefix could help. But in the meanwhile, this particular problem is gone, so I'll close it.

**Comment by schanzer** [comment]
FWIW - The Levenshtein distance I added to WeScheme has definitely helped in the occasional teacher PD. I'm fully in support of using this in Pyret, and so much the better if it can be used for unbound id errors!
