### ISSUE TITLE
immutable-string-dict and string-dict behave undesirably

### ISSUE THREAD

**Issue by melloc** [brownplt/pyret-lang#216]
It seems that both immutable-string-dict and string-dict don't handle bad key lookups. For example:

```pyret
    import string-dict as SD
    dict = SD.string-dict()
    a = dict.get("not-there")
```

This program will run forever. It looks like get() is returning undefined.

Also:

```pyret
    import string-dict as SD
    dict = SD.immutable-string-dict()
    a = dict.get("not-there")
```

Will raise the error "An unexpected error occurred: Error: Looked up not-there, not bound in namespace". Probably fine for now, but it's leaking the underlying implementation (Namespace.Namespace).

What should these return when there isn't anything there? "nothing"? Or should they always return an Option?

**Comment by jpolitz** [comment]
This has been fixed for a while by @ds26gte's string-dict library.
