### ISSUE TITLE
Zooming on code.pyret.org causes repl editor issues

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#221]
When zoomed in on the editor page, repl windows can become covered up by a scrollbar that appears on CodeMirror instances.  Happens for me on Linux at 175% magnification in Chrome, others saw it as well on other platforms.

![image](https://cloud.githubusercontent.com/assets/119891/3531101/cd9cb560-07ab-11e4-852b-5fba30b9989d.png)

**Comment by schanzer** [comment]
1) Ever since the UI rewrite, this hasn't been an issue.
2) It's likely to change even more with the work Paul's team is doing
3) This should be a CPO issue anyway, not pyret-lang
