### ISSUE TITLE
Revise the image library so it no longer takes strings for color names

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#261]
We already have a data type for `Color`s; we should use it exclusively.

**Comment by Emmay** [comment]
Relevant to Issue #417

**Comment by schanzer** [comment]
This is now implemented as part of the `image-structs` library.

**Comment by blerner** [comment]
No, not quite.  (1) I haven't landed the new image library yet; (2) it's not `image-structs` and `image` per se but rather a third library which needs a good name, and (3) once that PR lands then we can close this out.

**Comment by schanzer** [comment]
@blerner checking to see if the winter merge now puts us into a position to close this?

**Comment by schanzer** [comment]
@blerner now the PR has landed, _and_ it's on CPO. OK to close?
