### ISSUE TITLE
Unfortunate interactions between inexact numbers and the image library

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#262]
From the original emails:

I have a computed ::Number value which is a float between 0 and 1. How do I get an integer to dynamically construct an RGB value?

```
import image as I
import image-structs as C

I.circle(20, "solid",C.color(240,1,240,1))  # ==>magenta circle

I.circle(20, "solid",C.color(240.2,1,240,1))  # ==>black circle
```

And

The code below will work, using `num-exact` to force the number to be exact.  But I'm not happy with two things here that will get fixed:
- `truncate`/`floor`/`ceiling` should produce exact results
- one of `color` or `circle` should have given you an error message, not produced bogus answers

```
I.circle(20, "solid",C.color(240,1,num-exact(num-truncate(240.1)),1))  # ==>magenta circle
```

**Comment by blerner** [comment]
Related problems: `place-image-align(IMAGE1, 2.5, 10, "left", "middle", IMAGE2)` results in an internal error right now.  Any non-integer value dies, there...

**Comment by blerner** [comment]
(This seems specifically `Scene` related: SceneImage.prototype.add is using x and y without going through the jsnums library, so it's just dying horribly...

**Comment by blerner** [comment]
@jpolitz I've got this almost finished now: I've just gone through and fixed up image.js, image-lib.js and world.js to use jsnums.toFixnum properly everywhere, so we don't have internal errors any more.  (I'll want a code review, shortly -- it's fiddly and I might've typoed or missed one, and we don't have a comprehensive test suite for this, right?)

I've also modified `data Color` in pyret-lang to annotate its arguments to be `NumInteger`s.  This catches `240.1` as a color component, and also catches `~240`.  It gives a mediocre error message -- but it's way better than the Internal error we currently have! -- but I'm not 100% certain we want this to be the solution.  We also need to revisit #862, since that impacts the ergonomics of this solution as well.

**Comment by blerner** [comment]
(Also, incidentally, the semantics of colors evidently has changed at some point, so that alpha now ranges over integers from 0 to 255, rather than floats from 0 to 1.  Not sure when that happened, but it impacts the original example slightly.)

**Comment by sorawee** [comment]
@blerner regarding your last comment, see also #475

**Comment by schanzer** [comment]
IIRC, I implemented it this way to preserve compatibility with DrRacket. CPO is under no such restrictions.

**Comment by blerner** [comment]
I don't care either way, but it should be documented properly and enforced properly. Even the NumPositive constraint I have right now isn't rigid enough for the rgb components. So this has to get revised a bit anyway...

Which range do people prefer? Both scales are arbitrary, to some degree :-)

**Comment by schanzer** [comment]
What's most common in the languages we expect new Pyreteers to be most familiar with?

**Comment by shriram** [comment]
For my incoming cs019 applicants, Java and Python.

**Comment by blerner** [comment]
Perfect.  Java accepts (0-255) for all arguments, or (0.0--1.0) for all arguments.  Python supports (0-255), (0.0--1.0), three-char-hex, six-char-hex, eight-char-hex, and explicit percentages.

So...that tells us nothing whatsoever ;-)

**Comment by schanzer** [comment]
CSS uses 0-1, IIRC. Lots of people come in with minimal web knowledge, and "it works like the internet" is always a convincing response in PD. ;)

(Or maybe let Dorai fix it in the numbers library... *ducks and runs*)

**Comment by blerner** [comment]
Nope -- https://www.w3schools.com/cssref/css_colors_legal.asp

CSS uses three-char-hex, six-char-hex, eight-char-hex, (0-255) for three params and 0-1 for alpha, or HSL with percentages 0-100 and then 0-1 alpha.

It's all laughably inconsistent.  We just need to pick something and go with it.

**Comment by schanzer** [comment]
Then let's do 0-255. It's internally consistent, and makes the math easier if someone wants to write some kind of pixel-converting filter down the road.

**Comment by blerner** [comment]
What about the alpha?  0-1 is easier for multiplying; 0-255 is easier for averaging; etc etc.

**Comment by schanzer** [comment]
I was thinking for alpha too - maybe someone wants to write code that messes with each channel separately, and rotate the channels periodically?

**Comment by schanzer** [comment]
Since no one else has chimed in here, I'm going to make executive decision and say 0-255. Everyone can yell at me later if this turns out to be a disaster.

**Comment by blerner** [comment]
After thinking about it some more, I'm going to disagree and say it should be 0.0--1.0: alpha composition is done via multiplication: 50% more transparent of 50% transparency is simply 0.5 * 0.5 = 25%.  Doing the same thing via 0-255 is a nightmare.  _And_, limiting yourself to _integers_ in 0-255 mean you're going to have aliasing issues very quickly, where there are discrete changes in the transparency.  It really needs to be a float, and for that reason it ought to be a percentage in 0-1.

**Comment by blerner** [comment]
See https://github.com/brownplt/code.pyret.org/pull/190

**Comment by schanzer** [comment]
Works for me!
