### ISSUE TITLE
Nested check blocks confuse the compiler

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#268]
Nested check blocks (e.g. inside a function, or on a where block inside a function), throw an error in the compiler that complains about an Option vs. Expr mismatch.

**Comment by schanzer** [comment]
Now that we're disallowing multiple expressions within a non-block function body, we get the expected error message.

Even with `block:`, however, these tests now pass without any compiler error. @jpolitz , is this closable?
