### ISSUE TITLE
check block highlight a bit off

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#273]
Suppose I have

````
Check block: check-block-2
  ...
  The test passed.
Check block: check-block-1
  ... [failed test]
  The test failed.
````

When I mouse over the `test` items, the corresponding single test highlights. But when I mouse over the strings "The test passed" or "The test failed", the entire block highlights. When there is more than one passing or failing test, this highlighting makes sense, because it summarizes the block. But when there's only one, and the prose is rewritten to be singular, it's odd for the _block_ to be highlighted.

**Comment by schanzer** [comment]
Still an issue after the error message overhaul?
