### ISSUE TITLE
a nest of related issues with annotations and type-checking predicates.

### ISSUE THREAD

**Issue by elfprince13** [brownplt/pyret-lang#281]
given this `type MyType = List<OtherType>`, I want to ensure that some value was of type `MyType`; however there appears to be no `MyType` predicate in the namespace. There also appears to be no `List` predicate in the namespace, which feels contrary to the documentation for `data`. Are these types somehow special-cased?

Nonetheless, `is-link` and `is-empty` work, so I thought perhaps I could `is-empty(mt) or is-link<OtherType>(mt)`, but `is-link` doesn't make any checks based on `<OtherType>`, but doesn't complain about its being there either. 

That's fine, I thought, I'll try this to be extra tricky:`(lam(f :: MyType) -> MyType: f;)(l)`, but apparently neither annotation is enforced here, nor is `(lam(f :: MyType) -> Number: f;)` which should be able to throw a fit at compile time, irregardless of what I try to call it with, since `f` provably isn't a `Number`

(working in the code.pyret.org interface still)

**Comment by jpolitz** [comment]
This is documented in the tour as well as having the REPL-based issues exist, and the type-checker is in beta, so I think this can be safely closed in several ways.
