### ISSUE TITLE
errors printed in reverse order

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#285]
In this program, `with` is used as an identifier, which Pyret does not like (this year). However, the errors are reported in reverse order:

````
fun subst(with :: ExprC, at :: String, in :: ExprC) -> ExprC:
  cases (ExprC) in:
    | numC(n) => in
    | plusC(l, r) => plusC(subst(with, at, l), subst(with, at, r))
    | multC(l, r) => multC(subst(with, at, l), subst(with, at, r))
    | appC(f, a) => appC(f, subst(with, at, a))
    | idC(s) =>
      if s == at:
        with
      else:
        in
      end
  end
end
````

They should go from top to bottom. Presumably if the first `with` were reported, the user would fix that and remember to fix most/all of the uses in the body at the same time. Seeing the last one first is a bit confusing: "What's wrong with _this_ use, as opposed to the other ones? Oh, wait, I see...they're all wrong." It requires an extra moment of thought for a bad reason.

**Comment by schanzer** [comment]
This appears to be fixed on CPO

**Comment by schanzer** [comment]
@shriram , any reason to keep this open? Not trying to be a PITA - just doing my part to keep the issue list tidy. :)
