### ISSUE TITLE
Repl can't tell the difference between identifiers and variables

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#288]
At the REPL:

> var foo = 5
> foo := 5

Will report that foo was not defined as a variable.  This is because the repl exports don't distinguish correctly, so this is being statically flagged as an error before running the code at the repl.  The fix is to add more information in CompileEnv bindings so the compiler allows variables in its initial scope, and then have repl-support and repl-lib correctly add variables vs. identifiers to the environment.

**Comment by sorawee** [comment]
FYI: this bug was fixed in the typed Pyret.

**Comment by schanzer** [comment]
CPO can now tell the difference between the two, and the code mentioned in the OP runs without complaint. @jpolitz , OK to close?

**Comment by shriram** [comment]
Wait, what?

![image](https://cloud.githubusercontent.com/assets/75030/24326959/8920b268-1191-11e7-8c4c-55abdeb62686.png)

How is this "runs without complaint"?

**Comment by sorawee** [comment]
Fixed on horizon, but not on CPO

**Comment by schanzer** [comment]
This is now also fixed on CPO. OK to close?

**Comment by sorawee** [comment]
I don't think it's fixed on CPO. What Shriram posted above still happens.

**Comment by schanzer** [comment]
*headdesk* you're right - I had a CPO and horizon tab open, and I tested this out in the wrong one 😳

**Comment by sorawee** [comment]
@jpolitz have you merged the fix to CPO? I still get the same error...

**Comment by jpolitz** [comment]
This is (re-)fixed now; I had rolled back CPO briefly while @blerner and I worked out an issue that happened on the first deploy.
