### ISSUE TITLE
unhelpful error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#297]
This may be a duplicate, but anyway, there's another issue:

````
test (t(plusC(fdC("x", numT, numT, numC(3)), numC(1))) raises "arithmetic"): failed, reason:
Got unexpected exception arity-mismatch(srcloc("definitions", 40, 0, 713, 81, 3, 1782), 2, [
````

Not only is it not highlighting, it's also not showing me a stack trace. The src locs only tell me the callee that got the wrong number of args. But the call is obvious in my case. What I can't tell is the call site!

**Comment by blerner** [comment]
I have no idea what you did to deserve this error message, but I'm pretty sure this will work on horizon now.  Do you still have the program that triggered this?

**Comment by schanzer** [comment]
Without having the original source, it's hard to say if this error still exists. After the error message overhaul of the last few months, however, it's worth checking if this can be closed...
