### ISSUE TITLE
Expanding definitions hides prompt

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#298]
I typed C-m to expand the size of the definitions area. I clicked Run. I never saw a prompt, which is my visual reminder that the buffer evaluated successfully. This is a bit disruptive to certain quick-cycle development styles.

**Comment by shriram** [comment]
Is C-m gone now?

**Comment by jpolitz** [comment]
C-m toggles between the custom resize the user has dragged to, and 50%.

**Comment by shriram** [comment]
Whatever the problem I can't reproduce this from what I wrote, so let's consider it fixed.
