### ISSUE TITLE
need help to figure out what the keystroke help command is

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#299]
The UI should make clearer what to type to get the help menu of keystrokes. Even better would be if you didn't have to remember to type anything at all: if it were accessible from the "More V" dropdown menu.

**Comment by shriram** [comment]
Still no keystroke documentation (e.g., that Ctrl-Enter runs the definitions).

**Comment by schanzer** [comment]
@ds26gte : Ctrl-/ ("control question mark)" is a common convention here.

**Comment by schanzer** [comment]
"Help" should be visible at the top level. Personally, I see this as another argument for a footer with a series of icons (announcements, options, etc).

**Comment by blerner** [comment]
I'm leery of losing another toolbar's worth of vertical space, especially on lower-end machines (low resolution) or teacher machines (projectors already are very limited space-wise).  I think I agree the Bonnie menu is best compromise for this.

**Comment by schanzer** [comment]
This is now in the Bonnie menu. @blerner @shriram , OK to close? If we care about discovery, we could also put this in the new footer, which has _tons_ of space.
