### ISSUE TITLE
Saving a file in CPO/Drive renames it

### ISSUE THREAD

**Issue by hilmar-hoffmann** [brownplt/pyret-lang#303]
When I save a file A.arr in CPO and edit it and save the freshly edited state as B.arr, A.arr is lost.
Related with #204, the file presumably keeps its identity, but changes names.

Since you can save files locally, a workaround exists, it would just have been nice to know before.

**Comment by schanzer** [comment]
This no longer seems to apply, given the new behavior that explicitly requires a "rename". OK to close?
