### ISSUE TITLE
Remove open-image-url

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#308]
Documentation doesn't explain any difference between `open-image-url`, `image-url`, `bitmap-url`. If they _aren't_ different, it should at least say they aren't (and why are they there?).

**Comment by schanzer** [comment]
This seems like an easy Issue to knock-off: let's remove `open-image-url` and `bitmap-url` from the Image library.

**Comment by shriram** [comment]
These are still there.

**Comment by schanzer** [comment]
It's 3 years later. Let's keep `bitmap-url`, since there's a lot of code out there that relies upon it.
