### ISSUE TITLE
raw-array-to-list applied to a nested RawArray is different from the corresponding nested list

### ISSUE THREAD

**Issue by hilmar-hoffmann** [brownplt/pyret-lang#314]
I assume this should work:
`
check:
  raw-array-to-list(raw-array-of(raw-array-of(1, 1),1)) is [list: [list: 1]]
end
`
but it gives
`
Values not equal:
[list: [
  1
]]
[list: [list: 1]]
`

**Comment by blerner** [comment]
@jpolitz now that the type system is more baked, and this function seems even less likely to be typeable, should we keep this issue open?

**Comment by blerner** [comment]
@jpolitz now that the type system is more baked, and this function seems even less likely to be typeable, should we keep this issue open?

**Comment by jpolitz** [comment]
Yeah agreed w/ @blerner, closing as not fitting Pyret's type discipline.  It's a reasonable request, but not something that will go in Pyret right now.
