### ISSUE TITLE
underscore in mouseover is misleading

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#324]
Emu points out when you mouse over an error, it underlines the text at the same time as it highlights source. The underline is confusing because it makes something look clickable, when it's not really (because nothing new has become clickable than from the mouse-over).

**Comment by shriram** [comment]
@schanzer Do you think this is still a problem?

**Comment by schanzer** [comment]
The new error system does the right thing in terms of highlight/hover, IMHO. However, it doesn't auto-scroll to the relevant error on click. @jswrenn , can we scroll the definitions window to the relevant line?

**Comment by jpolitz** [comment]
The error highlight clicks autoscroll now.
