### ISSUE TITLE
Rename `tostring` method to `_tostring`

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#325]
Now that we've fixed up `tostring` and `torepr` to take a "use *this* function for recursive tostring/torepr calls" argument, it's simply always an error to invoke `any-value.tostring()`.  To encourage avoiding that behavior, can we renamed the `tostring` method on data values to `_tostring`, to match `_torepr`, and so make it less likely that people inadvertently screw up?

**Comment by jpolitz** [comment]
This was closed by 383f9721951a8c81b889a5b6a1fb566e798a8d0a, 5079f94c6636d1ce1d09152e9b3649feced1a875, and a few other commits around that time.
