### ISSUE TITLE
mouseover for errors appears to quickly, in the wrong spot.

### ISSUE THREAD

**Issue by elfprince13** [brownplt/pyret-lang#327]
As of the most recent 1730 assignment, I can't  click the "More" link in an error message because the mouseover shows up too fast and covers the whole thing, as soon as my mouse enters the box.

**Comment by sorawee** [comment]
I confirm that this issue really happens

**Comment by jpolitz** [comment]
@elibwhite is working on this on the `makeover` branch, along with a few other graphical/rendering issues.

**Comment by schanzer** [comment]
Still valid, given how much error messages have changed this year?

**Comment by jpolitz** [comment]
Yeah this is sort of N/A now.  It was useful feedback to inform lots of improvements, but since mouseovers and more... are both so different, it doesn't really apply.
