### ISSUE TITLE
Long lines in REPL are not consistent

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#347]
Currently, there are three ways to deal with very long lines:

1. wrap words: happens when long lines are produced from print(): `print(range(0, 100))`
2. add a scroll bar to the whole REPL: happens when long lines are produced from failed check/where block: `check: range(0, 100) is empty end`
3. add a scroll bar to only that line: happens when long lines are produced from evaluated expressions in REPL: `range(0, 100)`

Personally, I prefer 1) for all situations. Concerning debugging, 2) could be useful. But 3) is absolutely ugly. Moreover, when users scroll to the right because there is a scroll bar for whole REPL, they will see that long lines from 3) are incomplete. [This is misleading.](https://dl.dropboxusercontent.com/u/12865603/pyret-longlines.png)

This happens with both Chrome and Firefox on Mac.

**Comment by schanzer** [comment]
Did this make it into CPO, and if so can we close the issue?

**Comment by schanzer** [comment]
@sorawee 's proposed behavior (1) is now the default for all three cases on CPO. Close?
