### ISSUE TITLE
Multiline string fails when there is a character '`'

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#348]
For example, 

``````
```asd`asd```
``````

or

``````
```asd\`asd```
``````

will raise an error like `Pyret didn't understand your program around interactions1: line 1, column 0`. Since we use "```" as a delimiter, failing because of a single "`" shouldn't happen. In Python, for example, it's possible to write

```
"""""this"" will not upset Python\"\""""
```

**Comment by jpolitz** [comment]
Closing this as working-as-intended.
