### ISSUE TITLE
Images in check results don't get rendered as images

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#356]
For example:

```
check:
  I.circle(50, "solid", "red") is I.square(50, "solid", "red")
end
```

will print a to-string structure representation of the images rather than rendering them.  `error-ui.js` needs to not use the "reason" string from the check library directly, and do its own rendering, as usual.

This would also be a great example to make sure we can handle in a generic error renderer.

**Comment by blerner** [comment]
Hooray, this one's done :)
