### ISSUE TITLE
parsing issues

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#363]
This program doesn't parse:

```
f =
  lam(k):
    k((lam(shadow k):
          k(1)
        end)
      (lam(l-v):
          (lam(shadow k):
              k(2)
            end)
          (lam(r-v):
              k(l-v + r-v)
            end)
        end))
  end
```

I need to make clear to Pyret that I mean a function call:

```
f =
  lam(k):
    k((lam(shadow k):
          k(1)
        end)(lam(l-v):
          (lam(shadow k):
              k(2)
            end)
          (lam(r-v):
              k(l-v + r-v)
            end)
        end))
  end
```

But what I don' t understand is why I didn't need to do the same for the `(lam (r-v)` part.

**Comment by shriram** [comment]
Now I get a block error. I can't even tell whether this is an improvement. (-:

**Comment by jpolitz** [comment]
Closing as effectively a duplicate of https://github.com/brownplt/pyret-lang/issues/383

**Comment by schanzer** [comment]
@jpolitz says he closed it in July...but it's still open?
