### ISSUE TITLE
grammar error in `cases` error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#364]
````
The cases branch at definitions: line 62, column 6 should have only 2 arguments, but there are 1
````

"but there _is_ 1"

Also, I find the use of _only_ here strange: the error format should be, if F is the number of formal arguments and A is the number of actual arguments,

if F > A:
  ... should have F arguments, but there [is/are] only A
if A > F:
  ... should have only F arguments, but there are A

I don't mind rewording the entire phrasing to avoid having to parameterize is/are over how many A's there are.

**Comment by blerner** [comment]
I'm pretty certain I've fixed this grammar in the rich rendering of these errors: https://github.com/brownplt/pyret-lang/blob/101a3d152c70264d7f70264a45eae6a0989fd6c1/src/arr/base/error.arr#L139 (the two clauses you have above are swapped in the actual code).  @shriram please confirm and close.

**Comment by schanzer** [comment]
Pinging @shriram - if this is successfully fixed and folded into production CPO, can this be closed?

**Comment by jpolitz** [comment]
Yeah this is so fixed.

![screen shot 2016-07-16 at 10 13 37 pm](https://cloud.githubusercontent.com/assets/119891/16898325/9183812a-4ba2-11e6-93dd-bf202a96288d.png)
