### ISSUE TITLE
REPL should import standard modules although code contains some errors

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#373]
In code definition windows, type `a`, and click run. In REPL, it shows that code contains an error. As expected, REPL is still functional. The problem is, I can't refer to `list`, though I can still import it manually.

**Comment by schanzer** [comment]
Appears to be fixed on CPO, but will wait for @sorawee to confirm.

**Comment by jpolitz** [comment]
Confirmed fixed.
