### ISSUE TITLE
should this be an illegal string-dict?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#382]
````
[SD.string-dict: "Sue", 2, "Bob", 2, "Sue", 3]
````

[Note repeated value.]

Also, the SD lib really ought to export an empty-string-dict value to avoid having to write `[string-dict: ]`, which looks very awkward.

**Comment by jpolitz** [comment]
Immediate issue closed by b84ddde37dc1c2901df4bca088761fc52f070a08.

My vote:

A singleton called empty-string-dict for immutables
A function make-mutable-string-dict() for mutables

Same duplicate check for mutable dicts.

We should open/close separate issues for those, though.
