### ISSUE TITLE
Add well-formedness check for weird standalone statements

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#383]
There are a number of expressions that really ought to not appear on their own line.  For example,

```
e1 == e1
```

especially in a a check block, is probably a mistake.  Similarly, a lone identifier, binops, object lookup with dot, and underscore expressions have little reason to appear on their own before the end of a multi-statement block.  (Yes, binops could call side-effecting code and be useful... but that's a programming pattern I think we should be happy to disallow).

We should add a well-formedness check to look for these cases.  Especially the equality case above should get special treatment, because the user often will have meant `e1 is e2`.

**Comment by shriram** [comment]
I'm pleased to note that the original report was not frivolous — the issue clearly has staying power. (-:
