### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#390]
Suppose A import B and B import A, when the program runs, it will cause an infinite loop. This might be an expected outcome, but I think there should be a better way to handle this situation.

**Comment by schanzer** [comment]
Fixed?

**Comment by jpolitz** [comment]
Indeed.

It hasn't been prettified, but it reports explicitly that a module cycle was detected, and prints it; e.g.

```
"Detected module cycle: definitions:// => my-gdrive://middle-cycle.arr:0B32bNEogmncOWE13SFFnWWU4QkE => my-gdrive://provide-x.arr:0B32bNEogmncOSHhLR1VxLWpoLXM => my-gdrive://main-cycle.arr:0B32bNEogmncOMThGTDVLblJTWDA => my-gdrive://middle-cycle.arr:0B32bNEogmncOWE13SFFnWWU4QkE"
``
