### ISSUE TITLE
found two expressions should highlight each one separately

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#392]
````
fun f(x):
  x x
end
````

It says
````
Found two expressions on the same line
definitions: line 2, column 2
definitions: line 2, column 4
````
but each link highlights _both_ terms. It would be better if each highlight focused on that particular term: imagine a person still a bit fuzzy on the grammar. This would help them understand where the expressions begin and end, and hence might help them realize what is and isn't an expression (which might have been the source of the error).

**Comment by jpolitz** [comment]
This is fixed now.
