### ISSUE TITLE
tree-set's type inconsistency results in strange error highlighting

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#393]
> x = [tree-set: "3"]
    > x.member(1)
    Expected to get a Number as an argument, but got this instead:
    "3"
    at
    interactions2: line 1, column 0

So... it said that "3" causes the problem, but it highlights x.member(1)

(And actually, it's not only the error highlighting. `x = [tree-set: "3"]` is fine. It's `x.member(1)` that is not okay, so the function should not expect a Number, but should expect a String)

**Comment by blerner** [comment]
Horizon now renders this as:
```
Invalid use of < for these values:

1

"3"
Less-than requires:

    Two numbers,
    Two strings, or
    A left-hand operand that has a _lessthan method
```
which I think is far better than the existing error...

**Comment by sorawee** [comment]
Yes, this is better.
