### ISSUE TITLE
Using module import as type leaks JS undefined in error

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#394]
Example:

```
import sets as T
x :: T = 5
```

Says "undefined is not a function".

**Comment by blerner** [comment]
It's gotten worse: the error is now "An unexpected error occurred: TypeError: ann.check is not a function"

**Comment by jpolitz** [comment]
In the branch with modules and types, I'm adding a new kind of binding for import-defined names, and can make it an error if they are used on their own, which just kinda makes sense.

**Comment by blerner** [comment]
It's gotten worse: now it's an Internal error preventing any error from rendering.

**Comment by schanzer** [comment]
The error is now `The name T is used to indicate a type, but a definition of a type named T could not be found.`. Is this the error we want?

**Comment by blerner** [comment]
I think so; it will be hard to special-case noticing that T here happened also to be a module import, and have yet another special-purpose error message.  I think this is safe to close.
