### ISSUE TITLE
Use double-arrow and else instead of then: and otherwise: in ask expression

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#406]
For consistency, I think that cases expression and ask expression should have the same structure. then: and otherwise: are nice in a sense that it can be read literally and readers can understand the whole expression easily. However, => can mean imply or then as well. I see no reason why Pyret needs to distinguish them.

**Comment by schanzer** [comment]
This was last discussed nearly 2 years ago. Just checking if the issue is still live?

**Comment by shriram** [comment]
Yeah, I don't think this is a really pressing issue, nor is it going to change with any urgency. We'll reopen it once Oak graduates, get really rich, and makes a big donation.

**Comment by sorawee** [comment]
You know that's not gonna happen...
