### ISSUE TITLE
ignoredups for the REPL

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#416]

**Comment by blerner** [comment]
@ds26gte this seems like something you can tackle in the a11y stuff, too?

**Comment by ds26gte** [comment]
Do we care about keeping separate side-effecting programlets that are string-equal but produce different results on different runs?

**Comment by blerner** [comment]
I don't think so, no.

**Comment by ds26gte** [comment]
PR brownplt/code.pyret.org#283 now includes a fix for this. Excerpted from that PR's log:

> `Up/Dn` arrows traverse REPL history to populate the current prompt with an old input. These now skip all but one of contiguous duplicate inputs. However, `Alt-n` which traverses REPL history in order to recite it for the benefit of a blind user, should not skip duplicates.

> When populating the current prompt, the re-used input is said aloud for the benefit of a blind user.

**Comment by sorawee** [comment]
Fixed.
