### ISSUE TITLE
num-sin(10000000000000000) produces "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#419]

**Comment by ds26gte** [comment]
js-numbers.js did not have definitions for sin (and related functions) in BigInteger.prototype. Have added these now in 'roughnum' branch.

**Comment by jpolitz** [comment]
Do we have tests for all such functions?  This seems like something that testing ought to have caught.

**Comment by ds26gte** [comment]
I just added a fix in the 'roughnum' branch (documented in response to
sorawee's issue). The BigInteger.prototype didn't have definitions for sin,
atan, log and the like.  I converted the BigInteger to a JS fixnum before
calling the corresponding function. It may also be advisable to use the
modulo of the number wrt 2*pi, at least for the trig functions.

--d

**Comment by ds26gte** [comment]
(Ah. Didn't realize email was also going here.)

**Comment by schanzer** [comment]
Confirmed working on the roughnum branch. Closeable?

**Comment by ds26gte** [comment]
Yes, if we're closing issues even if they haven't been migrated to 'master'.

--d
