### ISSUE TITLE
Many roughnum errors are not Pyret errors

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#421]
For example, `num-sqrt(-1)` produces a JavaScript `Error`, not an `Error` as defined in `errors.arr`.  Using `throwMessageException` is the easiest way to get a bona fide Pyret error with a stack trace.

The same is true of "negative tolerance" (for within) and a few others; basically `throwRuntimeError` in js-numbers.js should not be used for errors that users see.

**Comment by blerner** [comment]
If we have the opportunity right now to make better errors than `throwMessageException`, we absolutely should: every time we've added a generic message exception, we've regretted it eventually... 

For these errors in particular, seems to me that we ought to have a `Number%(Positive)` annotation on these functions and get nice annotations errors, no?

**Comment by jpolitz** [comment]
Yup that seems like a much better idea for many of these that are checking properties of the numbers; especially division (check nonzero), and within/sqrt (check non-negative).

**Comment by blerner** [comment]
@jswrenn Can you tackle this?  We've already fixed the hardest part, of giving the js-numbers library the needed callbacks.  Remaining todo steps:
* In runtime.js, the `NumberErrbacks` object is used by the js-numbers library to throw actual Pyret exceptions.  Every method there currently has signature String -> thrown exception.
* Revise the signatures as needed, grep for the method uses in js-numbers, and change them to match.
* Add whatever new errors and render-fancy-reason/render-reason methods you need in error.arr to match.

**Comment by blerner** [comment]
Ah, what remains is #758.  Closing this one.
