### ISSUE TITLE
multi-line + up-arrow weird in command-line REPL

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#422]
In the REPL type
````
1 +
````
followed by C-Enter. Now the cursor is on the next line, but the command isn't yet done. Now hit up-arrow. The cursor is next to the `1`. Now hitting down-arrow doesn't take you back to the next line; you can only get to it by repeated right-arrow.

Furthermore, if you repeatedly right-arrow, you notice there's an extra newline (so the input is three, not two, lines long).

If you repeat the para in the opening, then type
````
3
````
on the new line, then hit up-arrow, the `3` disappears, but if you type down-arrow, the `3` reappears (but the cursor remains at the `1`).

**Comment by jpolitz** [comment]
@breuckelen, do you get notifications for these?  Just flagging this for you if not.

**Comment by breuckelen** [comment]
There were some bugs with up and down arrow key navigation and display that
I thought I fixed in some recent commits -- I'm not able to replicate any
of these issues, so can you try pulling the latest version and let me know
if you get the same problems? No need to rebuild pyret.
