### ISSUE TITLE
(unable to reproduce) deadlock? from confirmation box

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#423]
I don't know the exact condition that will trigger this issue. However, it happens to me more than three times and is very annoying. After I navigated to other pages, a confirmation box appeared and asked me whether I really want to close the page. However, both choices will produce another confirmation box and so on. In this state, I cannot focus on anything except the box itself, and Google Chrome's task manger is disabled as well, leaving me to the only choice: force quit Google Chrome.

**Comment by jpolitz** [comment]
What OS/version?  Do you remember anything more about what you were doing?  Just typing into the location bar and pressing enter, copying and pasting something, following a link...?

I navigate away from the editor a lot and have never had this.  I _have_ seen Chrome pop up the confirmation dialog twice before, but never more.  That's usually when I wake up from suspend or try to navigate away while the page is still loading, which probably catch it in odd states.

**Comment by sorawee** [comment]
OS X Yosemite, Chrome 39. I remembered that one time I clicked the back button and it happened, but I can't remember anything more than that.

**Comment by schanzer** [comment]
Given the difficulty of reproducing this, and that it's been half a decade with a LOT of work having been done under the hook, can we close this?

**Comment by sorawee** [comment]
Yep!
