### ISSUE TITLE
Inconsistent function name (num-tostring / string-to-number)

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#424]
Changing `string-to-number` to `string-tonum` would be better? ...

**Comment by justinpombrio** [comment]
There actually seem to be *four* functions in scope:
  num-tostring
  string-tonumber
  num-to-string
  string-to-number
Only the first and third are mentioned in the docs.

I presume there should be just two functions. Obviously it would be
preferable if "number" were spelled the same in both functions. I *really*
dislike the function name "string-tonumber", though. Why does the first
word boundary get a dash when the second doesn't? It's hard to remember,
has no semantic meaning that I can discern, and reads poorly ("tonumber" is
not a word).

How about naming the functions as follows?
  string-to-number  (already exists)
  number-to-string  (new)

Justin

**Comment by sorawee** [comment]
Yes, `number-to-string`/`string-to-number` would be nice. However, it seems that all functions about `Number` are named `num-*` (`num-sin`, `num-log`), and that all functions which convert one thing to another thing are named without hyphen (`_tostring` method, `tostring()`, `_torepr`, `torepr()`).

**Comment by justinpombrio** [comment]
You're right about num vs. number. A better naming would be:
    num-to-string
    string-to-num

It's not true that all functions that convert one thing to another thing
are named without hyphen, however. In fact, every other conversion that has
"to" in the name uses full hypenation:
    raw-array-to-list
    Array.to-list-now
    list-to-set
    Set.to-list

(And, even following your rule, the name would be "stringtonum", not
"string-tonum". What's the logic that goes from "tostring doesn't have a
hypen" to "string-tonum should have exactly one hyphen, in the first
position"?)

Is there actually a reason "tostring" and "torepr" lack hyphens in the
first place?

Justin

**Comment by shriram** [comment]
+2 -- +1 for summer, +2 for the Great Global Namespace Rename.

[I would question why "string" instead of "str", when we're using "num"
instead of "number". Etc.]

**Comment by schanzer** [comment]
According to https://www.pyret.org/docs/latest, this inconsistency is no longer an issue. Closing
