### ISSUE TITLE
nothing in tests results doesn't print rather than printing "nothing"

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#428]
At some point recently I started seeing test results where, if "nothing" mismatches a return type, it doesn't print in test results:

![image](https://cloud.githubusercontent.com/assets/119891/5924408/80825b3c-a629-11e4-83f7-d6fba3a4ab48.png)

**Comment by blerner** [comment]
@jpolitz Closable, now that the check blocks are rendered differently?  I tried it on this program:
```
fun foo(n :: Number): n end
check:
  foo(nothing) is 5
end
```
and `nothing` does get printed.
