### ISSUE TITLE
Searchable documentation

### ISSUE THREAD

**Issue by awan1** [brownplt/pyret-lang#433]
It would be really nice to be able to search the documentation (http://www.pyret.org/docs/latest), since Google searches for simple things like "Pyret for loop" often leads to the Tour page instead of the specific result... It's not hard to find the result I want from there, I guess, but when looking for something that doesn't exist ("Pyret while loop", which doesn't exist because we should use recursion with an accumulator) I'd prefer to get a "no matches found" with a documentation search than a bunch of results from Google that don't actually lead anywhere.

Thoughts?

**Comment by blerner** [comment]
It's a feature we definitely want to have, and/but we haven't figure out the technical means of doing so yet.  (At a nitty-gritty level, the mechanism by which we produce cross-references within the existing documentation, such as clicking on type or function names and jumping to their definitions, is not the same method as the one used by scribble to generate search indices.  We "just" have to figure out how to connect them, and also to produce search terms that aren't Pyret-defined expressions, such as "while loop".)

**Comment by dyoo** [comment]
By the way: you can scope the search to a particular site.  E.g.

    [site:http://www.pyret.org/docs/latest while loop]

Most of the search engines support such a feature.

**Comment by awan1** [comment]
Thanks, @dyoo - I completely forgot about that!

**Comment by schanzer** [comment]
OK to close, now that this exists?

**Comment by jpolitz** [comment]
Yup!
