### ISSUE TITLE
Feature Idea: keyboard shortcuts and switching between editor/REPL

### ISSUE THREAD

**Issue by awan1** [brownplt/pyret-lang#435]
Two parts to this:

1) **Is there a good way to toggle between the REPL and editor using the keyboard?** `shift+tab` comes to mind as a candidate, keeping `tab` to properly indent the current line.

2) I noticed that `ctrl+enter` and `shift+enter` both map to "Run". The Run button automatically shifts focus to the REPL, which definitely seems like the right default option; **I was wondering if one of the two keyboard shortcuts could be mapped to a Run-without-changing-focus option that would leave the focus on wherever it was last.** So I can type in a new line of code, hit Run-without-changing-focus, and continue editing from there without having to click on the line of code that I was just on. 

This feature wouldn't make sense if one of those two commands didn't work on some keyboards / setups but I can't immediately think of a case where that would be true.

(definitely a low-priority feature...)

**Comment by justinpombrio** [comment]
Actually, the "Run" button *doesn't* shift focus -- the completion of
running the program shifts focus. I often press to "Run" button to run
tests as I continue to type, so the focus suddenly shifts out from under my
cursor at an unknown point in the future.

It might actually be worth considering changing the default to *not* shift
focus: the question is whether "Run" more often means "run my tests", or
"run my code, and then I'll interact with it in the REPL".

(Of course, still pretty low-priority.)

Justin

**Comment by schanzer** [comment]
F6 is the proper convention for this (borrowing from Chatzilla), and it's an established norm in the blind community.

**Comment by blerner** [comment]
@schanzer: are those keystrokes common in *browsers* in the blind community? Ctrl+S is a browser hotkey to save the page locally as an html file, I think F6 focuses the address bar, etc etc... I genuinely don't know the right answer here, but +1 for following established convention if there is some!

**Comment by schanzer** [comment]
F6 is a convention, which was pioneered by Chatzilla but has now spread to numerous other web applications. (Citation: Sina Bahram, the a11y consultant who we've hired to help show us the way.)

**Comment by schanzer** [comment]
@ds26gte close this when you eventually upstream your changes.

**Comment by schanzer** [comment]
There's an open PR for this at https://github.com/brownplt/code.pyret.org/pull/261

**Comment by schanzer** [comment]
Between this being a CPO issue *and* addressed in Dorai's a11y work, can we close this in pyret-lang?

**Comment by schanzer** [comment]
Closing since this is (1) implemented (F6) and (2) was never a pyret-lang issue to begin with
