### ISSUE TITLE
"Values not equal" for seemingly equal values

### ISSUE THREAD

**Issue by rrshaban** [brownplt/pyret-lang#438]
I'm getting an odd error when trying to test out a program. Essentially, it looks like this:

```
Values not equal:
v-num(0)
v-num(0)
```
Running `check: v-num(0) is v-num(0) end` works fine, so I'm not sure what's causing this. It's occuring for all my checks: 

```
 test (eval("(first (link (link 4 empty) (link 2 (link 3 (link (link 4 empty) empty)))))") is
  v-link(v-num(4), v-empty)): failed, reason:
Values not equal:
v-link(v-num(4), v-empty)
v-link(v-num(4), v-empty)
```

Because the values output look exactly the same, it doesn't seem to be a problem with my function implemetation -- any thoughts?

**Comment by jpolitz** [comment]
Can you send me a share link (over email, I'd rather not post potential assignment answers here)?

I suspect it has to do with the way the assignment is configured in CS91, and I wonder if it's just something that's happening to you or if others will run into it as well.

**Comment by rrshaban** [comment]
The issue was datatypes being imported from the same file with a different name (due to typo). From @jpolitz 
>The difference causes it to be loaded as a different module than the one your tests use, so there are two defintions of "v-num" (and all the datatypes) floating around.
