### ISSUE TITLE
Flaky Travis runs

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#446]
Travis has been dying with "Error 137" recently.  I suspect this means Travis is running out of memory:

https://github.com/travis-ci/travis-ci/issues/1409
http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

I'm trying to reduce the number of processes from 4 to 3 to see if that makes runs fail less randomly.  It could be that Travis has weaker VMs now, or that something in Pyret changed that caused an increase in memory usage, though the repo has been quiet on compiler changes lately, so I'm a little confused about what that could be.  Anyway, making this issue to track future Travis breakages that aren't the fault of our tests and build script.

**Comment by blerner** [comment]
One possibility is just unlucky timing: the first few big Pyret files 
are anf, anf-loop-compiler, ast-anf, ast-util, and compile --- and 
they're all at the beginning of the alphabet, so they all run in 
parallel.  We may want the build-script for Travis to manually make 
those files in series, and then trigger the parallel build for the 
remainder...

**Comment by schanzer** [comment]
@jpolitz @blerner is this still an issue?
