### ISSUE TITLE
Readonly REPL entries should not have a blinking cursor

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#452]
I've looked around for a while and cannot find an agreed-upon convention for how cursors behave in read-only textfields, but a *really* common confusion among teachers/students is that prior REPL entries cannot be edited. Blinking the cursor seems to deepen this confusion, since there's no visual cue at all to differentiate readonly from editable fields. 

Suggest: don't have the cursor blink, or hide it altogether.

**Comment by jpolitz** [comment]
It's hidden now.  Thanks!
