### ISSUE TITLE
short-circuit evaluation and types

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#455]
I totally understand reasons behind this. It just doesn't make sense that one works while the other doesn't.

    > true or 'foo'
    true
    > true and 'foo'
    Expected to get a Boolean as an argument, but got this instead

**Comment by blerner** [comment]
In the absence of a static type system (i.e., the default case for most Pyret programs), you can't have both short-circuiting behavior and also type safety, since you'd have to evaluate the right hand side to determine what its type is.  There's nothing to be done about this.
