### ISSUE TITLE
Representation error in roughnums

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#456]
within(~0.1)(~6e-324, 5e-324)

Raises `RangeError: Invalid array length`

~~The error means that a call to `Array` got a non-integer argument.~~

Scratch that, it's when the `length` of the array is assigned into at https://github.com/brownplt/pyret-lang/blob/master/src/js/base/js-numbers.js#L211

**Comment by jpolitz** [comment]
It seems like `expandExponent` is blindly calling `zfill` with a negative exponent, which seems off.

**Comment by ds26gte** [comment]
Fixed in branch roughnum, but the expression now returns an error 

"roughnum tolerance too small for meaningful comparison"

(It's the absolute tolerance that's too small here.)
