### ISSUE TITLE
num-truncate returning fractions as they are

### ISSUE THREAD

**Issue by rrshaban** [brownplt/pyret-lang#460]
`num-truncate(1 / 3)` does not do what is expected (return `0`) but instead returns `1/3`. It seems to return all fractions as they are, instead of truncating. 

Lines 3633-3640 of /src/js/base/runtime-anf.js:
```
    var num_truncate = function(n) {
      thisRuntime.checkArity(1, arguments, "num-truncate");
      thisRuntime.checkNumber(n);
      if (jsnums.greaterThanOrEqual(n, 0)) {
        return thisRuntime.makeNumberBig(jsnums.floor(n));
      } else {
        return thisRuntime.makeNumberBig(jsnums.ceiling(n));
      }
```
I can't understand why this is happening, as both num-floor and num-ceiling (which call the same code as the two return statements) work on fractions (`num-floor(1/3) => 0` and `num-floor(1/3) => 1`):

Lines 3655-3664:
```
    var num_ceiling = function(n) {
      thisRuntime.checkArity(1, arguments, "num-ceiling");
      thisRuntime.checkNumber(n);
      return thisRuntime.makeNumberBig(jsnums.ceiling(n));
    }
    var num_floor = function(n) {
      thisRuntime.checkArity(1, arguments, "num-floor");
      thisRuntime.checkNumber(n);
      return thisRuntime.makeNumberBig(jsnums.floor(n));
    }
```

Any thoughts as to why this is happening?

**Comment by ds26gte** [comment]
I'm can't duplicate this bug. Which branch?

```
ds26gte@thefang:~/public_html/pyret-lang/src/js/base$ git branch
* master
  roughnum
ds26gte@thefang:~/public_html/pyret-lang/src/js/base$ cat s.arr
print(num-truncate(1 / 3))
ds26gte@thefang:~/public_html/pyret-lang/src/js/base$ py s.arr
0
The program didn't define any tests.
ds26gte@thefang:~/public_html/pyret-lang/src/js/base$ 
```

**Comment by jpolitz** [comment]
I'm pretty sure @rrshaban is running this from code.pyret.org, where I can confirm I get

```
> num-truncate(1/13)
1/13
```

Which is pretty clearly wrong.

**Comment by jpolitz** [comment]
(Also, it does look like this is fixed on master/roughnum, just not pushed out yet.)
