### ISSUE TITLE
Non-Pyret error messages in Roughnums

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#462]
There are still some errors in roughnums that raise a JavaScript error rather than a Pyret error, for example:

```
num-exp(1208769287562394756329857632985723645872)
```

Says "roughnum overflow error" and doesn't give a stack trace or any location information.

**Comment by blerner** [comment]
IIUC, it looks like this should be easy to fix.  The current js-numbers library exposes a `throwRuntimeError` function, which simply is `throw new Error(msg)`.  I *think* this is a legacy of js-numbers formerly being a library independent of Pyret, so it couldn't use Pyret's runtime errors directly.  Now, we could have js-numbers include ffi-helpers, and use that library's generic errors, or we could keep them statically independent, but dynamically have runtime-anf "patch" the exported js-numbers' throwRuntimeError function to use ffi-helpers instead.  Either way, there are ~40 roughnum errors that use `throwRuntimeError`, so they should all be simultaneously improved by fixing this one function.

**Comment by schanzer** [comment]
This does not appear to be fixed on horizon. 

```num-exp(1208769287562394756329857632985723645872)``` results in
`An unexpected error occurred: TypeError: Cannot read property 'throwDomainError' of undefined`

**Comment by blerner** [comment]
I've fixed this already, but the fix hasn't migrated through yet.

**Comment by jpolitz** [comment]
![screen shot 2016-07-15 at 7 51 37 am](https://cloud.githubusercontent.com/assets/119891/16873442/31db13e2-4a61-11e6-9a32-1e87558e19dd.png)

Looks sensible to me, though not pretty yet.

The unpretty-ness is covered by https://github.com/brownplt/pyret-lang/issues/758, so closing this issue.
