### ISSUE TITLE
shrunken image doesn't expand on window resize

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#463]
Generate an image big enough that it has to be shown in shrunken form. Resize the window so it no longer needs to be. It still is.

This leads to the odd behavior that your repl may show

```
> I # where I is some image expression
[shrunken image]
> I
[same image, but blown up]
```

because you resized in the middle.

This isn't a high priority, so if you want to just close it off that's fine, but it is mildly troubling.

**Comment by blerner** [comment]
I'm tempted to leave this alone, because as you resize the window just past the cutoff, a small image will grow enormously and cause a reflow of all the rest of the value around it (especially with lists of images...), leading to a jarring shift.

**Comment by schanzer** [comment]
I'm inclined to agree.

**Comment by jpolitz** [comment]
Agreed w @blerner and @schanzer . Closed by democracy.
