### ISSUE TITLE
overlay-xy should point to above

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#464]
`overlay-xy` is really bad for constructing certain kinds of images. For instance, if you want to put a triangle above a rectangle, it's hard to know what x and y to use: if the triangle is "size" 50, you need to do math that may be beyond a student's abilities to figure out what its _height_ is for the purpose of figuring out the offset. Plus there's the annoyance of what the x and y in `overlay-xy` even mean (though the documentation is now better at this). It would be a good idea for `overlay-xy` to point to `above` for these simple cases (and perhaps in the other direction, too). Also, `above` should probably be accompanied by `below`.

**Comment by blerner** [comment]
I'm dealing with something similar, trying to clean up this API in our Java implementation of the image library, and it's indeed awkward.  If I understand the docs correctly, using a delta of (0,0) the images should be aligned on their top-left corners, so presumably, a y-shift of `(0 - image-height(the-triangle))` would be "all" that's needed, right?

**Comment by blerner** [comment]
See also #417, where I tried to suggest a cleaner API for all this...

**Comment by shriram** [comment]
#417 is now closed. @blerner should this be closed too? Not sure we've completely resolved this…

**Comment by blerner** [comment]
Well, no one ever commented on my proposed API in the last comment of that issue, which I still think is a decent solution out of this tangle....

**Comment by shriram** [comment]
Reopening and commenting there.

**Comment by schanzer** [comment]
I'm all for the new API. Do we save this old one for compatibility's sake? Eliminate it and force Reactive to implement it via a teachpack?

**Comment by blerner** [comment]
As I wrote in #417, implementing the existing simpler APIs in terms of that one general one is probably a good idea: having simple things like `above` and `overlay-xy` continue to work simply is good.

**Comment by schanzer** [comment]
@blerner , we should close if this is addressed in `image-structs`. No need to spend cycles on the deprecated library.

**Comment by blerner** [comment]
I'm adding `below` in #417.  Also, list-y versions, like `above-list([list: red, yellow, green].map(lam (c): circle(30, mode-solid, c) end)`, and `below-list`, `beside-list`, `overlay-list` and `underlay-list`.
