### ISSUE TITLE
numeric argument to `star`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#467]
This is currently the length of the side. A much better semantics might be the length of the radius of the nearest enclosing circle. Then you can overlay a star in a circle and get what you normally expect (think Texaco logo). Right now it's extremely hard to obtain that with everything lined up right. [Code.org's star uses the "radius" interpretation.]

**Comment by shriram** [comment]
Thoughts on this?

**Comment by schanzer** [comment]
Actually, the numeric argument IS the size of the surrounding circle. The reason it doesn't line up is that `overlay` aligns the centers of the images, and the bottom-most pixel of a star is well above the bottom of the circle in which it's inscribed.

**Comment by schanzer** [comment]
Unless we choose to bring back pinholes, this issue should be closed. Without pinholes, there's no other way to refer to the "natural center" of an image other than finding the center of the bounding box.

**Comment by schanzer** [comment]
Since the numeric argument to `star` already does what @shriram Shriram proposes, I'm going to close this. Until we change the semantics of `overlay` (see Ben's revised API) or bring back pinholes, there's no action to be taken here.
