### ISSUE TITLE
fold library error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#469]
I wrote

```
space = 
  for fold(i from range(0, 100), s from spacebg):
    I.place-image(star, random(500), random(500), s)
  end
```

and got

```
Expected to get List because of the annotation at src/arr/base/lists.arr: line 644, column 51 but got
[big black square which is spacebg]
```

While literally true, this was a really unhelpful error message.

**Comment by blerner** [comment]
What would you want it to say?

**Comment by Emmay** [comment]
The error message for the above code now reads: `The annotation, List, at builtin://lists:740:51-740:58 was not satisfied by the value [big black square]`
Which is probably not any more helpful than the original error. @shriram, what would be a better error here?

**Comment by schanzer** [comment]
@shriram , ping?
