### ISSUE TITLE
Roughnum inequalities

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#471]
Is it OK that both `~1 <= ~1` and `~1 >= ~1` both return `false`?  Do we have a good justification?  I can see an argument, but I'm not sure I like the conclusion.  Do we care if both return `true`, and `(a <= b) and (a >= b)` is a way to tell if two roughnums are the same floating-point number?

**Comment by ds26gte** [comment]
That's certainly a way to go: but it makes one wonder why ~1 == ~1 doesn't just suck it in and return true.

The current thinking is that folks ideally should not use <= (=>) on roughnums, but if they did, these should be treated as simply < (>). 

Ideally <= (=>) should error, I think, but that would be too disruptive, as a user may have innocently used <= (=>) without expecting that a roughnum would bubble up on the scales because of roughnum contagion.

Ideally^2, even < and > should be disallowed on roughnums — ~2 < ~2.0000001 is not really persuasive to me. But that's probably too radical.

**Comment by jpolitz** [comment]
I agree on the last point that you can't _really_ trust `<` on floating point.

I'm writing up docs where I suggest that users use `within(~0)(a, b)` to check if two `Roughnum`s have exactly the same floating-point representation.  I think that's actually useful.

I'm mainly worried about someone who writes:

```
if x >= y:

else if x <= y:

end
```

And gets a baffling "no cases matched" error.  I think it's really confusing if that isn't the same as:

```
if x >= y:

else:

end
```

As for why `==` doesn't suck it in and return `true`, it's because a large part of the motivation for this is _testing_.  Programmers will probably find ways we're not even thinking of to figure out if numbers have the properties they desire in their functions, but when testing, we want to guide them away from checking equality of roughnums with `is`.  Since we care about `is` meaning the same thing as `==`, those need to be kept in sync.

**Comment by ds26gte** [comment]
I can see it as reasonable that ~1 >= ~1 should return true. 

Unless someone wants to voice an objection, I'll go ahead and code it and modify the tests.

**Comment by justinpombrio** [comment]
Is the concern that (<=) may somehow be more dangerous, or reveal more
about equality, than (<)? They actually reveal exactly the same
information. In particular, you can test for equality and inequality using
(<) just as easily as with (<=):

    x == y   iff       (x >= y) and (x >= y)
    x != y   iff   not((x >= y) and (x <= y))

    x == y   iff   not((x < y) or (x > y))
    x != y   iff       (x < y) or (x > y)

So if x < y is allowed, I don't see why x <= y shouldn't be allowed too.
Both leak equality, but neither is likely to be used for that purpose
accidentally.

Justin

**Comment by jpolitz** [comment]
My main uneasiness is that >= isn't  (a > b or a == b) for numbers, which
would be a useful and expected equivalence. But I think something has to
give in order for comparisons to be particularly usable.

**Comment by justinpombrio** [comment]
You get the other equivalence, at least: (a >= b) iff not(a < b).
