### ISSUE TITLE
image-lib: range of aStyle

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#475]
Currently, the code is:

        //////////////////////////////////////////////////////////////////////
        // colorString : hexColor Style -> rgba
        // Style can be "solid" (1.0), "outline" (1.0), a number (0-1.0) or null (1.0)
        var colorString = function(aColor, aStyle) {
          var alpha = isNaN(aStyle)? 1.0 : aStyle/255;
          return "rgba(" + colorRed(aColor) + "," +
                          colorGreen(aColor) + ", " +
                          colorBlue(aColor) + ", " +
                          alpha + ")";
        };

This doesn't make sense. Seeing from the code, I think that aStyle should have range from 0 to 255. Otherwise (if aStyle ranges from 0-1.0), there shouldn't be denominator.

**Comment by schanzer** [comment]
You're right - the comment there should say 0-255

**Comment by sorawee** [comment]
We have the contract `colorString : hexColor Style -> rgba` and then we say:

> Style can be ... a number (0-1.0)

It definitely describes the parameter.

I will fix this in the sql branch right now. No need to reopen the issue (nothing will be seen from user-side anyway).
