### ISSUE TITLE
Bad error when mixing assignment symbols

### ISSUE THREAD

**Issue by rrshaban** [brownplt/pyret-lang#482]
The following code
```
p = 1
p := 2
```
gives the following error, which doesn't seem to be an actual error message:
`bad-assignment(p, srcloc(definitions, 229, 4, 6795, 229, 16, 6807), srcloc(definitions, 226, 2, 6747, 226, 29, 6774))`

when what it probably should say is that `p = ` needs a `var` in front of it, or that you can't `:=` an identifier.

**Comment by jpolitz** [comment]
Thanks!  Fixed if you refresh, should now say something like:

```
The name x is defined as an identifier, but is assigned as if it were a variable at definitions: line 3, column 0.
One possible fix is to change the declaration of x to use var at definitions: line 1, column 0.
```
