### ISSUE TITLE
big bang box should be cleaned after it is closed

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#483]
Every time I call big bang, the box will be appended to the DOM. However, it is not removed when the box is closed despite the fact that it will not be able to be referenced anymore.

This is not that serious for the normal big bang, as the element inside the the box is just a canvas. However, for the project that I am doing, which invokes big bang box via `runtime.getParam("current-animation-port")`, there could be a lot of SVG elements. It therefore would not be a good idea to leave these elements.

Currently, my workaround is to remove elements manually:

    var terminate = function () {  d3.selectAll(".maind3").remove(); }; 
    // maind3 is the outmost div that elements I am working with lie in.
            
    // simulate dialogclose
    d3.selectAll(".ui-dialog-titlebar-close").on("click", terminate);
    // this is actually bad. there might be a lot of '.ui-dialog-titlebar-close' which are irrelevent
    d3.select("body").on("keyup", function(e) {
        if (d3.event.keyCode == 27) { terminate(); } // hit esc key
    });

It however should be Pyret itself that handles this issue.

**Comment by schanzer** [comment]
@sorawee , is this fixed now that your new world-lib is merged in?

**Comment by sorawee** [comment]
Will be fixed when https://github.com/brownplt/code.pyret.org/pull/77 is merged (there are two PRs. We merged only of them and forgot the other one; CC'ed. @jpolitz )

**Comment by jpolitz** [comment]
Got it.  It all makes so much sense now.  Thanks for clearing that up, @sorawee

**Comment by schanzer** [comment]
brownplt/code.pyret.org#77 is now merged. Closable?
