### ISSUE TITLE
Click run button before a program is loaded results in weird output

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#484]
When I load a file I created, if I click run button before it finishes loading, in CPO I got

    An unexpected error occurred: [object Object]

in patch-experiment.herokuapp.com, however, I got "Ahoy, world!" instead

**Comment by schanzer** [comment]
Confirmed fixed.

**Comment by jpolitz** [comment]
(Bad reference, meant to reference https://github.com/brownplt/code.pyret.org/issues/484)
