### ISSUE TITLE
Cannot find documentation on numeric functions.

### ISSUE THREAD

**Issue by Heimdell** [brownplt/pyret-lang#486]
I searched for modulus operation name, and wasn't able find any clues in the docs. At the end, I found `num-modulo` name somewhere in the pyret code. Could you please document it, along with other operations like num->string conversions, etc?

**Comment by jpolitz** [comment]
It's on this page, if it helps:

http://www.pyret.org/docs/latest/numbers.html

What did you try for finding it, and what do you wish had been available?
I'd agree that the docs aren't particularly searchable. In this case
Googling "modulo site:pyret.org" takes you to the right place, but that
isn't quite obvious.

Thanks for asking!

**Comment by schanzer** [comment]
This is more of a helpdesk-style question (with a great answer from @jpolitz !). Since it's answered, is there any reason to keep it open?
