### ISSUE TITLE
Only options at code.pyret.org are "Start Coding" and "What's Pyret?"

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#490]
There should be an option to log on and see a list of my programs. Going to Google Drive and opening my programs in Pyret is too much work and not intuitive.

**Comment by jpolitz** [comment]
Need a link to a good Drive page that's easy to open.

**Comment by blerner** [comment]
This is related to #489 and #459...

**Comment by jpolitz** [comment]
This is somewhat fixed on horizon.  Now the left button is "Log In", which changes to "My Programs" when already logged in, and it goes directly to the Drive folder view.

This still requires right-clicking on files to open them in CPO, but this is about half of what we wanted.  As far as I can tell from StackOverflow and Google's documentation, there isn't a way to _force_ user's double-click behavior in Drive to open up a file with a particular app, so they have to either right-click to open with "Open With...", or go into settings and set the app as a default.

**Comment by schanzer** [comment]
Now that we have the picker API, _and_ the "My Programs" button, I'm comfortable closing this.
