### ISSUE TITLE
Safari: Some images take longer to show up in animations than others

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#492]
Example: https://code.pyret.org/editor#share=0B9rKDmABYlJVN1o0TmdHVzhiQXM&v=v0.5r852

In safari, the image of the parachute jumper does not appear until roughly halfway down the screen, even through his coordinates are changing and the program is running. In Chrome, the jumper image appears at the top of the screen as soon as the program loads, as it should.

**Comment by schanzer** [comment]
This definitely improved (no diff btw horizon and CPO), but it still appears that Safari is starting the big-bang a little before the image is actually loaded. I suspect you've got some callbacks set up so that everything is paused until the needed resources are loaded, right? Any chance Safari is throwing the onload() event prematurely?

**Comment by Emmay** [comment]
I'm still seeing this behavior in Safari (not Chrome), but only the _first_ time the program is run. This happens in the code above (using big-bang) and newer programs like https://code.pyret.org/editor#share=0B9rKDmABYlJVWUlZTHVVRDFOdk0&v=f1d3c87
(using reactor). Since the images consistently load correctly after the initial run, I'm OK with closing this issue, unless you'd like to keep it open for reference.

**Comment by schanzer** [comment]
FYI - this issue is fixed in Safari 12 (and for all I know, Safari 11). Propose we close as WONTFIX.

**Comment by schanzer** [comment]
@blerner @jpolitz Current safari versions also do not have this issue. OK to close?

**Comment by schanzer** [comment]
This issue is fixed for any version of Safari less than 2 years old. Given that Apple is pretty militant about forcing upgrades on their users, _and_ that Safari probably makes up a very small percentage of CPO users, I'm going to close this. Feel free to re-open if I'm being too aggressive.
