### ISSUE TITLE
join-str is inefficient

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#495]
The complexity of `List.join-str` seems to be quadratic. Because String is immutable, `a.concat(b)` would need to allocate a space of the new string, resulting in `O(len(a) + len(b))`. Doing this operation on a growing string results in a bad performance. A quick search in Google, however, suggests that most Javascript engines optimize `.concat` to be faster somehow, but I don't think that we should rely on these optimization trick. Also, I tried running:

```
string-length(range(0, 5000000).map(lam(i): "a" end).join-str(""))
```

vs

```
for (var i = 0; i <= 5000000; i++) arr.push("a");
arr.join('').length
```

The latter is significantly faster. (Okay, I am not fair here since the latter is in Javascript level and works on array directly, but the point is that I think that optimization trick doesn't work with long list/array).

**Comment by schanzer** [comment]
Implemented in #1208, pending merge
