### ISSUE TITLE
Sharing code should show you a URL

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#496]
Not just an import.... line.

**Comment by sorawee** [comment]
You can right click on the link and select "Copy Link Address" to do so

**Comment by Emmay** [comment]
That's not ideal for middle school students. The URL should be clear and obvious. Even as an adult user, it's not clear how I would use the import... line to share my video game or code with a friend.

**Comment by jpolitz** [comment]
I agree.  What do you think, just put another box like the import box
(which highlights the text automatically) with the URL in it?

**Comment by Emmay** [comment]
I like that idea. Maybe make the URL bold, so it stands out more?

**Comment by Emmay** [comment]
Any updates on this? Tomorrow is the last day of my class and I'd like it to be easier for the students to share their game URLs.

**Comment by jpolitz** [comment]
Fixed by 5bf7e7629a092f1833ec97df5216860dea02a083 and pushed, thanks for the poke.
