### ISSUE TITLE
Reconsider multiline-comment token

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#499]
I recently found my old code with lines:

    #cases (List) lst:
    #|  empty => ...

The rest are all blue because `#|` indicates "open multiline-comment". This, to me, indicates that `#|` is not a good symbol to be used. Actually, any token which contains `#` should not be used as multiline comment token because it would be confusing.

**Comment by blerner** [comment]
Ironically, I'd say that's only a mediocre example, because your original uncommented code wasn't indented properly: the `|` should never align with the `cases`, but rather be indented two more spaces...

**Comment by sorawee** [comment]
Right. What about:

    ask:
      | a == 1 then: 10
      #| a == 2 then: 100
      | a == 3 then: 1000
      | otherwise: 10000
    end

**Comment by sorawee** [comment]
Putting a space there is an easy fix to solve it, though I'm still inclined to think that `#|` is not a good one.
