### ISSUE TITLE
Various issues on runtime-anf / js-numbers

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#503]
No location of error (like "interactions1: line 1, column 0")

```
> ~1e1000
roughnum overflow error
```

Error not displayed properly

```
> ~1 == ~2
Error:
equality-failure("Roughnums", ~1, ~2)
```

Check arity

```
> within(1, 1000)(1, 1, 2) # it is supposed to have one and two arguments respectively
true
> within-rel-now(1)(1)
false
> within-rel(1)(1)
false
> within-abs(1)(1)
false
> equal-always(1, 1, 3, 4)
true
...
```

Display function's name correctly:

```
relative tolerance -1 outside [0,1] => within: relative tolerance -1 outside [0,1]
                                                     => within-now3: relative tolerance -1 outside [0,1]
                                                     => ...
expt: division by zero => num-expt: division by zero
exp: argument too large => num-exp: argument too large
modulo: the first argument 6/5 is not an integer => num-modulo: the first argument 6/5 is not an integer
sqrt => num-sqrt
log => num-log
...
```

**Comment by jpolitz** [comment]
@ds26gte, can you tackle these?  They all seem roughnum related.

**Comment by blerner** [comment]
Ignore the error not displayed properly problem; I've handled that in a separate branch, and it'll get fixed here when that merges in.

**Comment by ds26gte** [comment]
Can I make the fixes (for the ones not related to the display) in the `master` branch?

**Comment by ds26gte** [comment]
Arity-check fixes for within* and equal* are now in the `roughnum` branch.

**Comment by schanzer** [comment]
Most of these are now fixed on CPO. The location information is still missing from ` ~1e1000`, bu the others appear to behave correctly.

**Comment by blerner** [comment]
This is very closely related to #758.

**Comment by jpolitz** [comment]
I think the right thing to do for this case is to have a new entrypoint, `makeNumberFromStringLiteral`, that gets a source location and reports a specific error.  @ds26gte are you interested in taking a whack at that approach?

(It also seems like we ought to be able to check for overflow as a well-formedness error, though that would require exposing the roughnum logic to the compiler rather than just the runtime, which is more engineering and dependencies added)

**Comment by schanzer** [comment]
@ds26gte can we give a better error for ~1e1000? That's the last problem keeping us from closing this issue.

**Comment by blerner** [comment]
I think this is on @jswrenn to improve the error message rendering.  The plumbing has been put in place through the js-numbers library to raise bespoke error messages where appropriate, but the implementation of the NumberErrbacks in runtime.js is still stalled on just throwing plain message exceptions.
