### ISSUE TITLE
Could not make docs

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#504]
~/pyret-lang/docs/written$ make
    scribble \
        ++style styles.css \
        ++style ../../node_modules/codemirror/lib/codemirror.css \
        ++style editor.css \
        --prefix myprefix.html \
        ++extra ../../node_modules/codemirror/mode/pyret/pyret.js \
        ++extra ../../node_modules/codemirror/lib/codemirror.js \
        ++extra ../../node_modules/codemirror/addon/runmode/runmode.js \
        ++extra hilite.js \
        --dest ../../build/ \
        --dest-name docs \
        ++arg "" \
        --htmls index.scrbl
    ...
    Could not find spec for is-Equal
      context...:
        ...
    make: *** [all] Error 1

**Comment by jpolitz** [comment]
Did you run `make docs` from the root directory of the repo first?  That
builds some necessary support files.

**Comment by sorawee** [comment]
Thanks a lot!
