### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#505]
type VertexOptions = {
      color :: I.Color,
      printer :: (Any -> String)
      }

The editor somehow does not unindent `}`. The code can be run correctly, though.

**Comment by blerner** [comment]
Hrm.  This works properly in emacs ;-)  Apparently the two indenters have diverged a bit.  I'll investigate.

**Comment by blerner** [comment]
Closing here, and moving to the CPO repository -- this isn't a Pyret problem per se.
