### ISSUE TITLE
Mutually recursive type does not work

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#506]
I don't understand why

    type A = {b :: Option<B>}
    type B = {a :: Option<A>}

should be prohibited.

I asked this question before (#357), and I am fine with that one because there is a way to define mutually recursive functions (by writing `fun`s consecutively). However, for type, there is no equivalent way to do so. I think `type` statement ought to have a special treatment to allow this.

**Comment by justinpombrio** [comment]
There's a simpler program that fails to typecheck that demonstrates the
same thing:

    type A = Option<A>

Types like this are called equi-recursive
<https://en.wikipedia.org/wiki/Recursive_data_type#Equirecursive_types>,
and they greatly complicate type checking/inference, so few languages
support them. (Haskell, for instance, doesn't.) The complication arises
from the fact that if you allow this, then there's another type:

    type B = Option<Option<B>>

that's actually the same type as A, and functions that accept an A would
have to also accept a B. You can usually get by without equi-recursion by
introducing a named data type, though. In this case:

    data A:
        a(a :: Option<A>)
    end

or for your original example:

    data A:
        a(b :: Option<B>)
    end
    data B:
        b(a :: Option<A>)
    end

Justin
