### ISSUE TITLE
Documentation and CSS

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#507]
It's hard to read some documentations because of their style. For example:

```
@member-spec["f" #:type "normal" #:contract (a-arrow N N)]{
  A function to be graphed. It can yield error for some `x`
  (such as division by zero or resulting in imaginary number).
}
```

With CSS, it will display:

![screenshot 2015-05-28 17 01 56](https://cloud.githubusercontent.com/assets/9099577/7871132/f4e02cca-055b-11e5-86ef-47f00685ba19.png)

while without CSS, it is much nicer:

![screenshot 2015-05-28 17 02 06](https://cloud.githubusercontent.com/assets/9099577/7871181/45244a4a-055c-11e5-8295-0e9b98455195.png)

The current image documentation shows description of arguments inline. This is confusing. Using `@member-spec` would make it nicer.

![screenshot 2015-05-28 17 03 01](https://cloud.githubusercontent.com/assets/9099577/7871241/a194b198-055c-11e5-8093-2dfd2832d335.png)

**Comment by jpolitz** [comment]
I don't understand what needs to be fixed in the first case.  I can think of a few things, like maybe there should be some vertical space between the signature and the prose, but that's not fixed by the "no CSS" version.  Do you have a particular layout in mind?

The second point is pretty good, that's not a particularly pretty layout.

**Comment by sorawee** [comment]
For the first one, maybe the prose should be indented one more level? Some vertical space will help, too.

**Comment by justinpombrio** [comment]
Just as another data point, I like the css version better. The prose
indentation on the other version makes it look like it's part of the
function signature.

Of course, both are fine: just want to point out that this is (apparently)
subjective.

Justin

**Comment by blerner** [comment]
I think this is moot now; our docs don't look like either of these screenshots any more.
