### ISSUE TITLE
check block example code has syntax error

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#510]
The sample code [presenting `check` blocks](http://www.pyret.org/#examples) has a syntax error. The code:
```pyret
check:
  fun get-status(url):
    request({
        url: url,
        type: "get",
        params: [list: ]
      }).status-code
  end
  get-status("http://google.com/") is 200
  get-status("http://healthcare.gov/") is 500
end
```
The error message:
```
Pyret didn't understand your program around definitions: line 5, column 8
```

The problem seems to be that `type` is a language keyword. This is either:
 - A documentation bug—The example should be changed.
 - A compiler bug—the error message should probably be more specific that the keyword `type` is disallowed in this context.
 - A compiler bug—the compiler should allow `type` to be used as an identifier in certain contexts.

**Comment by jpolitz** [comment]
Thanks!  Fixed at https://github.com/brownplt/pyret.org/commit/5cf59206e37394b5a72f3619cc2f4092ec0f2e7d#diff-e30bd86837208e2baabdcae0d55568afL337.

Had to use `verb` because `method` is also a keyword.
