### ISSUE TITLE
Cannot run programs on pyret-horizon

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#511]
Here's the error: 

    Field locator not found in the lookup expression at src/arr/compiler/compile-lib.arr: line 167, column 30
    
    The object was:
    
    {needs-compile<method>get-module<method>get-extra-imports<method>get-dependencies<method>get-provides<method>get-globals<method>get-namespace<method>uri<method>name<method>set-compiled<method>get-compiled<method>_equals<method>}
    (More...)

**Comment by sorawee** [comment]
I just saw 9c70de9e2553. Is it a fix for this?

**Comment by jpolitz** [comment]
Yeah I pushed a little too eagerly, this should be all set now.
