### ISSUE TITLE
check: should be changed to examples:

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#516]
Or at least have examples: be an option for writing test cases. I spoke to Shriram about this a while ago, so I think it's in the works. Wanted to make sure I opened an issue to put it on your radar.

**Comment by jpolitz** [comment]
Thanks!  There were some outstanding questions about it we'd use it for both `where:` and `check:` so both of these would work:

```
fun f():
  ...
examples:
  ...
end
```

and

```
fun f():
  ...
end
examples:
  ...
end
```

There are a few niggling points here, that I think @shriram and @blerner should chime in on:

- We'd have to restrict `examples` to the toplevel to avoid ambiguity with inner functions (IMO that's not a problem, and certainly not an issue for Bootstrap 2).
- We need to decide on the aesthetics/conceptual overloading of the above two concepts.

We just need a decision on details and it's easy to add.  It looks like the BS2 notes mostly use check, right, so the latter option is what the notes would look like (with `end` before `examples`)?

**Comment by Emmay** [comment]
BS:2 started using check, but I switched all the notes to use examples after discussing it with Shriram. We also write examples first, so each function is written:

```
# Contract
examples:
      .......
end

fun f():
    ......
end
```

**Comment by blerner** [comment]
Is this fixed by https://github.com/brownplt/pyret-lang/commit/28752f365671fd9dd6dd312d352de4100fffdfe9 and https://github.com/brownplt/pyret-lang/commit/3e31535eca31d277e65d589ebc784a322ab7d5e2?

**Comment by jpolitz** [comment]
Yeah some of these I'm waiting to close until they are on CPO proper (open issues by Emmay is an important category) so I won't close just yet.

**Comment by blerner** [comment]
That's fine - they should just have the horizon-fixed tag then...
