### ISSUE TITLE
Allowed modules should be filtered by CPO, not pyret-lang

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#519]
The repl-support library has a whilelist of allowed built-in modules.  This should be part of the "find" function in CPO, and removed from something the repl library is responsible for.

**Comment by blerner** [comment]
Was this fixed by f3b22ba602f72a579d34e8420a0b78317cc6a7cb and by https://github.com/brownplt/code.pyret.org/commit/daa66363d873885cce327672f7538bafa2de887b?
