### ISSUE TITLE
make fails when compiling files in compiler/locators

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#520]
> make standalone1 # Note: I just merge pyret/horizon to my branch
    ...
    node -max-old-space-size=8192 build/phase0/main-wrapper.js --compile-module-js src/arr/compiler/type-structs.arr > build/phase1/arr/compiler/type-structs.arr.js
    node -max-old-space-size=8192 build/phase0/main-wrapper.js --compile-module-js src/arr/compiler/well-formed.arr > build/phase1/arr/compiler/well-formed.arr.js
    node -max-old-space-size=8192 build/phase0/main-wrapper.js --compile-module-js src/arr/compiler/locators/builtin.arr > build/phase1/arr/compiler/locators/builtin.arr.js
    /bin/sh: build/phase1/arr/compiler/locators/builtin.arr.js: No such file or directory

After `mkdir -p build/phase1/arr/compiler/locators` manually, the build can continue to run normally

**Comment by jpolitz** [comment]
Yeah this works after a make clean, but the build directory creation isn't
clever enough if you have an old version and pull a locators version :-/
Need to look into the recursive directory creation code in tbe Makefile.

**Comment by sorawee** [comment]
Yeah, I also have a similar problem when I build something (say `/src/js/trove/a.js` => `/build/phase1/trove/a.js`). After that, I remove `a.js` under `/src`. I would expect that after I run `make` then `a.js` under `/build` will be removed, but it is not. This makes subsequent build of standalone try to build `a.js` and could make the whole build failed too.

Anyway, I will close this. Seems that this is `make`'s problem and it couldn't be solved by our side.
