### ISSUE TITLE
Consider making functions be aware of their own names

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#526]
It's becoming less and less informative to print "<function>" as the sum total of the information available about functions, especially in the REPL or CLI output.  Since the printer for REPL and CLI output is now distinct from that used for `tostring` and `torepr`, we can consider adding some reflective information (like names and definition-location) to `PFunction` objects.  We could also consider making data constructors know that they're different than just simple lambdas, and print as `<constructor:link>` or some such.  (I'm less keen on this last point, since it means that modules that export "smart" constructors will print differently and leak module implementation details.  But it's technically feasible, and worth considering briefly.)

**Comment by jpolitz** [comment]
As long as they leak module implementation details only at the REPL (and not to the program), I think the constructor printing is potentially a great idea.

Mainly it's a pedagogy question of when vocabulary that distinguishes functions and constructors is appropriate.  But I'm all for adding information to these.

**Comment by schanzer** [comment]
Wasn't this implemented recently? It works great for me...
