### ISSUE TITLE
Image library still relies on jsnums.isExactInteger, which doesn't exist

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#527]

**Comment by dyoo** [comment]
Did analysis in https://github.com/brownplt/pyret-lang/issues/535.

Appears to a copy-and-paste issue: there are multiple definitions of blocks of functions, where the first copy appears to be ok, and the second copy appears to refer to things like jsnums.isExactInteger.

**Comment by blerner** [comment]
This seems to no longer be true.
