### ISSUE TITLE
string-equal is not defined

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#528]
When I open this program from my CPO-shared folder on GDrive, it works fine. When I open it from this link, I get an error saying the string-equal function is used, but not defined. (Chrome and Safari)

https://code.pyret.org/editor#share=0B9rKDmABYlJVeFBBU2tHc0hDTlk&v=v0.5r852

**Comment by blerner** [comment]
It fails for me too on Firefox on Windows...but it passes just fine if I get rid of the `&v=v0.5r852` parameter, which leads me to suspect that you're using an older, buggier release of Pyret.  When you open the program from the CPO-shared folder, do you get this same version URL parameter?  If not, then somehow this URL is outdated; try re-sharing the program and getting one with the current version.  @jpolitz can chime in with more details about how the version parameters currently work, but that's my guess.

**Comment by Emmay** [comment]
Thanks Ben! You're right, the URL from Gdrive doesn't contain the v0.5r852 parameter. I shared again and the new link works fine. Thanks for your quick response!
