### ISSUE TITLE
s-contract does nothing

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#529]
You can write down a type annotation on its own line, which so far as I can tell does nothing:

```
foo :: Number
foo = "three" # no error
```

This is called s-contract in the grammar, and seems to be dropped by `resolve-scope.arr`.

**Comment by jpolitz** [comment]
For now it's a fancy comment (not totally useless given design-recipe kinds of things).  The plan is to weave the annotations in and have rules for having to match a toplevel function, etc.

**Comment by blerner** [comment]
This is now fixed :)
