### ISSUE TITLE
Parse error on `datatype`

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#530]
Is `datatype` supposed to mean something in Pyret, or is just a leftover variant of `data`?

    datatype F: end
    # error: Field s-datatype not found in the lookup expression at <builtin runtime>

**Comment by jpolitz** [comment]
It used to be a fully-desugared form of data with a concrete syntax.  Now it's subsumed by `data-expr` and only used internally.  Thanks for finding that; it's a tokenize/parse step that shouldn't be there anymore.  More negative tests needed!
