### ISSUE TITLE
Paused in debugger prevents showing error immediately

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#533]
<img width="1185" alt="screenshot 2015-07-03 10 50 02" src="https://cloud.githubusercontent.com/assets/9099577/8503247/777fc60a-2171-11e5-98db-6ec546faa1e2.png">

Seems that `debugger;` in `checkType` causes this. Shouldn't it be removed because from students' point of view, they should see the error message, not the debugger?

**Comment by sorawee** [comment]
Oh, nvm, it only actives in "Inspect Element" mode

**Comment by jpolitz** [comment]
We could remove it or comment it out, all the same, seems like leftover
debugging code.
