### ISSUE TITLE
Derivative example on front page reports compile-time error

### ISSUE THREAD

**Issue by dyoo** [brownplt/pyret-lang#536]
The front-page derivative program:

    https://code.pyret.org/editor#share=0B32bNEogmncOWU9OWW5MSFlHSDQ

reports the following error:

    The name within is already defined. You need to pick a different name for within at definitions: line 7, column 2

**Comment by jpolitz** [comment]
Thanks!  We added `within` as a primitive to do, uh, exactly what this within does.  I think I'll rename it to "around" in the example.
