### ISSUE TITLE
checkPositiveInteger in image.js is wrong, number annotations are not exported

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#537]
1) checkPositiveInteger in image.js is wrong. `jsnums.greaterThanOrEqual(val, 0)` should be changed to `jsnums.greaterThan(val, 0)` (https://github.com/brownplt/pyret-lang/blob/master/src/js/trove/image.js#L172)

2) most number annotations (listed in http://www.pyret.org/docs/latest/numbers.html) are not exported:

```
> a :: Exactnum = 1
The name Exactnum is used as a type but not defined as one, at ...
```

I see a lot of check functions (e.g., `var checkExactnum = makeCheckType(jsnums.isRational, "Exactnum");`) in runtime-anf.js, but these are not used at all.

**Comment by jpolitz** [comment]
The second part of this is fixed.

**Comment by blerner** [comment]
`checkPositiveInteger` still has not been fixed.  The only place it's used is in `text`, to ensure the font size is (currently) non-negative.  Do we want to allow zero font-size?  What about `12.5` as a valid size?

**Comment by schanzer** [comment]
I'm happy with positive integers only. Close?

**Comment by blerner** [comment]
No, the bug is still present in the code.

**Comment by blerner** [comment]
Amazingly, this is *still* present in the new image library...but then nothing in the new image library actually uses this annotation!  I'm deleting it, and then we can close this issue.
