### ISSUE TITLE
Links to programs sometimes open blank editors

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#538]
I'm creating bit.ly links to easily share code:
http://bit.ly/1M4ZXti
bit.ly/1S0LhNv

About half the time when I copy/paste these links into Safari or Firefox, they open an editor with the right name, but the default print statement in the definitions area. The links usually work fine in Chrome, but this also happens sometimes when opening files directly from Google Drive.

**Comment by jpolitz** [comment]
Should be fixed now, though "Ahoy world!" won't show up in empty files until I figure out how to resolve this better.

There was a race between Pyret loading and the Google Drive connection happening.  I've heard of this happening before, but it happened very rarely and I couldn't easily reproduce it.  I'm not sure what changed, but now it's easy to see what was going on.

**Comment by schanzer** [comment]
@jpolitz @Emmay - closeable?

**Comment by Emmay** [comment]
I haven't had this issue in a while, so fine by me.
