### ISSUE TITLE
Support for animated gifs?

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#539]
I've tried using animated gifs in programs in Chrome and Safari. In Chrome, the gif doesn't animate at all, and in Safari it only animates when a key is pressed to move the character. Is there planned support for animated gifs in CPO?

**Comment by schanzer** [comment]
Does the equivalent stuff work in WeScheme? AFAIK, CPO uses the same animated gif hack I wrote for WeScheme, which is already pretty inconsistent across browsers.

**Comment by schanzer** [comment]
@Emmay , have you found animated gifs that work in WeScheme, but not in CPO?

**Comment by schanzer** [comment]
CPO and WeScheme have almost the same image library (even moreso now than they used to!), so I expect animated gifs to work equally well/poorly on both. I'm closing this.

**Comment by blerner** [comment]
Can you confirm that they work at all on CPO?  Might be other interactions outside the image library that confound the issue.
