### ISSUE TITLE
Unable to save programs

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#542]
A lot of students are having this issue, all in Chrome: When trying to save a program after working for a bit they get "Unable to save". refreshing Google Drive to ensure they're still logged in doesn't work, but opening a blank editor and copying all their code into a new tab DOES work, and lets them save their new code.

**Comment by jpolitz** [comment]
Thanks, I'll see if I can figure out what's up.

Question -- do you think it's likely that they are starting from both (1) not logged in and (2) a share link?

**Comment by Emmay** [comment]
Most of them are starting from shared files, but I think all of them were logged in at the time.

**Comment by schanzer** [comment]
@Emmay @jpolitz closeable?

**Comment by Emmay** [comment]
Haven't had or heard of this issue coming up in a while, Happy to close this if @jpolitz is.

**Comment by schanzer** [comment]
We'd be hearing from a lot more users if this 5-year-old issue was still happening. Closing.
