### ISSUE TITLE
second include results in too many errors

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#544]
```
> include world
> include world
```

Basically it tries to import everything and reports `The name ... is already defined. You need to pick a different name` separately, and this could be very very long. In my opinion, the check should be done with the module first so that users get a nice error message.

**Comment by Emmay** [comment]
This is still an issue, and can confirm it's very disconcerting to get that many error messages at once. Are we any closer to being able to check against the module name first, to just get one error?

**Comment by sorawee** [comment]
Duplicate of #872. Closing.
