### ISSUE TITLE
import statement breaks types in the REPL

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#545]
On horizon (haven't tried on CPO)

    > import world as W # or other modules
    > a :: Number = 5
    The name Number is used as a type but not defined as one, at
    >

But if I refresh (simply clicking "Run" to reload REPL doesn't work) and do it again

    > a :: Number = 5
    > a
    5

**Comment by jpolitz** [comment]
Thanks.  The namespace management and typechecker are having a huge fight.  That's about as precise an explanation I can give at the moment.  But this will get fixed, thanks for the test!

**Comment by mkolosick** [comment]
I've fixed this on horizon. There was a bug with namespaces in the REPL.

**Comment by sorawee** [comment]
This was only an issue for horizon. CPO doesn't have type checker, so it doesn't get affect.
