### ISSUE TITLE
'=' funtion

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#548]
Is there a reason = doesn't work as a function for comparing 2 numbers? Is it because it's already used to define values? num-equal seems to do the same job, but this was confusing to me and a few kids yesterday.

**Comment by blerner** [comment]
Correct.  You can use the `==` operator to compare values.  Pyret made a conscious choice to use three separate operators for defining new bindings (`a = 5`), assigning to variables (`x := x + 1`) and comparisons (`y == z`).  Also be careful of terminology: `==` is an *operator*, not a function -- you can't write `==(3, 3)`, any more than you can write `+(3, 4)`.

**Comment by jpolitz** [comment]
Closing as explained.
