### ISSUE TITLE
Weird error with distance function

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#549]
Some students have run into this: the second example for the distance function fails, though I don't see any reason it should. 

An offending file: https://code.pyret.org/editor#share=0B9rKDmABYlJVYUowWjRheElUeTQ&v=v0.5r1418

Error:
Got unexpected exception
Attempted to compare the following two incomparable values:
~80.77747210701756~80.77747210701756
Roughnums

**Comment by jpolitz** [comment]
We should fix that error rendering so there's a newline between the numbers, and it actually gives feedback about using within (and probably the URLs below).  But the answer is at:

http://www.pyret.org/docs/latest/equality.html#%28part._s~3aroughnum-equality%29

and

http://www.pyret.org/docs/latest/equality.html#%28part._s~3abounded-equalities%29

**Comment by jpolitz** [comment]
Fixed by 50d013a346806bfe29d48335bf9629c06d642225
