### ISSUE TITLE
bug in rendering bug!

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#552]
```
# Illustrates how pairs of things can have an indistinguishable differences,
# but lots of those little differences can add up to a big difference.
# Meant to illustrate gradualism.

# The value below the circle is the RGB value of that circle.

# Left arrow moves redward, right arrow moves greenward.

# Change `change` to different values. 
# Small values = small change (e.g., at 1, the change is invisible),
# large values = large change (e.g., at 50, the change is clearly evident).

import image-structs as I
include image
include world

change = 50
radius = 250
type World = {l :: I.Color, r :: I.Color}
separator = square(radius, "solid", "white")

fun color-delta(c :: I.Color, delta :: Number) -> I.Color:
  new-c = I.color(c.red - delta, c.green + delta, c.blue, c.alpha)
  if (new-c.red < 0) or (new-c.red > 255) or (new-c.green < 0) or (new-c.green > 255):
    c
  else:
    new-c
  end
end

fun key-handler(w :: World, k :: String) -> World:
  ask:
    | k == "left" then: {l: color-delta(w.l, 0 - change), r: w.l}
    | k == "right" then: {l: w.r, r: color-delta(w.r, 0 + change)}
    | otherwise: w
  end
end

fun rgb-as-text(c :: I.Color) -> Image:
  text(num-tostring(c.red) + "," + num-tostring(c.green) + "," + num-tostring(c.blue),
    20,
    "black")
end

fun drawer(w :: World) -> Image:
  beside(
    above(circle(radius, "solid", w.l), rgb-as-text(w.l)),
    beside(separator,
      above(circle(radius, "solid", w.r), rgb-as-text(w.r))))
end

init = block:
  c = I.color(255, 0, 0, 0)
  {l: c, r: color-delta(c, 0 + change)}
end

big-bang(init, 
  [list:
    on-key(key-handler),
    to-draw(drawer)])
```

Type-checking this on horizon results in

```
An error occurred rendering the reason for this error; details logged to the console
```

Hopefully someone got this!

**Comment by blerner** [comment]
Grumblegrumble -- @jpolitz, looks like `unbound-type-id` errors aren't always thrown for `a-name` or `a-type-id` annotations, but apparently can be thrown on `a-dot` annotations.  I think I got misled by the name ("type id").  And fixing this is a bit trickier: annotations only have a `tosource` method, not a `toname` method, and the `tosourcestring` methods on `Name`s aren't identical to their `tosource` methods.  Which of a few ways do you think we should fix this?

**Comment by jpolitz** [comment]
I think we should fix the type-checker to not throw this error; it's sort of a silly way to report it.

It is probably also worth changing unbound-type-id to just take a name, rather than a whole annotation, so we can't make this mistake again.  We can have two variants, unbound-type-id and unbound-type-name, if we want to distinguish between the two varieties (though the current rendering doesn't).

**Comment by blerner** [comment]
The underlying issue (of badly named stringifying methods on Names) still remains, and we ought to clean that up at some point, too/though.

**Comment by schanzer** [comment]
While I make no judgements about the quality of the error displayed, the issue (bug in rendering bug) is now fixed. Will leave this open in case more discussion of the error is needed.

**Comment by schanzer** [comment]
Can we close or rename this issue? There is now no bug in the rendering bug.

**Comment by schanzer** [comment]
pinging @blerner and @jpolitz

**Comment by jpolitz** [comment]
Closing is the right thing here.
