### ISSUE TITLE
Multiline comment makes indentation incorrect

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#553]
```
fun test():
  cases (Something) something:
    | abc
      #|
      |#
  end
  end
```

**Comment by blerner** [comment]
This is a subtle one!  I think I've fixed it (@jpolitz, the fix is in the CodeMirror repo, not CPO -- how can I refresh pyret-horizon accordingly?), but keep any eye out for any regressions that may result.  Apparently, an invariant I thought to be true about CodeMirror simply wasn't...
