### ISSUE TITLE
'make docs' execution errors

### ISSUE THREAD

**Issue by awstlaur** [brownplt/pyret-lang#556]
I've already run make install, make phase1, and make test with no problems. Tried make docs (from the repo root). Here's the output:

```
node -max-old-space-size=8192 build/phase1/main-wrapper.js -no-check-mode docs/create-arr-generated-docs.arr src/arr/compiler/anf.arr docs/generated/arr/compiler/anf.arr.js.rkt
Field `parse-dialect` not found in the lookup expression at docs/create-arr-generated-docs.arr: line 165, column 17
The object was:
{surface-parse: <function>}
Stack trace:
  docs/create-arr-generated-docs.arr: line 165, column 17
  docs/create-arr-generated-docs.arr: line 163, column 6
  docs/create-arr-generated-docs.arr: line 158, column 2
There were execution errors
make: *** [docs/generated/arr/compiler/anf.arr.js.rkt] Error 1
```

**Comment by sorawee** [comment]
I used to have this problem. Can't remember exactly what I did to solve it:
either make clean or clone a fresh repo.

**Comment by awstlaur** [comment]
Hrm, that didn't seem to work for me. Same error.

**Comment by sorawee** [comment]
https://github.com/brownplt/pyret-lang/commit/f2798ef6c98458a8a584a3653b711c254f3a8abb (on the horizon branch) should fix it?

**Comment by jpolitz** [comment]
Just an update on this:  I fixed this on horizon and pushed, but the problems on master are slightly deeper than this.  @blerner, I think something that changed with modules affected how create-arr-doc-skeleton.arr detects `is-` methods for datatypes; probably something in resolve-scope doesn't bind things the way it expects.  This means that a bunch of docs that rely on auto-generated `is-empty` (and `is-Equal`, and so on) type signatures don't work.

**Comment by jpolitz** [comment]
(The `surface-parse` vs `parse-dialect` thing was a problem as well, but just one of a few.)

**Comment by jpolitz** [comment]
This is all fixed by a recent push to not rely on the auto-generation script (https://github.com/brownplt/pyret-lang/commit/9755e979f063aee8fc9bd4be42a0923651ee41a2)
