### ISSUE TITLE
No response when clicking "Save"

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#561]
When I click "Save", there is no box or text appearing to confirm that the save is successful or not. This could mislead people. In the worst case, if they understand that the saving is successful while it is not, they could lose their code. This happens sporadically.

**Comment by jpolitz** [comment]
Weird – I had seen this report in Safari once or twice, but now I see it on latest Chromium as well.  @elibwhite, do you have any thoughts on odd things with the z-index of the notifications that might be affecting this?

**Comment by elibwhite** [comment]
Could be z-index, or it could be a positioning thing. Can't duplicate in Canary or Chromium on Windows.

**Comment by sorawee** [comment]
Actually, I can reproduce this consistently on some files when using my laptop. I tested this on other computers and it seems to work fine... I don't know why.
