### ISSUE TITLE
list's index doesn't work as expected

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#566]
I always thought that `index` is a function to find the index of a given element. I found today that it's not true in Pyret, and `index` is just an alias of `get` (find an element given an index). Do you think that this is a right decision? Python (`index`), Java (`indexOf`), and Haskell (`elemIndex`, `findIndex`) also use the function named "index"-ish to find an index. Note that it also doesn't make sense to provide both `get` and `index` if they have the same functionality.

**Comment by blerner** [comment]
This was added, it seems, in d283d4b55efef0fcc256fd4c1f069e219ea1d995, and I don't know why.  Really, `index`, `get-help` and `set-help` should never have been exposed in the first place... I think Joe added them because of the `provide *` at the top, which was itself an over-simplification.

**Comment by blerner** [comment]
`index` is long since gone.
