### ISSUE TITLE
Need stack trace when tests result in error

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#567]
Right now it reports errors as string. It is kind of annoying that we have to copy them to the REPL to evaluate again to see the strack trace.

P.S. And I also see `test (1 is 2): failed, reason:`. Probably `test ()` should be removed as it is confusing.

**Comment by jswrenn** [comment]
Another use case: If you abstract a common testing pattern in a check block with a function that contains a testing expression, any tests you write that fail will list their failure point as the helper function, and there's no way to readily trace back to the line that called the helper function.

**Comment by sorawee** [comment]
Agreed.

**Comment by blerner** [comment]
@jswrenn is this thoroughly obsolete, now?

**Comment by jswrenn** [comment]
Completely obsolete!
