### ISSUE TITLE
Parse Errors low on detail

### ISSUE THREAD

**Issue by jwoberbeck** [brownplt/pyret-lang#57]
[pyret] Error in parsing:

Encountered parsing error near token 'data ("data") while parsing #<path:/gpfs/main/course/cs173/assignments/interp-basic/solution/interp_jwoberbe2.arr> [line=10, column=0, offset=144]

At:
/gpfs/main/course/cs173/assignments/interp-basic/solution/interp_jwoberbe2.arr:10:0

If possible, a quote of the line which causes the parse error would be welcome.

**Comment by blerner** [comment]
Parsing errors are nowhere near this bad any more.  Closing this bug; open a new one for specific parse errors that are still lousy.
