### ISSUE TITLE
link(1, link("asd", empty)) passes the type checker

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#574]
`link(1, link("asd", empty))` passes the type checker in pyret-horizon

**Comment by jpolitz** [comment]
Ugh.  So what's happening there is that there's a bit of local inference promoting this list to a `List<Any>`.  Try this program:

```
l = link(1, link("asd", empty))

fun get-first<a>(lst :: List<a>) -> a:
  cases(List<a>) lst:
    | empty => raise("no first")
    | link(f, _) => f
  end
end

check:
  get-first<Number>(l) is 1
end
```

@melloc , is this by design?  I suspect that the promotion to `Any` is included for some other case, because this should clearly be an error IMO.
