### ISSUE TITLE
Leakage of test results

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#576]
```
check:
  print(lam(): 1 is 2 end())
end
```

results in

`[list: failure-not-equal(definitions: line 2, column 15, 1 is 2, none, 1, 2)]`

**Comment by jpolitz** [comment]
Fixed by 682fd9ec2fc7da32972ed87d681bdea82bb59fe4

**Comment by blerner** [comment]
@jpolitz not that I'm complaining about this change, but hadn't you had a reason at some point why you wanted these to *not* be returning nothing?

**Comment by jpolitz** [comment]
I've thought about having them return something and be usable in expressions (maybe test-specific ones), like:

```
test elt satisfies is-specific-type then:
  elt.field1 is 5
  elt.field2 is [list: 1]
end
```

Which would make it easier to write conditional tests that don't blow up.  If `elt` came from some other computation, and might not be the right kind of variant, then the second test might cause an exception.  That's really annoying, and the pattern for getting around it is to have some kind of dependent-test combinator.

That requires some real design, and @sorawee's example is weird enough that I think we should avoid it until we know how we want something like that to work.

**Comment by blerner** [comment]
Got it.  Given that the conditional test in your example above is first-order, we might have some room to play (such that tests in a conditional context return sufficient information to run the subsequent tests, but statement-like tests evaluate to nothing).  Definitely worth brainstorming, and definitely worth avoiding the bizarreness above for now.
