### ISSUE TITLE
Get "leftResizePct is not defined" when ctrl-m

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#577]
Do we still need this feature as the window now can be resized?

**Comment by jpolitz** [comment]
Where do you see this?  I don't get it at all.

Ctrl-m is still useful, because it jumps between the current manual sizing and an even split – it's nice to be able to get back to an even split easily, which is the main thing I use it for.

**Comment by elibwhite** [comment]
It's in the console. If you use ctrl-m before you've resizing, leftResizePct (and presumably rightResizePct) are undefined. It doesn't break anything, but it'd probably make sense to initialize both to 50.

**Comment by jpolitz** [comment]
Oh, this should certainly be fixed then – if those callbacks are ever modified with other state changes, then things will break in really bizarre ways.  This should be considered a bug for sure.  Thanks for clarifying, @elibwhite.

**Comment by sorawee** [comment]
Oh, and if now `ctrl`-`m` is not used to "Toggle maximization of the editor window" anymore, the help message (from `ctrl`-`?`) should be updated as well.

**Comment by jpolitz** [comment]
Closed by https://github.com/brownplt/code.pyret.org/commit/0d1906cf10acaa2baf5cb1acdad8c12772c5ef82
