### ISSUE TITLE
Non-existing type in a module doesn't cause an error

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#578]
```
import something as M
a :: List<M.Foo> = link(1, empty) # where Foo doesn't exists
```

runs fine. I expect it to cause an error just like `a :: Foo = link(1, empty)` which causes "The name Foo is used as a type but not defined as one"

**Comment by jpolitz** [comment]
This is example is fixed by 9a6ca6a2984ab6b95b5e97829c39b50d1258ee53
