### ISSUE TITLE
Built-in types unbound on re-run in CPO Horizon

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#586]
Steps to reproduce:
- Open [Pyret Horizon Editor](https://pyret-horizon.herokuapp.com/editor).
- Click 'Run'
- Execute `a :: Number = 1` on the REPL

Yields the error `The name Number is used as a type but not defined as one...`

**Comment by sorawee** [comment]
Related: https://github.com/brownplt/pyret-lang/issues/545

**Comment by mkolosick** [comment]
I've fixed this on horizon. There was a bug with namespaces.
