### ISSUE TITLE
Number annotations (other than Number) cannot be used as annotations.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#587]
Input:
```pyret
a :: Roughnum = ~5
```
Error:
```
The name Roughnum is used as a type but not defined as one
```

**Comment by sorawee** [comment]
related: https://github.com/brownplt/pyret-lang/issues/537

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/pyret-lang/commit/ecc64e616de6084da2368f7d847381d05cf7922e.  @ds26gte , did I accidentally remove these at some point during a merge, or were they never provided?  Was scratching my head a little at this last night.

**Comment by ds26gte** [comment]
No, you didn't remove anything I'm sure. I had just added the primitive-annotation definitions in `runtime-anf.js`, but your additions to `compile-structs.arr` are new.
