### ISSUE TITLE
Stack management fails on shallow, but long-lasting, recursion

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#596]
This program runs out of memory without ever yielding control to the Stop button:

```
fun take<T>(n :: Number, s :: List<T>) -> List<T>:
  if n == 0:
    empty
  else:
    link(s.first, take(n - 1, s.rest.first()))
  end
end
fun lz-map2<A, B>(f :: (A, A -> B),
    s1 :: List<A>, s2 :: List<A>)
  -> List<B>:
  link(f(s1.first, s2.first),
    [list: lam(): lz-map2(f, s1.rest.first(), s2.rest.first()) end])
end

rec fibs =
  link(1, [list: lam():
        link(2, [list: lam():
          lz-map2((_ + _), fibs, fibs.rest.first()) end]) end])

take(50, fibs)
```

This is because instead of a stack like

```
lz-map2
lz-map2
lz-map2
...
<exponentially many>
...
<notice stack depth and bounce>
```

It was doing, repeatedly

```
lz-map2
.rest.first()
lz-map2
<only 20-30 frames deep>
```

Then creating a new closure that will create N+1 frames, unrolling nearly to the top, and calling the new closure (rinse and repeat).  So this would take a long time to blow the stack, and it's just working really hard on an exponential computation in the meantime.

We should detect this scenario with a different kind of counter that looks for total # of function calls, rather than stack depth, in order to insert a bounce.

**Comment by blerner** [comment]
This is still a problem, even with RUNGAS.  What's going on here?

**Comment by jpolitz** [comment]
Not sure in what merge, but the `||` with `RUNGAS` was lost in normal checks, and only included in tail calls.  f8b81a1 should fix it.

**Comment by blerner** [comment]
This seems to be fixed now.
