### ISSUE TITLE
indenter thrown off?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#599]
```
check:
  rec tr = nd("rec", lam(): tr end, lam(): tr end)
  t0 = nd(0, lam(): mt end, lam(): mt end)
  t1 = nd(1, lam(): t0 end, lam(): t0 end)
  t2 = nd(2, lam(): t1 end, lam(): t1 end)
  t3 = nd("top", lam(): nd("ll", lam(): mt end, lam(): t4 end))
    
    
  size(tr) is 1
  size(t0) is 1
  size(t1) is 2
  size(t2) is 3
end
```

When you tab into the line after `t3`, I believe the indentation is off.

**Comment by sorawee** [comment]
Because you forget an `end`?

**Comment by blerner** [comment]
I should point out that once @belph 's new highlighting code lands (which should be any day now), the `)` would highlight as mismatched against the `lam`, and you'd have a very quick way of seeing where the missing token is.

Meanwhile, the indenter lives to, er, indent another day :)

**Comment by jpolitz** [comment]
@belph's stuff is amazing, I'm just behind on merging it.  I pointed out a minor issue at https://github.com/jpolitz/CodeMirror/pull/2, but it seems mostly ready-to-go.

**Comment by blerner** [comment]
I think this issue should be closed as not-a-bug -- anyone disagree?

**Comment by jpolitz** [comment]
No disagreement from me.
