### ISSUE TITLE
test failure box should be easier to expand

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#601]
When a check box fails, the "click to expand" region is ONLY that text. Why not pretty much anywhere in the box, except maybe the edges in case someone wants to copy the text?

**Comment by blerner** [comment]
This is more properly a CPO issue, right?

**Comment by blerner** [comment]
Pinging @jswrenn

**Comment by jswrenn** [comment]
Duplicate of https://github.com/brownplt/pyret-lang/issues/913.
