### ISSUE TITLE
failed test highlighting disappears temporarily

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#602]
Consider a test failure like

```
test (b0!v == b1!v is false): failed, reason:

Values not equal
  true
  false
```

When you mouse over any line with text, the corresponding test highlights. But when you mouse over that blank line, it temporarily disappears. It'd be nicer if the test were associated with this entire block of output rather than just the text lines.

**Comment by blerner** [comment]
This is more properly a CPO issue, right?

**Comment by blerner** [comment]
Also, pinging @jswrenn since this will be a test-output-rendering issue.

**Comment by schanzer** [comment]
@shriram given how much has changed in our error output, and that this issue is almost half a decade old...is this still an issue?

**Comment by shriram** [comment]
What's relevant isn't the age or how much has changed, but rather that the issue has been addressed directly.
