### ISSUE TITLE
Prevent unused type variables and prevent using type variables as identifiers

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#603]
Parametric polymorphism should prevent unused type variables. The following should result in an (perhaps wellformness?) error.

```
fun len<A>(lst :: List<Any>) -> Number:
   ...
end
```

Also, it should prevent using type variables as identifiers.

```
fun my-link<A>(A :: A, lst :: List<A>) -> List<A>:
  link(A, lst)
end
```

This issue might be able to be fixed along with #442.

**Comment by blerner** [comment]
I'm not sure I agree with either part of this, actually.  Certainly for data types, there are perfectly valid (though advanced) uses of phantom type variables; such a type is not malformed.  And we affirmatively spent a decent amount of effort to ensure that a declaration like A :: A would work properly, that is, that the two A names were not conflated.  One could argue that this isn't good style, certainly...but it is semantically valid.

Regardless of whether we keep this, it seems utterly unrelated to #442, though.

**Comment by jpolitz** [comment]
Holy crap I think I just understood phantom type variables.

I do think the type name/variable name overlap is an issue we should consider, especially since we already worry about `shadow`.

**Comment by mkolosick** [comment]
I agree with @blerner and think that this is acceptable behavior.
