### ISSUE TITLE
empty hash-comment causes next line to be skipped

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#604]
Running this program
```
fun f(x):
  x + 10
where:
  f(10) is 20#foo
  f(20) is 30
end
```
says both tests passed, but changing the `#foo` to `#`, so the line reads
```
  f(10) is 20#
```
says only one test passed (the second test, in this case the one producing 30, is the one skipped).

The problem is not specific to tests. If I change the body of the function to
```
  x + 10#
```
I get an error saying I can't use `is` outside a `check` or `where` block.

Credit to Felix Merk for finding this problem.

**Comment by sorawee** [comment]
RegExp! In https://github.com/brownplt/pyret-lang/blob/master/src/js/base/pyret-tokenizer.js#L123

    "^(#([^|].*)?(?:\\n|\\r|\\r\\n|\\n\\r|$))"

could be changed to a negative lookahead. Something like:

    "^(#((?!\|).*)?(?:\\n|\\r|\\r\\n|\\n\\r|$))"

**Comment by blerner** [comment]
Well, it'd need to be `"(?!\\|)"` -- because RegExp + Javascript. But yes, this was a regexp mistake.

**Comment by blerner** [comment]
@jpolitz This looks good; merge and close?
