### ISSUE TITLE
can't view imported object?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#610]
```
import ast as A
```

In the REPL:
```
> A
<error displaying value: details logged to console>
```

**Comment by blerner** [comment]
Seems to be an issue with the JS: it errors with "CodeMirror.runMode is not a function".  I haven't touched that code in a while, but I think someone recently was working on stuff related to CodeMirror.runMode.  Any takers?

**Comment by jpolitz** [comment]
That's not the error; the error is a field-not-found on a `vs-str` for field `name`, it looks like.  That `runMode` thing is different, @sorawee was tracking it down, and it's just a spurious warning.

**Comment by blerner** [comment]
I just checked on horizon: the field-not-found thing is fixed there (looks like output-ui is out of date on CPO).  But then the CodeMirror.runMode thing is still a problem on horizon.

**Comment by sorawee** [comment]
@belph fixes .runMode issue in https://github.com/brownplt/code.pyret.org/pull/45

**Comment by sorawee** [comment]
Oh, but his fix is on horizon, not master, tho.

**Comment by jpolitz** [comment]
That's fine; I need to do some merging anyway, and the PR is open.  I'll get to it.

**Comment by blerner** [comment]
@jpolitz close this as horizon-fixed?
