### ISSUE TITLE
Debugger statement pauses Chrome.

### ISSUE THREAD

**Issue by awstlaur** [brownplt/pyret-lang#614]
https://github.com/brownplt/pyret-lang/blob/horizon/src/js/base/runtime-anf.js#L1072

When loading the pyret-horizon CPO (https://pyret-horizon.herokuapp.com/editor), the line in question gets hit and pauses everything. If it's not there on purpose, we should get rid of it. If it is there on purpose: why?

**Comment by sorawee** [comment]
It won't pause if you don't open the developer console.

**Comment by blerner** [comment]
Correct.  It's there, I believe, because type errors are annoying to debug and usually indicated errors in our code, rather than the users' code (for the small programs we were debugging via the dev console), and once the type error is thrown we lose the stack.

**Comment by awstlaur** [comment]
Okay sounds reasonable.
