### ISSUE TITLE
Mutating variable in interaction pane that was defined in definitions pane issues `bad-assignment` error

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#619]
## Steps to reproduce:

1) Define variable in definitions pane:
```pyret
var foo = 2
```
2) Click `Run`.
3) Mutate variable in interactions window, e.g.:
```pyret
foo := 3
```

## Expected result
`foo` is `3`
## Actual result
`bad-assignment` error is issued and a misleading error message is printed to the console, `The name x is defined as an identifier, but it is assigned as if it were a variable`

**Comment by jpolitz** [comment]
Closing as duplicate https://github.com/brownplt/pyret-lang/issues/288
