### ISSUE TITLE
Missing definition for CodeMirror.runMode causes error at runtime

### ISSUE THREAD

**Issue by dyoo** [brownplt/pyret-lang#621]
Reproduction:  in the interaction pane, type in a string constant, like "hello world", and press Enter.  The following error occurs in the JS console:

##################################
Uncaught TypeError: CodeMirror.runMode is not a function(anonymous function)
@ output-ui.js:575
##################################

This appears to be due to a missing script loading of addon/runmode/runmode.js.  See: https://codemirror.net/demo/runmode.html

**Comment by sorawee** [comment]
Fixed in horizon (https://github.com/brownplt/code.pyret.org/issues/43)

**Comment by blerner** [comment]
This is really a CPO bug (and indeed is filed there), so closing this one.
