### ISSUE TITLE
Consider enhancing the constructor protocol with small, fixed-arity constructors

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#629]
It's very sad that `[clist: 5]` requires allocating a JS array, a RawArray wrapper, a `cl-cons` object and a `cl-empty` object.  We would do better if we could say "When given only one argument, just use `cl-sing`.  When given two arguments, use `cl-cons(_, cl_sing(_))`. ..."

So the proposal is to change the constructor protocol so that instead of being an object

```
{ make : RawArray -> Whatever }
```

it's instead:

```
{
  make1 : Any -> Whatever,
  make2 : Any, Any -> Whatever,
  ...
  make5 : Any, Any, Any, Any, Any -> Whatever,
  make : RawArray -> Whatever
}
```

And the compiler would know by statically looking at the constructor syntax which arity to call.

This requires first adding the requisite new functions to every constructor definition, then fixing the compiler to use them.  It might be doable with a single bootstrap.  The only hazard is this is a breaking change: if we have students or instructors who've written their own constructors, they'll have to revise their code to add the new construction functions.

**Comment by shriram** [comment]
Given that it's early days of the language, I'm not afraid of a “breaking
change” to students and instructors: in reality I expect there are close to
zero such programs (with rounding). I say we go for it. This might also
slightly help the type-checker.

**Comment by jpolitz** [comment]
@blerner closeable?

**Comment by blerner** [comment]
Why is this still open?  Yeah, we fixed this a long time ago...
