### ISSUE TITLE
Error displaying values in the REPL

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#631]
Run the program below, then type "thing" in the REPL.

What I expect to happen: the REPL prints "thing".

What actually happens: the REPL says "\<error displaying value: details logged to console>".

    import valueskeleton as VS

    data Thing:
      | thing
    sharing:
      _output(self): VS.vs-str("thing") end
    end

**Comment by sorawee** [comment]
This is fixed in the horizon. See #610

**Comment by blerner** [comment]
Closing as dup of 610, then.
