### ISSUE TITLE
REPL doesn't work on Android tablet

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#635]
I tried to run Pyret last night on my Nexus 7 2013, running the latest Chrome on Android 6.

Pyret starts up, I can click Run, the REPL appears. I'm able to type at the REPL. However, when I hit Enter, the behavior is as if it hit Shift-Enter: I'm put on the next line, and the left bar of the entry box extends down. This continues for as many times as I hit Enter. (I also tried Shift + Enter, no difference.) As a result, I'm simply unable to evaluate any expressions. This is a real pity!

**Comment by sorawee** [comment]
Another problem with Android: if you use a customized keyboard, like SwiftKey, you will not be able to delete text (via backspace).

**Comment by shriram** [comment]
Related: when I was on a new line, I wasn't able to use backspace to undo the newline (though it did delete text on the same line).

**Comment by schanzer** [comment]
@shriram android and chrome are massively more mature now than they were 4 years ago. I don't have a modern Android device to test with, but I suspect (given that it's now _real chrome_) this is closeable. Can you confirm?

**Comment by shriram** [comment]
Running Chrome on Android, all these problems seem to be fixed!
