### ISSUE TITLE
duplicate definition error runs things together

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#640]
```
It looks like you've defined the name words twice, at
definitions: line 5, column 0definitions: line 85, column 0
You need to pick a different name for one of them.
```

Note the two source links on the same line.

I'm pretty certain I've reported this problem in the past, maybe even more than once. But it's still a bug in the current system.

**Comment by blerner** [comment]
I don't see it.  On CPO, I get
```
It looks like you've defined the name words twice, at

definitions: line 1, column 0 and

definitions: line 2, column 0.

You need to pick a different name for one of them.
```
where both locations are linkified.  And I can't reproduce this at the command line either.  Where are you running this, and what's your demo code?

**Comment by jpolitz** [comment]
@blerner try

```
fun words(): 1 end
fun words(): 2 end
```

**Comment by blerner** [comment]
?!?  How is that producing a different error from
```
words = 1
words = 2
```
and more importantly, why?
