### ISSUE TITLE
raw-array's repr shows JS objects

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#646]
```
> print([raw-array: 1, 2])
[raw-array: 1, 2]

[raw-array: [object Object], [object Object]]
```

**Comment by blerner** [comment]
Urk.  That's mildly bad...

**Comment by blerner** [comment]
This one's actually pretty funny.  The rendering is working terrifically...right up until the last step.  When assembling the final output, we were using the Pyret rendering of raw-arrays, which is correct, but the values being rendered were jQuery-wrapped DOM nodes, and so showed up as `[object Object]`.
