### ISSUE TITLE
"Should not get an empty block in desugar-scope-block"

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#649]
This program:

    check:
      t = 3
      t :: Number
    end

gives an internal compilation error:

    "Should not get an empty block in desugar-scope-block"
    src/arr/compiler/resolve-scope.arr: line 170, column 15

**Comment by blerner** [comment]
@sorawee 's commit is merged into `merged-horizons`, so it'll merge into new-horizons and then into horizon and then into master and then it'll be good...
