### ISSUE TITLE
_output() rendering fails in check blocks

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#650]
This program:

    import valueskeleton as VS
    
    data Foo:
      | foo()
    sharing:
      _output(self): VS.vs-str("foo") end
    end
    
    check:
      foo() is 3
    end

Fails to render `foo()` in the check block:

    Values not equal
    <error rendering embedded value; details logged to console>
    3

There doesn't seem to be a stack trace, and the logged error message is that field "name" is not found.

As a result, it seems impractical to write test cases over data that has custom printing right now.

**Comment by blerner** [comment]
Double-check this on pyret-horizon; it should be fixed already.

**Comment by sorawee** [comment]
But pyret-horizon is failing!

**Comment by blerner** [comment]
Well crud.  @jpolitz we gotta get horizon back into shape :(

**Comment by schanzer** [comment]
FYI - seems to render the check block on horizon now

**Comment by blerner** [comment]
This was fixed in https://github.com/brownplt/code.pyret.org/commit/cc1fb10b82fcd7ed7a4ae32486b34c45443d176d#diff-84d7c9dae3370794b6735318e2cc59a2L687, and I have no idea why it took so long to appear on the live horizon site.
