### ISSUE TITLE
code at the bottom of the screen

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#654]
As a lifelong Emacs user, I like to have the cursor in the middle of the screen and do most of my editing there. Even my screen height is mostly optimized for that.

Working with the CPO editor is frustrating in this light. There's no equivalent to C-l, but even more importantly, if you're editing at the bottom of a long enough file, you're stuck at the bottom of the screen: there are no “virtual lines” that let you move that back up to the middle.

For now there is a workaround of just adding lots of blank lines. But I wonder whether the editor could automatically support more flexibility.

**Comment by schanzer** [comment]
#964 is a repeat of this, but all the discussion is happening over there. Propose we close this one.
