### ISSUE TITLE
Type Mismatch Between anf.arr and ast-anf.arr

### ISSUE THREAD

**Issue by belph** [brownplt/pyret-lang#659]
[This line](https://github.com/brownplt/pyret-lang/blob/a5d99d0e9a1ace2e6f3504d62e2b913dd97949eb/src/arr/compiler/ast-anf.arr#L239) in `ast-anf.arr` says that the `args` field on `a-cases-branch` should have type `List<ABind>`, but on [this line](https://github.com/brownplt/pyret-lang/blob/a5d99d0e9a1ace2e6f3504d62e2b913dd97949eb/src/arr/compiler/anf.arr#L59) in `anf.arr`, the constructor is called with an argument of type `List<ACasesBind>`.

My personal guess is that the `List<ABind>` annotation is the incorrect one, but that's just a hunch.

**Comment by blerner** [comment]
Yup, sounds right to me.  Seems like an annoying failure mode of not dynamically checking the type parameter positions within generic annotations...
