### ISSUE TITLE
Prevent function comparison

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#662]
There are two cases that `==` will fail:

1. function / function (e.g. `lam(x: Number): x end == lam(x: Number): x end`)
2. roughnum / number (e.g. `~1 == 1`)

Would be nice if the type checker could catch these statically.

**Comment by jpolitz** [comment]
Something to keep in mind:  I think it's useful to be able to write generic filters, like:

```
fun get-equal-to<a>(l :: List<a>, other-elt :: a) -> List<a>:
  filter(lam(elt): elt == other-elt end, l)
end
```

To type-check this in isolation, we have to either:

- allow this to be called on lists of roughnums (and not catch the error statically in all cases)
- get into something like bounded polymorphism on the type class `equalable`, which is a whole design space of its own

**Comment by jpolitz** [comment]
One way to think about this concretely is to ask what the type of `equal-always` should be.  Right now it is:

`Any, Any -> Boolean`

In OCaml, it's

`forall a, a -> a -> bool`

To do the proposed, it would need to be something like:

`forall a <: Equalable: a, a -> Boolean`

If we want to allow numbers to be compared to objects, we'd need it to be

`forall a <: Equalable, b <: Equalable: a, b -> Boolean`

**Comment by jpolitz** [comment]
BTW @mkolosick, I think leaving this alone is a pretty good option; it mirrors what OCaml does, because it's also hard to statically catch things like lists of lists of tuples of functions.

As usual, it's a useful heuristic to be suspicious whenever the type system needs to get fancier than OCaml's.

**Comment by blerner** [comment]
On the other hand, SML has equality types, that coincide pretty closely with our intuition of what equality means for Pyret: http://mlton.org/PolymorphicEquality.  Base types (but not reals aka roughnums) can be compared, functions can't, data can be (structurally), references are compared by alias, all of which coincide with our notion of `equal-always`...

I wouldn't mind making it `forall a . a, a -> Boolean`, though.  It's no worse than div-by-zero not being statically caught.

**Comment by jpolitz** [comment]
Thanks for that reference. This link is also particularly helpful:

http://mlton.org/EqualityType

**Comment by blerner** [comment]
That said, the thing I recall vividly disliking when I was learning SML was "wait, why is `'a` different from `''a`, and why do I have to know the difference *right now*?"  The fact that it showed up in the signature was very confusing at first, and was Yet Another Thing to keep in my mind while I was trying to learn about and understand polymorphism in the first place.

**Comment by mkolosick** [comment]
@jpolitz My inclination is the same to just leave it as such. I don't think there's much expectation from people to prevent this sort of thing, and the error message is very reasonable.
