### ISSUE TITLE
Definitions in REPL interactions are given builtin locations.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#665]
Declaration and re-declaration in the same REPL run is fine. However, note the redefinition of `b` in a separate REPL run than its original definition and the error it produces:
![screenshot-localhost 5000 2016-03-03 14-24-44](https://cloud.githubusercontent.com/assets/3820879/13507273/ec1b7128-e14f-11e5-9812-ba08874d141c.png)

(Used screenshot from my errors branch because master/horizon use the same incorrectly use the same error message regardless of whether `shadow-id`'s `old-loc` is a builtin or not.)

**Comment by jpolitz** [comment]
Closing as dup of https://github.com/brownplt/pyret-lang/issues/190.  Working on this now.
