### ISSUE TITLE
Plot library not finishing plot?

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#669]
I haven't been able to narrow this down more, but if I try to plot a cube function, the plot library doesn't seem to finish:

```
import plot as P

fun cube(n :: Number):
  n * n * n
end

plot-window = P.plot-window-options.{
  x-min: 0,
  x-max: 2,
  y-min: 0,
  y-max: 5
}


P.plot-multi(
  [list:
    P.xy-plot(cube, P.plot-options)],
  plot-window)
```

It just spins and doesn't seem to give an answer.

If I change the body of `cube` to `n + n + n` or `n * n` it shows the plot as expected.  I'm not sure what's going on or where, but I want to make a note.

**Comment by jpolitz** [comment]
This is on current pyret-horizon.herokuapp.com

**Comment by sorawee** [comment]
This is bad. But yeah, my new plot library will use a new approach, and this kind of problem should not happen.

**Comment by sorawee** [comment]
This no longer happens. Closing.
