### ISSUE TITLE
Documentation page http://www.pyret.org/docs/latest/ points to old version of PAPL

### ISSUE THREAD

**Issue by spdegabrielle** [brownplt/pyret-lang#672]
.
Should it point to http://papl.cs.brown.edu/2016/ or http://papl.cs.brown.edu/2015/

Sorry if this is the wrong place to log

**Comment by shriram** [comment]
This is a perfectly good place to bring it up — thanks! We'll take any feedback we can through whatever channel is easiest. 

2015 is the "latest stable version", so it makes sense to point to 2015 for now. I don't know whether 2016 will get better than 2015 by summer or only late in the year, but when it is it should go in place.
