### ISSUE TITLE
bad division by zero

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#676]
```
> 1 / 0
Division by zero
> 1/0
An error occurred rendering the reason for this error; details logged to the console
```

**Comment by blerner** [comment]
That latter expression isn't a division by zero, but rather a fraction literal whose denominator is zero. That should be throwing a well-formedness error, and appears to not be throwing it correctly.

**Comment by shriram** [comment]
I think Oak knows that perfectly well. His point remains that it should produce a better error message!

**Comment by ds26gte** [comment]
I'd fixed this in my sandbox (see http://cpyret.herokuapp.com) to say

```
can't make rational with denominator zero
```

It may have been fixed in some other way in horizon too?

**Comment by blerner** [comment]
The bug was actually in the rendering of the error that described this problem, not in the jsnums code.

**Comment by ds26gte** [comment]
Gotcha. BTW, I ran into the same rendering problem for _every_ Spyret parse error when I merged the latest horizon. It appears that anything with a `make` method must henceforth also have the `make0` through `make5` methods defined. (I had introduced one such object and needed to endow it with the new methods.)

**Comment by blerner** [comment]
Different problem actually, but yes. We changed the details of constructor objects, which gave us a pretty drastic performance improvement.
