### ISSUE TITLE
resizing via menu causes cursor in REPL to lose track

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#680]
Imagine the REPL looks like:

```
> foo
```

and the cursor is at the end. Switch to a larger font using the Menu option. The cursor should still be past the "o" but if the font grows enough it ends up to the left of that point, and is not able to move to the right: basically, it gets “confused”.

[This may be a dup, but the problem persists.]

**Comment by blerner** [comment]
Far as I can tell, this is a bug in codemirror itself.  According to the API docs, when changing the font size we're supposed to call `refresh()`, which we're doing.  But we may need to call `setSize()` too.  It appears `setSize` makes the subsequent refresh signal be a "forced" one.  Dunno if that helps, but I noticed that when I tried to reproduce this bug and opened the developer console (and thereby resized the window's viewport), the bug went away.  @shriram could you confirm that behavior, too?  I.e. try (un)maximizing the window or tweaking its size, and seeing if that fixes the problem temporarily?

**Comment by shriram** [comment]
@blerner Confirmed. I tweaked the window size and the cursor repositioned itself correctly.

**Comment by schanzer** [comment]
This is now fixed. We can reopen if this bites someone else (and we'll know soon enough!).
