### ISSUE TITLE
copying objects doesn't work so well with punctuation

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#683]
```
> for map(m from range(0, 3)):
  for map(n from range(0, 3)):
    {m: m, n: n}
  end
end
```

produces, when copied-and-pasted,

```
[list: [list: {m0n0}, {m0n1}, {m0n2}], [list: {m1n0}, {m1n1}, {m1n2}], [list: {m2n0}, {m2n1}, {m2n2}]]
```

(copied from browser-tab to browser-tab in Chrome , OS X).

**Comment by blerner** [comment]
Known issue: I'm actually surprised the commas were copied!  The colons and commas are very tricky to get right, while also getting click-to-expand behavior working.  This is an annoying CSS/HTML issue and a low-ish priority papercut to fix.  Any takers?
