### ISSUE TITLE
Arity mismatch error message should give function name

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#69]
It would be helpful if arity mismatch error messages mentioned the name of the function that was called when it is available. A student was just confused because she couldn't tell what function was being misapplied (it was a hidden call introduced by cases, but she thought she had written her own function wrong).

For instance
    fun f(x): x;  f()
raises
    Expected 1 argument, but got none.
that does not mention the name 'f'.

**Comment by schanzer** [comment]
Functions now know their own names, and the new error messages at least _display_ the offending code (which includes the name). Not sure if this is "good enough" to close, or if we want to use the new functions-have-names ability to improve the error in a more substantial way

**Comment by schanzer** [comment]
Close-able? I may be one of the pickiest people about these sorts of things, and I've been happy with the current error for a while.

**Comment by shriram** [comment]
The current error message says

![image](https://cloud.githubusercontent.com/assets/75030/19190238/b1d7be38-8c9c-11e6-81a6-143509b17afb.png)

Hovering over "0 arguments" produces no highlight. It _could_ highlight the `()`…

**Comment by schanzer** [comment]
Oooh, great idea!

**Comment by blerner** [comment]
@jswrenn There's a gnarly little type error lurking in your code -- a single location, versus a list of ast nodes...I'm fixing this now.
