### ISSUE TITLE
On big-bang closes, stop button should be available if there's still computation

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#690]
Try running the following program and then click at the circle:

```
import image as I
import image-structs as II
import world as W

W.big-bang(0, [list: W.on-mouse(
      lam(_, x, y, event):
        when event == "button-down":
          time-stop = time-now() + 1000000000000
          fun loop():
            print('loop')
            if time-now() > time-stop:
              1
            else:
              loop()
            end
          end
          loop()
        end
      end), W.to-draw(lam(_): I.circle(100, "solid", II.blue) end)])
```

After I click x to close the window, the stop button greys out, despite the fact that there's some computation going on. So it's apparently impossible to stop the computation, which is bad. The stop button should still be available...

Note: it's actually possible to stop the computation by:
1. Click Run again, which will still not stop the computation, but make the Stop button available (but now the Run button will kinda grey out).
2. Click Stop, which weirdly will not stop the run, but stop the infinite loop -- I think it's because the new big bang is run in background but the interface is hidden somehow.
3. Now, both buttons grey out, but the REPL is functional now. So we can just type 1 and press enter. This will reset the Run button.

**Comment by blerner** [comment]
This sounds more to me like a known problem: #543, #508, and possibly others.  We need a bit more infrastructure in our stack-management so that we can shut these all down properly.

**Comment by sorawee** [comment]
Yup, I will close this as it's a duplicate then.
