### ISSUE TITLE
Accessing the `__proto__` field of an object should be a well-formedness error

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#691]
The following expression will crash the CPO repl:

```
{}.__proto__
```

and possibly other parts of Pyret, too.  This should be an easy fix: we need to check for `reserved-names` in the fields of the `s-dot` case of well-formedness, too.

**Comment by sorawee** [comment]
Also `valueOf`, `toString`, etc.

```
> {}.valueOf
<Unknown value: details logged to console>
```

I guess we should just read the ADsafety paper one more time...

**Comment by belph** [comment]
Really, shouldn't all fields in `Object` be disallowed (if that's easier to encode)?

**Comment by jpolitz** [comment]
This is a pretty foolish revelation for us to be having.

The prototype of all the objects we create should be `null`.  That avoids everything but the `__proto__` case.  The real question is why that isn't the case (or why it isn't the case anymore).

**Comment by blerner** [comment]
I'm kinda confused, actually.  `PBase.prototype.dict = emptyDict`, and `emptyDict = Object.create(null)`, and our field accesses should only ever be looking at the `dict` fields...  I don't know why `PBase` doesn't have a `null` `__proto__`, but I also don't know why it matters, here.

**Comment by jpolitz** [comment]
Yeah I guess we just need a helper to manage lines like this:

https://github.com/brownplt/pyret-lang/blob/master/src/arr/compiler/anf-loop-compiler.arr#L1267

It's wrong to just create object literals.  The helper could be roughly:

```
function makeNoProtoObj(obj) {
  var nullProtoObj = Object.create(null);
  Object.keys(obj).forEach(function(k) {
    nullProtoObj[k] = obj[k];
  });
  return nullProtoObj;
}
```

This would also be used by `makeObject`, constructors for datatypes, etc.

If we didn't actually _use_ prototype extension in some cases, we could just check `hasOwnProperty` in field lookup, and we also wouldn't have this issue (again, modulo `__proto__`).  But I believe there are situations where we want to actually use the prototype chain, so we should ensure that objects terminate in a `null` prototype.

Clearly, there ought to be tests for all these cases.

**Comment by blerner** [comment]
That line doesn't explain how `{}.__proto__` or `{}.valueOf` crashes though, because `{}` isn't a data value, and the `a-obj` case of anf-loop-compiler already calls `makeObject`, which creates a `PObject` with the given dict and brands.

**Comment by blerner** [comment]
OHHHHH.  This sux.  What happens is: `a-obj` gets compiled to a call to `makeObject` on a `j-obj` with the desired fields that will be used as the dictionary for the new Pyret object... instead of extending the `emptyDict`, which we specifically created for this reason.

**Comment by blerner** [comment]
Bump.  This needs to get fixed.
