### ISSUE TITLE
"checking/synthesis for s-extend not implemented"

### ISSUE THREAD

**Issue by samuela** [brownplt/pyret-lang#693]
It appears as though type checking has not been implemented for s-extend expressions. For example,

```
{}.{a: 1}
```

produces an "checking for s-extend not implemented" error. 

I believe extending the type checker to s-extend expressions should be relatively painless. At least synthesis is trivial: to synthesize a type for `A.{a: e1, b: e2, ...}` we simply synthesize a type for `A`, and then synthesize types for each `e1`, `e2`, and finally stitch everything together. Checking a type against an s-extend should simply amount to a subtype rule.

**Comment by blerner** [comment]
That makes a few assumptions that aren't necessarily true: whether we support this kind of subtyping by default in synthesis or not, whether stitching is that straightforward (what about the self parameters of methods?), whether the benefits outweigh the costs (do we expect students to typically want to add new fields to an object they've already typed?), etc.  @mkolosick should chime in here.

**Comment by mkolosick** [comment]
There are a couple reasons s-extend isn't implemented yet. One is that the story for objects isn't done, namely in terms of methods. Because of the `self` argument we need to be careful about overriding field values.

However, this should be coming soon as I've almost figured out typing for objects with methods.

**Comment by samuela** [comment]
Ah, yes. Methods do mess things up a bit.

Still, objects are just big `letrec`s so it shouldn't be too tricky. How about synthesizing as follows,
* create an existential variable â for the object,
* desugar each of the methods into lambdas, and annotate the `self` argument to each of the lambdas with type â,
* synthesize all of the fields including the methods, producing an object type A,
* apply `A <: â`
