### ISSUE TITLE
'animate' should be added to the World module

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#694]
Animate is a really excellent baby-step for students, before they move on to big-bang. I'd like to propose it be part of the World module, and I volunteer to implement it when the time comes. :)

**Comment by schanzer** [comment]
With the addition of Reactors, this is no longer a needed feature

**Comment by ds26gte** [comment]
But it's already in https://github.com/ds26gte/code.pyret.org/blob/latitude-mrg/src/web/js/trove/world.js, line 661 et seq.  Remove?

**Comment by schanzer** [comment]
It's definitely needed for Spyret, but not for Pyret. Is your implementation dependent on Pyret's `big-bang`? If so, this *might* be a problem if we ever deprecate big-bang in favor of Reactors.

**Comment by ds26gte** [comment]
Yes, both `animate` and Pyret's `big-bang` use a subroutine called `bigBang` (also in `world.js`). So if `bigBang` gets thrown out, `animate` will indeed have to be rewritten.

**Comment by schanzer** [comment]
That's unlikely to happen anytime remotely soon, and my guess is that your time at the moment is better spent on other items. :)
