### ISSUE TITLE
saving files considered harmful

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#698]
Every time I save a file, when I then click run, it takes a noticeable extra second or so (because it's saving the file again, even though nothing has changed). This is dreadfully annoying, and makes me want to not save files — I actually put them in my filesystem instead. I imagine students have noticed this and sometimes dont' save their file but _also_ don't do any backup, making them more prone to lose files outright. Can we have this save be less of an annoyance _at the very moment_ when the user most wants to see output?

**Comment by jpolitz** [comment]
I believe this is a perception problem, not an actual significant delay.

The request to save is sent, and then the program is run while the save request is still out.  The empty program often finishes before the save finishes, for example.

I wonder if simply removing the "saving..." dialog would improve this the perception, and simply popping up a "Saved" notification when it's done.

**Comment by shriram** [comment]
It's worth trying that and seeing if it changes the perception.

**Comment by Emmay** [comment]
@shriram Is this still an issue for you, or can it be closed? I haven't experienced any noticable lags when saving and running files, and I *strongly* support keeping the "Saving..." dialog. If it does take an extra second to save, I'd much rather know something is happening in the moment rather than waiting and wondering.

**Comment by shriram** [comment]
I think this can be closed, thanks. Over the past fall I paid attention to
this, and I’m willing to believe Joe that it’s a perception issue.
