### ISSUE TITLE
Horizon: tests with exceptions are run twice

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#704]
On Horizon, this test case:

```
var x = 0

fun foo(n):
  x := x + 1
  print(x)
  raise("boom")
end

check:
  foo(0) is 1
end
```

prints out "1    2", when it should just print "1".

**Comment by jswrenn** [comment]
Fixing this now.

**Comment by jswrenn** [comment]
This will be fixed on horizon on the next commit of a phase 0.

**Comment by jpolitz** [comment]
Why does if need to be s phase0?
