### ISSUE TITLE
(typechecker) Information in the error is in desugared form

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#710]
The following code:

```
lam(x :: Number): x + 2 end(lam(n): 1 end, [list: 1 * 2, 2, 3])
```

results in:

```
The type checker rejected your program because the function application expression

lam(x :: Number): _plus(x, 2) end(lam(n): 1 end, list.make3(_times(1, 2), 2, 3))

expects the applicant to evaluate to a function accepting exactly the same number of arguments as given to it in application.

However, the applicant is given 2 arguments and the type signature of the applicant

("Number" -> "Number")

indicates that it evaluates to a function accepting exactly 1 argument.
```

I think we are not supposed to see `_plus`, `.make3`, etc, right?

**Comment by jpolitz** [comment]
Good point.  That's a problem for @justinpombrio if I've ever seen one.

I also wonder if just using srcloc information and having the original AST/source around would be enough to reconstruct the original program, which I think is something @jswrenn has done before.

**Comment by justinpombrio** [comment]
The way I would expect this to work is that in an error message, you never show any part of the AST (since it has been desugared), and instead show srclocs (which by definition refer to the original program).

**Comment by jpolitz** [comment]
That sounds quite reasonable.

**Comment by blerner** [comment]
It also sounds like we have to be super-extra vigilant about preserving the best possible srclocs everywhere: even one sloppy dummy-loc, or one overly-broad location, will make that srcloc information utterly useless for error messages.  We've been pretty darned good so far, but there have been enough cases where the wrong location was used that it's worth mentioning again...
