### ISSUE TITLE
sin(n*pi), and Very Small Values

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#713]
From the thread "proposal for printing numbers", dated 4/27...

**Starting context**
Bootstrap teachers _immediately_ freak out when they see that sin(2*pi) isn't zero. There are plenty of ways to explain this, but the initial shock is so large that it's hard to overcome. Shriram points out that hand-tuning for this case may not be a good solution, since there may be lots of other instances that turn up in the future. 

**Shriram's original message**
• I do not want to change internal representations, which will almost certainly make computation more expensive.
• I don't want to change how internal computations are performed, which will also almost certainly make things costlier.
• This is mainly an i/o matter.
• I believe this problem is most drastic at zero, because really, really small values (numerically speaking) print out “big”.

Therefore, the proposal is this.
Suppose a roughnum has an automaton with presentation states P1 ... Pn P1 ... (e.g.: ~0.0000123, ~1.23xe^-4, etc.). Presentation states are the ones you can switch between by clicking (in the special case of just two, clicking toggles).

For numbers that are very close to zero, we will add one more state P0. In this state, the number will be printed as a special rough zero (see more below). The presentation states will become P0 P1 ... Pn P0 .... That is, you will see this special representation by default, but by clicking you can explore the true value in all its representations.

Because roughnums are not precise, this is a valid interpretation for very small values close to zero. However, if you're the kind of person who's doing numerical analysis with careful bounds-tracking, then you can still see the “true” (floating point) answer if that matters.

If we are not careful, evaluation will fail to obey substitability (because plugging in ~0 is not the same as plugging in the true value: imagine a function that changes behavior depending on the value of its parameter, and it's actually checking for very small values below the threshold we have chosen). Therefore, we could choose a representation that you can't actually paste back in (e.g., ~zero). Or we can be more subtle (~0, but with underlining, to say “you really ought not be pasting this in, but if you must…). Either way, it should be visually clear to the user that they got an answer that did not compute to rough 0, but was clamped to it.

**Dorai's response**
Yeah, it's too off-beat (though it's not quite a computer-algebra system). This whole thing was motivated by users using rational multiples of pi and getting puzzled, so it isn't unusual to want to hand-tune for that. But let's shelve it and see the problem for what it is.

Recognizing "zero-for-all-practical-purposes" (ZFAPP) won't really work either. Our goal is to have sin(n \* pi) produce 0, not to collapse small numbers in general to 0.

As I said, the fluctuation of sin(n \* pi) is proportional to the slope of sin(n \* x).  [The more the slope, the more y-variation there is for the same x-variation. You can test this handily in Racket by trying (sin (\* n pi)) for larger and larger n and seeing how the value progressively increases. Or in any other language for that matter.]

If we're somehow scaling ZFAPP to match n, we're practically recognizing multiples of pi anyway.

My original solution to Emu, was to have a wrapper for sin that added or subtracted enough pis to the argument to bring it within the interval (-pi/2, pi/2) and then call JS Math.sin(). This is not very kludgey really and the performance hit of adding this extra arithmetic is minor compared to the various number dispatches we're doing anyway.  It's also a very minor change, plus the user doesn't need to re-think or re-render anything.

**Comment by ds26gte** [comment]
Starting from d41d122,  `(sin (* n pi))` is now exact `0` rather an ultrasmall roughnum.  

(Only `sin` gets this special treatment. `(cos (/ pi 2))` and `(tan (/ pi 4))` still give roughnums that aren't quite `0` and `1` respectively.)

**Comment by schanzer** [comment]
This solves the immediate problem, though perhaps not other cases. This seems like the kind of thing we should deal with as it comes up in the future, since we don't have the bandwidth to discuss and implement One Fix To Rule Them All here. Recommend we close this. Any objections?

**Comment by schanzer** [comment]
Still recommending we close. Going once, going twice...
