### ISSUE TITLE
Downcast for Pyret?

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#717]
```
fun test(t :: { foo :: Number }) -> { foo :: Number }:
  t
end

a = test({ foo: 1, bar: 2})

print(a)
```

prints `{foo: 1, bar: 2}` which is correct. `a.bar` results in a type error which totally makes sense, but that also means it's impossible to use `a.bar` which ought to be possible by downcasting.

**Comment by shriram** [comment]
Noooo! This is the essence of information hiding. This is a non-bug. Downcasting is the language design bug.
