### ISSUE TITLE
code in error is not formatted properly

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#725]
<img width="654" alt="screenshot 2016-05-13 05 36 39" src="https://cloud.githubusercontent.com/assets/9099577/15243977/d455a716-18cc-11e6-942f-2b35197ddcf0.png">

**Comment by jpolitz** [comment]
I'm dubious that we should even be trying to format code in error messages; I think we have a good story for reporting locations instead, which seems more reliable (srclocs have a more tractable length, for one thing).

**Comment by jswrenn** [comment]
@sorawee I believe this is fixed. Can you confirm?

**Comment by sorawee** [comment]
Yup :) It's good now.

**Comment by schanzer** [comment]
Still only fixed on horizon?
