### ISSUE TITLE
does-not-raise is not displayed correctly

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#727]
On horizon

```
check:
  raise("a") does-not-raise
end
```

won't show a test summary. The JS console has the following error:

```
js/repl-ui.js:304 Error displaying result:  TypeError: Cannot read property 'brands' of undefined
```

**Comment by sorawee** [comment]
Please also see https://github.com/brownplt/code.pyret.org/issues/71. I believe it's the same issue.

**Comment by jswrenn** [comment]
brownplt/code.pyret.org#71 was not related.
