### ISSUE TITLE
js-numbers needs a different way to throw exceptions in multi-runtime runs

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#737]
It’s useful for there to only be one copy of js-numbers per JS VM, so that all runtimes can share number representations.  But this makes the `setThrowRuntimeError` method of js-numbers broken in the face of multiple runtimes, which can override this method and confuse error reporting.

I think the right thing to do is to simply not rely on js-numbers throwing Pyret exceptions, and include the logic to check and/or catch non-Pyret exceptions in places that use those functions.  I don’t think we want to instantiate js-nums on a per-runtime basis, because when we do write programs that rely on having different runtimes within the same JS VM, we want numbers to count as primitives that can be passed back and forth.

Another possible fix is to define a `NumberException` in js-numbers, throw it from js-numbers failure cases, and turn it into a runtime-specific `PyretException` as soon as it’s seen in an error case in a catch block in Pyret.  This would also give us a better opportunity to make number errors richer without entangling `js-numbers` with the runtime, since right now all the number errors are `messageException`s.

**Comment by jpolitz** [comment]
(To reproduce, run `make test` twice on the current commit 907553920ce5defd666511c185a0e01f8fe4e131)

**Comment by blerner** [comment]
Is there just a single `NumberException`, or are there multiple?  It might make sense for potentially-failing js-number methods to be given an `ffi` argument, so they can call the correct error thrower...

**Comment by jpolitz** [comment]
I'd rather not pass in just `ffi` argument, since `js-numbers` currently doesn't know anything about Pyret's internals, which is nice.  It may be better to just pass in an error callback that takes all the possible number errors and converts them to Pyret errors, then throws the corresponding Pyret error.

Since it's in the exceptional case, it's not like it's performance-killing to reconstruct a new error value.

**Comment by blerner** [comment]
True, though I view it slightly differently -- the fact that js-numbers is overly oblivious to Pyret is becoming a detriment.  Lemme broaden the question slightly, to see whether an analogous situation might shed light: how does d3-lib handle exceptions?  It currently just `throw`s strings and JS `Error`s, but they have nothing to do with Pyret.  How do those errors get converted into Pyret runtime errors, and is there a general strategy we can pull out here, for translating "exceptions raised by oblivious JS modules"?

**Comment by jpolitz** [comment]
In the case of d3, and other libraries that we don't control, there are two options I see.

The first is to simply wrap all the calls into the library in try/catch blocks, and deal with the conversion to a Pyret error in the wrapper.  That probably not great for performance, but the most robust and easiest to know what to blame.

The second is to have the code that uses d3 register with the runtime some predicates and transformers that recognize d3 errors and convert them to Pyret errors.  This would avoid needing try/catch blocks, but is tricky when there are multiple libraries that may use d3 and conflict on how to expose the errors, etc.

For js-numbers, I was thinking of defining an interface like:

```
NumberErrbacks : {
  throwLogOfNegative : number, number -> [throws error]
  throwDivideByZero : number, number -> [throws error]
  ...
}
```

There will be one such object defined on each `runtime` (or `ffi`) and it will be passed in to all the number functions, to be called on errors.  I think this hits a nice balance of being easy to extend, not costing too much on the caller side, and giving us much nicer errors than we have right now.

**Comment by schanzer** [comment]
Now that the new error callbacks are merged, can this be closed?

**Comment by jpolitz** [comment]
Yup!
