### ISSUE TITLE
Incorrect Tuple Binding Error

### ISSUE THREAD

**Issue by sarahkf** [brownplt/pyret-lang#741]
When reporting an error on a tuple binding using annotations locations can be wrong. I think what's going on is that if there are two annotations of the same type and the first annotation is incorrect, the error message will report the location of the second annotation.

For example error message from the test
```
x :: {Number; Number} = {"hello"; 123}
```
will claim that the annotation went wrong at the second number.

As another example the error message from the test
```
y :: {Number; String; Boolean; String; Number; Boolean} = {124; "hello"; 1245; "hi"; 124; true}
```
will claim that the annotation went wrong at the second Boolean.

**Comment by blerner** [comment]
FWIW, I tried running this in CPO right now, and it fails with "ffi is not defined", which is masking this problem...

Anyway, bigger question: in https://github.com/brownplt/pyret-lang/blob/horizon/src/arr/compiler/resolve-scope.arr#L186 you warn "note: reversed binds".  Where is the reversal, and why, and could that be part of the problem here?

**Comment by sarahkf** [comment]
Whoops! That comment is on something old and should have been removed a while ago. There was a reversal with the bindings happening for a short period of time, but it's not happening anymore so that should just be ignored.

**Comment by blerner** [comment]
There still is a call to `reverse` a couple lines down, so I thought it might still be relevant...

**Comment by sarahkf** [comment]
I think that that reverse just has to do with making sure that the bindings happen in the right order, not to make sure that everything gets bounded to the correct value. Getting rid of it doesn't change the error message.

**Comment by sarahkf** [comment]
Okay, I fixed it! There was an issue with the way that the location of the annotation was found.

**Comment by jpolitz** [comment]
Awesome!  If you paste the URL of the commit into a comment on the issue,
it will nicely link to it.

**Comment by sarahkf** [comment]
Okay, here is the link to the commit: https://github.com/sarahkf/pyret-lang/commit/549accf620cb97628c4c8e771c764ba5b91f3f34
