### ISSUE TITLE
Type checker reports ill-formed underscores as unbound ids

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#742]
This program:

```
fun f():
  _
end
```

reports the helpful error:

```
The underscore _ cannot be used where an expression is expected.
```

But when the type-checker is used, it reports:

```
The identifier _ is unbound. It is used but not previously defined.
```

This is because the underscore checking is done along with checking for unbound ids, at the end of the compilation pipeline.  Perhaps this should be moved earlier, to be pre-type-check?

Simply checking for `s-underscore`s in `well-formed.arr` doesn't work because desugaring will convert some underscores within expressions into functions.  So it would need to be a separate WF pass that is post-desugar and pre-type-check.

**Comment by sorawee** [comment]
Believe this is the same as #711

**Comment by jpolitz** [comment]
Closing as duplicate

**Comment by schanzer** [comment]
The typechecker now gives the same error. Closing.
