### ISSUE TITLE
Immediate JS load error

### ISSUE THREAD

**Issue by SDooman** [brownplt/pyret-lang#749]
On pyret-dev, when opening a file containing the following code:

```
x = 5
```

The following errors are logged to the console:

```
(program):5 Uncaught TypeError: Cannot read property 'removeAttribute' of null
(program):5 Uncaught TypeError: Cannot read property 'removeAttribute' of null
(program):5 Uncaught TypeError: Cannot read property 'removeAttribute' of null

cpo-main.jarr:722263 Abstraction breaking: Uncaught JavaScript error:
 Error: Module not loaded yet: js-file(../js/cpo-main) while loading file:///home/travis/build/brownplt/code.pyret.org/src/web/arr/cpo-main.arr(…)
```

**Comment by belph** [comment]
Does running the same program on [pyret-horizon](http://pyret-horizon.herokuapp.com) give the same issue?

**Comment by jpolitz** [comment]
The "Module not loaded yet" error happens on horizon, for sure.  I'm tracking that down.

However, it is, for the purposes of working on stuff in the editor, a sort of inconsequential error, since all the relevant loading happens before it does.

I don't see the removeAttribute errors, though.

**Comment by SDooman** [comment]
@belph Yes it does. 

@jpolitz from my testing, the error is inconsequential on [pyret-horizon](pyret-horizon.herokuapp.com).  However, on [pyret-dev](pyret-dev.herokuapp.com), when I run the previous program, then try to evaluate the following expression in the REPL, here's what happens:

`> x`
`trace #15`

The REPL on [pyret-dev](pyret-dev.herokuapp.com) also appears to be broken independently , here's an example:

`> y = 10`
`> y`
`trace #15`

**Comment by jpolitz** [comment]
Closing; pyret-dev in this form is deprecated, and this doesn't show up on current live sites.
