### ISSUE TITLE
`method`s can be applied at the REPL because of use of `getField`

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#751]
![image](https://cloud.githubusercontent.com/assets/119891/16588410/cf52a148-429c-11e6-94ec-e6f7359ef956.png)

This shouldn't work, but does, because the REPL uses `getField` to access `m` when binding it in the second interaction, which curries the method over the module object:

![image](https://cloud.githubusercontent.com/assets/119891/16588465/04d0da74-429d-11e6-8734-6b60d79a1eb7.png)

**Comment by blerner** [comment]
Ewwww

**Comment by jpolitz** [comment]
This is horizon-fixed by the `better-exports` merge.
