### ISSUE TITLE
Program causes internal compiler error when type-checked?

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#752]
https://pyret-horizon.herokuapp.com/editor#share=0B32bNEogmncObTZnZzhDd0FfaDA

Use "type-check and run" on this program, and it reports:

<img width="614" alt="screen shot 2016-07-05 at 4 49 40 pm" src="https://cloud.githubusercontent.com/assets/119891/16599486/81f7bf30-42d0-11e6-9095-dc9b8d18cfb3.png">

Haven't spent much time tracking this one down yet, just wanted to note it.

**Comment by jpolitz** [comment]
(Running with `Run` is just fine)

**Comment by blerner** [comment]
This program now runs on pyret-horizon in TC mode just fine; closing.

**Comment by schanzer** [comment]
I thought these issues stayed open with the “horizon-fixed” label, until they were fixed on production? Just asking as a procedural question, for when I start going through old issues again...

**Comment by blerner** [comment]
Yes, but it runs on CPO just fine also :)
