### ISSUE TITLE
can't find boolean constants listed in the docs

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#753]
I needed to check on them (when a parse error led me astray), but couldn't find where they might be listed in the docs.  If they are there, they aren't readily discoverable.

**Comment by blerner** [comment]
Docs -> Builtins -> Booleans: http://www.pyret.org/docs/latest/booleans.html ?
```
Boolean

The type of the values true and false.
```

Joe and I are working on revising the docs organization somewhat, but...what would you wish to see here, and how is this related to a parsing error?

**Comment by kfisler** [comment]
Only relationship to parsing is for context of what I was trying to do when this came up. I wasn't following some clean pedagogic flow that would have led me to this.  I simply went over to my "pyret docs" tabs, which was already in the "Language Constructs" section.  From there, I just didn't see where to navigate back to (it didn't occur to me to return to the top level docs, from which I might have seen the builtins category).  I just went to the top level of "Language Constructs" and felt lost.

For a newbie, it isn't obvious that "Language Constructs" isn't self contained.  The top-level "Pyret" subcategories make sense when you are looking at the set of sub-topics, but that organization isn't relevant from inside "Language Constructs".  A link back over to "builtins" at that point would likely do the trick, but I realize that violates rendering the straight-up hierarchical structure.

(Context: I'm gearing up for BS2 in Denver, so am basically being newbie Pyret user/teacher for the next two weeks)

**Comment by blerner** [comment]
The links we have right now are (surprise, surprise) whatever tree-like organization Scribble gives us.  I'm sure we could hack other prev/next links in there somewhere, but generally speaking we haven't fussed with that part yet.

**Comment by kfisler** [comment]
Right -- that's what I assumed.  Just getting this on record.  Will be making notes on what we see the teachers doing in Denver as well.

**Comment by schanzer** [comment]
@kfisler do the docs still need work here?

**Comment by kfisler** [comment]
I don't think so -- the constants are marked on the Booleans page now.  Okay to close.
