### ISSUE TITLE
check results in interactions causes bad shadowing error

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#754]
<img width="1276" alt="screen shot 2016-07-06 at 1 36 21 pm" src="https://cloud.githubusercontent.com/assets/119891/16628205/b1f289d2-437e-11e6-9357-4f115d3875f3.png">

Somehow the composition of check-block desugaring and global-name aggregation is causing generated check block names to shadow at the REPL.

**Comment by schanzer** [comment]
Appears fixed on CPO, using the example in the screenshot
