### ISSUE TITLE
Vars are seen as let-bindings in the REPL

### ISSUE THREAD

**Issue by hilmar-hoffmann** [brownplt/pyret-lang#755]
Entering 

```
var w = 1
w := 2
```

in the CPO-REPL results in:

> The name w is defined as an identifier, but it is assigned as if it were a variable [...]

On horizon it is:

> An error occurred rendering the reason for this error [...]

**Comment by sorawee** [comment]
I think this is a duplicate of #288

**Comment by hilmar-hoffmann** [comment]
Oh, right, what about the Horizon-REPL though?

**Comment by sorawee** [comment]
This is fixed on horizon REPL. Still not fixed on CPO. Let me close this as a duplicate of the issue I mentioned above.
