### ISSUE TITLE
function name doesn't match

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#756]
The name of constructor test is not `is-*` but is `*-test`. This is confusing because there is no function named `*-test`.

```
> import plot as P
> P
{
  ...
  is-line-plot: <function:line-plot-test>
  ...
}
```

**Comment by blerner** [comment]
This has been fixed already in https://github.com/brownplt/pyret-lang/commit/fa430cc60cbea0610e7f64023277a385ba930741
