### ISSUE TITLE
Run-time error not indicating where error occured

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#759]
I just got a run-time error for using > between a boolean and a number.  The error message gave no indication of where the error had occurred (no highlighting, line number, containing function, etc).

Should I have gotten some help locating which > in my program was at fault, or is this just a limitation of the language?

--------
In case context helps, here's the code that yielded the error (part of a world program).  The problem is detected inside reverse-growth, after I accidentally passed a boolean as the second argument in the if-statement.
```
fun reverse-growth(size, grow-rate):
  ((size < 20) and (grow-rate < 0)) or
  ((size > 50) and (grow-rate > 1))
end

# next-world : World -> World
fun next-world(w):
  world(w.star-size + w.star-grow,
    if (reverse-growth(w.star-size, w.star-grow < 0)):
      w.star-grow * -1
    else: 
      w.star-grow
    end,
    w.star-loc  
    )
end
```

**Comment by jpolitz** [comment]
Can you refresh and try the error again?  I now get this error:

![screen shot 2016-07-13 at 8 36 29 am](https://cloud.githubusercontent.com/assets/119891/16803575/1c0345f4-48d5-11e6-9265-b783ee4525a8.png)

**Comment by jswrenn** [comment]
@jpolitz I can't replicate this on my end, but even the message you're getting should highlight the left and right hand sides of `<`. Perhaps `runMarks` was not being called somewhere it should have been?

**Comment by jpolitz** [comment]
It does highlight, I think I just edited or clicked away before doing the screenshot.

**Comment by kfisler** [comment]
I refreshed and got a different message this time (as expected from your email earlier today about releasing the new error msgs).  Can close this issue from my perspective.
