### ISSUE TITLE
Printed representations of operators in new error messages

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#763]
I yielded an error on a > operation.  The error text uses

  "binary Greater-than operator expression"

rather than >.  The former is more verbose to process.  Making a longer-term note that it would be nice to use the shorter more readable version unless there's a good reason this is difficult or subtle under the hood.

**Comment by blerner** [comment]
It's actually trivial to change, but I think we went with words rather than symbols for the same reason that people sometimes write "I need 2 two-by-fours" rather than "I need 2 2x4s" --  sometimes the words help clarify what the symbol meant.

**Comment by schanzer** [comment]
@blerner makes an excellent point for _explainability_, but @kfisler 's point is about _identifiability_.  The easy solution seems to be to use both:
```binary Greater-than (>) operator expression```
