### ISSUE TITLE
Indentation after "is" in check block

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#764]
Is it feasible to indent the expected expression if a newline is entered after is in a check block?  I currently get 

  next-world(C1, vec(4, -4), INIT-PADDLE-COORD)) is 
  world(C2, vec(4, -4), INIT-PADDLE-COORD)

which makes it hard to tell the new examples from the continuations of the previous one

**Comment by sorawee** [comment]
I think the preferable way is to write

```
next-world(C1, vec(4, -4), INIT-PADDLE-COORD))
  is world(C2, vec(4, -4), INIT-PADDLE-COORD)
```

which will indent correctly

**Comment by blerner** [comment]
Yes indeed.  IMHO, it's better yet, because the keyword helps _highlight_ the actual-vs-expected distinction _in addition_ to having the correct indentation.

**Comment by blerner** [comment]
@kfisler good to close?

**Comment by schanzer** [comment]
@kfisler ping?
