### ISSUE TITLE
sort and arity

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#767]
On pyrroneous.herokuapp.com,
```
[list: 2, 1, 3].sort(lam(a, b): a < b end)
```
produces some sort of void/undefined answer.

On CPO this correctly produces an arity error. So I'm guessing the issue has been resolved, but I wanted to bring it up just in case this is a context that needs to be looked into.

**Comment by blerner** [comment]
Nope, fixed on CPO; pyrroneous is out of date.
