### ISSUE TITLE
Abstract error wording around "applicant" for mismatched arguments

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#772]
One of our teachers was trying to write a nested put-image expression.  She forgot to put the x/y at which to put the image.  So her code looked like

put-image(IMG1, put-image(IMG2, 100, 100, BACKGROUND))

The error message is written in terms of the abstract term "applicant".  She didn't manage to parse the message to realize it was reporting mismatched arguments.  It appears the "applicant" intermediate phrasing really threw her off

**Comment by schanzer** [comment]
@kfisler , this no longer uses "applicant". Are you satisfied with the new wording?

**Comment by schanzer** [comment]
@kfisler , OK to close?

**Comment by schanzer** [comment]
Closing. @kfisler , re-open if this is still an issue.
