### ISSUE TITLE
Request: Append "(Try Pyret)" to "Set Sail" button

### ISSUE THREAD

**Issue by oboff** [brownplt/pyret-lang#774]
I ended up downloading Pyret source not knowing that "Set Sail" led to the online interpreter.

**Comment by shriram** [comment]
Sorry about this. Yes, the label “Set Sail” is a bit too cute. We should just _change_ it to “Run Pyret” or “Try Pyret” and put any jokes about setting sail elsewhere in the site. Thanks for the feedback.

**Comment by blerner** [comment]
Fixed by https://github.com/brownplt/pyret.org/commit/8ad9ab9b8249047ea68713bfee4349f6dca3fbeb; @jpolitz please push to the live site?

**Comment by blerner** [comment]
This is live on pyret.org/, so closing.
