### ISSUE TITLE
destructuring binding doesn't work in argument lists

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#775]
I can write

```
fun f(w): 
  {x; y} = w
  x
end
```

but not

```
fun g({x; y}):
  x
end
```

This seems unfortunate, and it's especially a drag in `lam` expressions, where the one-line-ness of an expression is totally destroyed by not being able to destructure [though I admit it looks rather ugly if you do it in `{...}` lambda syntax as opposed to `lam` syntax].

As a general principle, I would have thought destructuring binding works in _all_ binding positions.

**Comment by jpolitz** [comment]
Coming soon!

**Comment by blerner** [comment]
This works now.
