### ISSUE TITLE
chaining tests/examples

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#776]
We need to sometimes write tests in multiple ways:
- lhs
- rhs as an _answer_
- rhs as an _expression_

It's painful to write

```
  lhs is rhs-answer
  lhs is rhs-expression
```

because it duplicates the LHS, causes twice as much computation, and leads to a less clear error message than possible.

We should allow multiple terms to be chained, and I suggest using `also-` as a prefix:

```
  lhs is rhs-answer also-is rhs-expression
```

By using a prefix, we can now have the whole family of testing connectives appear after it: `also-is-not`, `also-is%(...)`, etc.

**Comment by blerner** [comment]
I don't understand the motivation for this at all.  The Pyret mantra is "If you don't want to repeat yourself, then let-bind the result."  So

```
check:
  common-lhs = lhs
  common-lhs is rhs-answer
  common-lhs is rhs-expression
end
```

Why make the language more complicated when there's already a perfectly good (and more reusable) technique available?

**Comment by jpolitz** [comment]
@blerner: two reasons why naming isn't sufficient:

- Writing an expression on the LHS is better than let-binding it, because `is` catches exceptions and reports them on the is line, rather than stopping the whole test block (and this was decided to be clearly superior after not having `is` catch errors for a year).
- It would be good to allow this in `examples:` blocks, which only allow a sequence of testing statements.

**Comment by shriram** [comment]
Also, you've now taken three lines to write what might have been a one-liner. Vertical space is important.

Believe me, I currently do do this let-valued thing, and every time I do it, I find myself thinking, “I really wish I could write more than one pair of tests here”.

**Comment by shriram** [comment]
One other issue is error reporting. Reporting the output of a 3-way or _N_-way test is different from reporting a series of two-way tests.

**Comment by jswrenn** [comment]
> We need to sometimes write tests in multiple ways:
> - lhs
> - rhs as an answer
> - rhs as an expression

@shriram, can you clarify what you mean _answer_ and _expression_?

**Comment by blerner** [comment]
@jswrenn exactly.  @shriram I don't believe you could actually write anything interesting here in one line, certainly not _readably_.  At best, the "middle" test will be surrounded and lost by the other tests, and I do not see what concretely you're hoping for in terms of error messages.

I think @jpolitz 's objections are more compelling -- catching errors is useful, and making things available to BS:1 teachers is useful.  But I'm not convinced yet that we need this.  Do you have a specific example in mind?

**Comment by shriram** [comment]
"answer" = a value. "expression" = a non-value that will produce the desired value.

We run into this a lot in the pedagogy of abstraction. For instance:
```
examples:
  moon-weight(10) is 1/6 * 10
  moon-weight(100) is 1/6 * 100
  moon-weight(60) is 1/6 * 60
  moon-weight(0) is 1/6 * 0
end
```
You write it in this form to figure out how to abstract and create the function `moon-weight`. But there are times when you also want to write down the actual answer value:
```
  moon-weight(60) is 10
```
And sometimes you want to do both:
```
  moon-weight(60) is (1/6 * 60) also-is 10
```

**Comment by blerner** [comment]
@shriram this is addressed by the `because` syntax, right?

**Comment by shriram** [comment]
Sure, but is that syntax actually released? @kfisler said she tried it recently and couldn't get it to work. I tried to look for it in the docs, but gave up after 5 minutes (because Pyret docs).

**Comment by blerner** [comment]
No, it's stuck on horizon, and horizon is stuck until Joe and I can finish the modules and merge.  (Fortunately, we're getting really close, and this should happen soon.)  Also the docs are on horizon, and that'll merge too.

**Comment by schanzer** [comment]
`because` is now implemented on CPO. Is this still an issue?

**Comment by blerner** [comment]
I think this is good -- @shriram please confirm and close

**Comment by shriram** [comment]
Yes!!!
