### ISSUE TITLE
double-quotes paste oddly

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#783]
I am pasting the following excerpt from another document:

CLASS = “Bootstrap”  # yes, this is a syntax error

In some cases it pastes with the (erroneous) slanted-double-quotes and in other cases as (correct) unslanted ones — but in the latter case, that means it's not preserving the original formatting.

It first pasted with slanted into the editor. Then, it stopped doing that (i.e., it pasted them as unslanted into the editor) even as it continued to paste them as slanted into the REPL. I wonder if there's some CM modality issue here.

**Comment by blerner** [comment]
We have a filter that we apply to the definitions area that fixes smart quotes back into dumb ones. I don't think we apply that filter to the repl area yet.

**Comment by shriram** [comment]
Though I cannot reproduce it now, I am 99.99% certain the first time I pasted this I did so into the REPL and it did _not_ replace quotes, resulting in a syntax error. Is it possible there's some state so that in a pristine window it doesn't work? Oh — how about if I pasted while the loading process was still going on?

**Comment by blerner** [comment]
Reread my comment.  Pasting into the _definitions_ area will fix smart-quotes.  Pasting into the REPL will do nothing.  Hence, syntax error in REPL, but not a problem in the definitions area.  If you pasted into the definitions area and it didn't replace the quotes, then it's possible you hit a race condition in the definitions area, where it was enabled for editing but the quote-replacer hadn't been installed yet; I dunno.

**Comment by shriram** [comment]
Typo. I pasted into the _definitions window_. Therefore, I expect it's a race-condition in loading the editor, since I did paste while loading was still in progress. Is that @belph's?

**Comment by jpolitz** [comment]
Pretty sure @elibwhite implemented this with the UI redesign.  I think it's just a matter of finding the right code and moving it to `beforePyret.js` so it doesn't race.

I don't know if it's actually difficult to enable this in interactions, as well, or if it's just a matter of attaching the right listener to the same functionality.

**Comment by schanzer** [comment]
This seems pretty-consistently auto-converted in the definitions area now. OK to close?

(Though FWIW, I feel like it's a mistake to have the REPL behave differently)

**Comment by blerner** [comment]
No, I think @jpolitz 's comment is intended to fix the interactions area too.  Not finished yet.

**Comment by blerner** [comment]
I think this is fixed -- it seems to paste properly into both definitions and interactions

**Comment by schanzer** [comment]
Fine by me
