### ISSUE TITLE
field-not-found

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#787]
`check "field-not-found":
  {x:1}.y
nothing end`

Results in "...failed because the left hand side evaluated to an object that did not have a field named y"

I'd suggest "Attempted to lookup a field `y` on an `object` that did not have a field by that name", where y and object highlight the relevant snippets.

**Comment by jpolitz** [comment]
Interestingly, we never use the word `object` in BS:2, where this error message is quite important.  I think part of the reason for wanting to use `left-hand side` was that it didn't lie, and accurately covered both data values and objects, which are slightly different things.

No matter what the message ends up saying, this hints at a curriculum/language vocabulary discussion we should be having.

**Comment by schanzer** [comment]
The new error message looks a lot better, so I'm ready to close the issue. However, @jpolitz 's comment above makes me ask: should we be calling these structures or objects in BS:2? Which is more appropriate?

**Comment by schanzer** [comment]
Pinging @jpolitz

**Comment by blerner** [comment]
Ping @schanzer @jpolitz  I think we can close this...

**Comment by schanzer** [comment]
I’m happy if @jpolitz is..

**Comment by schanzer** [comment]
Since the problem was one that I created and I'm happy with the way it's addressed, I'm going to close this.
