### ISSUE TITLE
`transform` not handled properly by highlighter/indenter

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#790]
On pyret-dev, `transform` is not highlighted properly (the keyword `transform` is not bolded) and the indentation of the body of `transform` is also off. E.g.:

![image](https://cloud.githubusercontent.com/assets/75030/17233284/9273f9e4-54fc-11e6-92de-fc7b5dd2ce74.png)

**Comment by blerner** [comment]
Fixed by https://github.com/brownplt/code.pyret.org/commit/fcc13cdb1f769319782f09d9ddc38ab9d5284aa3
