### ISSUE TITLE
Table Feature Proposal:  Group By / Aggregate Functions

### ISSUE THREAD

**Issue by SDooman** [brownplt/pyret-lang#795]
Here's an excerpt of a table containing a user's music listening history.  The table keeps track of the Artist, Album, and Title of every song listened to, and the date/time of listening.

| Artist | Album | Title | Date |
| --- | --- | --- | --- |
| The Beatles | Abbey Road | Something | 27 Jul 2016 20:08 |
| Gnarles Barkley | St. Elsewhere | Crazy | 27 Jul 2016 20:06 |
| Massive Attack | Mezzanine | Teardrop | 26 Jul 2016 19:51 |
| Bonobo | Black Sands | Kong | 25 Jul 2016 05:12 |

A user might want to ask these questions:
- What are my 5 most played songs by The Beatles?
- What are my most played albums?

To answer these questions, analogous SQL queries would be:

```
SELECT Title, COUNT(Title) FROM
    (SELECT Title, Date FROM music WHERE Artist="The Beatles")
GROUP BY Title;
```

```
SELECT Album, SUM(Album) FROM music GROUP BY (Album);
```

**Comment by blerner** [comment]
@SDooman @jpolitz This is supported now, right?

**Comment by schanzer** [comment]
Paging @jpolitz ?

**Comment by jpolitz** [comment]
We can handle this with methods now, so I don't think syntax needs to be added for this.
