### ISSUE TITLE
Incorrect error message for Angle

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#799]
```
An annotation, Angle (a number 0-360), in ....
was not satisfied by the value

360
```

**Comment by schanzer** [comment]
CPO and Horizon both display the same error - so it's either _not_ fixed on horizon, or this can be safely closed. :)

**Comment by sorawee** [comment]
Sometimes `horizon-fixed` actually means `sql-fixed`, and I think it's the case here...

**Comment by jpolitz** [comment]
No such thing as `sql-fixed` anymore, because that branch is fully merged.  This says `< 360` now, so it's accurate:

```
An annotation, Angle (a number 'x' where 0 <= x < 360), in <builtin image>

was not satisfied by the value

360
```
