### ISSUE TITLE
C-y keybinding?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#802]
As an old Emacs hound, I can't have C-k work for killing a line but C-y not work for pasting it, especially since this is a standard copy-and-paste method. Can I please have C-y? (C-k doesn't seem to put the line in the clipboard, so standard OS paste doesn't work, either.)

**Comment by blerner** [comment]
You can't have C-k at all; in Firefox, it means "activate the search box", and in Chrome it activates the address bar with a "?" in it (presumably, to create a search).  Without C-k there's no need for C-y, and anyhow OS-standard copy and paste methods work in both browsers; I'd recommend using them.  I _really_ don't want to get into the business of emulating power-user keyboard shortcuts that won't be native on any browser or any OS.

**Comment by shriram** [comment]
Got it. So C-k just happens to work on Chrome, unfortunately in this case because there's no corresponding C-y.
