### ISSUE TITLE
check blocks not source-linked?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#803]
In the following check block

![image](https://cloud.githubusercontent.com/assets/75030/17276864/b42ebf26-5702-11e6-9855-726033b51450.png)

nothing seems clickable to link to source, so I can't get from the block to the corresponding test.

If there are source-linked elements, they're so small I'm having trouble finding them.

This is on pyret-dev.

**Comment by jswrenn** [comment]
Fixed on brownplt/code.pyret.org#105.

**Comment by schanzer** [comment]
@shriram is this still an issue for you?

**Comment by jswrenn** [comment]
#105 hasn't been merged yet.
