### ISSUE TITLE
unbound identifiers being reported twice? [on pyret-dev]

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#804]
My program contains
```
  r1 = {reactor:
      init: disp(0),
    on-tick: {(t): t + 1},
    to-draw: {(t):
          put-image(BALL,
            f(t),
            200,
        BG)}}

  r2 = {reactor:
      init: disp(0),
    on-tick: {(p): p + deriv-of-f(p)},
    to-draw: {(p):
          put-image(BALL,
            p,
            200,
        BG)}}
```
where `disp` is unbound. There are two instances of it.

The output I'm seeing is

![image](https://cloud.githubusercontent.com/assets/75030/17277077/370fbb84-5708-11e6-93f4-3ed6ead7ed1b.png)

The first two are for the first instance, the second two for the second one.

The colors are also odd (but consistent). When I click on the first error report, the chosen color is brown, and there are _five_ instances of a brown `disp`: two in that error, one in the source, and two more in the second error. When I click on the second report, there are similarly five blue `disp`s. The same behavior happens with the third and fourth errors, with pink and green, respectively. (You can see this behavior in the screenshot, where there are four green highlights in the errors; the definitions side is not shown.) Based on the colors, CPO really is recognizing that these are “the same `disp`s”. It seems to just be repeating the errors.

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/pyret-lang/commit/c6dce3d66d6c3d770b5e934900f71c5d586ee49a
