### ISSUE TITLE
indenter in wedged state

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#805]
In the following program
```
include image
include plot

epsilon = 0.00000000001
fun d-dx(f):  
  lam(x):
    (f(x + epsilon) - f(x - epsilon)) / (2 * epsilon)
  end
end

BALL = circle(10, "solid", "blue")
SCALE = 10

fun mmm(pts, f):
  deriv-f = d-dx(f)
  
  min = for fold(m from pts.first(), r from pts.rest()):
    if r < m: r else: m end
  end
  max = for fold(m from pts.first(), r from pts.rest()):
    if r > m: r else: m end
  end
  
  spread = max - min
  BG = rectangle((spread + 2) * SCALE, 100, "solid", "white")
  
  r = {reactor:
      init: pts,
      stop-when: {(ps): is-empty(ps)},
      on-tick: {(ps): place-image(BALL,
              (ps.first() + 1) * SCALE,
              50,
          BG)}
```
the next character ought to be a `}` (to close the reactor). 

[Nix what I wrote earlier. Due to a Chrome completion problem I'd ended up in CPO rather than pyret-dev. In CPO this closes and indents fine, though of course CPO doesn't recognize `reactor` as a construct.]

**Comment by jpolitz** [comment]
Closing as wontfix because the indenter has changed for new reactor syntax.

**Comment by hilmar-hoffmann** [comment]
@jpolitz A snippet of information that might be useful in this context:
At my company we have a lot of different versions of an application running in their respective environments: development, integration, earlier production versions, special versions/environments, etc. 
To be on the safe side and to distinguish them at first glance, their background colors are all configured to be different from each other. 
Maybe you could do something similar or have different icons for cpo, horizon and dev ...

**Comment by shriram** [comment]
I agree with this. In a different context, just a few days ago we were talking about this in CIT 357. A better visual differentiation between the different versions would be a great idea. In this case, it would have helped me immediately know I was in CPO and not in dev, before I even began coding. So I totally second @hilmar-hoffmann.
