### ISSUE TITLE
please do not use “you” in error messages

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#810]
«Binary operators of different kinds cannot be mixed at the same level, but you use \* at the same level as +. Use parentheses to group the operations and to make their precedence unambiguous.»

Saying “you” blames an individual, the user. That makes them feel bad. At worst, blame the program, not the user. Ideally, try not to blame anyone at all. (There is some good research on this by Andy Ko and others about how to _word_ error messages to not make people feel blamed.)

**Comment by blerner** [comment]
This is fixed, I think.  The only uses of "you" or "your" are not accusatory: "Pyret didn't understand your program", and "You may need to ... to fix your program", and "Did you mean to use a comparison operator instead?" @shriram good to close?

**Comment by shriram** [comment]
Once @jswrenn confirms that he's gone through and checked for this (and has it in the error message instruction guide — which he hasn't yet shown me), then he can close this.

**Comment by jswrenn** [comment]
Will do.

**Comment by jswrenn** [comment]
As @blerner noted, the word "you" is always followed by "program".
