### ISSUE TITLE
pyret-dev running button spins forever

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#816]
If I Run the program twice in rapid succession (though hitting Ctrl-Enter twice, quickly), this seems to cause the running button to run forever even though the program loads and runs successfully. That is, my REPL is available for use but "Run" becomes "Running" with Bonny spinning the whole time. After every REPL interaction, it goes back to spinning.

**Comment by schanzer** [comment]
horizon no longer has this issue, and pyret-dev is no longer active. Closing
