### ISSUE TITLE
underflow error?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#819]
I was working with some really small roughnums and got

Error:
TypeError: Cannot read property 'throwDomainError' of undefined

I suspect the roughnum underflowed into `undefined`, resulting in an arithmetic error, resulting in an internal error in error reporting. That's my conjecture, anyway.

**Comment by blerner** [comment]
That's an errback issue, where the errbacks object isn't flowing through js-numbers correctly.  Darn it. I thought we'd caught and tested all those.  Can you post the exact code that led to it, or email it to me?

**Comment by shriram** [comment]
I can't reproduce it right now. I've been maniacally tuning differential
equation parameters. Maybe Dorai can try a few overflow/underflow values to
see if he can trigger this?

**Comment by shriram** [comment]
Isolated to this code. When you run the following program on pyret-dev, you'll get the above error.

```
alpha = 200
beta = 0.0000001
gamma = 0.5
delta = 0.00000000001

fun new-pop(pop) block:
  {pred; prey} = pop
  
  new-pred = 
    pred * (1 - (gamma + (delta * prey)))
  new-prey =
    prey * (1 + (alpha - (beta * pred)))

  {new-pred; new-prey}
end

new-pop({ ~-3.3062302521667433e+223; ~-3.306230252166743e+227 })
```

**Comment by blerner** [comment]
Thanks, I'll take a look

**Comment by ds26gte** [comment]
Even shorter: `~2e222 * ~2e222` triggers this. The overflow isn't being properly reported. (The roughnums are too large absolutely, not too small.)

**Comment by blerner** [comment]
Yup, some fixes definitely got dropped from the js-numbers file, to properly propagate errbacks throughout.

**Comment by blerner** [comment]
Should be fixed by 32ea46f0e5f5.

**Comment by schanzer** [comment]
This is fixed on both horizon and CPO: we get a proper "roughnum overflow" error. OK to close?

**Comment by schanzer** [comment]
poke? Fixed on CPO...
