### ISSUE TITLE
Tuples don't work in cases

### ISSUE THREAD

**Issue by samuela** [brownplt/pyret-lang#824]
For example, on pyret-horizon this code

```pyret
cases ({List<a>; List<a>}) {empty; empty}:
  | {empty; empty} => 0
end
```

produces a syntax error on the opening { in `| {empty; empty} => 0`.

**Comment by blerner** [comment]
Only data types work in cases. Tuples are an independent feature, so they don't work there. Neither do objects, strings, booleans, images, ...

A general pattern-match construct is currently beyond the scope of Pyret, but we probably want one someday.

**Comment by samuela** [comment]
Hmm, well I'll call this a feature request then!
