### ISSUE TITLE
Tuple assignment doesn't type check in some cases

### ISSUE THREAD

**Issue by samuela** [brownplt/pyret-lang#825]
On pyret-horizon, this fails the type checker:

```pyret
{a; b} = split-at(2, [list: 1, 2, 3, 4])
```

because `it found a {prefix : List@module-uri("builtin://lists")<Number@module-uri("builtin://global")>, suffix : List@module-uri("builtin://lists")<Number@module-uri("builtin://global")>} but it expected a {atom#exists#83; atom#exists#84}`. This sounds to me as if the existential types of `a` and `b` are not being checked against anything. It also seems to indicate another bug with the type checker: unchecked existential variables should never escape the type checker; they should be instantiated to have `∀ a. a` type.

Somewhat surprisingly, this:

```pyret
{x; y} = {(): {1; "a"}}()
```

type checks and runs just fine.

**Comment by blerner** [comment]
Split-at returns an object, not a tuple, so yes it certainly shouldn't type check that way! 

Your second example is a success: you defined a Lana that returns a tuple, and call it immediately, and so it does type check. Hooray!

**Comment by samuela** [comment]
Ah, so I misread the documentation! I read https://www.pyret.org/docs/latest/lists.html#%28part._lists_.List_split-at%29, saw the {...} syntax, the two `List<a>`s and thought that it was certainly a tuple. This is really programmer error, but it only adds to my feeling that the syntax for tuples can be confusing.
