### ISSUE TITLE
_internal_ error on type-checking even a very simple `reactor`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#827]
```
reactor:
  init: 0,
  on-tick: lam(x): x + 1 end
end
```
results in
"An error occurred rendering the reason for this error; details logged to the console"

**Comment by jswrenn** [comment]
Got to run, but see https://github.com/brownplt/code.pyret.org/commit/1353c0c5a4f931af7407791cb2d6bfd295990038 for a fix for the fallback not rendering.
