### ISSUE TITLE
add-line doesn't handle non-integer coordinates correctly

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#830]
`add-line(square(50, "solid", yellow), 10, 25.5, 40, 25, blue)` produces an image whose width is 50, and whose height is NaN.  No output is drawn at all, though calling image-width and image-height on the result do produce results...

**Comment by schanzer** [comment]
This should have been fixed by f6b08d526927337de3c86ee24deb0f81bfed4832, but the [build failed because of a "page crash"](https://travis-ci.org/brownplt/code.pyret.org/builds/152232919).  No further information is given.

**Comment by blerner** [comment]
May be worth just force-pushing an empty commit to try to rerun the tests?  They've been annoyingly flaky sometimes, and if nothing you've done should trigger a crash like that, it may well not be your fault

**Comment by jpolitz** [comment]
I don't think you mean "force-push" here, @blerner, there shouldn't be a `--force` necessary, just `--allow-empty`.

**Comment by schanzer** [comment]
I just pushed a whitespace-only commit, and Travis died again at the exact same place.

**Comment by jpolitz** [comment]
I think we may need to break up that test.  It runs successfully locally, though it makes my laptop sound like it's going to lift off.  I think the free Travis servers just run out of memory trying to compare all those images.

**Comment by schanzer** [comment]
Closable?
