### ISSUE TITLE
default reactor pop-up window should exit once `stop-when` is true

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#837]
Once the `stop-when` condition is true, the reactor window should close and return the value of the reactor. Currently it appears to suspend, and the only way to make it go away is to kill the pop-up (e.g., by clicking on the x). For instance:
```
r = reactor:
  init: true,
  stop-when: {(w): w}
end

r.interact()
```
should immediately return with `true`.

**Comment by blerner** [comment]
Disagree -- especially for physics reactors, the final stop-when scene is often the most interesting.  It would suck to tantalizingly flash that scene, then immediately wipe it away.

**Comment by jpolitz** [comment]
Add `close-when-stop: true` to the reactor.

**Comment by shriram** [comment]
I can live with this. Hopefully the documentation for `stop-when` will make this clear (so the reader doesn't need to know to look for `close-when-stop`).
