### ISSUE TITLE
callee reactor interferes with return value of caller reactor?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#841]
Here's a simple program with a nested reactor call:
```
include reactors

fun word-reactor():
  rw =
    reactor:
      init: "",
      on-key: 
        lam(w, k): w + k end,
    end
  interact(rw)
end

fun num-reactor():
  rn =
    reactor:
      init: 0,
      on-tick:
        lam(w) block:
          word-reactor()
          w + 1
        end,
    end
  interact(rn)
end
```
Suppose I run `num-reactor()`. I type some text, then hit Esc to leave the string reactor. I then hit Esc again to leave the numeric reactor. At this point, I would expect the return value (shown in the REPL or bound to a variable) to be a _number_ (wrapped in `reactor`, but I'm ignoring that part); however, it is a _string_, namely the string representing the state of the string reactor at the point when I hit Esc. I cannot find any trace of the state of the numeric reactor. This violates the fundamental invariant that calling `num-reactor()` should eventually yield a (wrapped) number.

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/code.pyret.org/commit/19a748b0121702049cd0893ac278d011ed337c42
