### ISSUE TITLE
Pyret keeps restarting on mobile Safari

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#843]
iPad OS version 9.3.2 (13F69) / iPad 2 (pretty ancient)

This program
http://pyret-dev.herokuapp.com/editor#share=0B8tMj1kiBo09M2VrVDVxMzNzcFk&v=undefined
seems to load, then at the point where I would expect it to start executing (there's a command at the bottom of the file), Safari prints the message
«A problem occurred with this webpage so it was reloaded.»
and the loading cycle starts over.

Several Web hits suggest this is a known problem; suggested fixes are vague and intrusive (reload everything, reboot everything…) and are still not proven to work.

If this is just a problem with ancient hardware/OS, then it's fine. If someone with a newer iPad can try it out and confirm that it's no longer a problem, that would be great.

**Comment by schanzer** [comment]
Is this still an issue, given the better-optimized CPO and more powerful mobile safari of today?

**Comment by shriram** [comment]
Well, has someone actually tried this on a relatively modern iPad? I don't have access to one.

**Comment by YanyanR** [comment]
I got the error "Pyret failed to load; check your connection or try refreshing the page. If this happens repeatedly, please report it as a bug." on iPad version 10.2

**Comment by schanzer** [comment]
You may need to test it on mainline CPO. The original URL didn’t load for me either.

Ed Campos just tested it on an iPad mini 2, which has 1gb RAM and a 4 year old A7 chip. The program runs successfully without Mobile Safari crashing.

Recommend we close.
