### ISSUE TITLE
Pyret does not seem to load on iOS Safari 9.0.2 (11601.3.9)

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#846]
On both CPO and pyret-dev, I get a spinning Bonny and the text "Raising the masts…". The text never changes, and Pyret never really seems to load.

**Comment by jpolitz** [comment]
Sorry for the late followup – this worked fine for me on 9.1.x when this was reported and still does (I'm at 9.1.3).  Unfortunately, Sauce Labs, my main way of trying myriad browser versions, doesn't let me pick between point releases (I get 9.1.2 from their service).

Does this still happen for you?

**Comment by sorawee** [comment]
I have Safari 9.0.2 (11601.3.9) too! Everything is functional...

**Comment by schanzer** [comment]
Ditto.

**Comment by shriram** [comment]
My mistake. I meant to report a problem from @kfisler's iPad, which is ancient. It gets through loading some ways and then says there was an error, the page needs to be reloaded, and goes into an infinite loop of those.

(To be honest, I can't remember whether there was _also_ a problem on her desktop Safari, which too may be a bit outdated. But there's definitely one on her tablet.)

**Comment by jpolitz** [comment]
Can we safely close as a dup of https://github.com/brownplt/pyret-lang/issues/843?

**Comment by shriram** [comment]
I forgot I'd filed that. Yes, let's consider that to be the only open issue. Not sure what this was (it probably really _was_ some desktop version), but if nobody else has been able to reproduce it, it's not worth worrying about.
