### ISSUE TITLE
type checker not failing program

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#849]
On CPO: This program:
```
fun rev<T>(l :: List<T>) -> List<T>:
  fun h(shadow l, rv):
    cases (List) l:
      | empty => rv
      | link(f, r) =>
        h(r, link(f, rv))
    end
  end
  h(l, empty)
end

check:
  rev(empty) is empty
  rev([list: 1]) is [list: 1]
  rev([list: 1, 2]) is [list: 2, 1]
  rev([list: 1, 2, 3, 4]) is [list: 4, 3, 2, 1]
  rev([list: "x", "y", "z"]) is [list: "z", "y", "x"]
end
```
type-checks and runs fine. I was a bit surprised it type-checks given the lack of any internal annotations (how could it infer the type of the shadowed `l` or of `rv`?). So I changed the call to the helper to read `h(l, 3)`. Instead of getting a _type_ error, I get five _test failures_.

**Comment by blerner** [comment]
Explaining the type inference without additional annotations is doable: `rv` must have type `List<T>` because `rev` is annotated to return `List<T>` and returns `h(l, empty)`, and `h` returns `rv` when `shadow l` is empty`.  Then since `rv :: List<T>`, we know from the type of `link` that `f` must have type `T`, so `shadow l :: List<T>` also.  Alternately, `l :: List<T>`, and `l` gets passed to `h`, so `shadow l :: List<T>`.

I'm impressed with the subtlety of the inference, if it's working as expected here! :)

**Comment by shriram** [comment]
Well, yeah, that's _possible_. I found an example of inference in Typed Racket once that both Matthias and Sam said was impossible (but it wasn't), so I do have my eyes open to the power of local inference. But the fact that it doesn't report a pretty obvious type error makes me worry that the "successful" inference is also buggy behavior: that is, it's just plain failing to check anything at all, rather than inferring something very cleverly.

**Comment by mkolosick** [comment]
What is the obvious type error?

**Comment by shriram** [comment]
Passing `3` as the second parameter to `h`. This is bound to `rv`, which is the second parameter of a `link`. Shouldn't that be a type error?

**Comment by mkolosick** [comment]
What line is this on? I don't see `3` being passed to `h` anywhere.

**Comment by shriram** [comment]
Please read the entire submission.

**Comment by mkolosick** [comment]
Ah, missed that sorry. Investigating now.

**Comment by shriram** [comment]
That's why it was a bug report in the first place. (-:

**Comment by awstlaur** [comment]
> So I changed the call to the helper to read `hv(l, 3)`

Was that supposed to be `h(l,3)` ?

**Comment by shriram** [comment]
@awstlaur correct, thanks. Edited the original.

**Comment by schanzer** [comment]
Assuming I'm reading the original issue, we should see a type error for both the original code and the same code with the helper call changed to `h(l,3)`. On CPO, I see the same type error for both -- it's unable to infer the type of `l`

**Comment by shriram** [comment]
I can confirm that with an annotation for `l`, this now type-checks (`rv` does not seem to need one), and it now also flags the type error when `empty` is replaced by `3`. So this is all fixed. Thanks.
