### ISSUE TITLE
Unexpected `within` results.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#853]
```
> within(1)(none, none)
true

> within(1)(some(2), none)
false

> within(1)(some(2), some(3))
true

> within(1)(some(2), some(4))
true
```
The third and fourth interactions are surprising; the documentation states that on non-numeric values, `equal-always` will be used for testing equality.

**Comment by blerner** [comment]
Where do you see that?  I see at http://www.pyret.org/docs/latest/equality.html#%28part._equality_within%29
```
Examples:

check:
  num-sqrt(10) is%(within(0.1)) 3.2
  num-sqrt(10) is-not%(within(0.1)) 5
end

Finally, within accepts any two values, not just numbers. On non-numeric arguments, within traverses the structures just as in equal-always, but deferring to the bounds-checking equality when a pair of numbers is encountered. All other values are compared with equal-always.
```
That "deferring to the bounds-checking equality when a pair of numbers is encountered" is key.

**Comment by jswrenn** [comment]
I'm an idiot. I read that part, what I didn't read was that the first argument was a percentage. I was confusing `within` for `within-abs`.
