### ISSUE TITLE
broken links in docs

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#856]
http://www.pyret.org/docs/latest/lists.html

Look for "Produces a new list whose contents are the same as those of the current list, sorted by < and ==". `<` and `==` are underlined but not links. Similarly in "Like sort, but the comparison and equality operators can be specified.", `sort` is underlined but not linked.

**Comment by sorawee** [comment]
Unrelated, but should we move this to https://github.com/brownplt/pyret-docs/issues?

**Comment by belph** [comment]
Fixed; this can be closed once someone with permissions pushes out a rebuild of the documentation (@jpolitz).

**Comment by schanzer** [comment]
Confirmed fixed. Closing.
