### ISSUE TITLE
Pyret compiler generates invalid javascript code!

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#858]
This file compiles and runs tests when [opened on its own in an editor](https://code.pyret.org/editor#share=0B10yEbrPEl1ZS3paMDFGYkRIOHM), but produces a _javascript_ syntax error upon import:
```
import shared-gdrive("parse", "0B10yEbrPEl1ZS3paMDFGYkRIOHM") as C
```

This problem affects `master`, but not `horizon`. This was reported by @ajpal, and CS173 depends on this file being importable.

**Comment by jpolitz** [comment]
Thanks, easy fix and it'll be up soon (~15 min).  Just a stupid typo in the way URIs are generated for shared files, which is what I get for trying to work fast.

**Comment by jswrenn** [comment]
Confirming that this works on CPO, now. Thanks, @jpolitz!

**Comment by jpolitz** [comment]
Sorry for the hiccup, this was really dumb of me.  Regression test added so I can't make this mistake again.
