### ISSUE TITLE
Treating modules as records causes huge error printout

### ISSUE THREAD

**Issue by mkolosick** [brownplt/pyret-lang#859]
In both the type checker and dynamically, attempting to access an identifier that is not present in a module causes a huge printout.

Example:
`error("this should have been raise")`

Perhaps there should be a way to collapse records in the view?

**Comment by mkolosick** [comment]
See #826

**Comment by jpolitz** [comment]
6a514338448b42c82a3ab0fe698f4ccbfc83de12 and a419b946208a647da87b3114bb644db5b6cba51e are moving towards making this a static error that we have much more control over.

**Comment by schanzer** [comment]
This now generates the error "The identifier `error` is unbound:". Not sure what that means for closing this issue v. keeping it open...

**Comment by blerner** [comment]
I think the modules work has fixed this
