### ISSUE TITLE
do not print out large tables in full except on demand!

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#861]
I made the mistake of clicking on a student file that loaded a table and, following instructions, in the REPL, typed the name of the variable holding the table contents. The table has 2000 rows. I was able to create this issue in the time it took to get control back.

If we're going to put tables in front of _beginners_, we can't let the act of trying to inspect a table have such drastic consequences.

(Several beginners will be using tables a week from now…)

**Comment by jswrenn** [comment]
There are libraries that allow displaying large tables very, very efficiently by not immediately dumping the entire thing at once to the DOM. [Clusterize.js](https://clusterize.js.org/) has a really impressive demo on their home page of loading 500k rows.

**Comment by shriram** [comment]
We don't need something hyper-fancy. Just something that prints maybe the first 10 rows, then offers a button for showing more (and to get fancy, "show 10 more" versus "show all remaining 1990 rows").

**Comment by shriram** [comment]
Btw, this is pretty brilliant:
![image](https://cloud.githubusercontent.com/assets/75030/18256898/a4aea3c4-7389-11e6-8af6-aa46847075cd.png)

**Comment by schanzer** [comment]
Still only on horizon?
