### ISSUE TITLE
Data definition with no constructor raises a weird error

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#867]
```
data Foo: end
```

results in:

```
Evaluating the field lookup expression at file:///home/travis/build/brownplt/code.pyret.org/node_modules/pyret-lang/src/arr/compiler/ast-util.arr:206:40-206:48 errored.

does not have a field named first

Please report this as a bug.
```

Besides the bug, I think that this should be allowed generally. Though usually useless, this is used by, for example, Coq, to represent False in the proof system.

**Comment by jswrenn** [comment]
> I think that this should be allowed generally. Though usually useless, this is used by, for example, Coq, to represent False in the proof system.

Agreed. You could do something with phantom types in typed Pyret with this, too.

**Comment by sorawee** [comment]
Close as duplicated
