### ISSUE TITLE
Non-rectangular tables can be constructed, but cause internal errors when used

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#873]
This program:

```
t = table: a, b
  row: 
  row: 1, 2
end
```

runs without error, but any use of the table generally results in sadness.  Tables should have better well-formedness checking to make sure that they are rectangular – this ought to be easy to do statically.

**Comment by jpolitz** [comment]
This came up with a student who tried to comment out a row by starting the comment after `row:`

```
t = table: a, b, c
  row: # 4, 5, 6
  row: 1, 2, 3
end
```

**Comment by blerner** [comment]
That should be a well-formedness error, no?  It's a syntactic form, so it should be trivial to check syntactically...

**Comment by belph** [comment]
It [_is_][wf] a well-formedness error, actually. The question is why it's not showing up.

[wf]: https://github.com/brownplt/pyret-lang/blob/master/src/arr/compiler/well-formed.arr#L868-L870
