### ISSUE TITLE
Tables bug

### ISSUE THREAD

**Issue by esloan** [brownplt/pyret-lang#874]
The following code causes a bug when running the code in firefox (but not when running it in chrome). Specifically, it returned `Internal errors prevented this error message from being shown. Please report this as a bug.`

import data-source as DS
import gdrive-sheets as GS
#Import ice cream data
ice-cream-ssheet = GS.load-spreadsheet("1Y1R8MgH9WeM75j2cOJ8EgubTOkFcxGa51Tko7lqIFk0")
ice-cream = load-table:
  time-period :: Number, 
  amt-consumed :: Number,
  income :: Number, 
  price :: Number, 
  temperature :: Number
  source: ice-cream-ssheet.sheet-by-name("Sheet1", true)
  sanitize time-period using DS.strict-num-sanitizer
  sanitize amt-consumed using DS.strict-num-sanitizer
  sanitize income using DS.strict-num-sanitizer
  sanitize price using DS.strict-num-sanitizer
  sanitize temperature using DS.strict-num-sanitizer
end
################################################################################
################################################################################

#Note that running the individual lines of code on their own works fine
#Extremely similar code has also produced a buggy error message:
#|

` Evaluating a expression in <builtin dummy location> errored.  `

It was expected to produce a "Number", but it produced a non-"Number" value:
false
(Hide program execution trace...)

Evaluation in progress when the error occurred (most recent first):
|#

price-list = extract price from ice-cream end
lowest-price= price-list.sort().take(7)
table = sieve ice-cream using price:
  lowest-price.member(price)
end

**Comment by blerner** [comment]
Pinging @belph for the error, and @jswrenn for the message...

**Comment by belph** [comment]
I'll look into it some more when I can, but this is almost certainly a stack safety issue. Evidence:

- Removing the `sieve` expression at the end of the program causes it to work as expected
- Pasting the `sieve` expression into the REPL after running the program without it works without error
- Replacing `lowest-price.member(price)` with `price == price` causes the program to compile and run without error

Thus, it seems that something in the following call stack is to blame:
```
?
+-> lowest-price.member(<price>)
    +-> <lam>
        +-> raw-array-filter
            +-> <desugared sieve>
```
My money is on `raw-array-filter`, personally.

**Comment by jpolitz** [comment]
Yup.  This line is wrong:

https://github.com/brownplt/pyret-lang/commit/a9e8ec3035988ad3ba50682b31b119432974bf78#diff-513890bc2bd618b462d3b814b861e024R3568

The return of the continuation is a boolean, not an array.  Looks like `raw-array-filter` is completely untested...
