### ISSUE TITLE
lists.sum() is undefined

### ISSUE THREAD

**Issue by benjaminmurphy** [brownplt/pyret-lang#875]
From the documentation, lists.sum() would seem to return the sum of the values in a list, and sum(<list>) would do the same. However, both seem to be undefined at the moment:

> lists.sum([list: 1, 2])

Evaluating this field lookup expression errored:
lists.sum([list: 1, 2])
The left side was an object that did not have a field named sum:
{nonenoneis-nonefunction:is-nonesomefunction:someis-somefunction:is-someleftfunction:leftrightfunction:rightis-Listfunction:is-Listempty[list: ]is-emptyfunction:is-emptylinkfunction:linkis-linkfunction:is-linkgetfunction:getsetfunction:setpushfunction:pushreverse-helpfunction:reverse-helpreversefunction:reversesort-byfunction:sort-bysortfunction:sortrangefunction:rangerange-byfunction:range-byrepeatfunction:repeatfilterfunction:filterappendfunction:appendpartitionfunction:partitionremovefunction:removefindfunction:findsplit-atfunction:split-attakefunction:takedropfunction:droplastfunction:lastanyfunction:anyallfunction:allall2function:all2mapfunction:mapmap2function:map2map3function:map3map4function:map4map_nfunction:map_nmap2_nfunction:map2_nmap3_nfunction:map3_nmap4_nfunction:map4_neachfunction:eacheach2function:each2each3function:each3each4function:each4each_nfunction:each_neach2_nfunction:each2_neach3_nfunction:each3_neach4_nfunction:each4_nfold-whilefunction:fold-whilefoldfunction:foldfoldlfunction:foldfoldrfunction:foldrfold2function:fold2fold3function:fold3fold4function:fold4fold_nfunction:fold_nmember-withfunction:member-withmember3function:member3memberfunction:membermember-always3function:member3member-alwaysfunction:membermember-now3function:member-now3member-nowfunction:member-nowmember-identical3function:member-identical3member-identicalfunction:member-identicalshufflefunction:shufflefilter-mapfunction:filter-mapfilter-valuesfunction:filter-valuesdistinctfunction:distinctlengthfunction:lengthjoin-strfunction:join-strlist{makefunction:raw-array-to-listmake0<function:<anonymous function>>make1<function:<anonymous function>>make2<function:<anonymous function>>make3<function:<anonymous function>>make4<function:<anonymous function>>make5<function:<anonymous function>>}}
(Show program execution trace...)

> [list: 1, 2].sum()
> Evaluating this field lookup expression errored:
> [list: 1, 2].sum()
> The left side was an object that did not have a field named sum:
> [list: 1, 2]
> 
>  sum([list: 1, 2])
> The identifier sum is unbound. It is used but not previously defined.

**Comment by sorawee** [comment]
That is now in `math` package.

```
import math as M
check:
  M.sum([list: 1, 2, 3]) is 6
end
```

**Comment by blerner** [comment]
Since this is now documented properly in www.pyret.org/docs/latest, I'm closing as fixed.
