### ISSUE TITLE
baffling error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#877]
When a user uses the name of the datatype (rather than of one of its variants) as a constructor, they're told

```
The name is being used as a value.
```

I'm not sure I could explain this error message!

**Comment by schanzer** [comment]
Seconded. Suggestion: "<name-of-datatype> is a Type of data, and cannot be used as a Value"

My bias: we use the type/value distinction in Bootstrap, and even suggest that teachers play a "type or value?" quiz game with their kids.

**Comment by jswrenn** [comment]
This error message broke the principle of referring to all relevant parts; namely, it's missing any mention of where the type name is introduced.

Thanks to the additional information that is now statically associated with modules, it's possible to refer directly to the _type_ that's being shadowed. As of 99e100ba67083c8cf00e15d539e3e6f3df97ed9a:

*Using a local type name as a value:*
<img title="Local type name used as value" alt="data Foo: foo(a) end&#13;&#13;Foo(1)" src="https://cloud.githubusercontent.com/assets/3820879/21533591/225a724a-cd2a-11e6-99ad-d399ab0f548c.png"></img>

*Using a type name from a module as a value:*
<img title="Local type name used as value" alt="List(empty)" src="https://cloud.githubusercontent.com/assets/3820879/21533597/36b3101c-cd2a-11e6-815a-7f2ca450820a.png"></img>

**Comment by schanzer** [comment]
This is now fixed on CPO. OK to close?
