### ISSUE TITLE
table header error causes cascading errors

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#880]
Suppose I write

```
  table: a :: Number
    row: "x"
    row: "y"
    row: "z"
  end
```

This halts with a single error, saying `"x"` is not a `Number`. But if I replace `Number` with `Foo`, I get one error _per row_. For a large table, this can become very annoying.

**Comment by jpolitz** [comment]
That's an "interesting" interaction between the order of desugaring and unbound identifier checking.

Definitely needs to be fixed, if only because it suggests duplication of code in table desugaring, which is to be avoided in general.

**Comment by shriram** [comment]
That's what I was worried about!

**Comment by blerner** [comment]
So this is better, now -- it gives two errors, no matter how many rows you have.  Dunno why it still has two errors instead of one, but hey, progress!

**Comment by blerner** [comment]
This seems to be fixed on CPO -- only one error message appears.  Closing.
