### ISSUE TITLE
export rows from tables?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#883]
Tables are pretty useless without some way to extract row. In particular, ordering a table does not produce a value that is useful for anything further. Can we provide an export feature at least for individual rows as a record?

**Comment by jswrenn** [comment]
This has been a feature since just about the first draft of tables, but it's apparently undocumented. This works now:
```
(table:  foo,  bar
  row:    1,    2
  row:    3,    4
  row:    5,    6
end).get-row(1)
```

**Comment by jpolitz** [comment]
The outstanding issue of course being that we lack the type language to annotate `get-row`, until we know what parts of table types can be parametric.

**Comment by schanzer** [comment]
`<Table>.row-n` now does this. Closing
