### ISSUE TITLE
`raise` vs `raises`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#884]
Student accidentally writes `raises` instead of `raise`, tries several variants, all give relatively useless parsing errors.

It would be nice if they at least got feedback saying "`raises` is a keyword, and its syntax is only valid inside checking contexts. Note that the following program _does_ produce such an error:

```
fun f(x):
  x raises 2
end
```

but if I accidentally use `raises` without the `x` — i.e., the whole line is `raises 2` or `raises(2)` — I don't get this and the error is much less helpful.

[Incidentally, the report I filed earlier that it doesn't refer to all checking block forms persists.]

**Comment by jpolitz** [comment]
@blerner, do you agree with my reasoning below?

This is the kind of thing a handwritten parser can do well that a generated one cannot.

The notion of "inside a checking context" is pretty difficult to encode reasonably in a typical parser generator's grammar specification.  You'd end up needing to duplicate a lot of productions to have the production itself "know" which context it's in.  Adding state to the actions to track this out-of-band with the parsing itself is also a little fraught, aside from not being possible with our parser infrastructure, which generates the whole parse tree first, and then processes it.

If you process the tokens "by hand," though, it's more straightforward to get the nested state right for this kind of contextual information.

**Comment by blerner** [comment]
The notion of "inside" a context isn't too bad -- yes, there's some duplication, but it's not horrid.  The hard part is coding "outside" a context, which is what matters here -- that's much trickier to do and involves a lot more duplication.

Even so, I don't think a hand-coded parser will be of much help in this sort of case.  Essentially you'd need to add heuristic logic to look for a production

bad-stmt: 'raises' [expr] | [expr] 'raises'

which overlap horribly and ambiguously with the actual testing productions.  I think the right solution is to dive into the SPPF that our parser generator creates, even on error, and walk back the productions in progress to see what the context is.  I don't think it's easy, I know I tried it once before and didn't get far, but I think it's easier/more effective than trying to craft a handwritten ambiguous recursive-descent parser by hand.

(But then again, I'm pretty dour on the possibility of recovering gracefully from parsing errors, so take that with a grain of salt.)

**Comment by jpolitz** [comment]
I was thinking the handwritten parser, when it encounters a `raises` token outside the context of a check block (which would be a boolean in the parser state), it would simply emit "bad use of raises outside of a checking context."  No special productions, no care for if there are expressions or + or - or whatever on either side of it.

Happy to hear how that's naïve :-)

**Comment by blerner** [comment]
This is closely related to https://github.com/brownplt/pyret-lang/issues/1407, which is fixed in https://github.com/brownplt/pyret-lang/pull/1460.  This specific program now gives a decent message:
![image](https://user-images.githubusercontent.com/918464/61419349-dcef2b80-a8cb-11e9-9790-cb8c17a13cec.png)

and the tweak that just says `raises 2` manages to give a decent message also:
![image](https://user-images.githubusercontent.com/918464/61419363-eed0ce80-a8cb-11e9-898f-f33ea5f4ceec.png)

(and once #1460 lands, it'll say more specifically "You may have been looking for the `raise` operator...")

Ok to close?
