### ISSUE TITLE
using plot and image

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#885]
If you include both plot and image, you get an error saying «The declaration of the identifier named Image shadows a previous declaration of an identifier also named Image». If you get rid of the import of image, you get an error saying, e.g., circle is not bound.

**Comment by jpolitz** [comment]
Thanks, this should have been fixed, and seems like a regression to me.  I'll see what's up.

**Comment by sorawee** [comment]
This is a known issue, and the fix is in my local computer. Will push it soon.

**Comment by schanzer** [comment]
Now fixed on CPO, for both `plot` and `chart`. closing.
