### ISSUE TITLE
error message verbosity

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#886]
I purposely called this function with one fewer argument than it needs. I'm really wondering whether this verbosity of message is actually an improvement over, say, the Racket version of the error.

![image](https://cloud.githubusercontent.com/assets/75030/19105597/1e853986-8ae3-11e6-8983-7f8e560df48e.png)

I especially wonder how a non-native-English-speaker would react to this many words and this complex a sentence.

**Comment by schanzer** [comment]
I thought we'd decided to drop 'applicant'?

**Comment by jswrenn** [comment]
We did. This is the error message you get when there's a Pyret bug--the error message is complaining about an arity mismatch with something internal (`<builtin Evaluating $toplevel>`), rather than the one of the user.

**Comment by jpolitz** [comment]
But... `line-plot` is just a variant constructor provided by `plot`.

The same thing happens for `link(1)`.  I don't think that's a Pyret bug – it's pretty clearly the user mis-using a function.

**Comment by jswrenn** [comment]
This is a pyret bug--the source location of the application of `line-plot` or `link` isn't `<builtin Evaluating $toplevel>`, it's `interactions://whatever`.

**Comment by shriram** [comment]
Look: this is just silly. If the function position weren't a function, I can see how a phrase like “expected the applicant to evaluate to a function” makes…some…sense. But it _is_ a function. WeScheme says “f: expects 2 arguments«…», but given 1: …”. What exactly are we arguing about here? (And what does “builtin Evaluating $toplevel” mean? (And why isn't “expected” capitalized?)

**Comment by blerner** [comment]
Closing as fixed; the current error message is clear and terse
