### ISSUE TITLE
display-multi-plot docs wrong

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#889]
http://www.pyret.org/docs//latest/plot.html says it takes three arguments. The implementation expects two.

**Comment by dlicata335** [comment]
Also, the positions that the docs say are PlotOptions and PlotWindowOptions seem to be functions 
(PlotOptions -> PlotOptions) and (PlotWindowOptions -> PlotWindowOptions) that take the default config?  At least this worked for me:

```
display-multi-plot(
  [list: function-plot(profit, lam(x): x end)], 
  lam(c): c.{x-min: 0, x-max: 5, y-min: 0, y-max: 1200} end
  )
```

**Comment by sorawee** [comment]
@dlicata335 That `PlotOptions` and `PlotWindowOptions` are functions is correct. This is explained here: https://www.pyret.org/docs/latest/plot.html#%28part._.The_.Options_.Types_and_.Default_.Values%29

The plot library is going to be updated to the chart library next week, where we have completely redesigned and improved the interface. The above program can be written as:

```
render-chart(function-plot(profit))
  .x-min(0)
  .x-max(5)
  .y-min(0)
  .y-max(1200)
  .display()
```

**Comment by jpolitz** [comment]
I wouldn't say it's going to be "update to" the chart library – that sounds like we're making a backwards-incompatible change.

Rather, the chart library will be available as a better substitute.

**Comment by dlicata335** [comment]
oops, I missed that section; thanks for the help!

**Comment by shriram** [comment]
Dan, fwiw, Oak's new chart library interfaces directly to the Google Charts
API [https://developers.google.com/chart/], so over time we will be able to
provide more and more of their widgets. While it has some quirks and bugs,
it's much better than developing our own. And we can refer any bugs to
someone else. <-;

**Comment by sorawee** [comment]
The original issue is fixed. Closing the issue.
