### ISSUE TITLE
really confusing display output

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#891]
`p` is bound to a plot value. I can't pass it to `display-line`. But if I do, I get this very confusing-looking error message:

![image](https://cloud.githubusercontent.com/assets/75030/19105980/45c14650-8ae5-11e6-86a2-c20e2ee79977.png)

I have to scroll all the way to the bottom to see the constructor, to see that the error message isn't saying "table isn't a table":

![image](https://cloud.githubusercontent.com/assets/75030/19106023/6f6b5536-8ae5-11e6-816d-ea1b3b411902.png)

**Comment by jpolitz** [comment]
This is basically the same issue as https://github.com/brownplt/code.pyret.org/issues/67, there's more discussion there.

**Comment by schanzer** [comment]
@shriram ok to close, since this is subsumed by #67?
