### ISSUE TITLE
why does display-line demand "tight" tables?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#892]
If I give `display-line` a table with columns beyond `x` and `y`, it actually reports an error. Why?

«"plot: expect the table for line-plot to have two columns: `x` and `y`"»

I mean, just select out the ones you want, right? It means to take a simulation output, I not only have to write

```
t1 = extend t using tick, state:
  x: tick,
  y: state
end
```

but _also_

```
t2 = select x, y from t1 end
```

**Comment by blerner** [comment]
FWIW, _you_ insisted on this ;-)  It's because we don't have a type describing a row-polymorphic table "containing x, y, and a bunch of other stuff".

**Comment by shriram** [comment]
CC @sorawee

**Comment by jpolitz** [comment]
Closing as working-as-intended (also the plot/chart APIs have shifted since this was reported)
