### ISSUE TITLE
examples blocks break auto-indentation

### ISSUE THREAD

**Issue by tchin** [brownplt/pyret-lang#893]
If I have any examples blocks in my code, then autoindentation will only fix lines above the examples block and will left-justify everything below it.

**Comment by jpolitz** [comment]
Thanks for reporting!  Can you copy/paste a program that's showing the bad behavior here for us to try?

**Comment by tchin** [comment]
```
provide *

fun len(l :: List) -> Number:
  cases(List) l:
    | empty => 0
    | link(_,r) => 1 + len(r)
  end
where:
  len(empty) is 0
  len([list: 1, 2 ,3]) is 3
end

examples:
len([list: 1]) is 1
end

fun add1(n :: Number) -> Number:
n + 1
where:
add1(1) is 2
end
```

It seems like the problem might have something to do with the combination of provide and examples. The indentation works fine when I take out either of those.

**Comment by jpolitz** [comment]
Thanks!  That is an incredibly helpful report – I see the same thing.  If I change `examples:` to `check:`, the problem also goes away.  I think that should be enough for us to diagnose.

For now, changing `examples:` to `check:` might make your program look a bit nicer while we get this fixed up.

**Comment by belph** [comment]
@blerner I can't investigate too much right this moment, but [this line][cm] would seem to imply that this means the the CM line state is non-empty at the time we see `examples:`. It [also looks like][prov] we are pushing `PROVIDE` onto the stack and leaving it there, which may help explain the behavior (like I said, though, I haven't looked too deeply yet).

[cm]: https://github.com/brownplt/code.pyret.org/blob/00f9541ed18ecba26fdfa8523ddceb1994129383/src/web/js/codemirror/pyret-mode.js#L642
[prov]: https://github.com/brownplt/code.pyret.org/blob/00f9541ed18ecba26fdfa8523ddceb1994129383/src/web/js/codemirror/pyret-mode.js#L606

**Comment by blerner** [comment]
The first line isn't the problem, because the previous if clause handles `examples` with non-empty line states.  The problem does seem to be that lingering PROVIDE -- not sure why that is happening.  I think support for `examples` just was never finished.  It's not present in the emacs mode, and the equivalent program using a `check` block indents properly, so the lingering PROVIDE is getting cleared away somehow -- maybe line 815?  When you get a chance, could you fix both modes? ;-)

**Comment by belph** [comment]
I'll take a look into it this weekend.

**Comment by belph** [comment]
Issue is now fixed and should be reflected upon the next deploy of code.pyret.org.
