### ISSUE TITLE
bar-chart appears to return anonymous function

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#894]
```
include plot

import image-structs as I


x = bar-chart(
    table: label, value
      row: 'A', 11
      row: 'B', 1
      row: 'C', 3
      row: 'D', 4
      row: 'E', 9
      row: 'F', 3
    end, 'Letter', _,{
      title: 'Frequency of letters'
    })
```

```
> x
<function:<anonymous function>>
```

<img width="1273" alt="screen shot 2016-10-05 at 5 27 07 pm" src="https://cloud.githubusercontent.com/assets/119891/19132330/fc904350-8b20-11e6-84f5-23296710b72b.png">

**Comment by jpolitz** [comment]
Hah.  See the typo in the parameter list!

**Comment by jpolitz** [comment]
(`_` and this manner of indicating options considered harmful)

**Comment by blerner** [comment]
Shouldn't this have thrown an arity error then?

**Comment by sorawee** [comment]
If we have a syntax to extend an object with another object, then we can get rid of this funny options. I don't like it too, but it's the shortest way to do provide optional data.

@blerner well, it desugared to `lam(v): bar-chart(a-table, 'Letter', v, an-object) end`, so I think that there is expected. The type checker would be able to catch this though.

**Comment by blerner** [comment]
Ewwwwwwwwww. That's super unfortunate. I didn't even think of underscore-functions here. Underscore function syntax... may need improvement. :-(
