### ISSUE TITLE
Issues with set-to-list comparison

### ISSUE THREAD

**Issue by les-bres** [brownplt/pyret-lang#895]
Comparing these two lists using list-to-set using the following code outputs true, even though they are in fact different lists (The second one has an extra nested list for the first element).  However, when comparing in the exact same lists in the opposite order, the comparison output is false (correct).  I was not able to recreate this error with any simpler code because removing any of the other elements (the equal ones that appear in both lists) changed the output to false. 

`list-to-set([list: 

 &nbsp;&nbsp;[list: "top","mid-a"],

 &nbsp;&nbsp;[list: "top","mid-b","low-b-a"],

 &nbsp;&nbsp;[list: "top","mid-b"]]) == 

list-to-set([list: 

&nbsp;&nbsp;[list: [list: "top","mid-a"]],

&nbsp;&nbsp;[list: "top","mid-b"],

&nbsp;&nbsp;[list: "top","mid-b","low-b-a"]])`

**Comment by jpolitz** [comment]
Thanks!  I'm close to figuring this out, just want to document what's going on.

Something is generating a bogus equality callback in the equality algorithm.  The implementation of equality in sets is fine, it's just that the recursive equality callback is reporting true for things it shouldn't.

Here's an example for posterity of how to illustrate this issue:

https://code.pyret.org/editor#share=0B32bNEogmncOcDNUNFFuYkkzWmc&v=07a51eb

**Comment by jpolitz** [comment]
This is fixed now, thanks for reporting!
