### ISSUE TITLE
Cyclic equality cache does not respect paths

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#896]
The cyclic equality cache should not have algorithm-global state, it should have stacks of state.  If the same pair of (`===`) objects is checked once, regardless of success or failure, it is added to the cache and _stays in the cache_ for future comparisons.

For example, this program prints NotEqual and then Equal:

```
o = {
  method _equals(self, other, eq) block:
    v1 = {}
    v2 = {x:"a"}
    print(eq(v1, v2))
    print(eq(v1, v2))
    eq(1, 1)
  end
}
o == {}
```

**Comment by blerner** [comment]
Not sure I completely agree -- in the pathological cases, making this be a path-sensitive stack-like cache could take a linear-time comparison and make it exponential:
```
a = {}
b = {left: a, right: a}
c = {left: b, right: b}
...
z = {left: y, right: y}

z == z
```
If we don't memoize the objects on paths, this will end badly.

I think the better solution is to make the cache be

```js
      var cache = {left: [], right: [], equal: []};
      function findPair(obj1, obj2) {
        for (var i = 0; i < cache.left.length; i++) {
          if (cache.left[i] === obj1 && cache.right[i] === obj2)
            return cache.equal[i];
        }
        return NotEqual;
      }
```
and then update the uses of the cache in the algorithm: when we `cachePair`, we _presume_ that the two values are going to be equal, and then see if that stays consistent.  All we need to do is say `cachePair(x, y, true)`, and then on every `return` from the algorithm, we update `cachePair(x, y, ans);` before `return ans;`

**Comment by jpolitz** [comment]
Yeah, aside from minor quibbles about side-effects in `_equals` functions that may show up unexpectedly few times (and I think we should ignore these quibbles), I agree with this.

**Comment by blerner** [comment]
Agreed -- `_equals` ought to be a _function_, mapping the same inputs to the same outputs every time; if you screw around with side effects, on your own head be it... ;-)

**Comment by jpolitz** [comment]
This had a serious (negative) impact on performance.  For example, compiling ast.arr on my laptop went from 30-ish seconds to 38-ish (lots of trials).  Several other programs are noticeably slower as well.

Is there a better way to do this?  Is all of the extra necessary?

There are two cases the commit above handles:

1. When a _nested_ value is determined to be false, we need to set not-equal for everything that's currently on the stack.  For example, for two lists containing unequal objects:

```
l1 = [list: { x: "a" }]
l2 = [list: { x: "b" }]
rec-eq({o: l1}, {o: l2})
rec-eq(l1, l2)
```

we need to make sure that the cache is cleared for the two lists, even though they weren't the values passed to rec-eq, and were just on the stack.

2. When a value is visited, has its elements pushed on to the stack, and then one of them is found to be  unknown, and then the algorithm continues, it can't be left true:

```
o1 = { x: lam(): nothing end }
o2 = { x: lam(): nothing end }
rec-eq({ o: o1, y: 10 }, { o: o2, y: 10 })
rec-eq(o1, o2)
```

This is different than the nested case, because nothing about the `o` field is on the stack when the algorithm moves on to comparing `y`.  So the algorithm needs to have an extra stack frame to pop off when it moves on to indicate that the answer has been reached.

This is the reason for pushing extra information onto the stack, and processing it in two different places (the top of the equality loop, and on return from the function).

**Comment by blerner** [comment]
Possibility: instead of pushing `setCache: true`, could you push `setCache: the-index-where-it-was-pushed`, and have `cachePair` return the index where it was pushed?  Then the `setCachePair` won't have to do a linear search every time...?

**Comment by jpolitz** [comment]
Yep, that was a good idea.  I also realized that the `setCachePair` on `left` and `right` is covered by the other two cases (it either stays on the stack and is hit by the for loop, or it is popped off the stack in the loop).  That brings it down to a difference that I can't measure.

**Comment by blerner** [comment]
@jpolitz close as horizon-fixed?

**Comment by blerner** [comment]
ping?

**Comment by blerner** [comment]
I think this is fixed -- the initial example now works, and my example runs in reasonable time (linear rather than exponential).
