### ISSUE TITLE
Bad source location in function application errors.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#899]
(Stealing @shriram's [comment](https://github.com/brownplt/pyret-lang/issues/198#issuecomment-252253577) for another bug report:)

For example, this program

```
data Foo:
  | foo(x, y)
end

foo(1)
```

reports an incorrect application source location (`builtin("Evaluating $toplevel")`):

![image](https://cloud.githubusercontent.com/assets/75030/19191661/b3e717a8-8ca3-11e6-8064-784f6d9106a6.png)

**Comment by belph** [comment]
Did some rough tracing of this, and here's what I found (bear in mind that I'm not too familiar with this part of the compiler, so I may be way off):

[This line][embed-make] creates an `ED.embed` out of the constructor's arity, which should be fine, given the signature of [its constructor][embed-def]. However, the renderer [calls exn-unwrap][renderer] on the arity, which causes [this line][err] to fail.

[embed-make]: https://github.com/brownplt/pyret-lang/blob/d458af1c07ec910e966d9ed3c7758138e54b6bba/src/arr/trove/error.arr#L1350
[embed-def]: https://github.com/brownplt/pyret-lang/blob/master/src/arr/trove/error-display.arr#L13
[renderer]: https://github.com/brownplt/pyret-lang/blob/master/src/arr/trove/render-error-display.arr#L31
[err]: https://github.com/brownplt/pyret-lang/blob/43e8049bdd40a2336fe4bd4a38ff618dbb941345/src/js/base/runtime.js#L3434

**Comment by jswrenn** [comment]
f2f9cff394b007107d1b179aa74d21cced2e5b64 fixes this issue and, from a user's perspective, fixes #886.

**Comment by blerner** [comment]
@jswrenn There's something weird here: with this exact example, the arguments (purple) don't get highlighted, even when I click on it...:
![image](https://user-images.githubusercontent.com/918464/27258366-98533c34-53c6-11e7-8c8f-da0939ca9903.png)

**Comment by shriram** [comment]
Yeah, I see this too. Whereas if you write `foo` as a _function_ there's no problem. Maybe that offers a hint as to what's going on.

**Comment by blerner** [comment]
That's mostly a red herring (I think it's running the same code paths, for the most part, but there are some cases expressions that might be doing some funky things based on ast types).

**Comment by jswrenn** [comment]
@blerner: An explanation of why the constructor arguments are not highlighted:

For arity mismatch errors, we have a source location corresponding to the entire extent of the definition. When the definition site is a _function_, we can then reparse the corresponding fragment of the program to get back the source locations of the parameters. When the definition site is a _method_ or _constructor_, this is not possible—the syntax for a method or constructor isn't valid at the top-level of a Pyret program. I can think of a few ways to overcome this shortcoming:
 - extend JGLR to support performing a parse with some previously stated 'context'; e.g., tell JGLR to parse `| foo(a, b)` not as a `program`, but as a `data-variant`
 - replicate the grammar rules these sorts of fragments into their own files, and generate a parser specifically for this use case
 - just reparse the whole file that contains the problematic method/constructor definition, and walk the AST until the node matching the definition srcloc is found.

The first strategy is beyond my expertise. The third strategy seems too expensive. The second strategy might work, but that sort of code duplication is obviously not ideal (and the generated javascript parsers are fairly big).

**Comment by blerner** [comment]
Options 1&2 aren't feasible, and 3 is too expensive. But a variant declaration is equivalent to a function header, except for the potential for ref fields. So take the source of the declaration, replace "ref " with "ref_" to keep the relative source positions correct, and surround the thing with "fun " and ": end", which can then easily be parsed, and the source locations post-processed to correct them.

Or, don't highlight "2 parameters" in purple and make it look like all the others, when it doesn't in fact work.

**Comment by shriram** [comment]
And if you _know_ that it's a parameter, maybe you can give a more useful error that says something expressly about a constructor (sans highlighting, per Ben's most recent message).

**Comment by blerner** [comment]
@jswrenn This isn't quite horizon-fixed, since the purple highlighting still exists.
