### ISSUE TITLE
math.arg-max does not return index of largest number in list of numbers

### ISSUE THREAD

**Issue by bleirdalag** [brownplt/pyret-lang#907]
code:

```
import math as m

l = [list: 0, 1, 2, 3]
l.get(m.arg-max(l)) == m.max(l)
```

seen output: false

expected output: true

**Comment by jpolitz** [comment]
Sorry about that, we know about this and I'll push out the fix shortly, I'll post here when it is up.

**Comment by jpolitz** [comment]
Sorry this took a few extra days – releasing on Friday turned out to be broken due to the widespread DNS outages on the east coast.
