### ISSUE TITLE
type-inference considered unusable

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#914]
Below is a 69-line program.

Running it consistently takes about three seconds. (That's really long, but it's at least usable.)

Type-checking it consistently takes over 38 seconds. (That's 38 seconds on second and third runs; the first one, without a warm cache, is longer!)

That's a 35-second type-checking overhead over 69 lines (of which about half are some combination of blank, `end`, `check`, etc.). So, about a second a line.

I was curious whether adding return type annotations (there are none below) would make a difference, so I added them everywhere. No difference. I added annotations on the `rec` lines. Also no difference.

I commented out the three `check` blocks. Now we were down to 8-12 seconds. That's a LOT better. I mean, not usable (at least 5-6 seconds to type-check about 45 lines of code), but almost usable in a small class demo.

I went back and removed all the `rec` and return type annotations. Still 9-11 seconds. So that's still not the source of the problem.

@mkolosick, I don't see any possibility of writing any papers about inference when it's literally impossible to use on even trivial programs.

```
data Stream<T>:
  | lz-link(h :: T, t :: ( -> Stream<T>))
end

fun lz-first<T>(s :: Stream<T>):
  cases (Stream) s:
    | lz-link(h, t) => h
  end
end

fun lz-rest<T>(s :: Stream<T>):
  cases (Stream) s:
    | lz-link(h, t) => t()
  end
end

rec ones = lz-link(1, {(): ones})

fun nats-from(n :: Number):
  lz-link(n, {(): nats-from(n + 1)})
end
nats = nats-from(0)

fun take<T>(n :: Number, s :: Stream<T>):
  ask:
    | n == 0 then: empty
    | n > 0  then:
      link(lz-first(s), take(n - 1, lz-rest(s)))
  end
end

check:
  take(5, ones) is [list: 1, 1, 1, 1, 1]
  take(5, ones) is map({(_): 1}, range(0, 5))
  take(5, nats) is [list: 0, 1, 2, 3, 4]
end

fun lz-map<A, B>(f :: (A -> B), s :: Stream<A>):
  lz-link(
    f(lz-first(s)),
    {(): lz-map(f, lz-rest(s))})
end

fun lz-map2<A, B, C>(
    f :: (A, B -> C), 
    s1 :: Stream<A>,
    s2 :: Stream<B>):
  lz-link(
    f(lz-first(s1), lz-first(s2)),
    {(): lz-map2(f, lz-rest(s1), lz-rest(s2))})
end

check:
  twos = lz-map({(n): n + 1}, ones)
  nat-1 = lz-map({(n): n + 1}, nats)
  take(5, twos) is [list: 2, 2, 2, 2, 2]
  take(5, nat-1) is [list: 1, 2, 3, 4, 5]
end

rec fibs =
  lz-link(0,
    {(): lz-link(1,
          {(): lz-map2({(a :: Number, b :: Number): a + b},
                fibs,
            lz-rest(fibs))})})

check:
  take(10, fibs) is [list: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
end
```

**Comment by shriram** [comment]
PS: Note that this program _needs no inference_: everything is already fully annotated. Therefore, it is especially unconscionable for inference to be taking so long, since it doesn't need to run at all.

**Comment by mkolosick** [comment]
This is an old issue that was fixed, but the fix was then reverted. Our `string-dict` implementation was very inefficient, so I adapted Facebook's immutable-js implementation (based on a HAMT). However, it was not merged into master. Running a test now on my computer it took type-checking this file from taking about 25 seconds to just under 1 second.

@blerner @jpolitz, can I merge in the optimized string dictionary?

**Comment by blerner** [comment]
Yes, fine by me

**Comment by jpolitz** [comment]
Yeah.  Actually, if you want to try it, there's a module called `str-dict` that is the immuable-js version, so we could just switch over the TC if there are any concerns.  @sarahkf made it be tuple-ified in the constructor, and uses the immutable-js implementation.  This runs on current CPO, for example:

```
import str-dict as S

s = [S.string-dict: {"a"; 1}]
```

**Comment by mkolosick** [comment]
Changing over to the tuple-ified version would be a relatively large quantity of work. I have a drop-in replacement ready to go, and I can open a pull request in the morning if we feel comfortable using it. It was the implementation on horizon for awhile and is tested by large swathes of the compiler and compiler test code. I'll open a pull request in the morning for that one and if there are any concerns I can try switching to the tuple-ified version instead?

**Comment by jpolitz** [comment]
Yeah, do the drop-in, I didn't mean to make work.  I forgot how many string-dict literals there were in type-defaults, and thought it would be easier.

**Comment by shriram** [comment]
WOW. Can we also make this the default for Pyret in general, then?!?

**Comment by shriram** [comment]
Does it make sense for Dorai to think about doing this integration instead,
replacing his string-dict with this one? And maybe seeing what other data
structures we can pilfer from immutable-js?

«

Immutable.js provides many Persistent Immutable data structures including:
List <https://facebook.github.io/immutable-js/docs/#/List>, Stack
<https://facebook.github.io/immutable-js/docs/#/Stack>, Map
<https://facebook.github.io/immutable-js/docs/#/Map>,OrderedMap
<https://facebook.github.io/immutable-js/docs/#/OrderedMap>, Set
<https://facebook.github.io/immutable-js/docs/#/Set>, OrderedSet
<https://facebook.github.io/immutable-js/docs/#/OrderedSet> and Record
<https://facebook.github.io/immutable-js/docs/#/Record>.

These data structures are highly efficient on modern JavaScript VMs by
using structural sharing viahash maps tries
<http://en.wikipedia.org/wiki/Hash_array_mapped_trie> and vector tries
<http://hypirion.com/musings/understanding-persistent-vector-pt-1> as
popularized by Clojure and Scala, minimizing the need to copy or cache data.

Immutable also provides a lazy Seq
<https://facebook.github.io/immutable-js/docs/#/Seq>, allowing efficient
chaining of collection methods like map andfilter without creating
intermediate representations. Create some Seq
<https://facebook.github.io/immutable-js/docs/#/Seq> with Range
<https://facebook.github.io/immutable-js/docs/#/Range> and Repeat
<https://facebook.github.io/immutable-js/docs/#/Repeat>.
»

**Comment by mkolosick** [comment]
It probably makes sense for @ds26gte to actually do this. My version was put together quickly, apparently has some rough edges, and should probably be rewritten.

I don't have the exact numbers anymore, but the runtime of the type checker is currently dominated by checking if the object iterator is at the final object in the prototype chain. This is because the current string-dict is essentially a linked list of key-value pairs.

**Comment by shriram** [comment]
I'm fine with having a local copy of this for the type checker, and
@ds26gte working on integrating the library into the language as a whole,
then you can migrate to calling his version instead. Let's get the type
checker working quickly for now.

**Comment by ds26gte** [comment]
Sorry I didn't see this thread. Yes, I can do this.

**Comment by mkolosick** [comment]
This is fixed in [commit eb335a27](https://github.com/brownplt/pyret-lang/commit/eb335a27471d9e7d282b698cd44cd1ce9238b4ab). 

Additionally, to fix another issue, polymorphic types (for now) need their return types annotated.

**Comment by mkolosick** [comment]
@shriram, this should be fixed now if you want to confirm. The other necessary change was requiring return type annotations on polymorphic functions. So the code should now be. 

```
data Stream<T>:
  | lz-link(h :: T, t :: ( -> Stream<T>))
end

fun lz-first<T>(s :: Stream<T>) -> T:
  cases (Stream) s:
    | lz-link(h, t) => h
  end
end

fun lz-rest<T>(s :: Stream<T>) -> Stream<T>:
  cases (Stream) s:
    | lz-link(h, t) => t()
  end
end

rec ones = lz-link(1, {(): ones})

fun nats-from(n :: Number):
  lz-link(n, {(): nats-from(n + 1)})
end
nats = nats-from(0)

fun take<T>(n :: Number, s :: Stream<T>) -> List<T>:
  ask:
    | n == 0 then: empty
    | n > 0  then:
      link(lz-first(s), take(n - 1, lz-rest(s)))
  end
end

check:
  take(5, ones) is [list: 1, 1, 1, 1, 1]
  take(5, ones) is map({(_): 1}, range(0, 5))
  take(5, nats) is [list: 0, 1, 2, 3, 4]
end

fun lz-map<A, B>(f :: (A -> B), s :: Stream<A>) -> Stream<B>:
  lz-link(
    f(lz-first(s)),
    {(): lz-map(f, lz-rest(s))})
end

fun lz-map2<A, B, C>(
    f :: (A, B -> C), 
    s1 :: Stream<A>,
    s2 :: Stream<B>) -> Stream<C>:
  lz-link(
    f(lz-first(s1), lz-first(s2)),
    {(): lz-map2(f, lz-rest(s1), lz-rest(s2))})
end

check:
  twos = lz-map({(n): n + 1}, ones)
  nat-1 = lz-map({(n): n + 1}, nats)
  take(5, twos) is [list: 2, 2, 2, 2, 2]
  take(5, nat-1) is [list: 1, 2, 3, 4, 5]
end

rec fibs =
  lz-link(0,
    {(): lz-link(1,
          {(): lz-map2({(a :: Number, b :: Number): a + b},
                fibs,
            lz-rest(fibs))})})

check:
  take(10, fibs) is [list: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
end
```

Let me know if that doesn't run in a reasonable time for you.

**Comment by mkolosick** [comment]
A quick note: the desugaring of check blocks results in a huge block of code. This is why removing the check blocks sped up type checking, not due to slowness of the test inference algorithm.

**Comment by shriram** [comment]
>
> A quick note: the desugaring of check blocks results in a huge block of
> code. This is why removing the check blocks sped up type checking, not due
> to slowness of the test inference algorithm.
>
Interesting!!!

**Comment by jpolitz** [comment]
The test block comment is also relevant for flatness analysis, since the LHS and RHS of each test is thunked, but many of them contain only a tail call or only a value or only a call to a bunch of constructors.  With good flatness analysis, these can generate dramatically less code for each testing statement.

**Comment by blerner** [comment]
@shriram is this still an issue for you?

**Comment by blerner** [comment]
@shriram ping?

**Comment by shriram** [comment]
This is great now.
