### ISSUE TITLE
Pyret throws an error that it said to report

### ISSUE THREAD

**Issue by jleiken** [brownplt/pyret-lang#918]
Full error:

```
Evaluating a field lookup expression in <builtin runtime> errored.

does not have a field named result-after-checks1

Please report this as a bug.

(Hide program execution trace...)
Evaluation in progress when the error occurred (most recent first):
```

I was evaluating multiple expressions in a check block, my code also accesses another pyret file.

**Comment by jpolitz** [comment]
Thanks for reporting!  I have an idea what happened.

Did you put multiple check blocks in subsequent entries in the REPL/interactions area?  (This should work, just checking if it's the cause I've identified.)

**Comment by jleiken** [comment]
No, I had multiple expressions in one block in the document editing area.
When I broke the expressions out into multiple check blocks the error
persisted.

**Comment by jpolitz** [comment]
Can you share a Publish link to it (if it's assignment code you don't want to post publicly, you can send to joe.politz@gmail.com)?

Thanks!

**Comment by jleiken** [comment]
I talked to a TA of the course I'm writing it for and they said that it
shouldn't be working anyway. So I don't think it's a problem on your side,
sorry for the false alarm. If you still want to take a look at it, the URL
is https://code.pyret.org/editor#program=0B5P0X9pIBILsSUtwTEVXUm91MHM

**Comment by jswrenn** [comment]
That link only works for you. Can you click 'Publish' and 'Share a new copy', and post that link here? 

A message complaining about variables you didn't declare is definitely a problem on our end!

**Comment by jleiken** [comment]
OK, sorry about that. Here you go!
https://code.pyret.org/editor#share=0B5P0X9pIBILsQXgxTm53cFNkLUk&v=08d40a4

**Comment by jswrenn** [comment]
I'm not receiving any errors when I run that code. 

(However, I do receive a funky type-checking error if I try to type-check it, @mkolosick.)

**Comment by blerner** [comment]
Close as not reproducible?

**Comment by jleiken** [comment]
Yes, please close it
		

		
	





On Sun, Apr 2, 2017 at 1:57 PM -0400, "Ben Lerner" <notifications@github.com> wrote:












Close as not reproducible?
