### ISSUE TITLE
Median function does not work on even-numbered lists

### ISSUE THREAD

**Issue by les-bres** [brownplt/pyret-lang#921]
When you use the built-in median function from statistics, it does not perform any averaging given an even-numbered list.  For example:
`median([list: 1, 2, 3, 4])`
outputs 3 rather than 2.5

**Comment by schanzer** [comment]
Now that this is merged, can we close the issue?

**Comment by schanzer** [comment]
pinging @SDooman

**Comment by schanzer** [comment]
Now it's also fixed on CPO. Close?

**Comment by schanzer** [comment]
Now also fixed on CPO. OK to close?
