### ISSUE TITLE
test error report perversely hides text

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#923]
When you have a failing test error and click on the report to open it up, for reasons I cannot fathom there is an light opaque layer over the error report, mousing over it produces some weird flashing behavior, and until you click on it, it isn't made completely readable.

I've complained about this in person to @jswrenn and I understood him to say he'd fix it, but it doesn't seem to have changed.

I see no reason for this behavior. The flashing animation feels especially perverse, like the environment is taunting me about what I can't read until I click.

**Comment by jswrenn** [comment]
This was fixed by brownplt/code.pyret.org@4606a3c4a318e4140064d2ca1e64f312b6525d2f, but hasn't made it to release yet.

> [...] mousing over it produces some weird flashing behavior [...] 
> The flashing animation feels especially perverse, like the environment is taunting me about what I can't read until I click.

You previously argued that the animation was effective enough that we could remove 'Highlight This!' button. If you now feel that it makes the user feel taunted, we need to revisit this interface.

**Comment by shriram** [comment]
I'd be interested in seeing any remark I've ever made in favor of that
animation, which to me has always been exhibit number 1 in "time spent
poorly".

**Comment by jswrenn** [comment]
In the May 6 bootstrap meeting, Emmanuel said he thought that the animation alone was more than enough to invite the user to click on error messages, and that the "Highlight This!" text should be removed. You agreed, but it completely slipped my mind to follow through on this (the next month was spent dealing with stack safety issues), until _you_ reminded me (resulting in brownplt/code.pyret.org@5e5ad92013a9bcc0a5e6136b13f7bc3c4590af10). I don't recall if you've ever said anything favorable about the animation, but I am surprised you did not raise your concerns in either of those meetings.

**Comment by shriram** [comment]
I expressed my unhappiness in person over the summer. I can certainly
understand that this may not have been stated clearly enough for you to
note. I am annoyed that this was put in without any discussion in the first
place.

**Comment by jpolitz** [comment]
The fix works for dynamic errors, but static errors (like an unbound id) still require clicking, on current horizon.

**Comment by jswrenn** [comment]
Ah, thanks. The heuristic _should_ be this: if there is a single error in your program, it is safe to assume that you will proceed by immediately fixing that error. Accordingly, when Pyret finds one error, it highlights it immediately. When Pyret encounters multiple errors (e.g., multiple well-formedness errors or multiple test failures), it should not presume the order in which you want to deal with them.

So the _actual_ heuristic being used now is weaker: multiple top-level error situations will always be well-formedness errors, so we don't auto-highlight on those. However, if there is only _one_ well-formedness error (as there very well might be), it _should_ be automatically highlighted.

**Comment by schanzer** [comment]
@shriram a lot has changed in the error reporting since 2016. Where do you stand on the current behavior?
