### ISSUE TITLE
Poor error message: non-mutable field

### ISSUE THREAD

**Issue by justinpombrio** [brownplt/pyret-lang#925]
The error message for this program:

```
data Thing: | thing(stuff) end
t = thing("stuff")
t!{stuff: "more stuff"}
```

says "The [field] is not a reference in the [object]".

This is a poor message. "Reference" is an overloaded term, and it's not clear what it means. Instead, the message should say something about mutability. Maybe using the phrase "cannot be changed".

**Comment by jswrenn** [comment]
The message now reads "The [field] is not a mutable reference in the [object]:".

**Comment by schanzer** [comment]
@justinpombrio , is @jswrenn 's change to your satisfaction?

**Comment by justinpombrio** [comment]
The error message accurately reflects Pyret's behavior, so yes, all set.

*Separately*, I still think Pyret's behavior around `ref` is confusing, but
Jack says there's already a bug report for this.

Pyret has things called "references" that are like mutable boxes, but can
only be created inside of a `data`, and give confusing error messages if
you look them up with "." (thus obtaining the reference, which prints out
like a value but isn't), instead of looking them up with "!", which returns
the current value.

    data Thing: | thing(ref stuff) end
    t = thing("stuff")
    x = t.stuff
    print(x + "ok") # Gives a confusing error message, because the
reference is printed like a value

**Comment by schanzer** [comment]
Okay - as long as this other bug has its own issue, I'm going to close this.

**Comment by shriram** [comment]
Also: I think as we develop the terminology and notional machine for
stateful Pyret, we're almost certainly going to want to keep the term
“reference” handy. At that point, having `ref` as a keyword for “mutable”
would no longer be tenable. We'd have to change that.
