### ISSUE TITLE
What is going on? This is the most unhelpful error message ever!

### ISSUE THREAD

**Issue by Solomonz** [brownplt/pyret-lang#926]
![image](https://cloud.githubusercontent.com/assets/8081782/19820505/b454665c-9d27-11e6-9a78-538a2830a8a2.png)

The line that's causing the error is line 62. I commented out line 55, which is pretty much identical, because it was giving me a weird error too:

![image](https://cloud.githubusercontent.com/assets/8081782/19820573/eea5da34-9d27-11e6-9afa-1f9adb464d66.png)

Please help! I have no idea what to do!

**Comment by Solomonz** [comment]
oh also look at this! it must be something in the type signature??
![image](https://cloud.githubusercontent.com/assets/8081782/19820714/8e936f7a-9d28-11e6-9aed-d30e33b36178.png)

**Comment by jpolitz** [comment]
Which oracle-support import is at the top of the file?

**Comment by awstlaur** [comment]
Hi @Solomonz,

Could you try using this one instead?
```
include shared-gdrive("oracle-support.arr", "0Bz8lcSxx1xz6QXB4ckxhMEhCbXM")`
```

**Comment by jpolitz** [comment]
Use this one:

```
include shared-gdrive("oracle-support.arr", "0B15X1zsBYb5jYXgzcnNZTGJvaG8")
```

the bug is the same as this one, which will be fixed soon:

https://github.com/brownplt/code.pyret.org/issues/145

Sorry that happened – the support file didn't provide the types.

**Comment by awstlaur** [comment]
@jpolitz We posted at the same type! The cs19 ta staff is encouraging the one I posted, not that one.

**Comment by jpolitz** [comment]
Updated my comment to use yours.

**Comment by jpolitz** [comment]
This was bad module provide/import stuff fixed by the `better-exports` merge.

**Comment by schanzer** [comment]
Has this been merged to CPO?

**Comment by blerner** [comment]
I think it has; @jpolitz ok to close this?
