### ISSUE TITLE
import and include mismatch?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#927]
The `s-exp` library documentation says there's a function called `read-s-exp`. If I `include s-exp`, there's no `read-s-exp` function defined. But if I `import s-exp as S`, there is a `S.read-s-exp`. I can't make any sense out of this.

**Comment by jpolitz** [comment]
Looks like it's missing static metadata, so include can't find any bindings
for it, even though the members are available dynamically. Will fix.

**Comment by schanzer** [comment]
@shriram `read-s-exp` is now defined via `include`. OK to close?

**Comment by blerner** [comment]
It's fixed
