### ISSUE TITLE
Shadowing an auto-generated predicate.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#934]
![data Foo:   
  | foo
  | is-foo
end](https://cloud.githubusercontent.com/assets/3820879/19981873/14e97442-a1da-11e6-9a08-ae83e4dfe5b5.png)

The standard shadowed-identifier error message doesn't cut it for situations when the identifier being shadowed was generated by a desugaring. I suggest we introduce an additional well-formedness for this case. Does that seem like a good idea?

**Comment by jpolitz** [comment]
For this case, sure.  But the same underlying problem will result from

```
data Foo:
  | foo
end

fun f(is-foo):
  ...
end
```

So I think the general solution needs to be aware that a generated name is being shadowed.

**Comment by blerner** [comment]
ISTM that the error message would be greatly improved by two additional bits of information, saying whether the name-being-shadowed was a generated name, and whether the name-doing-the-shadowing was generated (e.g. as might occur just by swapping the two lines in the original example above).  Which information, of course, we don't currently have...but it might be something we could generate...

**Comment by blerner** [comment]
The original error is fixed by https://github.com/brownplt/pyret-lang/commit/2ce6b44ee893d852cb4c4018e2f46d0b53d71b58.  Joe's additional one is not handled yet.

**Comment by blerner** [comment]
@jswrenn a variation on Joe's example above yields a very wide srcloc:
```
data Foo:
  | foo with:
    method something(self): ... end
end

fun f(is-foo):
  3
end
```
complains about `is-foo` being defined in function `f` (which is fine), but also the entirety of text on lines 2 and 3 (from the `|` to the `end`).  I thought I'd figured out where the location was coming from (resolve-scope, around line 243--246), but changing that to use the `constr-loc` field of `v` (when available; it could be a `s-singleton-variant`) didn't seem to help at all.  Could you help me pinpoint why I'm not getting a tighter srcloc here?  At least that much should be feasible...

@jpolitz I don't know how to get this right, in the general case.  Do I add a flag to `s-bind` of type `Option<Srcloc>` that's none if it's a normal name, and some location if it was generated from something else?  If so, how to propagate that?  It needs to flow across modules, and it needs to make its way into the `value-bind` environment somehow, I think?  Ultimately it has to wind up in resolve-scope, line 552, which is the one and only place that `shadow-id` errors get raised...

**Comment by jpolitz** [comment]
Probably the right thing to do is to either:

- Have more variants of `s-bind` that track information about synthetic
bindings, since really the error message here should refer to the fact that
`is-foo` is generated from the data definition; no granularity of source
location is going to explain this as well as talking about data definitions
will.
- Add a field to `s-bind` that tracks this information

As far as doing this across modules, I don't quite get it.  Do you want to
refer to source locations in another module in the error message for
shadowing?  That seems like a more general problem than anything
auto-generated, since we already don't propagate any source information
across module boundaries.

**Comment by blerner** [comment]
This appears to be long-since fixed:
![image](https://github.com/brownplt/pyret-lang/assets/918464/e191ae01-9330-43bf-bf51-ee85b2bd2da6)
![image](https://github.com/brownplt/pyret-lang/assets/918464/11543ba6-2619-4ce2-9927-a271df8cd65c)

**Comment by blerner** [comment]
(The follow-up errors are not quite fixed; let's see if they ever matter in practice, though, since we haven't touched this issue in 7+ years...)
