### ISSUE TITLE
killing CPO tab on Brave browser does not result in warning

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#938]
When I kill a CPO tab on Chrome, I get a prompt asking me whether I'm sure. On Brave, the tab closes without any warning. [NB: This could be a bug on Brave.] This is on macOS.

**Comment by jswrenn** [comment]
This is probably related to brave/browser-laptop#4079, which was recently marked as fixed.

**Comment by schanzer** [comment]
Current version of Brave on macOS raises the warning. Closing.
