### ISSUE TITLE
`unbound-id` errors are unhelpful if error spans files.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#940]
This is an `unbound-id` error:
![unbound-id_unhelpful](https://cloud.githubusercontent.com/assets/3820879/20496436/21cbd75a-aff3-11e6-9d27-7fa8d9b3fce0.png)
It works perfectly fine if the unbound identifier is in the same file that is being run, but is unhelpful if the unbound identifier is in a different file.

**Comment by jswrenn** [comment]
This bug is fixed by c04039a9dd18b6cd71b56ed28230728df867f78f, which introduces a code snippet into the message:
![unbound-id](https://cloud.githubusercontent.com/assets/3820879/20496482/5df57556-aff3-11e6-90b2-ea4023dcda69.png)

**Comment by jswrenn** [comment]
Since `unbound-id` errors are by far the most common, it would be great to get this into release as soon as possible.

**Comment by schanzer** [comment]
Now that the snippet is on CPO, is this ok to close?
