### ISSUE TITLE
program that shouldn't type-check does

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#943]
This program has two type errors: the `some` (rather than `someM`) in the last line of `addMO`, and the `some` and `none` (instead of `someM` and `noneM`) in the tests. However, these all seem to pass the type-checker and seem to only be caught by the annotation checker when the tests are run.

```
data MOption<T>:
  | noneM with:
    method bind(self, transformer): self end
  | someM(v :: T) with:
    method bind(self, transformer): transformer(self.v) end
end

fun addMO(a :: MOption<Number>, b :: MOption<Number>) -> MOption<Number>:
  a.bind({(av :: Number):
        b.bind({(bv :: Number):
          some(av + bv)})})
end

check:
  addMO(someM(3), someM(5)) is some(8)
  addMO(someM(3), noneM) is none
  addMO(noneM, someM(5)) is none
end
```

**Comment by mkolosick** [comment]
This is part of a (hopefully temporary) optimization. Standalone check blocks are desugared before the type checker runs and blow up into a huge block of code. This blow up slows down the type checker tremendously, so for now check blocks are ignored by the type checker.
