### ISSUE TITLE
Methods don't play consistently between programs and the repl

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#946]
The following program
```
m = method(self): 42 end
print(m)
```
displays in the REPL
```
# print output
<method>
# print result
<method:<anonymous method>>
```
But then the following also happens in the REPL:
```
>>> print(m)
<function>
<function:>
>>> m
<function:>
```
Are names getting looked up via `getField` in the REPL, and hence currying?

**Comment by jpolitz** [comment]
This is essentially a dupe of #751, which is horizon-fixed.

**Comment by blerner** [comment]
Closing as dupe.
