### ISSUE TITLE
Empty block errors are raised with the wrong location.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#949]
`wf-empty-block` errors are raised with incorrect locations. 

Actual behavior:
<img title="Actual Behavior" alt="fun add(a, b):&#13;  a + b&#13;where:&#13;  # empty-block&#13;end" src="https://cloud.githubusercontent.com/assets/3820879/20983351/25e646c4-bc8a-11e6-877c-ccdcc5997ae8.png"></img>

Expected (in a perfect world) behavior:
<img title="Expected Behavior" alt="fun add(a, b):&#13;  a + b&#13;where:&#13;  # empty-block&#13;end" src="https://cloud.githubusercontent.com/assets/3820879/20983704/77683bb4-bc8b-11e6-8f7a-022ca80ce312.png"></img>

I don't recall it being this broken earlier in the summer; perhaps the explicit `block` changes introduced this?

**Comment by blerner** [comment]
I don't recall this either. The relevant srcloc is set on line 480 of
parse-pyret.js, where it's the srcloc of the body of the where block, and
doesn't include the location of the keyword. If you had that, you could
compute the full location including the end keyword, from the srcloc of the
function itself. But I don't see an easy efficient way to tweak the srcloc
of that block, once it's been constructed...

**Comment by jswrenn** [comment]
Another case of this happening:
<img title="Actual Behavior" alt="fun foo(bar :: Number):&#13;  doc: ```Foobarizes a bar```&#13;end" src="https://cloud.githubusercontent.com/assets/3820879/21527950/e9926e40-ccfc-11e6-8770-7425cd302491.png"></img>

As far as I can tell, the only times this well-formedness error behaves as expected now is in the trivial cases, like:
```
block:
end
```

**Comment by blerner** [comment]
Nope, that's a completely separate problem (in terms of what's causing it).

**Comment by jswrenn** [comment]
> Specifically, the last-visited-loc variable that you'd added to well-formedness checking is not correctly set and reset.

I'm aware of this, but isn't this the underlying issue behind both buggy programs (as opposed to a separate problem)? (I'm aware that attaining "perfect-world" behavior is dependent on changes to the parser stage.)

I started a bit of work earlier today to eliminate `last-visited-loc` altogether by performing the check in nodes which could be parents of an `s-block`. Unfortunately, this gets pretty unwieldy because a _lot_ of things can wrap an `s-block`. I'm not confident I could make that change without forgetting something. Would it be possible to have the visitor handle this and have a `parent` field so that within the `s-block` visitor, you could write `self.parent`?

**Comment by blerner** [comment]
Not efficiently, no. I'll handle this, and push a fix later tonight.
