### ISSUE TITLE
bad type error

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#953]
```
eps = 0.001
fun d-dx(f :: (Number -> Number)) -> (Number -> Number):
  doc: "Approximate the derivative of f"
  lam(x :: Number): (f(x + eps) - f(x)) / eps end
where:
  fun square(x :: Number): x * x end
  fun around(delta, target):
    lam(actual :: Number): num-abs(actual - target) < delta end
  end

  dsquare = d-dx(square)

  dsquare(5) satisfies around(0.1, 10)
  dsquare(10) satisfies around(0.1, 20)
end
```

I get the error "The type checker could not infer the type of the function. Please add type annotations to the arguments." and it refers to the entire `d-dx` function. But that function is clearly fully annotated! 

I then added annotations to `around`, at which point everything seems to be annotated (with at least argument types), but I still get the same error.

I then went in and added _all_ the return type annotations as well. When I added then incorrectly it flagged that as an error: good. But when they were all added correctly…I still get the same error.

I think the problem is entirely with the type inference mechanism, because if I delete the `where` block entirely, all is well.

**Comment by mkolosick** [comment]
I was accidentally overzealous in switching to using test inference. This has been corrected in the type-checker-fixes branch now.
