### ISSUE TITLE
String-dict equality is wrong

### ISSUE THREAD

**Issue by blerner** [brownplt/pyret-lang#954]
Assume for the moment we have a method `clone-now` on string-dicts, to allow us to easily clone a mutable string dict.  (I've implemented this method as an optimization that's paying off in speeding up js-dag-utils, so it's a good thing to have...)  Then the following code is incorrect:

```
include string-dict

l1 = lam(): 5 end

d1 = [mutable-string-dict: "a", 1, "b", l1, "c", 3]
d2 = d1.clone-now()

print(identical(d1, d2)) # ==> false
print(equal-now(d1, d2)) # ==> true !!! YIKES
print(equal-now(d1.get-value-now("b"), d2.get-value-now("b"))) # ==> Error: tried to compare incomparable values
```

The problem is in the equals method itself, which only looks whether two fields are NotEqual, and discards the answer otherwise and moves on to another field.  Since the last field in this dictionary (at least in 2/3 of the possible field iteration orders) is not a function, the equality succeeds.

**Comment by schanzer** [comment]
Looks like this is still not present (even on horizon) - I'm assuming it's part of a larger merge, planned for after classes end this semester?

**Comment by blerner** [comment]
Yes, it's on the memo-jsast branch, which isn't ready to merge into horizon yet.
