### ISSUE TITLE
field reference should be narrower in error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#968]
In this error output
![image](https://cloud.githubusercontent.com/assets/75030/21935579/140ac2a4-d97c-11e6-943d-19f9244e4834.png)
the word "field" is associated with the entire `x: 3` part. However, what is on the right of the `:` may be quite large, and is anyway irrelevant. The field that is missing is just `x`. Therefore, the error should focus just on the field name. (I also wonder why it doesn't just print `x` explicitly instead of only referring to it by a dereference.)

**Comment by jswrenn** [comment]
Just need to add a `field-loc` to [`a-field`](https://github.com/brownplt/pyret-lang/blob/horizon/src/arr/compiler/ast-anf.arr#L448). There are [a lot of call sites to update](https://github.com/brownplt/pyret-lang/search?utf8=%E2%9C%93&q=a-field&type=), but this is doable; will tackle tomorrow.
