### ISSUE TITLE
imported name not available by include

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#975]
```
import gdrive-sheets as GDS

nutrition-sheet = GDS.load-spreadsheet("1YXOMMSdpKwsiGzFE8SY7LJXEvuAHNBzw1RgJYuxSvZc")
```
works fine, but
```
include gdrive-sheets

load-spreadsheet
```
gives an unbound identifier error. What gives?

**Comment by blerner** [comment]
Explanation (but not reason): a module needs to explicitly list the values it provides, in order for them to be included by an `include` statement, and gdrive-sheets doesn't currently export anything at all, so the include statement achieves nothing.  Accessing a field in a module doesn't check whether the field is exported, so the dot-access works.

Moral of the story: modules need to explicitly list their exports, and compilation of module.field access needs to be smarter (which is now can be, thanks to the module information we have available).

**Comment by shriram** [comment]
Why not correlate the two? If it's not exported, the name should probably not be accessible through `import` either. This is just too confusing, and it also means modularity is being violated (because non-exported things are being made available).

**Comment by jpolitz** [comment]
You're  in agreement.  This is fixed (with some caveats having to do with using `import` module names at the REPL, the reason it hasn't been merged just yet) on a branch, which _statically_ checks that `GDS.load-spreadsheet` is defined using the same mechanism as `include` uses for finding bound names.

**Comment by belph** [comment]
@jpolitz So you're saying that `import gdrive-sheets as GDS`...`GDS.load-spreadsheet` will no longer work as-is on the new branch due to what @blerner said, yes?

**Comment by jpolitz** [comment]
Not without changing gdrive-sheets, but that change will come along with the update.

**Comment by SDooman** [comment]
@jpolitz What's the status of this update?  I'm getting the same error running these two programs on CPO:
```
import gdrive-sheets as GDS
presidents-sheet = GDS.load-spreadsheet("14er5Mh443Lb5SIFxXZHdAnLCuQZaA8O6qtgGlibQuEg")
```
```
include gdrive-sheets
presidents-sheet = load-spreadsheet("14er5Mh443Lb5SIFxXZHdAnLCuQZaA8O6qtgGlibQuEg")
```

Since the `import as` version works, does that mean this update was never added to CPO?  If so, what's the timeline for adding it?  CONTEXT:  We would like the `include` version for Data Science Lite, since it does not involve dot accessors.

**Comment by jpolitz** [comment]
I'll push a quicker fix for this soon (like within a day or two).

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/code.pyret.org/commit/b9f62914e968698650d90a54f439855a50a09c72

**Comment by schanzer** [comment]
Confirming this works on CPO. Closing.
