### ISSUE TITLE
`sheet-by-name` not documented

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#976]
https://www.pyret.org/docs/latest/tables.html

The table method `sheet-by-name` is not documented. Not even clear what other methods there might be (because simply evaluating a table shows the content, rather than listing the fields/methods).

**Comment by blerner** [comment]
@jpolitz I've written a scaffolding of docs for this, so we're mostly done with it.  Todo: 
- we don't have scribble formatting for documenting fields of an object (unlike data constructors), and 
- when I compile it locally, I get different formatting than the current pyret-docs site.  Not sure if this is a scribble version issue, though :-\

**Comment by blerner** [comment]
The commit above (and its sequels) have been merged.  Marking as horizon-fixed, because it will be, shortly.
