### ISSUE TITLE
negative seconds-per-tick should error

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#977]
Currently, it sends a negative value to `setTimeout`, which uses the browser's minimum time threshold for the delay.

**Comment by blerner** [comment]
@joe, is this properly a CPO issue with world.js?  I don't see it in reactors.js anywhere...

**Comment by blerner** [comment]
Fixed by https://github.com/brownplt/pyret-lang/commit/a24b53c56a9ef6dfa4ff8defd98a5da5c65c00e0

**Comment by blerner** [comment]
Ugh, this gives an error, but a meaningless, unactionable one!
```
The annotation
  seconds-per-tick: [[[[-1]]]],
was not satisfied by the value
-1
```
Uh, what annotation?  What's wrong with this value?

I could've sworn I'd gotten better annotation error than this when I committed the fix above.

**Comment by schanzer** [comment]
This appears to do the right thing now:
![image](https://user-images.githubusercontent.com/77126/90021054-ba6e4400-dc7e-11ea-83b1-b7de62d1a5a8.png)

@blerner OK to close?
