### ISSUE TITLE
The website has problems ?

### ISSUE THREAD

**Issue by Kerollmops** [brownplt/pyret-lang#979]
https://www.pyret.org/ seems to be in the incapacity to give a correct ssl certificate

**Comment by jpolitz** [comment]
Thanks for reporting, we're looking into it.

**Comment by jpolitz** [comment]
In the meantime, the non-https version is serving fine, if anyone needs docs and can tolerate a non-secure connection:

http://www.pyret.org/
http://www.pyret.org/docs/latest/

etc.

**Comment by jpolitz** [comment]
This should be fixed now, it was a server configuration issue at our host that has been resolved.
