### ISSUE TITLE
Change Plot lib functions to consume List<Number> rather than Tables

### ISSUE THREAD

**Issue by SDooman** [brownplt/pyret-lang#985]
In the current version of the `plot` library, Plot functions require all input tables to have columns named **x, y**.  The contents of these columns make up the ordered pairs that appear in the plot images.

When using tables loaded from Google Drive, the programmer is often forced to use an additional `extend` operation to create new columns **x, y** that contain data from other columns to be plotted.  This is at best annoying, and at worst prohibitive, for new students' program comprehension.

Here is a slightly contrived example of plotting multiple columns against each other:

```
import plot as P

my-table = table: age :: Number, height :: Number, weight :: Number
  row: 45, 65, 124
  row: 37, 68, 132
  row: 22, 71, 155
  row: 31, 60, 122
  row: 8, 52, 89
end

# First plot

to-plot-height-weight = extend my-table using height, weight:
  x: height,
  y: weight
end

height-vs-weight-points = 
  P.scatter-plot(select x, y from to-plot-height-weight end,
    P.default-options)

P.display-multi-plot(
  [list: height-vs-weight-points],
  _.{title: 'Height vs. Weight', x-min: 0, x-max: 100, y-min: 20, y-max: 200})

# Second plot

to-plot-age-height = extend my-table using age, height:
  x: age,
  y: height
end

age-vs-height-points = 
  P.scatter-plot(select x, y from to-plot-age-height end,
    P.default-options)

P.display-multi-plot(
  [list: age-vs-height-points],
  _.{title: 'Age vs. Weight', x-min: 0, x-max: 90, y-min: 0, y-max: 100})
```

Alternatively, if plot functions consumed lists for the ordered pairs **x, y** dimensions, the program would look like this:

```
import plot as P

my-table = table: age :: Number, height :: Number, weight :: Number
  row: 45, 65, 124
  row: 37, 68, 132
  row: 22, 71, 155
  row: 31, 60, 122
  row: 8, 52, 89
end

# Lists of values

age-values = extract age from my-table end
height-values = extract height from my-table end
weight-values = extract weight from my-table end

# First plot

height-vs-weight-points = 
  P.scatter-plot(height-values, weight-values,
    P.default-options)

P.display-multi-plot(
  [list: height-vs-weight-points],
  _.{title: 'Height vs. Weight', x-min: 0, x-max: 100, y-min: 20, y-max: 200})

# Second plot

age-vs-height-points = 
  P.scatter-plot(age-values, height-values,
    P.default-options)

P.display-multi-plot(
  [list: age-vs-height-points],
  _.{title: 'Age vs. Weight', x-min: 0, x-max: 90, y-min: 0, y-max: 100})
```

This program structure much clearer & more extensible when creating plots for comparison of multiple columns of data.

**Comment by sorawee** [comment]
@SDooman initially the plot library consumes a list. @shriram suggests that it should consume tables instead. I am happy to change it back to list style, but just want to make sure that it will be the finalized interface that we want.

What should a `scatter-plot` look like? I previously have it as `scatter-plot :: List<Posn> -> Plot` where `Posn` is from `data Posn: posn(x, y) end`. Now we have tuples, so `scatter-plot :: List<{x; y}> -> Plot` would work as well. Another possibility is `scatter-plot :: List<Number> -> List<Number> -> Plot`, but this has a downside being that it doesn't enforce that both lists have the same size.

**Comment by jpolitz** [comment]
I think this is a good idea -- we should just add them as _new_ functions, or write a new plot module that provides the new interface, so we don't break existing code.

**Comment by shriram** [comment]
Agreed.

**Comment by SDooman** [comment]
@sorawee In the use case I described, `scatter-plot :: List<Posn> -> Plot` requires that students construct the `List<Posn>` with some function that maps over lists containing `x` and `y` values.  This also requires the teacher to expose students to structs/compound data before using the `plot` library.  From the perspective of a student in Bootstrap Data Science Lite, these concepts (functions & structs) may be too much at one time for a student who has only written arithmetic expressions & table operations.  However, since the other Bootstrap courses cover `Posn` structs, I could be convinced otherwise.

`scatter-plot :: List<Number> -> List<Number> -> Plot` does not have those above restrictions.  IMO raising an error with mismatched length lists is an acceptable tradeoff, especially since all lists extracted from the same table are guaranteed to have the same length.

Also, I agree with the @jpolitz and @shriram on the _new functions_ point.

**Comment by SDooman** [comment]
bump @jpolitz @shriram @sorawee 

If nobody has objections with `scatter-plot :: List<Number> -> List<Number> -> Plot` being preferable to `scatter-plot :: List<Posn> -> Plot`,  then we should create a new module called `plot-lists`, so that I can adjust the Bootstrap curriculum accordingly.

I know that we're changing the table syntax in the medium/long term (after this summer),  but providing this library is a necessary stop gap for the students that will be using the v1.0 Bootstrap Data Science course.

**Comment by jpolitz** [comment]
I'm happy with doing this, is there a PR we can use?  Do you need help adding it?

**Comment by sorawee** [comment]
Here: https://github.com/brownplt/code.pyret.org/tree/plot-list

So far only `line-plot` and `scatter-plot` are converted to list style. The rest are still tables. This is all I can do today, sorry.

**Comment by SDooman** [comment]
Thanks @sorawee!

**Comment by schanzer** [comment]
Did https://github.com/brownplt/code.pyret.org/pull/175 snag the rest? Would be helpful to get a running list of what's still outstanding.

**Comment by sorawee** [comment]
I believe this is fixed now, correct? @SDooman

**Comment by schanzer** [comment]
This is complete.
