### ISSUE TITLE
Data declaration with no variants produces bad error message

### ISSUE THREAD

**Issue by nickgaya** [brownplt/pyret-lang#986]
Defining a data type with no variants produces an awkward error message.

    data NoVariants:
    end

> Evaluating the field lookup expression at `file:///home/travis/build/brownplt/code.pyret.org/node_modules/pyret-lang/src/arr/compiler/ast-util.arr:206:40-206:48` errored.
> 
> does not have a field named `first`
> 
> Please report this as a bug.

This is caused by the `collect-shared-fields` helper function in [ast-util.arr](https://github.com/brownplt/pyret-lang/blob/master/src/arr/compiler/ast-util.arr).  Possible fixes:
* Explicitly prohibit no-variant data types with a better error message.
* Add an `is-empty` check in `collect-shared-fields`.  This would allow empty data types to be created.  Non-instantiable data types are potentially useful for annotating non-returning functions.

**Comment by blerner** [comment]
This is definitely a bug, and the second suggested fix sounds like the right one.  (Oddly though, the reported location looks not at all correct, but I wonder if that's because I'm on a different branch or if it's really because we goofed on some function application srcloc tracing...)

**Comment by jswrenn** [comment]
[The srcloc looks about right on master.](https://github.com/brownplt/pyret-lang/blob/master/src/arr/compiler/ast-util.arr#L206)

**Comment by blerner** [comment]
This is fixed by #987, and will be merged when that branch merges back in.
