### ISSUE TITLE
Wrong srcloc + reactor bypasses wf-errors

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#989]
```
1 > true * 2
```

results in an error about needing parentheses as expected. However, it highlights `> true *` which doesn't make sense to me

-------

But worse:

```
reactor:
  init: nothing,
  on-tick: lam(_):
      1 > true * 2
      1 + _
    end,
end
```

does not result in an error (notice all wf-errors: multiple expressions in one block, missing parens, use underscore as expr). Also:

```
reactor:
  init: nothing,
  on-tick: lam(_):
      x = 1
    end
end
```

results in `"Should not get an empty block in desugar-scope-block"` as an internal error.

Same as

```
reactor:
  init: nothing,
  on-tick: lam(_):
      1/0
    end
end
```

results in `/: division by zero, 1 0` as an internal error.

**Comment by blerner** [comment]
Underscore isn't being used as an expression, `1 + _` === `(lam(x): 1 + x)`

**Comment by sorawee** [comment]
Yeah, I just try again and find that in fact it handles `_` just fine.

**Comment by blerner** [comment]
Let's make this bug be about the missing well-formedness checks within reactors.  I'll file a second bug about the weird srcloc.
